# Generated by Django 5.2.4 on 2026-02-12 11:18

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название валюты', max_length=50, verbose_name='Название')),
                ('code', models.CharField(help_text='ISO 4217 код валюты (RUB, USD, EUR)', max_length=3, unique=True, verbose_name='Код')),
                ('symbol', models.CharField(blank=True, help_text='₽, $, €, ¥ и т.д.', max_length=10, verbose_name='символ')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание валюты', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип валюты',
                'verbose_name_plural': 'Типы валюты',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название вида цен', max_length=50, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код вида цен', max_length=20, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание вида цен', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Вид цены',
                'verbose_name_plural': 'Виды цен',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY')], db_index=True, max_length=3, verbose_name='валюта')),
                ('date', models.DateField(db_index=True, verbose_name='дата курса')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Сколько RUB за 1 единицу валюты', max_digits=12, verbose_name='курс')),
                ('nominal', models.PositiveIntegerField(default=1, help_text='Количество единиц валюты (обычно 1 или 100)', verbose_name='номинал')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency'],
                'unique_together': {('currency', 'date')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название текст', max_length=100, verbose_name='Название товара')),
                ('code', models.CharField(blank=True, help_text='Код товара (необязательно', max_length=50, null=True, verbose_name='Код')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(blank=True, help_text='Комментарий к цене', null=True, verbose_name='Комментарий')),
                ('price_date', models.DateField(blank=True, help_text='Дата, на которую зафиксирована цена', null=True, verbose_name='Дата цены')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.currency', verbose_name='Валюта')),
                ('price_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.pricevariety', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Известные цены',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
