# Generated by Django 5.2.4 on 2026-05-20 14:45

import core.models.mixins
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_company_company_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('price', '0001_initial'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('project_customers', '0002_userparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Строка документа цен',
                'verbose_name_plural': 'Строки документа цен',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('partner', 'Партнёр'), ('company', 'Клиент')], max_length=10, verbose_name='Тип цели')),
                ('scope_type', models.CharField(choices=[('brand', 'Бренд'), ('equipment_type', 'Тип оборудования'), ('model_line', 'Серия'), ('product', 'Конкретный товар')], max_length=20, verbose_name='Область действия')),
                ('rule_type', models.CharField(choices=[('discount', 'Скидка'), ('markup', 'Наценка')], max_length=10, verbose_name='Тип правила')),
                ('value', models.DecimalField(decimal_places=2, help_text='Положительное число: 10 = 10% скидки/наценки', max_digits=5, verbose_name='Значение, %')),
                ('priority', models.IntegerField(default=0, help_text='Больше = приоритетнее при конфликте', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило ценообразования',
                'verbose_name_plural': 'Правила ценообразования',
                'ordering': ['-priority'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-price_date'], 'verbose_name': 'История цен', 'verbose_name_plural': 'История цен'},
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='description',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Модель товара (PneumaticFitting, ElectricActuatorModelLineItem...)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип товара'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Текущая действующая цена', verbose_name='Актуальная'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, help_text='₽, $, €, ¥ и т.д.', max_length=10, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='code',
            field=models.CharField(blank=True, default=1, help_text='Копируется из GFK-товара для быстрого поиска', max_length=100, verbose_name='Код товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='name',
            field=models.CharField(blank=True, help_text='Копируется из content_object при сохранении', max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.pricevariety', verbose_name='Вид цены'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Cортировка'),
        ),
        migrations.CreateModel(
            name='PriceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_applied', models.BooleanField(default=False, help_text='Цены из документа записаны в PriceHistory', verbose_name='Применён')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('item_content_type', models.ForeignKey(help_text='Все позиции документа — одного типа (напр. PneumaticFitting)', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Тип товаров в документе')),
            ],
            options={
                'verbose_name': 'Документ цен',
                'verbose_name_plural': 'Документы цен',
                'ordering': ['-document_date'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='PriceDocument, из которого взята цена', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='price.pricedocument', verbose_name='Документ-источник'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['content_type', 'object_id'], name='price_price_content_2374c4_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['price_variety', 'is_current'], name='price_price_price_v_092450_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['content_type', 'object_id', 'price_variety', 'is_current'], name='price_price_content_f567fa_idx'),
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип товара'),
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='price.pricedocument', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='price_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.pricevariety', verbose_name='Вид цены'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='clients.company', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='project_customers.projectcustomer', verbose_name='Партнёр'),
        ),
    ]
