# Generated by Django 4.2.23 on 2026-05-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_pricehistory_sku'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='price_ph_sku_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='price_ph_sku_var_cur_idx',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='sku',
        ),
    ]
