# Generated by Django 5.2.7 on 2026-05-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('price', '0006_remove_pricehistory_price_ph_sku_idx_and_more'),
        ('sku', '0004_alter_sku_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Позиция номенклатуры (основной способ привязки)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='sku.sku', verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['sku'], name='price_price_sku_id_55f7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['sku', 'price_variety', 'is_current'], name='price_price_sku_id_5aec64_idx'),
        ),
    ]
