# Generated by Django 5.2.7 on 2026-05-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_pricehistory_sku'),
    ]

    operations = [
    ]
