# Generated by Django 5.2.7 on 2026-05-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_link_pricehistory_to_sku'),
        ('sku', '0004_alter_sku_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedocument',
            name='item_content_type',
        ),
        migrations.RemoveField(
            model_name='pricedocumentitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pricedocumentitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Позиция номенклатуры', null=True, on_delete=django.db.models.deletion.PROTECT, to='sku.sku', verbose_name='SKU'),
        ),
    ]
