# Generated by Django 5.2.7 on 2026-06-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0037_electricactuatorconstructor'),
        ('price', '0009_document_to_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAPriceConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_field', models.CharField(help_text='Имя поля в ElectricActuatorConstructor (или "base" для базовой цены)', max_length=100, verbose_name='Поле опции')),
                ('option_id', models.PositiveIntegerField(blank=True, help_text='ID выбранной опции (through-модели или реальной)', null=True, verbose_name='ID опции')),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Базовая цена (для base) или надбавка к базовой цене', max_digits=12, verbose_name='Цена / надбавка')),
                ('currency', models.CharField(default='RUB', help_text='Трёхбуквенный код: RUB, USD, EUR, CNY', max_length=3, verbose_name='Валюта')),
                ('price_type', models.CharField(default='retail', help_text='retail, wholesale, dealer, ...', max_length=20, verbose_name='Тип цены')),
                ('is_active', models.BooleanField(default=True, help_text='Учитывать при расчёте цены', verbose_name='Активно')),
                ('model_line_item', models.ForeignKey(help_text='Модель в серии электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='price_rows', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель')),
                ('power_supply', models.ForeignKey(help_text='Выбранное напряжение питания', on_delete=django.db.models.deletion.CASCADE, related_name='price_rows', to='electric_actuators.electricpowersupplyoption', verbose_name='Напряжение питания')),
            ],
            options={
                'verbose_name': 'Строка конфигуратора цен ЭП',
                'verbose_name_plural': 'Конфигуратор цен ЭП',
                'ordering': ['model_line_item', 'power_supply', 'option_field', 'option_id'],
                'indexes': [models.Index(fields=['model_line_item', 'power_supply', 'price_type'], name='price_eapri_model_l_a50e92_idx'), models.Index(fields=['model_line_item', 'power_supply', 'option_field', 'option_id'], name='price_eapri_model_l_0037ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_line_item', 'power_supply', 'option_field', 'option_id', 'price_type'), name='uq_ea_price_row')],
            },
        ),
    ]
