# Generated by Django 5.2.7 on 2026-06-09 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0037_electricactuatorconstructor'),
        ('price', '0010_eapriceconstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAPriceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('posted', 'Проведён')], default='draft', help_text='Черновик → На согласовании → Проведён', max_length=20, verbose_name='Статус')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Документ конфигуратора цен ЭП',
                'verbose_name_plural': 'Документы конфигуратора цен ЭП',
                'ordering': ['-document_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='eapriceconstructor',
            name='uq_ea_price_row',
        ),
        migrations.RemoveIndex(
            model_name='eapriceconstructor',
            name='price_eapri_model_l_a50e92_idx',
        ),
        migrations.RemoveField(
            model_name='eapriceconstructor',
            name='price_type',
        ),
        migrations.AddField(
            model_name='eapriceconstructor',
            name='price_variety',
            field=models.ForeignKey(blank=True, help_text='Вид цены', null=True, on_delete=django.db.models.deletion.PROTECT, to='price.pricevariety', verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='eapriceconstructor',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Валюта цены', null=True, on_delete=django.db.models.deletion.PROTECT, to='price.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='currency',
            field=models.ForeignKey(help_text='Валюта цены', on_delete=django.db.models.deletion.PROTECT, to='price.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='model_line',
            field=models.ForeignKey(help_text='Серия электроприводов', on_delete=django.db.models.deletion.PROTECT, related_name='price_documents', to='electric_actuators.electricactuatormodelline', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='power_supply',
            field=models.ForeignKey(help_text='Напряжение, для которого заполняются цены', on_delete=django.db.models.deletion.PROTECT, related_name='price_documents', to='electric_actuators.electricpowersupplyoption', verbose_name='Напряжение питания'),
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='price_variety',
            field=models.ForeignKey(help_text='Вид цены: РРЦ, опт, дилерская, ...', on_delete=django.db.models.deletion.PROTECT, to='price.pricevariety', verbose_name='Тип цены'),
        ),
        migrations.AddField(
            model_name='eapriceconstructor',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Документ конфигуратора цен (если цена импортирована из документа)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='price.eapricedocument', verbose_name='Документ'),
        ),
        migrations.AddIndex(
            model_name='eapriceconstructor',
            index=models.Index(fields=['model_line_item', 'power_supply', 'price_variety'], name='price_eapri_model_l_d14140_idx'),
        ),
        migrations.AddConstraint(
            model_name='eapriceconstructor',
            constraint=models.UniqueConstraint(fields=('model_line_item', 'power_supply', 'option_field', 'option_id', 'price_variety'), name='uq_ea_price_row'),
        ),
    ]
