# Generated by Django 5.2.7 on 2026-06-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0037_electricactuatorconstructor'),
        ('price', '0011_eapricedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eapricedocument',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Валюта цены', null=True, on_delete=django.db.models.deletion.PROTECT, to='price.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='eapricedocument',
            name='model_line',
            field=models.ForeignKey(blank=True, help_text='Серия электроприводов', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_documents', to='electric_actuators.electricactuatormodelline', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='eapricedocument',
            name='price_variety',
            field=models.ForeignKey(blank=True, help_text='Вид цены: РРЦ, опт, дилерская, ...', null=True, on_delete=django.db.models.deletion.PROTECT, to='price.pricevariety', verbose_name='Тип цены'),
        ),
    ]
