# Generated by Django 5.2.1 on 2026-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_alter_eapricedocument_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eapricedocument',
            options={'verbose_name': 'Документ конфигуратора цен ЭП', 'verbose_name_plural': 'Документы конфигуратора цен ЭП'},
        ),
        migrations.AlterModelOptions(
            name='pricedocument',
            options={'verbose_name': 'Документ цен', 'verbose_name_plural': 'Документы цен'},
        ),
        migrations.AlterModelOptions(
            name='pricedocumentitem',
            options={'verbose_name': 'Строка документа цен', 'verbose_name_plural': 'Строки документа цен'},
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='code',
            field=models.CharField(blank=True, help_text='Уникальный код документа (из нумератора или ручной)', max_length=50, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01T00:00:00', verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapricedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AddField(
            model_name='pricedocument',
            name='code',
            field=models.CharField(blank=True, help_text='Уникальный код документа (из нумератора или ручной)', max_length=50, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='pricedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01T00:00:00', verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01T00:00:00', verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricedocumentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='eapricedocument',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='eapricedocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('posted', 'Проведён'), ('deleted', 'Удалён')], default='draft', help_text='Черновик → На согласовании → Проведён → Удалён', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pricedocument',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='pricedocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('posted', 'Проведён'), ('deleted', 'Удалён')], default='draft', help_text='Черновик → На согласовании → Проведён → Удалён', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pricedocumentitem',
            name='comment',
            field=models.CharField(blank=True, help_text='Комментарий к строке документа', max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='pricedocumentitem',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
