# Generated by Django 5.2.4 on 2026-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0037_electricactuatorconstructor'),
        ('price', '0013_alter_eapricedocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eapriceconstructor',
            name='uq_ea_price_row',
        ),
        migrations.AddConstraint(
            model_name='eapriceconstructor',
            constraint=models.UniqueConstraint(fields=('document', 'model_line_item', 'power_supply', 'option_field', 'option_id', 'price_variety'), name='uq_ea_price_row'),
        ),
    ]
