# Generated by Django 5.2.7 on 2026-08-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0019_add_prompt_template_to_composition_group'),
        ('core', '0010_alter_equipmenttype_ai_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код: temperature_min, exd, thread_size, ip', max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('match_type', models.CharField(choices=[('exact', 'Точное совпадение'), ('directional', 'Направленное сравнение'), ('hierarchy', 'Иерархия'), ('compatible', 'Группы совместимости'), ('subset', 'Подмножество')], default='exact', max_length=16)),
                ('match_config', models.JSONField(blank=True, default=dict, help_text='Конфигурация сравнения — семантика зависит от match_type:\n  exact:         {} — не используется\n  directional:   {"direction": "min"}  — чем меньше, тем лучше\n                  {"direction": "max"}  — чем больше, тем лучше\n  hierarchy:     {"levels": ["общепром", "Ex ia", "Ex e", "Exd"]}\n                  требование уровня N → подходят модели уровня ≥ N\n  compatible:    {"groups": [["M20", "M20×1.5"], ["G1/4", "G1/4×1.5"]]}\n  subset:        {"field": "ip_rank"}  — значение модели ⊇ требование')),
                ('hardness', models.CharField(choices=[('hard', 'Жёсткое — невыполнение исключает модель'), ('soft', 'Мягкое — невыполнение даёт штраф')], default='soft', max_length=8)),
                ('relaxation_strategy', models.CharField(choices=[('none', 'Не релаксировать'), ('step', 'Пошагово (шаг из config)'), ('percentage', 'Процент (шаг из config)'), ('compatible', 'Соседние группы совместимости'), ('any', 'Игнорировать ограничение')], default='none', max_length=16)),
                ('relaxation_config', models.JSONField(blank=True, help_text='Конфигурация релаксации:\n  step:       {"step": 5, "max_steps": 4}  — шаг 5°C, макс 4 шага\n  percentage: {"percent": 5, "max_steps": 3}  — шаг 5%, макс 3 шага\n  compatible: {} — перейти к соседним группам\n  any:        {} — полностью игнорировать', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Приоритет: выше → важнее. Штраф за отклонение = deviation × priority')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Rule',
                'verbose_name_plural': 'Parameter Rules',
                'db_table': 'configurator_parameter_rule',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('global_requirements', models.JSONField(blank=True, default=dict, help_text='Общие требования: temperature_min, exd, pressure, ...')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В подборе'), ('done', 'Завершён')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition_group', models.ForeignKey(help_text='Шаблон сборки (pa-kit, ea-kit, ...)', on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='ai_assistant.compositiongroup')),
                ('conversation', models.ForeignKey(blank=True, help_text='Сессия AI, если подбор инициирован через LLM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='ai_assistant.aiconversation')),
                ('root_node', models.ForeignKey(blank=True, help_text='Точка входа — если указана, дерево обрезается до этой ветки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_point_assemblies', to='ai_assistant.compositiongroup')),
            ],
            options={
                'verbose_name': 'Assembly Requirements',
                'verbose_name_plural': 'Assembly Requirements',
                'db_table': 'configurator_assembly_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DerivationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('source_product_field', models.CharField(help_text='Поле в БД-модели продукта. Например, у модели PA есть поле port_size_npt — его значение пойдёт в target', max_length=128)),
                ('target_param', models.CharField(help_text='Имя параметра требований дочернего типа. Должно совпадать с PropagationRule.param_name для target_type', max_length=128)),
                ('transform', models.JSONField(blank=True, help_text='null — прямое присваивание. {"map": {"G1/4": "1/4", "G1/2": "1/2"}} — словарь замены', null=True)),
                ('condition', models.JSONField(blank=True, help_text='null — срабатывает всегда. {"field": "actuator_variety", "value": "SR"} — только для SR-приводов', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Приоритет при нескольких правилах на одну пару типов')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_type', models.ForeignKey(help_text='Тип-источник (откуда берём значение)', on_delete=django.db.models.deletion.CASCADE, related_name='derivations_from', to='core.equipmenttype')),
                ('target_type', models.ForeignKey(help_text='Тип-приёмник (куда пробрасываем значение)', on_delete=django.db.models.deletion.CASCADE, related_name='derivations_to', to='core.equipmenttype')),
            ],
            options={
                'verbose_name': 'Derivation Rule',
                'verbose_name_plural': 'Derivation Rules',
                'db_table': 'configurator_derivation_rule',
                'ordering': ['source_type', 'target_type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='FittingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Условие срабатывания шаблона. Примеры:\n  {"valve_function": ["5/2", "5/3"], "mounting": "namur_on_actuator"}\n  {"valve_function": ["5/2"], "mounting": "standalone"}\n  {"mounting": "namur_on_actuator"}  — любой function_type')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applies_to', models.ForeignKey(help_text='К какому типу оборудования относится шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='fitting_patterns', to='core.equipmenttype')),
            ],
            options={
                'verbose_name': 'Fitting Pattern',
                'verbose_name_plural': 'Fitting Patterns',
                'db_table': 'configurator_fitting_pattern',
                'ordering': ['applies_to', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FittingPatternItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Количество фитингов этого типа')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Конфигурация фитинга:\n  {"angle": "straight", "size_from": "parent.port_size_npt"} — прямой, размер от привода\n  {"angle": "angled_90", "size_from": "parent.port_size_npt"} — угловой 90°\n  {"purpose": "bracket"} — скоба/кронштейн (не фитинг)')),
                ('order', models.IntegerField(default=0)),
                ('equipment_type', models.ForeignKey(help_text='Тип оборудования для этой позиции (fitting-thread-pipe, mk-...)', on_delete=django.db.models.deletion.PROTECT, related_name='fitting_pattern_items', to='core.equipmenttype')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configurator.fittingpattern')),
            ],
            options={
                'verbose_name': 'Fitting Pattern Item',
                'verbose_name_plural': 'Fitting Pattern Items',
                'db_table': 'configurator_fitting_pattern_item',
                'ordering': ['pattern', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ComponentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text="Materialized path: '1', '1/2', '1/2/1'", max_length=256)),
                ('level', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('own_requirements', models.JSONField(blank=True, default=dict, help_text='Что явно указал пользователь/AI для этого компонента')),
                ('effective_requirements', models.JSONField(blank=True, default=dict, help_text='Вычисляемое: global + inherited + derived + own')),
                ('cascade_params', models.JSONField(blank=True, help_text='Параметры, проброшенные от выбора родительского продукта (DerivationRule)', null=True)),
                ('filter_results', models.JSONField(blank=True, help_text='Результат API-фильтра: candidate list', null=True)),
                ('selected_product_type', models.CharField(blank=True, help_text='app_label.ModelName выбранного продукта', max_length=128, null=True)),
                ('selected_product_id', models.IntegerField(blank=True, help_text='ID выбранного продукта', null=True)),
                ('selected_product_specs', models.JSONField(blank=True, help_text='Фактические характеристики выбранного продукта', null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('requirements_filled', 'Требования заданы'), ('filtered', 'Варианты получены'), ('selected', 'Выбран'), ('skipped', 'Пропущен (optional)')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='configurator.assemblyrequirements')),
                ('composition_group_node', models.ForeignKey(blank=True, help_text='Узел CompositionGroup, из которого создан этот компонент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_requirements', to='ai_assistant.compositiongroup')),
                ('equipment_type', models.ForeignKey(help_text='Тип оборудования (пневмопривод, соленоид, ...)', on_delete=django.db.models.deletion.PROTECT, related_name='component_requirements', to='core.equipmenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='configurator.componentrequirement')),
            ],
            options={
                'verbose_name': 'Component Requirement',
                'verbose_name_plural': 'Component Requirements',
                'db_table': 'configurator_component_requirement',
                'ordering': ['assembly', 'path'],
                'indexes': [models.Index(fields=['assembly', 'status'], name='configurato_assembl_6aeb88_idx'), models.Index(fields=['equipment_type', 'status'], name='configurato_equipme_33dbca_idx')],
                'unique_together': {('assembly', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ParameterBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(help_text='Имя поля в модели/фильтре оборудования', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_bindings', to='core.equipmenttype')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='configurator.parameterrule')),
            ],
            options={
                'verbose_name': 'Parameter Binding',
                'verbose_name_plural': 'Parameter Bindings',
                'db_table': 'configurator_parameter_binding',
                'ordering': ['equipment_type', 'param_name'],
                'unique_together': {('equipment_type', 'param_name')},
            },
        ),
        migrations.CreateModel(
            name='PropagationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('param_name', models.CharField(help_text='Имя параметра (temperature_min, exd, voltage, ...)', max_length=128)),
                ('source', models.CharField(choices=[('user', 'Пользователь — должен указать явно'), ('global', 'Глобальные требования сборки'), ('parent', 'От родительского компонента в дереве'), ('derived', 'Вычисляется из выбранной модели — см. DerivationRule')], max_length=16)),
                ('source_param', models.CharField(blank=True, help_text='Имя параметра-источника (если source=parent: родительский param_name)', max_length=128, null=True)),
                ('allow_override', models.BooleanField(default=True, help_text='True — своё значение приоритетнее источника')),
                ('is_mandatory', models.BooleanField(default=False, help_text='True — поле обязательно для заполнения')),
                ('mandatory_condition', models.JSONField(blank=True, help_text='Условие обязательности. null — всегда. {"param": "actuator_variety", "value": "SR"} — только для SR', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Приоритет: выше → важнее при scoring и релаксации')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagation_rules', to='core.equipmenttype')),
            ],
            options={
                'verbose_name': 'Propagation Rule',
                'verbose_name_plural': 'Propagation Rules',
                'db_table': 'configurator_propagation_rule',
                'ordering': ['equipment_type', 'priority'],
                'unique_together': {('equipment_type', 'param_name')},
            },
        ),
    ]
