# Generated by Django 5.2.7 on 2026-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0019_add_prompt_template_to_composition_group'),
        ('configurator', '0001_initial'),
        ('core', '0010_alter_equipmenttype_ai_placeholder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentrequirement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parameterbinding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='propagationrule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='componentrequirement',
            constraint=models.UniqueConstraint(fields=('assembly', 'path'), name='uq_component_requirement_assembly_path'),
        ),
        migrations.AddConstraint(
            model_name='parameterbinding',
            constraint=models.UniqueConstraint(fields=('equipment_type', 'param_name'), name='uq_parameter_binding_type_param'),
        ),
        migrations.AddConstraint(
            model_name='propagationrule',
            constraint=models.UniqueConstraint(fields=('equipment_type', 'param_name'), name='uq_propagation_rule_type_param'),
        ),
    ]
