# Generated by Django 5.2.7 on 2026-08-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_componentrequirement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterrule',
            name='combine',
            field=models.CharField(blank=True, choices=[('and', 'AND — все дочерние правила должны выполниться'), ('or', 'OR — достаточно выполнения любого дочернего')], help_text='Как комбинировать sub_rules (только для родительского правила с match_type=composite)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='parameterrule',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительское правило (если это — часть составного composite-правила)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_rules', to='configurator.parameterrule'),
        ),
        migrations.AlterField(
            model_name='parameterrule',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Точное совпадение'), ('directional', 'Направленное сравнение'), ('hierarchy', 'Иерархия'), ('compatible', 'Группы совместимости'), ('subset', 'Подмножество'), ('composite', 'Составное правило')], default='exact', max_length=16),
        ),
    ]
