# Generated by Django 5.2.7 on 2026-08-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_parameterrule_combine_parameterrule_parent_and_more'),
        ('core', '0010_alter_equipmenttype_ai_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentrequirement',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Тип оборудования (null для виртуальных узлов без ET)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_requirements', to='core.equipmenttype'),
        ),
    ]
