# Generated by Django 5.2.7 on 2026-08-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_make_equipment_type_nullable'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_alter_equipmenttype_ai_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Код источника: 'user', 'global', 'parent', 'derived'", max_length=16, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Человекочитаемое название', max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Как работает этот источник', verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Источник параметра',
                'verbose_name_plural': 'Источники параметров',
                'db_table': 'configurator_parameter_source',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text="Уникальный код: 'pa-torque', 'lsb-sensor'. Автоматически генерируется если не указан.", max_length=128, null=True, unique=True, verbose_name='Код')),
                ('product_model_ref', models.CharField(blank=True, help_text="app_label.ModelName: 'gearbox.GearBox' — fallback без ContentType", max_length=128, null=True, verbose_name='Ссылка на модель')),
                ('field_path', models.CharField(help_text="Путь к полю в модели продукта: 'ip', 'body__max_work_torque'", max_length=256, verbose_name='Путь к полю')),
                ('param_name', models.CharField(help_text="Имя в own_requirements: 'ip_id', 'torque_nm'", max_length=128, verbose_name='Имя параметра')),
                ('label', models.CharField(help_text="Отображаемое название: 'IP защита', 'Крутящий момент'", max_length=256, verbose_name='Заголовок')),
                ('field_type', models.CharField(choices=[('integer', 'Целое число'), ('decimal', 'Десятичное'), ('boolean', 'Да/нет'), ('choice', 'Выбор из списка'), ('fk', 'Foreign Key'), ('string', 'Строка')], default='choice', max_length=16, verbose_name='Тип поля')),
                ('source_param', models.CharField(blank=True, help_text='Для source=parent: имя параметра родителя', max_length=128, null=True, verbose_name='Параметр-источник')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('allow_override', models.BooleanField(default=True, verbose_name='Разрешить переопределение')),
                ('required_condition', models.JSONField(blank=True, help_text='{"param": "actuator_variety_code", "value": "SR"}', null=True, verbose_name='Условие обязательности')),
                ('priority', models.IntegerField(default=0, help_text='Выше = важнее при scoring', verbose_name='Приоритет')),
                ('options_source', models.CharField(blank=True, choices=[('foreign_key', 'Из связанной модели'), ('field_values', 'Уникальные значения поля'), ('global_model', 'Из глобального справочника'), ('choices', 'Из choices поля'), ('custom', 'Кастомный метод')], max_length=16, null=True, verbose_name='Источник опций')),
                ('options_config', models.JSONField(blank=True, help_text='{"model": "params.IpOption", "field": "name", "active_only": true}', null=True, verbose_name='Конфигурация опций')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('parameter_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_parameters', to='configurator.parameterrule', verbose_name='Правило сравнения')),
                ('product_model', models.ForeignKey(blank=True, help_text='Django-модель продукта: GearBox, DirectionValve, ...', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Модель продукта')),
                ('source', models.ForeignKey(blank=True, help_text='Откуда берётся значение: user/global/parent/derived', null=True, on_delete=django.db.models.deletion.PROTECT, to='configurator.parametersource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Параметр типа оборудования',
                'verbose_name_plural': 'Параметры типов оборудования',
                'db_table': 'configurator_equipment_type_parameter',
                'ordering': ['equipment_type', 'sorting_order', 'param_name'],
                'indexes': [models.Index(fields=['equipment_type', 'source'], name='configurato_equipme_5aff6d_idx'), models.Index(fields=['equipment_type', 'is_active'], name='configurato_equipme_9358aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('equipment_type', 'param_name'), name='uq_param_equipment_type_param_name')],
            },
        ),
    ]
