# Generated by Django 5.2.7 on 2026-08-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_add_parameter_source_and_etp'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='ai_extraction_hint',
            field=models.CharField(blank=True, help_text="'ищи значение в Нм', 'спроси диаметр кабеля'", max_length=512, null=True, verbose_name='Подсказка AI для извлечения'),
        ),
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='description',
            field=models.TextField(blank=True, help_text='Подсказка для AI: что означает этот параметр', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='enum_values',
            field=models.JSONField(blank=True, help_text='[{"id": 1, "name": "Нержавейка"}, ...] или ["NPT", "BSP"]', null=True, verbose_name='Возможные значения'),
        ),
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='param_type',
            field=models.CharField(blank=True, choices=[('integer', 'Целое число'), ('decimal', 'Десятичное'), ('boolean', 'Да/нет'), ('choice', 'Выбор из списка'), ('string', 'Строка')], max_length=16, null=True, verbose_name='Тип значения'),
        ),
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='unit',
            field=models.CharField(blank=True, help_text="'Нм', '°C', 'бар', 'мм'", max_length=64, null=True, verbose_name='Единица измерения'),
        ),
    ]
