# Generated by Django 5.2.7 on 2026-08-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_add_param_semantics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='data_source_type',
            field=models.CharField(blank=True, choices=[('field_values', 'Field Values'), ('unique_field_values', 'Unique Field Values'), ('foreign_key', 'Foreign Key'), ('global_model', 'Global Model'), ('choices', 'Choices'), ('custom', 'Custom')], help_text='Откуда брать опции для селектов: FK, глобальная модель, значения поля', max_length=32, null=True, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('min', 'Min'), ('max', 'Max'), ('temp_min', 'Temp Min'), ('temp_max', 'Temp Max'), ('ip_rank', 'IP Rank'), ('exd_compatible', 'Exd Compatible'), ('choice', 'Choice'), ('boolean', 'Boolean'), ('fk_cascade', 'FK Cascade'), ('thread_compatible', 'Thread Compatible')], help_text='Какой UI-компонент показать: селект, слайдер, IP-ранг', max_length=32, null=True, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='equipmenttypeparameter',
            name='allow_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipmenttypeparameter',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Без этого параметра подбор невозможен (gate)', verbose_name='Обязательное'),
        ),
        migrations.AlterField(
            model_name='equipmenttypeparameter',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurator.parametersource', verbose_name='Источник (deprecated)'),
        ),
        migrations.AlterField(
            model_name='equipmenttypeparameter',
            name='source_param',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
