# Generated by Django 5.2.7 on 2026-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_add_filter_type_and_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='compare_direction',
            field=models.CharField(blank=True, choices=[('min', 'Min — чем больше, тем лучше'), ('max', 'Max — чем меньше, тем лучше'), ('exact', 'Exact — точное совпадение')], help_text='Как сравнивать требование с фактом: min (момент, IP), max (темп.), exact (резьба)', max_length=8, null=True, verbose_name='Направление сравнения'),
        ),
        migrations.AddField(
            model_name='equipmenttypeparameter',
            name='compare_label',
            field=models.CharField(blank=True, help_text="'не менее', 'не хуже', 'не выше' — для AI-промптов", max_length=64, null=True, verbose_name='Метка сравнения'),
        ),
    ]
