# Generated by Django 5.2.7 on 2026-08-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_add_parameter_type_fields'),
        ('core', '0011_remove_et_prompt_and_schema_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFieldSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(help_text="Реальный путь в Django-модели: 'work_temp_min', 'body__weight'", max_length=256, verbose_name='Путь к полю')),
                ('param_name', models.CharField(blank=True, db_index=True, help_text="Унифицированное имя параметра для AI/UI: 'temp_min', 'ip_id'. Пусто = ещё не синхронизировано. Один param_name объединяет разные field_path из разных моделей.", max_length=128, null=True, verbose_name='Канонический ключ')),
                ('field_type', models.CharField(choices=[('fk', 'Foreign Key'), ('m2m', 'Many-to-Many'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('float', 'Float'), ('boolean', 'Boolean'), ('char', 'Char'), ('text', 'Text'), ('json', 'JSON'), ('other', 'Другой')], default='other', max_length=16, verbose_name='Тип поля')),
                ('target_model', models.CharField(blank=True, help_text='app_label.ModelName для FK/M2M. Пусто для скалярных полей.', max_length=128, null=True, verbose_name='Связанная модель')),
                ('source_model', models.CharField(blank=True, help_text='Где поле определено (для FK-цепочек может отличаться от equipment_type)', max_length=128, null=True, verbose_name='Модель-источник')),
                ('depth', models.IntegerField(default=0, help_text='0 = прямое поле модели, 1 = поле через один FK, 2 = через два', verbose_name='Уровень вложенности')),
                ('filter_type', models.CharField(blank=True, help_text='Инференция: exact, choice, gte, boolean, icontains, ...', max_length=32, null=True, verbose_name='Тип фильтра')),
                ('data_source_type', models.CharField(blank=True, help_text='Инференция: foreign_key, global_model, field_values, choices', max_length=32, null=True, verbose_name='Источник данных')),
                ('is_active', models.BooleanField(default=True, help_text='Включать ли в ETP при sync_to_etp()', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(help_text='EquipmentType, для которого собран снимок', on_delete=django.db.models.deletion.CASCADE, related_name='field_snapshots', to='core.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Снимок поля модели',
                'verbose_name_plural': 'Снимки полей моделей',
                'ordering': ['equipment_type', 'depth', 'field_path'],
                'indexes': [models.Index(fields=['equipment_type', 'is_active'], name='configurato_equipme_f773b6_idx'), models.Index(fields=['param_name'], name='configurato_param_n_2c49f4_idx')],
                'unique_together': {('equipment_type', 'field_path')},
            },
        ),
    ]
