# Generated by Django 5.2.7 on 2026-08-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_add_model_field_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Канонический ключ: 'temp_min', 'ip_id', 'torque_nm'. Это же значение попадает в EquipmentTypeParameter.param_name.", max_length=128, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text="Человекочитаемое имя: 'Минимальная температура'", max_length=256, verbose_name='Название')),
                ('namespace', models.CharField(blank=True, db_index=True, help_text="Группировка: 'temperature', 'connection', 'protection', 'ip' — для выпадающего списка на фронте", max_length=64, null=True, verbose_name='Namespace')),
                ('description', models.TextField(blank=True, help_text="Чтобы не забыть, к чему это: 'Нижний предел рабочей температуры изделия'", null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Каталог параметров',
                'verbose_name_plural': 'Каталог параметров',
                'ordering': ['namespace', 'code'],
            },
        ),
        migrations.RenameIndex(
            model_name='modelfieldsnapshot',
            new_name='configurato_param_n_e1eb29_idx',
            old_name='configurato_param_n_2c49f4_idx',
        ),
        migrations.AddIndex(
            model_name='parametercatalog',
            index=models.Index(fields=['namespace', 'is_active'], name='configurato_namespa_b6d26d_idx'),
        ),
        migrations.AlterField(
            model_name='modelfieldsnapshot',
            name='param_name',
            field=models.ForeignKey(blank=True, help_text='Ссылка на запись в ParameterCatalog — унифицированное понятие для AI/UI. Пусто = ещё не синхронизировано. На фронте — выпадающий список из каталога.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_snapshots', to='configurator.parametercatalog', verbose_name='Канонический параметр'),
        ),
    ]
