# Generated by Django 5.2.7 on 2026-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_add_parameter_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfieldsnapshot',
            name='help_text',
            field=models.TextField(blank=True, help_text='help_text из Django-поля (подсказка к назначению поля)', null=True, verbose_name='Help text'),
        ),
        migrations.AddField(
            model_name='modelfieldsnapshot',
            name='verbose_name',
            field=models.CharField(blank=True, help_text='verbose_name из Django-поля (человекочитаемое название поля)', max_length=256, null=True, verbose_name='Verbose name'),
        ),
    ]
