# Generated by Django 5.2.7 on 2026-08-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0012_remove_clientrequestitem_assembly'),
        ('configurator', '0011_add_snapshot_verbose_help'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssemblyRequirements',
        ),
        migrations.DeleteModel(
            name='ComponentRequirement',
        ),
    ]
