# Generated by Django 5.2.7 on 2026-08-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0012_remove_componentrequirement_assembly_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipmenttypeparameter',
            name='configurato_equipme_5aff6d_idx',
        ),
        migrations.RemoveField(
            model_name='equipmenttypeparameter',
            name='source',
        ),
        migrations.RemoveField(
            model_name='equipmenttypeparameter',
            name='allow_override',
        ),
        migrations.RemoveField(
            model_name='equipmenttypeparameter',
            name='source_param',
        ),
        migrations.DeleteModel(
            name='ParameterSource',
        ),
        migrations.DeleteModel(
            name='PropagationRule',
        ),
    ]
