# Generated by Django 5.2.7 on 2026-10-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0014_fittingpattern_description_i18n_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fittingpattern',
            name='description_i18n',
        ),
    ]
