# Generated by Django 4.2.23 on 2026-05-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('params', '0048_filtrationgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название название типа слива', max_length=200, verbose_name='Название типа слива')),
                ('code', models.CharField(blank=True, help_text='Код типа слива', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа слива', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип слива',
                'verbose_name_plural': 'Типы слива',
            },
        ),
        migrations.CreateModel(
            name='FilterRegulatorVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название типа фильтра-регулятора', max_length=200, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа фильтра-регулятора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа фильтра-регулятора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип фильтр-регулятора',
                'verbose_name_plural': 'Типы фильтр-регуляторов',
            },
        ),
        migrations.CreateModel(
            name='FilterRegulatorModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название фильтр-регулятора', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код фильтр-регулятора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности серии фильтр-регуляторов', verbose_name='Описание')),
                ('name_template', models.CharField(help_text='Шаблон для текстового названия фильтр-регулятора', max_length=300, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания фильтр-регулятора', verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('bowl_material_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал стакана')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С')),
                ('pressure_min', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Минимальное давление на выходе, бар', max_digits=6, null=True, verbose_name='P выход.мин, бар')),
                ('pressure_max', models.DecimalField(blank=True, decimal_places=2, default=8, help_text='Максимальное давление на выходе, бар', max_digits=6, null=True, verbose_name='P выход.макс, бар')),
                ('pressure_inlet_max', models.DecimalField(blank=True, decimal_places=2, default=10, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_model_line_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('body_material_specified', models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_model_line_body_material_specified', to='materials.materialspecified', verbose_name='Материал корпуса')),
                ('bowl_material', models.ForeignKey(blank=True, help_text='Стакан', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_model_line_bowl_material', to='materials.materialgeneral', verbose_name='Тип материала стакана')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_model_line_brand', to='producers.brands', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Серия фильтр-регуляторов',
                'verbose_name_plural': 'Серии фильтр-регуляторов',
                'ordering': ['brand', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FilterRegulatorBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название корпуса фильтр-регулятора', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код клапана', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание корпуса фильтр-регулятора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Вес', max_digits=5, null=True, verbose_name='Вес, кг')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('drain_port_size', models.ForeignKey(blank=True, help_text='Резьба слива', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body_drain_port_thread', to='params.threadsize', verbose_name='Резьба слива')),
                ('gauge_port_size', models.ForeignKey(blank=True, help_text='Резьба манометра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body_gauge_port_thread', to='params.threadsize', verbose_name='Резьба манометра')),
                ('thread', models.ForeignKey(blank=True, help_text='Резьба портов IN/OUT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body_thread', to='params.threadsize', verbose_name='Резьба портов')),
            ],
            options={
                'verbose_name': 'Корпус фильтр-регулятора',
                'verbose_name_plural': 'Корпуса фильтр-регуляторов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='FilterRegulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название модели фильтр-регулятора', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели фильтр-регулятора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели фильтр-регулятора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('gauge_quantity', models.IntegerField(choices=[(0, 'Без манометра'), (1, '1 манометр в комплекте'), (2, '2 манометра в комплекте')], default=1, verbose_name='Комплектация манометром')),
                ('filtration_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Тонкость фильтрации (мкм)')),
                ('filter_element_material', models.CharField(choices=[('bronze', 'Спеченная бронза'), ('plastic', 'Пористый полимер'), ('ss', 'Нержавеющая сетка')], max_length=20, verbose_name='Материал фильтрующего элемента')),
                ('protection_material', models.CharField(max_length=50, verbose_name='Материал защиты (кожуха)')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Макс. расход (л/мин)')),
                ('wall_mounting_included', models.CharField(choices=[('no', 'Нет'), ('yes', 'В комплекте')], default='yes', max_length=20, verbose_name='Настенное крепление в комплекте')),
                ('has_shut_off_valve', models.BooleanField(default=False, verbose_name='Отсечной клапан в комплекте')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('body', models.ForeignKey(blank=True, help_text='Корпус фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body', to='filter_regulator.filterregulatorvariety', verbose_name='Корпус')),
                ('drain_variety', models.ForeignKey(blank=True, help_text='Тип модели фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_drain_variety', to='filter_regulator.drainvariety', verbose_name='Тип')),
                ('filter_variety', models.ForeignKey(blank=True, help_text='Тип модели фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_variety', to='filter_regulator.filterregulatorvariety', verbose_name='Тип')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия модели фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_model_line', to='filter_regulator.filterregulatormodelline', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Фильтр-регулятор',
                'verbose_name_plural': 'Фильтр-регуляторы',
                'ordering': ['sorting_order'],
            },
        ),
    ]
