# Generated by Django 4.2.23 on 2026-05-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterregulator',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Корпус фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body', to='filter_regulator.filterregulatorbody', verbose_name='Корпус'),
        ),
    ]
