# Generated by Django 4.2.23 on 2026-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0002_alter_filterregulator_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='description_template',
            field=models.TextField(blank=True, help_text='Шаблон для описания фильтр-регулятора', null=True, verbose_name='Шаблон описания'),
        ),
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='name_template',
            field=models.TextField(blank=True, help_text='Шаблон для текстового названия фильтр-регулятора', null=True, verbose_name='Шаблон названия'),
        ),
    ]
