# Generated by Django 4.2.23 on 2026-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0003_alter_filterregulatormodelline_description_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterregulator',
            name='protection_material',
        ),
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='protection_material',
            field=models.CharField(default=1, max_length=50, verbose_name='Материал защиты (кожуха)'),
            preserve_default=False,
        ),
    ]
