# Generated by Django 5.2.4 on 2026-05-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0004_remove_filterregulator_protection_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterregulator',
            name='filter_variety',
        ),
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='filter_variety',
            field=models.ForeignKey(blank=True, help_text='Тип модели фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_nodel_line_variety', to='filter_regulator.filterregulatorvariety', verbose_name='Тип'),
        ),
    ]
