# Generated by Django 5.2.4 on 2026-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0005_remove_filterregulator_filter_variety_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterregulator',
            name='name',
            field=models.TextField(blank=True, help_text='Текстовое название модели фильтр-регулятора', verbose_name='Название'),
        ),
    ]
