# Generated by Django 5.2.4 on 2026-05-12 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0006_alter_filterregulator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='body_material_text',
            field=models.CharField(blank=True, help_text='Материал корпус фильтр-регулятора', max_length=200, null=True, verbose_name='Корпус (текст)'),
        ),
        migrations.AlterField(
            model_name='filterregulator',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Материал корпус фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body', to='filter_regulator.filterregulatorbody', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='bowl_material_text',
            field=models.CharField(blank=True, help_text='Материал стакана фильтр-регулятора', max_length=200, null=True, verbose_name='Стакан (текст)'),
        ),
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='protection_material',
            field=models.CharField(help_text='Материал стакана фильтр-регулятора', max_length=200, verbose_name='Материал кожуха (текст)'),
        ),
    ]
