# Generated by Django 5.2.4 on 2026-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0007_filterregulatormodelline_body_material_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterregulator',
            name='pressure_inlet_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='pressure_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=8, help_text='Максимальное давление на выходе, бар', max_digits=6, null=True, verbose_name='P выход.макс, бар'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='pressure_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Минимальное давление на выходе, бар', max_digits=6, null=True, verbose_name='P выход.мин, бар'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='work_temp_max',
            field=models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='work_temp_min',
            field=models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С'),
        ),
    ]
