# Generated by Django 5.2.4 on 2026-05-25 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0008_filterregulator_pressure_inlet_max_and_more'),
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
        ('params', '0054_alter_threadsize_thread_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterregulator',
            name='pressure_inlet_max',
        ),
        migrations.RemoveField(
            model_name='filterregulator',
            name='pressure_max',
        ),
        migrations.RemoveField(
            model_name='filterregulator',
            name='pressure_min',
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='body_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_regulator_body_material', to='materials.materialgeneral', verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_regulator_ip', to='params.ipoption', verbose_name='Степень защиты IP'),
        ),
        migrations.AddField(
            model_name='filterregulator',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AlterField(
            model_name='filterregulator',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Корпус фильтр-регулятора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_body', to='filter_regulator.filterregulatorbody', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='filterregulator',
            name='drain_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_drain_variety', to='filter_regulator.drainvariety', verbose_name='Слив'),
        ),
    ]
