# Generated by Django 5.2.4 on 2026-05-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0003_remove_certdata_equipment_type_and_more'),
        ('filter_regulator', '0009_remove_filterregulator_pressure_inlet_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
    ]
