# Generated by Django 5.2.4 on 2026-05-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0010_filterregulatormodelline_cert_docs'),
        ('sku', '0004_alter_sku_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterregulator',
            name='sku',
            field=models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU'),
        ),
    ]
