# Generated by Django 5.2.7 on 2026-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0017_filterregulatormodelline_description_template_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='body_material_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с полем «Корпус (текст)».', verbose_name='Переводы материала корпуса (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='bowl_material_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с полем «Стакан (текст)».', verbose_name='Переводы материала стакана (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='filterregulatormodelline',
            name='protection_material_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с полем «Материал кожуха (текст)».', verbose_name='Переводы материала кожуха (ru/en/cn)'),
        ),
    ]
