# Generated by Django 5.2.7 on 2026-10-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_regulator', '0018_filterregulatormodelline_body_material_text_i18n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='body_material_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с body_material_text.', verbose_name='Переводы материала корпуса (ru/en/cn)'),
        ),
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='bowl_material_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с bowl_material_text.', verbose_name='Переводы материала стакана (ru/en/cn)'),
        ),
        migrations.AlterField(
            model_name='filterregulatormodelline',
            name='protection_material_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с protection_material.', verbose_name='Переводы материала кожуха (ru/en/cn)'),
        ),
    ]
