# Generated by Django 5.1.4 on 2025-02-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequesttype',
            name='symbolic_code',
            field=models.CharField(help_text='Название типа запроса', max_length=100),
        ),
    ]
