# Generated by Django 5.1.4 on 2025-02-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0002_alter_clientrequesttype_symbolic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='need_electric_actuator_selection',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='need_pneumatic_actuator_selection',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='need_valve_selection',
        ),
    ]
