# Generated by Django 5.1.4 on 2025-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0003_remove_clientrequest_need_electric_actuator_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='request_date',
            field=models.DateField(),
        ),
    ]
