# Generated by Django 4.2.19 on 2025-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0004_alter_clientrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequestitem',
            name='item_no',
            field=models.IntegerField(default=0, help_text='Номер строки в таблице запроса', verbose_name='Номер строки в таблице запроса'),
        ),
        migrations.AlterField(
            model_name='clientrequestitem',
            name='request_line_number',
            field=models.IntegerField(blank=True, help_text='Номер строки в запросе клиента', null=True, verbose_name='Номер строки в запросе клиента'),
        ),
        migrations.AlterField(
            model_name='clientrequestitem',
            name='request_line_ol',
            field=models.CharField(blank=True, help_text='Идентификатор (номер) ОЛ для этой строки в запросе клиента', max_length=255, null=True, verbose_name='Идентификатор (номер) ОЛ для этой строки в запросе клиента'),
        ),
    ]
