# Generated by Django 5.1.4 on 2025-02-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0005_alter_clientrequestitem_item_no_and_more'),
        ('valve_data', '0003_remove_valveline_voltage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valverequirement',
            name='valve_model_model_line',
            field=models.ForeignKey(blank=True, help_text='Требования к арматуре', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_model_model_line_for_request_line', to='valve_data.valvemodeldata'),
        ),
    ]
