"""Заполняет en/cn переводы name_template/description_template серий.

Ключ перевода — точная ru-строка шаблона (с плейсхолдерами {field} как есть).
Шаблоны, которых нет в словаре, остаются ru (fallback) — команда сообщает о них.

Идемпотентна: по умолчанию заполняет только отсутствующие локали;
`--force` — перестроить en/cn заново из словаря (затирает ручные правки).
"""

from django.core.management.base import BaseCommand
from django.apps import apps


MODELS = (
    'cable_glands.CableGlandModelLine',
    'pneumatic_actuators.PneumaticActuatorModelLine',
    'pneumatic_fittings.PneumaticFittingModelLine',
    'solenoid_valves.DirectionalValveModelLine',
    'pa_controls.LimitSwitchModelLine',
    'pa_controls.PosiModelLine',
    'filter_regulator.FilterRegulatorModelLine',
    'gearbox.GearBoxModelLine',
)

FIELDS = ('name_template', 'description_template', 'title_template')


def _tr(en, cn):
    return (en, cn)


TRANSLATIONS = {
    'name_template': {
        # ── Кабельные вводы ──
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  d кабеля {cable_diameter} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd_short}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; cable d {cable_diameter} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd_short}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆直径 {cable_diameter} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd_short}'),
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  d кабеля {cable_diameter} мм; d МР {metal_sleeve_range} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd_short}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; cable d {cable_diameter} mm; MS d {metal_sleeve_range} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd_short}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆直径 {cable_diameter} mm; 软管直径 {metal_sleeve_range} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd_short}'),
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  Внутр. d кабеля {cable_diameter} мм; Внешн. d кабеля {cable_diameter_outer} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd_short}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; Inner cable d {cable_diameter} mm; Outer cable d {cable_diameter_outer} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd_short}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆内径 {cable_diameter} mm; 电缆外径 {cable_diameter_outer} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd_short}'),
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  Внутр. d кабеля {cable_diameter} мм; Внешн. d кабеля {cable_diameter_outer} мм; d МР {metal_sleeve_range} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd_short}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; Inner cable d {cable_diameter} mm; Outer cable d {cable_diameter_outer} mm; MS d {metal_sleeve_range} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd_short}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆内径 {cable_diameter} mm; 电缆外径 {cable_diameter_outer} mm; 软管直径 {metal_sleeve_range} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd_short}'),
        # ── Пневмопривод ──
        '{model_code} Пневмопривод {brand} {variety_description} {construction_name} Пружин: {springs_qty}; Положение безопасности:{safety_position}; {ip}; Взрывозащита: {exd_short}; Темп. {temperature}};':
            _tr('{model_code} Pneumatic actuator {brand} {variety_description} {construction_name} Springs: {springs_qty}; Fail-safe position: {safety_position}; {ip}; Explosion protection: {exd_short}; Temp. {temperature}};',
                '{model_code} 气动执行器 {brand} {variety_description} {construction_name} 弹簧: {springs_qty}; 安全位置: {safety_position}; {ip}; 防爆: {exd_short}; 温度 {temperature}};'),
        # ── Пневмофитинги ──
        '{model_code} {fixation_method} {shape} {brand}, {thread_inner_outer} резьба {thread}, для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 304':
            _tr('{model_code} {fixation_method} {shape} {brand}, {thread_inner_outer} thread {thread}, for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 304',
                '{model_code} {fixation_method} {shape} {brand}, {thread_inner_outer} 螺纹 {thread}, 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 304'),
        '{model_code} Фитинг цанговый прямой Artorq, {thread_inner_outer} резьба {thread}, для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316':
            _tr('{model_code} Straight collet fitting Artorq, {thread_inner_outer} thread {thread}, for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316',
                '{model_code} 直通快插接头 Artorq, {thread_inner_outer} 螺纹 {thread}, 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316'),
        '{model_code} Фитинг цанговый L угловой Artorq, {thread_inner_outer} резьба {thread}, для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 304':
            _tr('{model_code} L-shape collet fitting Artorq, {thread_inner_outer} thread {thread}, for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 304',
                '{model_code} L型角通快插接头 Artorq, {thread_inner_outer} 螺纹 {thread}, 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 304'),
        '{model_code} Фитинг цанговый L угловой Artorq, {thread_inner_outer} резьба {thread}, для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316':
            _tr('{model_code} L-shape collet fitting Artorq, {thread_inner_outer} thread {thread}, for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316',
                '{model_code} L型角通快插接头 Artorq, {thread_inner_outer} 螺纹 {thread}, 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316'),
        '{model_code} Глушитель Artorq {thread} {thread_inner_outer} резьба, латунь, сетчатый фильтр из спеченной бронзы, "Конус", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар':
            _tr('{model_code} Silencer Artorq {thread} {thread_inner_outer} thread, brass, sintered bronze mesh filter, "Cone", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar',
                '{model_code} 消声器 Artorq {thread} {thread_inner_outer} 螺纹, 黄铜, 烧结青铜网过滤器, "锥形", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar'),
        '{model_code} Глушитель Artorq {thread} {thread_inner_outer} резьба, латунь, сетчатый фильтр из нерж. стали, "таблетка", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар':
            _tr('{model_code} Silencer Artorq {thread} {thread_inner_outer} thread, brass, stainless steel mesh filter, "tablet", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar',
                '{model_code} 消声器 Artorq {thread} {thread_inner_outer} 螺纹, 黄铜, 不锈钢网过滤器, "片式", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar'),
        '{model_code} Фитинг цанговый прямой Camozzi, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение NBR':
            _tr('{model_code} Straight collet fitting Camozzi, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal NBR',
                '{model_code} 直通快插接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 NBR'),
        '{model_code} Фитинг цанговый прямой Camozzi, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение PTFE':
            _tr('{model_code} Straight collet fitting Camozzi, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal PTFE',
                '{model_code} 直通快插接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 PTFE'),
        '{model_code} Фитинг c накидной гайкой угловой {swivel} Camozzi, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение NBR':
            _tr('{model_code} Swivel-nut angle fitting {swivel} Camozzi, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal NBR',
                '{model_code} 带活接螺母角通接头 {swivel} Camozzi, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 NBR'),
        '{model_code} Фитинг c накидной гайкой прямой Camozzi, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение NBR':
            _tr('{model_code} Swivel-nut straight fitting Camozzi, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal NBR',
                '{model_code} 带活接螺母直通接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 NBR'),
        '{model_code} Глушитель Camozzi  {thread} {thread_inner_outer} резьба, латунь, сетчатый фильтр из нерж. стали, "таблетка", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар':
            _tr('{model_code} Silencer Camozzi {thread} {thread_inner_outer} thread, brass, stainless steel mesh filter, "tablet", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar',
                '{model_code} 消声器 Camozzi {thread} {thread_inner_outer} 螺纹, 黄铜, 不锈钢网过滤器, "片式", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar'),
        '{model_code} Глушитель Camozzi {thread} {thread_inner_outer} резьба, латунь, сетчатый фильтр из спеченной бронзы, "Конус", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар':
            _tr('{model_code} Silencer Camozzi {thread} {thread_inner_outer} thread, brass, sintered bronze mesh filter, "Cone", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar',
                '{model_code} 消声器 Camozzi {thread} {thread_inner_outer} 螺纹, 黄铜, 烧结青铜网过滤器, "锥形", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar'),
        '{model_code} Фитинг цанговый L угловой, {swivel}, Camozzi, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение PTFE':
            _tr('{model_code} L-shape collet fitting, {swivel}, Camozzi, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal PTFE',
                '{model_code} L型角通快插接头, {swivel}, Camozzi, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 PTFE'),
        '{model_code} Фитинг цанговый L угловой, {swivel}, Camozzi, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение NBR':
            _tr('{model_code} L-shape collet fitting, {swivel}, Camozzi, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal NBR',
                '{model_code} L型角通快插接头, {swivel}, Camozzi, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 NBR'),
        '{model_code} Фитинг цанговый L угловой, {swivel}, Camozzi, из технополимера, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение NBR':
            _tr('{model_code} L-shape collet fitting, {swivel}, Camozzi, technopolymer, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal NBR',
                '{model_code} L型角通快插接头, {swivel}, Camozzi, 工程塑料, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 NBR'),
        '{model_code} Заглушка Camozzi  {thread} {thread_inner_outer} резьба Т раб. {temperature_range}, Р раб. {pressure_range}':
            _tr('{model_code} Plug Camozzi {thread} {thread_inner_outer} thread, Oper. temp. {temperature_range}, Oper. pressure {pressure_range}',
                '{model_code} 堵头 Camozzi {thread} {thread_inner_outer} 螺纹, 工作温度 {temperature_range}, 工作压力 {pressure_range}'),
        '{model_code} Фитинг обжимной с 2 врезными кольцами L угловой Hy-Lock, {thread_inner_outer} резьба {thread}, для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316':
            _tr('{model_code} L-shape compression fitting with 2 cutting rings Hy-Lock, {thread_inner_outer} thread {thread}, for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316',
                '{model_code} L型角通双卡套卡套式接头 Hy-Lock, {thread_inner_outer} 螺纹 {thread}, 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316'),
        '{model_code} Фитинг обжимной с 2 врезными кольцами прямой Hy-Lock, {thread_inner_outer} резьба {thread}, для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316':
            _tr('{model_code} Straight compression fitting with 2 cutting rings Hy-Lock, {thread_inner_outer} thread {thread}, for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316',
                '{model_code} 直通双卡套卡套式接头 Hy-Lock, {thread_inner_outer} 螺纹 {thread}, 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316'),
        '{model_code} Фитинг c накидной гайкой прямой {swivel} СМАРТА, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение Нитрил / фторполимер':
            _tr('{model_code} Swivel-nut straight fitting {swivel} SMARTA, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal Nitrile / fluoropolymer',
                '{model_code} 带活接螺母直通接头 {swivel} SMARTA, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 丁腈/氟聚合物'),
        '{model_code} Фитинг c накидной гайкой угловой {swivel} СМАРТА, {thread_inner_outer} резьба {thread}, для трубки пластик наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, уплотнение Нитрил / фторполимер':
            _tr('{model_code} Swivel-nut angle fitting {swivel} SMARTA, {thread_inner_outer} thread {thread}, for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, seal Nitrile / fluoropolymer',
                '{model_code} 带活接螺母角通接头 {swivel} SMARTA, {thread_inner_outer} 螺纹 {thread}, 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 密封 丁腈/氟聚合物'),
        # ── Соленоидные клапаны ──
        '{model_code} Пневмораспределитель {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; корпус: {body_material};  катушка: {solenoid_body_material}; уплотнение {sealing_material_specified}; P {pressure_range} бар; T {temperature_range}°С;  {exd_short}; {ip}; {power_supply};':
            _tr('{model_code} Solenoid valve {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; body: {body_material}; coil: {solenoid_body_material}; seal {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd_short}; {ip}; {power_supply};',
                '{model_code} 电磁阀 {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; 阀体: {body_material}; 线圈: {solenoid_body_material}; 密封 {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd_short}; {ip}; {power_supply};'),
        '{model_code} Пневмораспределитель {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; корпус: {body_material};  катушка: {solenoid_body_material}; уплотнение {sealing_material_specified}; P {pressure_range} бар; T {temperature_range}°С;  {exd_short} ; {ip}; {power_supply};':
            _tr('{model_code} Solenoid valve {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; body: {body_material}; coil: {solenoid_body_material}; seal {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd_short}; {ip}; {power_supply};',
                '{model_code} 电磁阀 {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; 阀体: {body_material}; 线圈: {solenoid_body_material}; 密封 {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd_short}; {ip}; {power_supply};'),
        '{model_code} Пневмораспределитель {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; корпус: {body_material};  катушка: {solenoid_body_material}{solenoid_body_material_specified}; уплотнение {sealing_material_specified}; P {pressure_range} бар; T {temperature_range}°С;  {exd}; {ip}; {power_supply};':
            _tr('{model_code} Solenoid valve {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; body: {body_material}; coil: {solenoid_body_material}{solenoid_body_material_specified}; seal {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd}; {ip}; {power_supply};',
                '{model_code} 电磁阀 {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; 阀体: {body_material}; 线圈: {solenoid_body_material}{solenoid_body_material_specified}; 密封 {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd}; {ip}; {power_supply};'),
        '{model_code} Пневмораспределитель {brand} {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; корпус: {body_material};  катушка: {solenoid_body_material_specified}; уплотнение {sealing_material_specified}; P {pressure_range} бар; T {temperature_range}°С;  {exd_short}; {ip}; {power_supply};':
            _tr('{model_code} Solenoid valve {brand} {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; body: {body_material}; coil: {solenoid_body_material_specified}; seal {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd_short}; {ip}; {power_supply};',
                '{model_code} 电磁阀 {brand} {function} {operation} {actuation}; {pneumatic_connection}; {pneumatic_connection_thread}; 阀体: {body_material}; 线圈: {solenoid_body_material_specified}; 密封 {sealing_material_specified}; P {pressure_range} bar; T {temperature_range}°C; {exd_short}; {ip}; {power_supply};'),
        # ── БКВ ──
        '{model_code} Блок концевых выключателей {brand};  {points}, тип датчика: {sensor_variety}, {primary_sensor_signal_type},  {primary_sensor_contact_form}; {ip}, Взрывозащита: {exd}; Т.окр. {work_temp_min}..{work_temp_max} °С, Материал корпуса: {body_material_specified}, Отверстия под КВ:{cable_glands_holes}, вес {weight}кг.':
            _tr('{model_code} Limit switch box {brand}; {points}, sensor type: {sensor_variety}, {primary_sensor_signal_type}, {primary_sensor_contact_form}; {ip}, Explosion protection: {exd}; Ambient temp. {work_temp_min}..{work_temp_max} °C, Body material: {body_material_specified}, Cable entries: {cable_glands_holes}, weight {weight}kg.',
                '{model_code} 限位开关盒 {brand}; {points}, 传感器类型: {sensor_variety}, {primary_sensor_signal_type}, {primary_sensor_contact_form}; {ip}, 防爆: {exd}; 环境温度 {work_temp_min}..{work_temp_max} °C, 壳体材料: {body_material_specified}, 电缆入口: {cable_glands_holes}, 重量 {weight}kg.'),
        '{model_code} Блок концевых выключателей {brand};  {points}, тип датчика: {sensor_variety}, {primary_sensor_signal_type},  {primary_sensor_contact_form}; {ip}, Взрывозащита: {exd_short}; Т.окр. {work_temp_min}..{work_temp_max} °С, Материал корпуса: {body_material_specified}, Отверстия под КВ:{cable_glands_holes}, вес {weight}кг.':
            _tr('{model_code} Limit switch box {brand}; {points}, sensor type: {sensor_variety}, {primary_sensor_signal_type}, {primary_sensor_contact_form}; {ip}, Explosion protection: {exd_short}; Ambient temp. {work_temp_min}..{work_temp_max} °C, Body material: {body_material_specified}, Cable entries: {cable_glands_holes}, weight {weight}kg.',
                '{model_code} 限位开关盒 {brand}; {points}, 传感器类型: {sensor_variety}, {primary_sensor_signal_type}, {primary_sensor_contact_form}; {ip}, 防爆: {exd_short}; 环境温度 {work_temp_min}..{work_temp_max} °C, 壳体材料: {body_material_specified}, 电缆入口: {cable_glands_holes}, 重量 {weight}kg.'),
        'БКВ TopWorx Emerson':
            _tr('LSB TopWorx Emerson', '限位开关盒 TopWorx Emerson'),
        # ── Позиционеры ──
        '{model_code} Позиционер {acting_type} для приводов {actuator_action}  {brand};  Т.окр.  {work_temp_min}..{work_temp_max} °С; Исп: {exd_short}; Материал корпуса: {body_material}; Присоединия: {body_connection}; Сигналы: {signal_profile_summary};':
            _tr('{model_code} Positioner {acting_type} for {actuator_action} actuators {brand}; Ambient temp. {work_temp_min}..{work_temp_max} °C; Ver.: {exd_short}; Body material: {body_material}; Connections: {body_connection}; Signals: {signal_profile_summary};',
                '{model_code} 定位器 {acting_type} 用于 {actuator_action} 执行器 {brand}; 环境温度 {work_temp_min}..{work_temp_max} °C; 型式: {exd_short}; 壳体材料: {body_material}; 连接: {body_connection}; 信号: {signal_profile_summary};'),
        '{model_code} Позиционер {acting_type} для приводов {actuator_action}  {brand};  Т.окр.  {work_temp_min}..{work_temp_max} °С; Исп: {exd}; Материал корпуса: {body_material}; Присоединия: {body_connection}; Сигналы: {signal_profile_summary};':
            _tr('{model_code} Positioner {acting_type} for {actuator_action} actuators {brand}; Ambient temp. {work_temp_min}..{work_temp_max} °C; Ver.: {exd}; Body material: {body_material}; Connections: {body_connection}; Signals: {signal_profile_summary};',
                '{model_code} 定位器 {acting_type} 用于 {actuator_action} 执行器 {brand}; 环境温度 {work_temp_min}..{work_temp_max} °C; 型式: {exd}; 壳体材料: {body_material}; 连接: {body_connection}; 信号: {signal_profile_summary};'),
        # ── Фильтр-регуляторы ──
        '{model_code} {filter_variety} {brand}; Расход {flow_rate} л/мин; {drain_variety}; Т.окр. {work_temp_min}..{work_temp_max} °С, Рег.давления {pressure_min}..{pressure_max} бар; Порты: {thread}; фильтрация {filtration_rating} мкм;':
            _tr('{model_code} {filter_variety} {brand}; Flow {flow_rate} l/min; {drain_variety}; Ambient temp. {work_temp_min}..{work_temp_max} °C, Pressure regulation {pressure_min}..{pressure_max} bar; Ports: {thread}; filtration {filtration_rating} µm;',
                '{model_code} {filter_variety} {brand}; 流量 {flow_rate} l/min; {drain_variety}; 环境温度 {work_temp_min}..{work_temp_max} °C, 压力调节 {pressure_min}..{pressure_max} bar; 接口: {thread}; 过滤精度 {filtration_rating} µm;'),
        # ── Ручные дублёры ──
        '{model_code} {gearbox_variety} {is_declutchable} {gearbox_output_variety} {brand} Макс: {max_output_torque} Нм; {ip};  Темп. {work_temp_min}..{work_temp_max}°С; К приводу: {mounting_plate_top_list_text}, {stem_shape_top} {stem_size_top}, К арматуре: {mounting_plate_bottom_list_text} {stem_shape_bottom} {stem_size_bottom}':
            _tr('{model_code} {gearbox_variety} {is_declutchable} {gearbox_output_variety} {brand} Max: {max_output_torque} Nm; {ip}; Temp. {work_temp_min}..{work_temp_max}°C; To actuator: {mounting_plate_top_list_text}, {stem_shape_top} {stem_size_top}, To valve: {mounting_plate_bottom_list_text} {stem_shape_bottom} {stem_size_bottom}',
                '{model_code} {gearbox_variety} {is_declutchable} {gearbox_output_variety} {brand} 最大: {max_output_torque} Nm; {ip}; 温度 {work_temp_min}..{work_temp_max}°C; 接执行器: {mounting_plate_top_list_text}, {stem_shape_top} {stem_size_top}, 接阀门: {mounting_plate_bottom_list_text} {stem_shape_bottom} {stem_size_bottom}'),
    },
    'description_template': {
        # ── Кабельные вводы ──
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread}; d кабеля {cable_diameter} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd}; {extra_params}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; cable d {cable_diameter} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd}; {extra_params}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆直径 {cable_diameter} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd}; {extra_params}'),
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  d кабеля {cable_diameter} мм; d металлорукава {metal_sleeve_range} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd}; Для металлорукава {metal_sleeve}; {extra_params}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; cable d {cable_diameter} mm; metal sleeve d {metal_sleeve_range} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd}; For metal sleeve {metal_sleeve}; {extra_params}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆直径 {cable_diameter} mm; 软管直径 {metal_sleeve_range} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd}; 适用软管 {metal_sleeve}; {extra_params}'),
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  Внутр. d кабеля {cable_diameter} мм; Внешн. d кабеля {cable_diameter_outer} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd}; {extra_params}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; Inner cable d {cable_diameter} mm; Outer cable d {cable_diameter_outer} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd}; {extra_params}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆内径 {cable_diameter} mm; 电缆外径 {cable_diameter_outer} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd}; {extra_params}'),
        '{model_code} Кабельный ввод {brand} {cable_types}; {body_material}; Резьба {thread};  Внутр. d кабеля {cable_diameter} мм; Внешн. d кабеля {cable_diameter_outer} мм; d металлорукава {metal_sleeve_range} мм; {ip}; Темп. {temp_range} °C; Вес {weight} кг; {exd}; Для металлорукава {metal_sleeve}; {extra_params}':
            _tr('{model_code} Cable gland {brand} {cable_types}; {body_material}; Thread {thread}; Inner cable d {cable_diameter} mm; Outer cable d {cable_diameter_outer} mm; metal sleeve d {metal_sleeve_range} mm; {ip}; Temp. {temp_range} °C; Weight {weight} kg; {exd}; For metal sleeve {metal_sleeve}; {extra_params}',
                '{model_code} 电缆接头 {brand} {cable_types}; {body_material}; 螺纹 {thread}; 电缆内径 {cable_diameter} mm; 电缆外径 {cable_diameter_outer} mm; 软管直径 {metal_sleeve_range} mm; {ip}; 温度 {temp_range} °C; 重量 {weight} kg; {exd}; 适用软管 {metal_sleeve}; {extra_params}'),
        # ── Пневмофитинги ──
        '{model_code} {fixation_method} {shape} {brand}, {thread_inner_outer} резьба {thread}, цанговый зажим для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 304, в сборе с уплотнительным кольцом, трубки для присоединения: нержавеющая сталь, медь':
            _tr('{model_code} {fixation_method} {shape} {brand}, {thread_inner_outer} thread {thread}, collet clamp for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 304, assembled with sealing ring, connection tubing: stainless steel, copper',
                '{model_code} {fixation_method} {shape} {brand}, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 304, 配密封圈, 适用气管: 不锈钢、铜'),
        '{model_code} Фитинг цанговый прямой Artorq, {thread_inner_outer} резьба {thread}, цанговый зажим для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316, в сборе с уплотнительным кольцом, трубки для присоединения: нержавеющая сталь, медь':
            _tr('{model_code} Straight collet fitting Artorq, {thread_inner_outer} thread {thread}, collet clamp for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316, assembled with sealing ring, connection tubing: stainless steel, copper',
                '{model_code} 直通快插接头 Artorq, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316, 配密封圈, 适用气管: 不锈钢、铜'),
        '{model_code} Фитинг цанговый L угловой Artorq, {thread_inner_outer} резьба {thread}, цанговый зажим для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 304, в сборе с уплотнительным кольцом, трубки для присоединения: нержавеющая сталь, медь':
            _tr('{model_code} L-shape collet fitting Artorq, {thread_inner_outer} thread {thread}, collet clamp for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 304, assembled with sealing ring, connection tubing: stainless steel, copper',
                '{model_code} L型角通快插接头 Artorq, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 304, 配密封圈, 适用气管: 不锈钢、铜'),
        '{model_code} Глушитель Artorq {thread} {thread_inner_outer} резьба, корпус - латунь, сетчатый фильтрующий элемент из спеченной бронзы, корпус - "Конус", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар, уровнь шума {noise_level} Дб,':
            _tr('{model_code} Silencer Artorq {thread} {thread_inner_outer} thread, body - brass, sintered bronze mesh filter element, body - "Cone", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar, noise level {noise_level} dB,',
                '{model_code} 消声器 Artorq {thread} {thread_inner_outer} 螺纹, 壳体 - 黄铜, 烧结青铜网过滤元件, 壳体 - "锥形", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar, 噪音 {noise_level} dB,'),
        '{model_code} Глушитель Artorq {thread} {thread_inner_outer} резьба, корпус - латунь, сетчатый фильтрующий элемент из нерж. стали, корпус - "таблетка", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар, уровнь шума {noise_level} Дб,':
            _tr('{model_code} Silencer Artorq {thread} {thread_inner_outer} thread, body - brass, stainless steel mesh filter element, body - "tablet", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar, noise level {noise_level} dB,',
                '{model_code} 消声器 Artorq {thread} {thread_inner_outer} 螺纹, 壳体 - 黄铜, 不锈钢网过滤元件, 壳体 - "片式", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar, 噪音 {noise_level} dB,'),
        '{model_code} Фитинг цанговый прямой Camozzi, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - латунь ОТ58 покрытая никелем, в сборе с уплотнительным кольцом NBR, трубки для присоединения: полиуретан, полиэтилен, полиамид, полиэстер, PTFE':
            _tr('{model_code} Straight collet fitting Camozzi, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated OT58 brass, assembled with NBR sealing ring, connection tubing: polyurethane, polyethylene, polyamide, polyester, PTFE',
                '{model_code} 直通快插接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜 OT58, 配 NBR 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺、聚酯、PTFE'),
        '{model_code} Фитинг цанговый прямой Camozzi, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - латунь ОТ58 покрытая никелем, в сборе с уплотнительным кольцом NBR, трубки для присоединения: полиуретан, полиэтилен, полиамид, полиэстер, NBR':
            _tr('{model_code} Straight collet fitting Camozzi, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated OT58 brass, assembled with NBR sealing ring, connection tubing: polyurethane, polyethylene, polyamide, polyester, NBR',
                '{model_code} 直通快插接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜 OT58, 配 NBR 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺、聚酯、NBR'),
        '{model_code} Фитинг цанговый прямой Camozzi, из технополимера, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - латунь ОТ58 покрытая никелем, в сборе с уплотнительным кольцом NBR, трубки для присоединения: полиуретан (TPU)':
            _tr('{model_code} Straight collet fitting Camozzi, technopolymer, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated OT58 brass, assembled with NBR sealing ring, connection tubing: polyurethane (TPU)',
                '{model_code} 直通快插接头 Camozzi, 工程塑料, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜 OT58, 配 NBR 密封圈, 适用气管: 聚氨酯 (TPU)'),
        '{model_code} Фитинг цанговый прямой Camozzi, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - латунь ОТ58 покрытая никелем, в сборе с уплотнительным кольцом PTFE, трубки для присоединения: полиуретан, полиэтилен, полиамид, полиэстер, PTFE':
            _tr('{model_code} Straight collet fitting Camozzi, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated OT58 brass, assembled with PTFE sealing ring, connection tubing: polyurethane, polyethylene, polyamide, polyester, PTFE',
                '{model_code} 直通快插接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜 OT58, 配 PTFE 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺、聚酯、PTFE'),
        '{model_code} Фитинг c накидной гайкой угловой {swivel} Camozzi, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - никелерованная латунь, в сборе с уплотнительным кольцом NBR, трубки для присоединения: полиуретан, полиэтилен, полиамид, полиэстер, PTFE':
            _tr('{model_code} Swivel-nut angle fitting {swivel} Camozzi, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated brass, assembled with NBR sealing ring, connection tubing: polyurethane, polyethylene, polyamide, polyester, PTFE',
                '{model_code} 带活接螺母角通接头 {swivel} Camozzi, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜, 配 NBR 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺、聚酯、PTFE'),
        '{model_code} Фитинг c накидной гайкой прямой Camozzi, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - никелерованная латунь, в сборе с уплотнительным кольцом NBR, трубки для присоединения: полиуретан, полиэтилен, полиамид, полиэстер, PTFE':
            _tr('{model_code} Swivel-nut straight fitting Camozzi, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated brass, assembled with NBR sealing ring, connection tubing: polyurethane, polyethylene, polyamide, polyester, PTFE',
                '{model_code} 带活接螺母直通接头 Camozzi, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜, 配 NBR 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺、聚酯、PTFE'),
        '{model_code} Глушитель Camozzi  {thread} {thread_inner_outer} резьба, корпус - латунь, сетчатый фильтрующий элемент из нерж. стали, корпус - "таблетка", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар, уровнь шума {noise_level} Дб,':
            _tr('{model_code} Silencer Camozzi {thread} {thread_inner_outer} thread, body - brass, stainless steel mesh filter element, body - "tablet", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar, noise level {noise_level} dB,',
                '{model_code} 消声器 Camozzi {thread} {thread_inner_outer} 螺纹, 壳体 - 黄铜, 不锈钢网过滤元件, 壳体 - "片式", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar, 噪音 {noise_level} dB,'),
        '{model_code} Глушитель Camozzi {thread} {thread_inner_outer} резьба, корпус - латунь, сетчатый фильтрующий элемент из спеченной бронзы, корпус - "Конус", расход {flow_rate} Нл/мин; P раб.макс. {operating_pressure} бар, уровнь шума {noise_level} Дб,':
            _tr('{model_code} Silencer Camozzi {thread} {thread_inner_outer} thread, body - brass, sintered bronze mesh filter element, body - "Cone", flow {flow_rate} Nl/min; max oper. pressure {operating_pressure} bar, noise level {noise_level} dB,',
                '{model_code} 消声器 Camozzi {thread} {thread_inner_outer} 螺纹, 壳体 - 黄铜, 烧结青铜网过滤元件, 壳体 - "锥形", 流量 {flow_rate} Nl/min; 最大工作压力 {operating_pressure} bar, 噪音 {noise_level} dB,'),
        '{model_code} Заглушка Camozzi  {thread} {thread_inner_outer} резьба Т раб. {temperature_range}, Р раб. {pressure_range} корпус - латунь ОТ58 покрытая никелем':
            _tr('{model_code} Plug Camozzi {thread} {thread_inner_outer} thread, Oper. temp. {temperature_range}, Oper. pressure {pressure_range}, body - nickel-plated OT58 brass',
                '{model_code} 堵头 Camozzi {thread} {thread_inner_outer} 螺纹, 工作温度 {temperature_range}, 工作压力 {pressure_range}, 壳体 - 镀镍黄铜 OT58'),
        '{model_code} Фитинг обжимной с 2 врезными кольцами L угловой Hy-Lock, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316, в сборе с уплотнительным кольцом, трубки для присоединения: нержавеющая сталь, медь':
            _tr('{model_code} L-shape compression fitting with 2 cutting rings Hy-Lock, {thread_inner_outer} thread {thread}, collet clamp for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316, assembled with sealing ring, connection tubing: stainless steel, copper',
                '{model_code} L型角通双卡套卡套式接头 Hy-Lock, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316, 配密封圈, 适用气管: 不锈钢、铜'),
        '{model_code} Фитинг обжимной с 2 врезными кольцами прямой Hy-Lock, {thread_inner_outer} резьба {thread}, цанговый зажим для трубки из металла наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - Нержавеющая сталь 316, в сборе с уплотнительным кольцом, трубки для присоединения: нержавеющая сталь, медь':
            _tr('{model_code} Straight compression fitting with 2 cutting rings Hy-Lock, {thread_inner_outer} thread {thread}, collet clamp for metal tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - stainless steel 316, assembled with sealing ring, connection tubing: stainless steel, copper',
                '{model_code} 直通双卡套卡套式接头 Hy-Lock, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用金属管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 不锈钢 316, 配密封圈, 适用气管: 不锈钢、铜'),
        '{model_code} Фитинг c накидной гайкой прямой {swivel} СМАРТА, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - никелерованная латунь, в сборе с уплотнительным кольцом Нитрил / фторполимер, трубки для присоединения: полиуретан, полиэтилен, полиамид':
            _tr('{model_code} Swivel-nut straight fitting {swivel} SMARTA, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated brass, assembled with Nitrile / fluoropolymer sealing ring, connection tubing: polyurethane, polyethylene, polyamide',
                '{model_code} 带活接螺母直通接头 {swivel} SMARTA, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜, 配 丁腈/氟聚合物 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺'),
        '{model_code} Фитинг c накидной гайкой угловой {swivel} СМАРТА, {thread_inner_outer} резьба {thread}, цанговый зажим для пластикой трубки наружн.диам. {pipe_diameter} мм, Т раб. {temperature_range} °С, Р раб. {pressure_range} бар, корпус - никелерованная латунь, в сборе с уплотнительным кольцом Нитрил / фторполимер, трубки для присоединения: полиуретан, полиэтилен, полиамид':
            _tr('{model_code} Swivel-nut angle fitting {swivel} SMARTA, {thread_inner_outer} thread {thread}, collet clamp for plastic tube outer dia. {pipe_diameter} mm, Oper. temp. {temperature_range} °C, Oper. pressure {pressure_range} bar, body - nickel-plated brass, assembled with Nitrile / fluoropolymer sealing ring, connection tubing: polyurethane, polyethylene, polyamide',
                '{model_code} 带活接螺母角通接头 {swivel} SMARTA, {thread_inner_outer} 螺纹 {thread}, 快插夹紧 适用塑料管外径 {pipe_diameter} mm, 工作温度 {temperature_range} °C, 工作压力 {pressure_range} bar, 壳体 - 镀镍黄铜, 配 丁腈/氟聚合物 密封圈, 适用气管: 聚氨酯、聚乙烯、聚酰胺'),
        # ── Соленоидные клапаны ──
        '{model_code} Пневмораспределитель {operation} {construction} функция {function}; тип пневмоприсоединения - {pneumatic_connection}; присоединение {pneumatic_connection_thread}; Kv-{kv} м3/ч; корпус {body_material}; катушка {solenoid_body_material}; уплотнение {sealing_material_specified}; Давление {pressure_range} бар; Темп.окр.среды {temperature_range}°С; отверстие под кабельный ввод {cable_glands_holes},  взрывозащита {exd}; {ip}; Dn {dn} мм; Питание {power_supply}; Мощность холодного/ном/удерж: {power_consumption_start} /  {power_consumption_hot} / {power_consumption_hold}, Вт; Ручной дублер: {manual_override}; макс. плотность рабочей среды {medium_density_max} сСт (мм2/с); Класс изоляции соленоида: {solenoid_insulation_class}; макс 5 циклов/сек; вес {weight}':
            _tr('{model_code} Solenoid valve {operation} {construction} function {function}; pneumatic connection type - {pneumatic_connection}; connection {pneumatic_connection_thread}; Kv-{kv} m3/h; body {body_material}; coil {solenoid_body_material}; seal {sealing_material_specified}; Pressure {pressure_range} bar; Ambient temp. {temperature_range}°C; cable entry {cable_glands_holes}, explosion protection {exd}; {ip}; DN {dn} mm; Power supply {power_supply}; Inrush/rated/holding power: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; Manual override: {manual_override}; max. medium density {medium_density_max} cSt (mm2/s); Solenoid insulation class: {solenoid_insulation_class}; max 5 cycles/s; weight {weight}',
                '{model_code} 电磁阀 {operation} {construction} 功能 {function}; 气动连接类型 - {pneumatic_connection}; 连接 {pneumatic_connection_thread}; Kv-{kv} m3/h; 阀体 {body_material}; 线圈 {solenoid_body_material}; 密封 {sealing_material_specified}; 压力 {pressure_range} bar; 环境温度 {temperature_range}°C; 电缆入口 {cable_glands_holes}, 防爆 {exd}; {ip}; DN {dn} mm; 电源 {power_supply}; 启动/额定/保持功率: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; 手动超越: {manual_override}; 介质最大密度 {medium_density_max} cSt (mm2/s); 线圈绝缘等级: {solenoid_insulation_class}; 最大 5 次/秒; 重量 {weight}'),
        '{model_code} Пневмораспределитель {operation} {construction} функция {function}; тип пневмоприсоединения - {pneumatic_connection}; присоединение {pneumatic_connection_thread}; Kv-{kv} м3/ч; корпус {body_material}; катушка {solenoid_body_material}; уплотнение {sealing_material_specified}; Давление {pressure_range} бар; Темп.окр.среды {temperature_range}°С; отверстие под кабельный ввод {cable_glands_holes},  взрывозащита {exd}; {ip}; Dn {dn} мм; Питание {power_supply}; Мощность холодного/ном/удерж: {power_consumption_start} /  {power_consumption_hot} / {power_consumption_hold}, Вт; Ручной дублер: {manual_override}; макс. плотность рабочей среды {medium_density_max} сСт (мм2/с); Класс изоляции соленоида: {solenoid_insulation_class}; вес {weight}':
            _tr('{model_code} Solenoid valve {operation} {construction} function {function}; pneumatic connection type - {pneumatic_connection}; connection {pneumatic_connection_thread}; Kv-{kv} m3/h; body {body_material}; coil {solenoid_body_material}; seal {sealing_material_specified}; Pressure {pressure_range} bar; Ambient temp. {temperature_range}°C; cable entry {cable_glands_holes}, explosion protection {exd}; {ip}; DN {dn} mm; Power supply {power_supply}; Inrush/rated/holding power: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; Manual override: {manual_override}; max. medium density {medium_density_max} cSt (mm2/s); Solenoid insulation class: {solenoid_insulation_class}; weight {weight}',
                '{model_code} 电磁阀 {operation} {construction} 功能 {function}; 气动连接类型 - {pneumatic_connection}; 连接 {pneumatic_connection_thread}; Kv-{kv} m3/h; 阀体 {body_material}; 线圈 {solenoid_body_material}; 密封 {sealing_material_specified}; 压力 {pressure_range} bar; 环境温度 {temperature_range}°C; 电缆入口 {cable_glands_holes}, 防爆 {exd}; {ip}; DN {dn} mm; 电源 {power_supply}; 启动/额定/保持功率: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; 手动超越: {manual_override}; 介质最大密度 {medium_density_max} cSt (mm2/s); 线圈绝缘等级: {solenoid_insulation_class}; 重量 {weight}'),
        '{model_code} Пневмораспределитель {operation} {construction} функция {function}; тип пневмоприсоединения - {pneumatic_connection}; присоединение {pneumatic_connection_thread}; Kv-{kv} м3/ч; корпус {body_material}({body_material_specified}); катушка {solenoid_body_material}{solenoid_body_material_specified}; уплотнение {sealing_material_specified}; Давление {pressure_range} бар; Темп.окр.среды {temperature_range}°С; отверстие под кабельный ввод {cable_glands_holes},  взрывозащита {exd}; {ip}; Dn {dn} мм; Питание {power_supply}; Мощность холодного/ном/удерж: {power_consumption_start} /  {power_consumption_hot} / {power_consumption_hold}, Вт; Ручной дублер: {manual_override}; макс. плотность рабочей среды {medium_density_max} сСт (мм2/с); Класс изоляции соленоида: {solenoid_insulation_class}; вес {weight}':
            _tr('{model_code} Solenoid valve {operation} {construction} function {function}; pneumatic connection type - {pneumatic_connection}; connection {pneumatic_connection_thread}; Kv-{kv} m3/h; body {body_material}({body_material_specified}); coil {solenoid_body_material}{solenoid_body_material_specified}; seal {sealing_material_specified}; Pressure {pressure_range} bar; Ambient temp. {temperature_range}°C; cable entry {cable_glands_holes}, explosion protection {exd}; {ip}; DN {dn} mm; Power supply {power_supply}; Inrush/rated/holding power: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; Manual override: {manual_override}; max. medium density {medium_density_max} cSt (mm2/s); Solenoid insulation class: {solenoid_insulation_class}; weight {weight}',
                '{model_code} 电磁阀 {operation} {construction} 功能 {function}; 气动连接类型 - {pneumatic_connection}; 连接 {pneumatic_connection_thread}; Kv-{kv} m3/h; 阀体 {body_material}({body_material_specified}); 线圈 {solenoid_body_material}{solenoid_body_material_specified}; 密封 {sealing_material_specified}; 压力 {pressure_range} bar; 环境温度 {temperature_range}°C; 电缆入口 {cable_glands_holes}, 防爆 {exd}; {ip}; DN {dn} mm; 电源 {power_supply}; 启动/额定/保持功率: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; 手动超越: {manual_override}; 介质最大密度 {medium_density_max} cSt (mm2/s); 线圈绝缘等级: {solenoid_insulation_class}; 重量 {weight}'),
        '{model_code} Пневмораспределитель {brand} {operation} {construction} функция {function}; тип пневмоприсоединения - {pneumatic_connection}; присоединение {pneumatic_connection_thread}; Kv-{kv} м3/ч; корпус {body_material}({body_material_specified}); катушка {solenoid_body_material_specified}; уплотнение {sealing_material_specified}; Давление {pressure_range} бар; Темп.окр.среды {temperature_range}°С; отверстие под кабельный ввод {cable_glands_holes},  взрывозащита {exd}; {ip}; Dn {dn} мм; Питание {power_supply}; Мощность холодного/ном/удерж: {power_consumption_start} /  {power_consumption_hot} / {power_consumption_hold}, Вт; Ручной дублер: {manual_override}; макс. плотность рабочей среды {medium_density_max} сСт (мм2/с); Класс изоляции соленоида: {solenoid_insulation_class}; вес {weight}':
            _tr('{model_code} Solenoid valve {brand} {operation} {construction} function {function}; pneumatic connection type - {pneumatic_connection}; connection {pneumatic_connection_thread}; Kv-{kv} m3/h; body {body_material}({body_material_specified}); coil {solenoid_body_material_specified}; seal {sealing_material_specified}; Pressure {pressure_range} bar; Ambient temp. {temperature_range}°C; cable entry {cable_glands_holes}, explosion protection {exd}; {ip}; DN {dn} mm; Power supply {power_supply}; Inrush/rated/holding power: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; Manual override: {manual_override}; max. medium density {medium_density_max} cSt (mm2/s); Solenoid insulation class: {solenoid_insulation_class}; weight {weight}',
                '{model_code} 电磁阀 {brand} {operation} {construction} 功能 {function}; 气动连接类型 - {pneumatic_connection}; 连接 {pneumatic_connection_thread}; Kv-{kv} m3/h; 阀体 {body_material}({body_material_specified}); 线圈 {solenoid_body_material_specified}; 密封 {sealing_material_specified}; 压力 {pressure_range} bar; 环境温度 {temperature_range}°C; 电缆入口 {cable_glands_holes}, 防爆 {exd}; {ip}; DN {dn} mm; 电源 {power_supply}; 启动/额定/保持功率: {power_consumption_start} / {power_consumption_hot} / {power_consumption_hold}, W; 手动超越: {manual_override}; 介质最大密度 {medium_density_max} cSt (mm2/s); 线圈绝缘等级: {solenoid_insulation_class}; 重量 {weight}'),
        # ── БКВ ──
        '{model_code} Блок концевых выключателей {brand}; {points}, тип датчика: {sensor_variety}, {ip}, Взрывозащита: {exd}; Т.окр. {work_temp_min}..{work_temp_max} °С, Материал корпуса: {body_material_specified}, Отверстия под КВ:{cable_glands_holes}, Монтаж:{mounting}, вес {weight}кг. Сигналы: {signal_profile_summary}':
            _tr('{model_code} Limit switch box {brand}; {points}, sensor type: {sensor_variety}, {ip}, Explosion protection: {exd}; Ambient temp. {work_temp_min}..{work_temp_max} °C, Body material: {body_material_specified}, Cable entries: {cable_glands_holes}, Mounting: {mounting}, weight {weight}kg. Signals: {signal_profile_summary}',
                '{model_code} 限位开关盒 {brand}; {points}, 传感器类型: {sensor_variety}, {ip}, 防爆: {exd}; 环境温度 {work_temp_min}..{work_temp_max} °C, 壳体材料: {body_material_specified}, 电缆入口: {cable_glands_holes}, 安装: {mounting}, 重量 {weight}kg. 信号: {signal_profile_summary}'),
        'БКВ TopWorx DXP DXS Emerson':
            _tr('LSB TopWorx DXP DXS Emerson', '限位开关盒 TopWorx DXP DXS Emerson'),
        # ── Позиционеры ──
        '{model_code} Позиционер {acting_type} для приводов {actuator_action}  {brand} Исп: {exd}; Т.окр.  {work_temp_min}..{work_temp_max} °С; Давление питания {supply_pressure_range} бар; Материал корпуса: {body_material}; Пневмоприсоединение: {pneumatic_connection}; Кабельный ввод: {cable_gland_hole}; Сигналы: {signal_profile_summary}; Сигнал тревоги: {alarm}; Смарт-возможности: {smart_capabilities}; вес: {weight}кг; Присоединение к приводу: {lever}':
            _tr('{model_code} Positioner {acting_type} for {actuator_action} actuators {brand} Ver.: {exd}; Ambient temp. {work_temp_min}..{work_temp_max} °C; Supply pressure {supply_pressure_range} bar; Body material: {body_material}; Pneumatic connection: {pneumatic_connection}; Cable entry: {cable_gland_hole}; Signals: {signal_profile_summary}; Alarm signal: {alarm}; Smart capabilities: {smart_capabilities}; weight: {weight}kg; Actuator connection: {lever}',
                '{model_code} 定位器 {acting_type} 用于 {actuator_action} 执行器 {brand} 型式: {exd}; 环境温度 {work_temp_min}..{work_temp_max} °C; 供气压力 {supply_pressure_range} bar; 壳体材料: {body_material}; 气动连接: {pneumatic_connection}; 电缆入口: {cable_gland_hole}; 信号: {signal_profile_summary}; 报警信号: {alarm}; 智能功能: {smart_capabilities}; 重量: {weight}kg; 与执行器连接: {lever}'),
        # ── Фильтр-регуляторы ──
        '{model_code} {filter_variety} {brand}; Расход {flow_rate} л/мин; {drain_variety}; Т.окр. {work_temp_min}..{work_temp_max} °С, Материал корпуса: {body_material}, Материал стакана: {bowl_material}, Кожух: {protection_material} Порты: {thread}; слив: {drain_port_size}; {gauge_quantity}; фильтрация {filtration_rating} мкм; Диапазон регулировки давления {pressure_min}..{pressure_max} бар; Макс. входное давление {pressure_inlet_max} бар; вес {weight}кг. Настенное крепление: {wall_mounting_included}':
            _tr('{model_code} {filter_variety} {brand}; Flow {flow_rate} l/min; {drain_variety}; Ambient temp. {work_temp_min}..{work_temp_max} °C, Body material: {body_material}, Bowl material: {bowl_material}, Guard: {protection_material} Ports: {thread}; drain: {drain_port_size}; {gauge_quantity}; filtration {filtration_rating} µm; Pressure regulation range {pressure_min}..{pressure_max} bar; Max inlet pressure {pressure_inlet_max} bar; weight {weight}kg. Wall mounting: {wall_mounting_included}',
                '{model_code} {filter_variety} {brand}; 流量 {flow_rate} l/min; {drain_variety}; 环境温度 {work_temp_min}..{work_temp_max} °C, 壳体材料: {body_material}, 滤杯材料: {bowl_material}, 防护罩: {protection_material} 接口: {thread}; 排水: {drain_port_size}; {gauge_quantity}; 过滤精度 {filtration_rating} µm; 压力调节范围 {pressure_min}..{pressure_max} bar; 最大入口压力 {pressure_inlet_max} bar; 重量 {weight}kg. 壁挂安装: {wall_mounting_included}'),
        # ── Ручные дублёры ──
        '{model_code} {gearbox_variety} {is_declutchable} {gearbox_output_variety} {brand} Макс.выходной момент: {max_output_torque} Нм; {ip};  Темп. {work_temp_min}..{work_temp_max}°С; Монтажные площадки, Верх (к приводу): {mounting_plate_top_list_text}, Шток: {stem_shape_top} {stem_size_top}, высота штока {stem_height_top}мм // Низ (к арматуре): {mounting_plate_bottom_list_text} Шток: {stem_shape_bottom} {stem_size_bottom}, глубина под шток {stem_height_bottom}мм; Диаметр штурвала: {handwheel_diameter} мм; Макс. усилие на штурвале: {handwheel_force_nominal}; Передаточное число: {reduction_ratio_text};  Угол поворота: {turn_angle} ±{turn_tuning_limit}°; Вес {weight} кг.{transmission_variety} передача; {locking_mechanism}; Материал корпуса: {body_material_text};':
            _tr('{model_code} {gearbox_variety} {is_declutchable} {gearbox_output_variety} {brand} Max output torque: {max_output_torque} Nm; {ip}; Temp. {work_temp_min}..{work_temp_max}°C; Mounting pads, Top (to actuator): {mounting_plate_top_list_text}, Stem: {stem_shape_top} {stem_size_top}, stem height {stem_height_top}mm // Bottom (to valve): {mounting_plate_bottom_list_text} Stem: {stem_shape_bottom} {stem_size_bottom}, stem depth {stem_height_bottom}mm; Handwheel diameter: {handwheel_diameter} mm; Max handwheel force: {handwheel_force_nominal}; Gear ratio: {reduction_ratio_text}; Rotation angle: {turn_angle} ±{turn_tuning_limit}°; Weight {weight} kg.{transmission_variety} transmission; {locking_mechanism}; Body material: {body_material_text};',
                '{model_code} {gearbox_variety} {is_declutchable} {gearbox_output_variety} {brand} 最大输出扭矩: {max_output_torque} Nm; {ip}; 温度 {work_temp_min}..{work_temp_max}°C; 安装平台, 上（接执行器）: {mounting_plate_top_list_text}, 阀杆: {stem_shape_top} {stem_size_top}, 阀杆高度 {stem_height_top}mm // 下（接阀门）: {mounting_plate_bottom_list_text} 阀杆: {stem_shape_bottom} {stem_size_bottom}, 阀杆深度 {stem_height_bottom}mm; 手轮直径: {handwheel_diameter} mm; 手轮最大力: {handwheel_force_nominal}; 传动比: {reduction_ratio_text}; 旋转角度: {turn_angle} ±{turn_tuning_limit}°; 重量 {weight} kg.{transmission_variety} 传动; {locking_mechanism}; 壳体材料: {body_material_text};'),
    },
}


class Command(BaseCommand):
    help = ('Заполняет en/cn переводы name_template_i18n / description_template_i18n '
            'серий каталогов из словаря (ключ — ru-шаблон).')

    def add_arguments(self, parser):
        parser.add_argument('--force', action='store_true',
                            help='Перестроить en/cn заново из словаря (затирает ручные правки).')
        parser.add_argument('--dry-run', action='store_true',
                            help='Только показать, что будет записано.')

    def handle(self, *args, **options):
        force = options['force']
        dry_run = options['dry_run']

        updated = 0
        missing = set()
        for label in MODELS:
            model = apps.get_model(label)
            for ml in model.objects.all():
                for field in FIELDS:
                    if not hasattr(ml, field) or not hasattr(ml, f'{field}_i18n'):
                        continue
                    ru = getattr(ml, field) or ''
                    if not ru:
                        continue
                    i18n = getattr(ml, f'{field}_i18n') or {}
                    if not isinstance(i18n, dict):
                        i18n = {}
                    changed = False
                    # title_template серий КВ совпадает с name_template — переводы из того же словаря
                    source = 'name_template' if field == 'title_template' else field
                    for locale in ('en', 'cn'):
                        if force or locale not in i18n:
                            translation = TRANSLATIONS.get(source, {}).get(ru)
                            if translation is not None:
                                i18n[locale] = translation[0 if locale == 'en' else 1]
                                changed = True
                            else:
                                missing.add(f'{field}: {ru[:90]}')
                    if changed:
                        setattr(ml, f'{field}_i18n', i18n)
                        updated += 1
                        if not dry_run:
                            ml.save()

        self.stdout.write(self.style.SUCCESS(
            f'{("DRY-RUN " if dry_run else "")}обновлено серий: {updated}'
        ))
        if missing:
            self.stdout.write(self.style.WARNING(
                f'Шаблоны без перевода (fallback ru) — {len(missing)}:'
            ))
            for item in sorted(missing):
                self.stdout.write(f'  {item}')
