# Generated by Django 4.2.23 on 2025-11-20 19:57

from django.db import migrations, models
import django.db.models.deletion
# import temperature_options.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0020_temperaturerange'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
        ('media_library', '0002_alter_medialibraryitem_media_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticActuatorBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название модели корпуса привода', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели корпуса привода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса привода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('max_stem_height', models.PositiveIntegerField(blank=True, help_text='Глубина отверстия под шток арматуры', null=True, verbose_name='Высота штока')),
                ('max_stem_diameter', models.PositiveIntegerField(blank=True, help_text='Максимальный диаметр отверстия под шток арматуры', null=True, verbose_name='Макс шток')),
                ('min_pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=2.5, help_text='Давление удержания: минимальное давление необходимое для работы привода, бар', max_digits=4, null=True, verbose_name='Мин давление, бар')),
                ('max_pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=2.5, help_text='Максимальное допустимое давление для работы привода, бар', max_digits=4, null=True, verbose_name='Макс давление, бар')),
                ('air_usage_open', models.DecimalField(blank=True, decimal_places=2, help_text='Расход воздуха пневмоприводом за цикл открытия, л', max_digits=10, null=True, verbose_name="Расход откр, л'")),
                ('air_usage_close', models.DecimalField(blank=True, decimal_places=1, help_text='Расход воздуха пневмоприводом за цикл закрытия, л', max_digits=4, null=True, verbose_name="Расход закр, л'")),
            ],
            options={
                'verbose_name': 'Название модели корпуса привода',
                'verbose_name_plural': 'Названия моделей корпуса привода',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticActuatorBodyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название таблицы корпусов', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код таблицы корпусов', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание таблицы корпусов', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Таблица корпусов',
                'verbose_name_plural': 'Таблица корпусов для их логического объединения для групповой обработки',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticActuatorConstructionVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название разновидности конструкции', max_length=10, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код разновидности конструкции привода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности конструкции привода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Название разновидности конструкции привода - RP/SY',
                'verbose_name_plural': 'Названия разновидностей конструкции привода - RP/SY',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticActuatorModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название серии', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели корпуса привода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса привода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('allowed_body_coating', models.ManyToManyField(blank=True, default=1, help_text='Возможные для выбора покрытия корпуса для серии (можно выбрать несколько)', related_name='pneumatic_model_line_allowed_body_coating', to='params.bodycoatingoption')),
                ('allowed_exd', models.ManyToManyField(blank=True, default=1, help_text='Возможные для выбора степени взрывозащиты для серии (можно выбрать несколько)', related_name='pneumatic_model_line_allowed_exd', to='params.exdoption')),
                ('allowed_ip', models.ManyToManyField(blank=True, default=1, help_text='Возможные для выбора степени защиты IP для серии (можно выбрать несколько)', related_name='pneumatic_model_line_allowed_ip', to='params.ipoption')),
                ('allowed_temperature', models.ManyToManyField(blank=True, default=1, help_text='Возможные для выбора температурные исполнения для серии (можно выбрать несколько)', related_name='pneumatic_model_line_allowed_temperature', to='params.envtempparameters')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_brand', to='producers.brands')),
                ('default_body_coating', models.ForeignKey(blank=True, help_text='Стандартное исполнение покрытия корпуса для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_default_body_coating', to='params.bodycoatingoption')),
                ('default_exd', models.ForeignKey(blank=True, help_text='Стандартное исполнение степени взрывозащиты для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_default_exd_option', to='params.exdoption')),
                ('default_hand_wheel', models.ForeignKey(blank=True, help_text='Стандартно установленный ручной дублер для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_default_hand_wheel', to='params.handwheelinstalledoption')),
                ('default_ip', models.ForeignKey(blank=True, help_text='Стандартное исполнение степени защиты IP для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_default_ip_option', to='params.ipoption')),
                ('default_output_type', models.ForeignKey(blank=True, help_text='Тип работы серии приводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_default_output_type', to='params.actuatorgearboxoutputtype')),
                ('default_temperature', models.ForeignKey(blank=True, help_text='Стандартное температурное исполнения для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_default_temperature', to='params.envtempparameters')),
                ('pneumatic_actuator_construction_variety', models.ForeignKey(blank=True, help_text='Тип конструкции привода - кулисный или шестерня-рейка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_pneumatic_actuator_variety', to='pneumatic_actuators.pneumaticactuatorconstructionvariety', verbose_name='')),
            ],
            options={
                'verbose_name': 'Название модели корпуса привода',
                'verbose_name_plural': 'Названия моделей корпуса привода',
                'ordering': ['sorting_order'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PneumaticActuatorSpringsQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название кол-ва пружин', max_length=10, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код кол-ва пружин', max_length=10, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание кол-ва пружин', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Название кол-ва пружин пневмопривода SR',
                'verbose_name_plural': 'Названия кол-ва пружин пневмопривода SR',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticActuatorTechDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название таблицы техданных серии пневмоприводов', max_length=100, verbose_name='Название таблицы')),
                ('code', models.CharField(help_text='Код таблицы техданных', max_length=50, unique=True, verbose_name='Код таблицы')),
                ('description', models.TextField(blank=True, help_text='Описание таблицы техданных', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Таблица техданных',
                'verbose_name_plural': 'Таблицы техданных',
            },
        ),
        migrations.CreateModel(
            name='PneumaticActuatorVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название разновидности', max_length=10, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код разновидности привода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса привода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Название разновидности пневмопривода - DA/SR',
                'verbose_name_plural': 'Названия разновидностей пневмопривода - DA/SR',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticAirSupplyPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Давление в пневмосистеме, бар', max_length=10, verbose_name='Давление, бар')),
                ('code', models.CharField(blank=True, help_text='Код давления в пневмосистеме, бар', max_length=10, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание давления питания', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('pressure_bar', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Давление в бар')),
            ],
            options={
                'verbose_name': 'Давление питания пневмопривода',
                'verbose_name_plural': 'Давления питания пневмопривода',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticActuatorTechDataTableDrawingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Порядок отображения чертежа в списке', verbose_name='Порядок отображения')),
                ('description', models.TextField(blank=True, help_text='Описание чертежа в контексте этой таблицы данных', verbose_name='Описание')),
                ('allowed_body', models.ManyToManyField(blank=True, help_text='Корпуса моделей, для которых применим этот чертеж.', related_name='tech_data_allowed_allowed_body', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Применимые корпуса')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_data_drawing_relations', to='media_library.medialibraryitem', verbose_name='Чертеж')),
                ('tech_data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_data_drawing_relations', to='pneumatic_actuators.pneumaticactuatortechdatatable', verbose_name='Таблица техданных')),
            ],
            options={
                'verbose_name': 'Связь таблицы техданных с чертежом',
                'verbose_name_plural': 'Связи таблиц техданных с чертежами',
                'ordering': ['display_order'],
                'unique_together': {('tech_data_table', 'drawing')},
            },
        ),
        migrations.AddField(
            model_name='pneumaticactuatortechdatatable',
            name='drawings',
            field=models.ManyToManyField(help_text='Чертежи, связанные с этой таблицей техданных', related_name='pneumatic_tech_data_tables', through='pneumatic_actuators.PneumaticActuatorTechDataTableDrawingItem', to='media_library.medialibraryitem', verbose_name='Чертежи'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='body_table',
            field=models.ForeignKey(help_text='Таблица корпусов для их логического объединения для групповой обработки', on_delete=django.db.models.deletion.PROTECT, related_name='model_body_body_table', to='pneumatic_actuators.pneumaticactuatorbodytable', verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='mounting_plate',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка', related_name='model_body_mounting_plate_pneumatic_model_line', to='params.mountingplatetypes', verbose_name='Монт.площадка'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='stem_shape',
            field=models.ForeignKey(blank=True, help_text='Тип отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_stem_shape_pneumatic_model_line', to='params.stemshapes', verbose_name='Тип штока'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='stem_size',
            field=models.ForeignKey(blank=True, help_text='Размер отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_stem_size_pneumatic_model_line', to='params.stemsize', verbose_name='Размер штока'),
        ),
        migrations.CreateModel(
            name='BodyThrustTorqueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bto', models.DecimalField(decimal_places=1, help_text='BTO Момент/усилие страгивания для открытия', max_digits=10, verbose_name='Момент/усилие BTO')),
                ('rto', models.DecimalField(decimal_places=1, help_text='RTC Момент/усилие в среднем положении', max_digits=10, verbose_name='Момент/усилие RTC(MID)')),
                ('eto', models.DecimalField(decimal_places=1, help_text='ETO Конечный Момент/Усилие открытия', max_digits=10, verbose_name='Момент/усилие BTC')),
                ('body', models.ForeignKey(blank=True, help_text='Модель корпуса привода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_thrust_torque_table', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Модель')),
                ('pressure', models.ForeignKey(blank=True, help_text='Давление питания или spring - для пружин', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_thrust_torque_table', to='pneumatic_actuators.pneumaticairsupplypressure', verbose_name='Давление')),
                ('spring_qty', models.ForeignKey(blank=True, help_text='Количество пружин или DA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_thrust_torque_table', to='pneumatic_actuators.pneumaticactuatorspringsqty', verbose_name='Пружин / DA')),
            ],
            options={
                'verbose_name': 'Таблица моментов/усилий пневмоприводов',
                'verbose_name_plural': 'Таблица моментов/усилий пневмоприводов',
            },
        ),
        migrations.CreateModel(
            name='PneumaticTemperatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_temp_min', models.IntegerField(help_text='Минимальная рабочая температура, °С', verbose_name='Т мин, °С')),
                ('work_temp_max', models.IntegerField(help_text='Максимальная рабочая температура, °С', verbose_name='Т макс, °С')),
                ('temperature_option', models.CharField(choices=[('default', 'Стандартное'), ('optional', 'Опционное')], default='optional', max_length=10, verbose_name='Тип опции')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('encoding', models.CharField(blank=True, help_text='Код температурной опции (HT, XHT, ARCTIC). Для стандартного исполнения можно оставить пустым.', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой температурной опции', verbose_name='Описание')),
                ('air_consumption_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Влияние температуры на расход воздуха', max_digits=5, null=True, verbose_name='Коэффициент расхода воздуха')),
                ('max_operating_pressure', models.DecimalField(blank=True, decimal_places=1, help_text='Максимальное рабочее давление при данной температуре', max_digits=4, null=True, verbose_name='Макс. рабочее давление')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_options', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия пневмоприводов')),
            ],
            options={
                'verbose_name': 'Температурная опция пневмопривода',
                'verbose_name_plural': 'Температурные опции пневмоприводов',
                'ordering': ['temperature_option', 'sorting_order'],
                'unique_together': {('model_line', 'encoding')},
            },
        ),
    ]
