# Generated by Django 4.2.23 on 2025-11-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0022_create_initial_pneumatic_pressure_data'),
        ('pneumatic_actuators', '0002_initial_pneumatic_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticactuatormodelline',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Серия моделей пневмоприводов', 'verbose_name_plural': 'Серии моделей пневмоприводов'},
        ),
        migrations.AlterModelOptions(
            name='pneumatictemperatureoption',
            options={'ordering': ['is_default', 'sorting_order'], 'verbose_name': 'Температурная опция пневмопривода', 'verbose_name_plural': 'Температурные опции пневмоприводов'},
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='allowed_body_coating',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='allowed_exd',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='allowed_ip',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='allowed_temperature',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='default_body_coating',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='default_exd',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='default_ip',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='default_temperature',
        ),
        migrations.RemoveField(
            model_name='pneumatictemperatureoption',
            name='air_consumption_factor',
        ),
        migrations.RemoveField(
            model_name='pneumatictemperatureoption',
            name='max_operating_pressure',
        ),
        migrations.RemoveField(
            model_name='pneumatictemperatureoption',
            name='temperature_option',
        ),
        migrations.AddField(
            model_name='pneumatictemperatureoption',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция'),
        ),
        migrations.AlterField(
            model_name='pneumatictemperatureoption',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pneumatictemperatureoption',
            name='encoding',
            field=models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка'),
        ),
        migrations.AlterField(
            model_name='pneumatictemperatureoption',
            name='work_temp_max',
            field=models.IntegerField(default=0, help_text='Максимальная рабочая температура, °С', verbose_name='Т макс, °С'),
        ),
        migrations.AlterField(
            model_name='pneumatictemperatureoption',
            name='work_temp_min',
            field=models.IntegerField(default=0, help_text='Минимальная рабочая температура, °С', verbose_name='Т мин, °С'),
        ),
        migrations.CreateModel(
            name='PneumaticIpOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('ip_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.ipoption', verbose_name='Опция IP')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_options', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия пневмоприводов')),
            ],
            options={
                'verbose_name': 'Опция IP пневмопривода',
                'verbose_name_plural': 'Опции IP пневмоприводов',
                'ordering': ['ip_option__ip_rank', 'sorting_order'],
                'unique_together': {('model_line', 'ip_option')},
            },
        ),
        migrations.CreateModel(
            name='PneumaticExdOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('exd_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.exdoption', verbose_name='Опция взрывозащиты')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exd_options', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия пневмоприводов')),
            ],
            options={
                'verbose_name': 'Опция взрывозащиты пневмопривода',
                'verbose_name_plural': 'Опции взрывозащиты пневмоприводов',
                'ordering': ['exd_option__sorting_order', 'sorting_order'],
                'unique_together': {('model_line', 'exd_option')},
            },
        ),
        migrations.CreateModel(
            name='PneumaticBodyCoatingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('body_coating_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.bodycoatingoption', verbose_name='Опция покрытия корпуса')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_coating_options', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия пневмоприводов')),
            ],
            options={
                'verbose_name': 'Опция покрытия корпуса пневмопривода',
                'verbose_name_plural': 'Опции покрытия корпуса пневмоприводов',
                'ordering': ['body_coating_option__sorting_order', 'sorting_order'],
                'unique_together': {('model_line', 'body_coating_option')},
            },
        ),
    ]
