# Generated by Django 4.2.23 on 2025-11-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0022_create_initial_pneumatic_pressure_data'),
        ('pneumatic_actuators', '0003_alter_pneumaticactuatormodelline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodythrusttorquetable',
            name='pressure',
            field=models.ForeignKey(blank=True, help_text='Давление питания или spring - для пружин', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_thrust_torque_table', to='params.pneumaticairsupplypressure', verbose_name='Давление'),
        ),
        migrations.DeleteModel(
            name='PneumaticAirSupplyPressure',
        ),
    ]
