# Generated by Django 4.2.23 on 2025-11-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0004_alter_bodythrusttorquetable_pressure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticactuatorbody',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Модель корпуса пневмопривода', 'verbose_name_plural': 'Модели корпусов пневмоприводов'},
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='piston_diameter',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Диаметр поршня, мм', max_digits=4, null=True, verbose_name='Поршень'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='turn_angle',
            field=models.CharField(blank=True, help_text='Угол поворота', max_length=50, null=True, verbose_name='Угол поворота'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='turn_tuning_limit',
            field=models.CharField(blank=True, help_text='Настройка ограничителя на ±1° (об.)', max_length=50, null=True, verbose_name='Ограничитель'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='weight_body',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Вес корпуса, кг', max_digits=8, null=True, verbose_name='Вес корпуса'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='weight_spring',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Вес 1 пружины, кг', max_digits=4, null=True, verbose_name='Вес пружины'),
        ),
    ]
