# Generated by Django 4.2.23 on 2025-11-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0005_alter_pneumaticactuatorbody_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pneumaticactuatorbody',
            name='weight_body',
        ),
        migrations.CreateModel(
            name='PneumaticWeightParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Вес корпуса привода с кол-вом пружин или DA', max_digits=10, verbose_name='Вес, кг')),
                ('body', models.ForeignKey(blank=True, help_text='Модель корпуса привода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_weight_parameter', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Модель')),
                ('spring_qty', models.ForeignKey(blank=True, help_text='Количество пружин или DA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_weight_parameter', to='pneumatic_actuators.pneumaticactuatorspringsqty', verbose_name='Пружин / DA')),
            ],
            options={
                'verbose_name': 'Вес пневмопривода',
                'verbose_name_plural': 'Вес пневмоприводов',
                'ordering': ['spring_qty'],
                'unique_together': {('body', 'spring_qty')},
            },
        ),
        migrations.CreateModel(
            name='PneumaticCloseTimeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_close', models.DecimalField(decimal_places=2, default=0.0, help_text='Время закрытия пневмопривода с кол-вом пружин или DA, секунд', max_digits=4, verbose_name='Закрытие, сек')),
                ('time_open', models.DecimalField(decimal_places=2, default=0.0, help_text='Время открытия пневмопривода с кол-вом пружин или DA, секунд', max_digits=4, verbose_name='Открытие, сек')),
                ('body', models.ForeignKey(blank=True, help_text='Модель корпуса привода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_close_time_parameter', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Модель')),
                ('spring_qty', models.ForeignKey(blank=True, help_text='Количество пружин или DA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_close_time_parameter', to='pneumatic_actuators.pneumaticactuatorspringsqty', verbose_name='Пружин / DA')),
            ],
            options={
                'verbose_name': 'Вес пневмопривода',
                'verbose_name_plural': 'Вес пневмоприводов',
                'ordering': ['spring_qty'],
                'unique_together': {('body', 'spring_qty')},
            },
        ),
    ]
