# Generated by Django 4.2.23 on 2025-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0006_remove_pneumaticactuatorbody_weight_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatorbody',
            name='air_usage_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Расход воздуха пневмоприводом за цикл закрытия, л', max_digits=4, null=True, verbose_name="Расход закр, л'"),
        ),
    ]
