# Generated by Django 4.2.23 on 2025-11-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0007_alter_pneumaticactuatorbody_air_usage_close'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticclosetimeparameter',
            options={'ordering': ['spring_qty'], 'verbose_name': 'Время открытия/закрытия пневмопривода', 'verbose_name_plural': 'Время открытия/закрытия пневмоприводов'},
        ),
        migrations.AlterField(
            model_name='pneumaticclosetimeparameter',
            name='body',
            field=models.ForeignKey(default=1, help_text='Модель корпуса привода', on_delete=django.db.models.deletion.CASCADE, related_name='pa_close_time_parameter', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pneumaticweightparameter',
            name='body',
            field=models.ForeignKey(default=1, help_text='Модель корпуса привода', on_delete=django.db.models.deletion.CASCADE, related_name='pa_weight_parameter', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Модель'),
            preserve_default=False,
        ),
    ]
