# Generated by Django 4.2.23 on 2025-11-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0023_pneumaticconnection'),
        ('pneumatic_actuators', '0008_alter_pneumaticclosetimeparameter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='pneumatic_connection',
            field=models.ManyToManyField(blank=True, help_text='Возможные типы пневмоподключений', related_name='model_body_pneumatic_connection', to='params.pneumaticconnection', verbose_name='Пневмоподключения'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='thread_in',
            field=models.ForeignKey(blank=True, help_text='Резьба входного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_thread_in', to='params.threadtypes', verbose_name='Пневмовход'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorbody',
            name='thread_out',
            field=models.ForeignKey(blank=True, help_text='Резьба выходного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_thread_out', to='params.threadtypes', verbose_name='Пневмовыход'),
        ),
    ]
