# Generated by Django 4.2.23 on 2025-11-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0023_pneumaticconnection'),
        ('pneumatic_actuators', '0009_pneumaticactuatorbody_pneumatic_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatorbody',
            name='thread_in',
            field=models.ForeignKey(blank=True, help_text='Резьба входного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_thread_in', to='params.threadsize', verbose_name='Пневмовход'),
        ),
        migrations.AlterField(
            model_name='pneumaticactuatorbody',
            name='thread_out',
            field=models.ForeignKey(blank=True, help_text='Резьба выходного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_thread_out', to='params.threadsize', verbose_name='Пневмовыход'),
        ),
    ]
