# Generated by Django 5.2.7 on 2025-11-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_medialibraryitem_media_file_and_more'),
        ('params', '0025_alter_pneumaticconnection_code'),
        ('pneumatic_actuators', '0010_alter_pneumaticactuatorbody_thread_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatortechdatatable',
            name='drawings',
            field=models.ManyToManyField(help_text='Чертежи, связанные с этой таблицей техданных', related_name='pneumatic_tech_data_tables', through='pneumatic_actuators.PneumaticActuatorTechDataTableDrawingItem', through_fields=('tech_data_table', 'drawing'), to='media_library.medialibraryitem', verbose_name='Чертежи'),
        ),
        migrations.CreateModel(
            name='PneumaticActuatorModelLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('body', models.ForeignKey(blank=True, help_text='Корпус модели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_item_body', to='pneumatic_actuators.pneumaticactuatorbody')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_line_item_model_line', to='pneumatic_actuators.pneumaticactuatormodelline')),
                ('pneumatic_actuator_variety', models.ForeignKey(blank=True, help_text='Вид пневмопривода - DA/SR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_model_line_item_actuator_variety', to='pneumatic_actuators.pneumaticactuatorvariety', verbose_name='DA/SR')),
            ],
            options={
                'verbose_name': 'Серия моделей пневмоприводов',
                'verbose_name_plural': 'Серии моделей пневмоприводов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PneumaticSafetyPositionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_position_option_model_line_item', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Положение безопасности')),
                ('safety_position', models.ForeignKey(help_text='Положения безопасности', on_delete=django.db.models.deletion.CASCADE, to='params.safetypositionoption', verbose_name='Положение безопасности')),
            ],
            options={
                'verbose_name': 'Положение безопасности модели пневмопривода',
                'verbose_name_plural': 'Положения безопасности моделей пневмоприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line_item', 'safety_position')},
            },
        ),
        migrations.CreateModel(
            name='PneumaticSpringsQtyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='springs_qty_option_model_line_item', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Количество пружин')),
                ('springs_qty', models.ForeignKey(help_text='Количество пружин', on_delete=django.db.models.deletion.CASCADE, to='pneumatic_actuators.pneumaticactuatorspringsqty', verbose_name='Количество пружин')),
            ],
            options={
                'verbose_name': 'Количество пружин модели пневмопривода',
                'verbose_name_plural': 'Количество пружин моделей пневмоприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line_item', 'springs_qty')},
            },
        ),
    ]
