# Generated by Django 4.2.23 on 2025-11-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0011_alter_pneumaticactuatortechdatatable_drawings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticactuatormodellineitem',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Модель пневмопривода', 'verbose_name_plural': 'Модели пневмоприводов в серии'},
        ),
        migrations.CreateModel(
            name='PneumaticActuatorSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название привода - формируется автоматически', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код привода - формируется автоматически', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание привода - формируется автоматически', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('selected_model', models.ForeignKey(help_text='Модель пневмопривода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_pneumatic_actuator_model_line_item', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Модель')),
                ('selected_safety_position', models.ForeignKey(blank=True, help_text='Выбранное положение безопасности привода', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticsafetypositionoption', verbose_name='Выбранное положение безопасности')),
                ('selected_springs_qty', models.ForeignKey(blank=True, help_text='Выбранное количество пружин привода', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticspringsqtyoption', verbose_name='Выбранное количество пружин')),
            ],
            options={
                'verbose_name': 'Выбранный пневмопривод',
                'verbose_name_plural': 'Выбранные пневмоприводы',
                'ordering': ['sorting_order'],
            },
        ),
    ]
