# Generated by Django 4.2.23 on 2025-11-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0012_alter_pneumaticactuatormodellineitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='selected_body_coating',
            field=models.ForeignKey(blank=True, help_text='Выбранное покрытие корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticbodycoatingoption', verbose_name='Покрытие корпуса'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='selected_exd',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticexdoption', verbose_name='Взрывозащита'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='selected_ip',
            field=models.ForeignKey(blank=True, help_text='Выбранная степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticipoption', verbose_name='Степень защиты IP'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='selected_temperature',
            field=models.ForeignKey(blank=True, help_text='Выбранная температурная опция', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumatictemperatureoption', verbose_name='Температурная опция'),
        ),
        migrations.AlterField(
            model_name='pneumaticactuatorselected',
            name='selected_model',
            field=models.ForeignKey(default=1, help_text='Модель пневмопривода', on_delete=django.db.models.deletion.CASCADE, related_name='selected_pneumatic_actuator_model_line_item', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Модель'),
            preserve_default=False,
        ),
    ]
