# Generated by Django 4.2.23 on 2025-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0013_pneumaticactuatorselected_selected_body_coating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='model_item_code_template',
            field=models.CharField(blank=True, help_text='Шаблон артикула для конкретной модели серии', max_length=500, null=True, verbose_name='Шаблон артикула'),
        ),
    ]
