# Generated by Django 5.2.4 on 2025-12-03 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pneumatic_actuators', '0014_pneumaticactuatormodelline_model_item_code_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticActuatorModelLineCertRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Отметьте если это основной сертификат для объекта', verbose_name='Основной сертификат')),
                ('valid_for_model', models.BooleanField(default=True, help_text='Действителен ли сертификат для этой конкретной модели', verbose_name='Действует для модели')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания по применению сертификата', verbose_name='Примечания')),
                ('applied_date', models.DateField(blank=True, help_text='Дата применения сертификата к объекту', null=True, verbose_name='Дата применения')),
                ('expires_on_model', models.DateField(blank=True, help_text='До какой даты сертификат действителен для этой модели', null=True, verbose_name='Действует до для модели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('cert_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='cert_doc.certdata', verbose_name='Сертификат')),
                ('content_type', models.ForeignKey(blank=True, help_text='Тип объекта к которому привязан сертификат', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип связанного объекта')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал связь')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_relations', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Связь сертификата с серией пневмоприводов',
                'verbose_name_plural': 'Связи сертификатов с сериями пневмоприводов',
                'ordering': ['-is_primary', '-applied_date', '-created_at'],
                'abstract': False,
                'unique_together': {('cert_data', 'model_line')},
            },
        ),
    ]
