# Generated by Django 5.2.4 on 2025-12-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0015_pneumaticactuatormodellinecertrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticactuatormodellinecertrelation',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Связь сертификата с серией пневмоприводов', 'verbose_name_plural': 'Связи сертификатов с сериями пневмоприводов'},
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='expires_on_model',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='valid_for_model',
        ),
        migrations.AddField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
