# Generated by Django 5.2.4 on 2025-12-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0025_alter_pneumaticconnection_code'),
        ('pneumatic_actuators', '0016_alter_pneumaticactuatormodellinecertrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='model_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_data_model_line', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='PneumaticHandWheelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('hand_wheel_option', models.ForeignKey(help_text='Тип установленного ручного дублера', on_delete=django.db.models.deletion.CASCADE, to='params.handwheelinstalledoption', verbose_name='Ручной дублер')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_wheel_options', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия пневмоприводов')),
            ],
            options={
                'verbose_name': 'Тип установленного ручного дублера',
                'verbose_name_plural': 'Типы установленного ручного дублерапневмоприводов',
                'ordering': ['is_default', 'sorting_order'],
                'unique_together': {('model_line', 'encoding')},
            },
        ),
    ]
