# Generated by Django 4.2.23 on 2025-12-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0017_alter_pneumaticactuatormodellinecertrelation_model_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='selected_hand_wheel',
            field=models.ForeignKey(blank=True, help_text='Встроенный ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumatichandwheeloption', verbose_name='Встроенный дублер'),
        ),
    ]
