# Generated by Django 5.2.4 on 2025-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0018_pneumaticactuatorselected_selected_hand_wheel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pneumaticactuatorselected',
            old_name='selected_model',
            new_name='selected_model_line_item',
        ),
        migrations.AlterField(
            model_name='pneumaticactuatormodelline',
            name='code',
            field=models.CharField(blank=True, help_text='Код серии приводов', max_length=50, null=True, verbose_name='Код'),
        ),
    ]
