# Generated by Django 5.2.4 on 2025-12-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0019_rename_selected_model_pneumaticactuatorselected_selected_model_line_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatormodellinecertrelation',
            name='model_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_data_model_line', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия пневмоприводов'),
        ),
    ]
