# Generated by Django 5.2.4 on 2026-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0020_alter_pneumaticactuatormodellinecertrelation_model_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumatichandwheeloption',
            options={'ordering': ['is_default', 'sorting_order'], 'verbose_name': 'Тип установленного ручного дублера', 'verbose_name_plural': 'Типы установленного ручного дублера пневмоприводов'},
        ),
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='default_hand_wheel',
        ),
    ]
