# Generated by Django 5.2.4 on 2026-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0021_alter_pneumatichandwheeloption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticactuatorselected',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Модель пневмопривода', 'verbose_name_plural': 'Модели пневмоприводов'},
        ),
        migrations.AddConstraint(
            model_name='pneumaticactuatorselected',
            constraint=models.UniqueConstraint(fields=('name', 'selected_model_line_item', 'selected_safety_position', 'selected_springs_qty', 'selected_temperature', 'selected_ip', 'selected_exd', 'selected_body_coating', 'selected_hand_wheel'), name='unique_actuator_configuration'),
        ),
    ]
