# Generated by Django 5.2.4 on 2026-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0022_alter_pneumaticactuatorselected_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pneumaticactuatorselected',
            name='unique_actuator_configuration',
        ),
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='is_unique',
            field=models.BooleanField(default=True, verbose_name='Это уникальная конфигурация'),
        ),
    ]
