# Generated by Django 5.2.4 on 2026-04-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0031_threadinnerouter'),
        ('pneumatic_actuators', '0023_remove_pneumaticactuatorselected_unique_actuator_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticclosetimeparameter',
            name='pressure',
            field=models.ForeignKey(default=13, help_text='Давление в пневмосистеме, бар', on_delete=django.db.models.deletion.SET_DEFAULT, to='params.pneumaticairsupplypressure', verbose_name='Давление питания'),
        ),
    ]
