# Generated by Django 4.2.23 on 2026-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0003_remove_certdata_equipment_type_and_more'),
        ('pneumatic_actuators', '0025_pneumaticactuatormodelline_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты, применимые к этой серии', related_name='%(class)s_related', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
    ]
