# Generated by Django 4.2.23 on 2026-05-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0026_pneumaticactuatormodelline_cert_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pneumaticactuatormodelline',
            name='cert_docs',
        ),
    ]
