# Generated by Django 5.2.4 on 2026-06-08 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0056_alter_climaticplacementcategory_options_and_more'),
        ('pneumatic_actuators', '0027_remove_pneumaticactuatormodelline_cert_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticActuatorConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название привода - формируется автоматически', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код привода - формируется автоматически', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание привода - формируется автоматически', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('work_temp_min', models.IntegerField(default=0, help_text='Минимальная рабочая температура, °С', verbose_name='Т мин, °С')),
                ('work_temp_max', models.IntegerField(default=0, help_text='Максимальная рабочая температура, °С', verbose_name='Т макс, °С')),
                ('is_unique', models.BooleanField(default=True, verbose_name='Это уникальная конфигурация')),
                ('selected_body_coating', models.ForeignKey(blank=True, help_text='Выбранное покрытие корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.bodycoatingoption', verbose_name='Покрытие корпуса')),
                ('selected_exd', models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.exdoption', verbose_name='Взрывозащита')),
                ('selected_hand_wheel', models.ForeignKey(blank=True, help_text='Встроенный ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.handwheelinstalledoption', verbose_name='Встроенный дублер')),
                ('selected_ip', models.ForeignKey(blank=True, help_text='Выбранная степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.ipoption', verbose_name='Степень защиты IP')),
                ('selected_model_line', models.ForeignKey(blank=True, help_text='Серия пневмоприводов — фильтрует доступные модели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_model_lines', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия')),
                ('selected_model_line_item', models.ForeignKey(blank=True, help_text='Модель пневмопривода', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor_model_line_items', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Модель')),
                ('selected_safety_position', models.ForeignKey(blank=True, help_text='Выбранное положение безопасности привода', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.safetypositionoption', verbose_name='Выбранное положение безопасности')),
                ('selected_springs_qty', models.ForeignKey(blank=True, help_text='Выбранное количество пружин привода', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticactuatorspringsqty', verbose_name='Выбранное количество пружин')),
                ('selected_temperature', models.ForeignKey(blank=True, help_text='Выбранная температурная опция', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumatictemperatureoption', verbose_name='Температурная опция')),
            ],
            options={
                'verbose_name': 'Конструктор пневмопривода',
                'verbose_name_plural': 'Конструктор пневмоприводов',
                'ordering': ['sorting_order'],
            },
        ),
    ]
