# Generated by Django 5.2.7 on 2026-07-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('pneumatic_actuators', '0028_pneumaticactuatorconstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
    ]
