# Generated by Django 5.2.7 on 2026-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0004_alter_certdata_media_item'),
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('pneumatic_actuators', '0029_add_image_gallery_to_model_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
    ]
