# Generated by Django 5.2.7 on 2026-07-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0004_alter_certdata_media_item'),
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('pneumatic_actuators', '0030_add_techdoc_certdoc_to_model_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodellineitem',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatormodellineitem',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatormodellineitem',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
    ]
