# Generated by Django 5.2.7 on 2026-07-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0031_add_image_tech_cert_docs_to_model_line_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pneumaticactuatormodellineitem',
            name='cert_docs',
        ),
    ]
