# Generated by Django 5.2.7 on 2026-07-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0033_migrate_certs_to_m2m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PneumaticActuatorModelLineCertRelation',
        ),
    ]
