# Generated by Django 5.2.4 on 2026-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0034_remove_certrelation_through_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatorbody',
            name='air_usage_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Расход воздуха пневмоприводом за цикл закрытия, л', max_digits=10, null=True, verbose_name="Расход закр, л'"),
        ),
    ]
