# Generated by Django 5.2.4 on 2026-08-31 14:53

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_et_prompt_and_schema_fields'),
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('params', '0069_add_way_switch_x2_role'),
        ('pneumatic_actuators', '0035_alter_pneumaticactuatorbody_air_usage_close'),
        ('sku', '0005_mbom_mbomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodellineitem',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры'),
        ),
        migrations.CreateModel(
            name='PneumaticActuatorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Текстовое название пневмопривода — формируется из шаблона серии', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Артикул пневмопривода', max_length=150, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание пневмопривода — формируется из шаблона серии', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры в JSON', verbose_name='Параметры')),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Корпус')),
                ('equipment_type', models.ForeignKey(help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('model_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items', to='pneumatic_actuators.pneumaticactuatormodelline', verbose_name='Серия')),
                ('pneumatic_actuator_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items', to='pneumatic_actuators.pneumaticactuatorvariety', verbose_name='Вид привода (DA/SR)')),
                ('selected_body_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_coating', to='params.bodycoatingoption', verbose_name='Покрытие корпуса')),
                ('selected_exd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_exd', to='params.exdoption', verbose_name='Взрывозащита')),
                ('selected_hand_wheel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_hand_wheel', to='params.handwheelinstalledoption', verbose_name='Встроенный ручной дублер')),
                ('selected_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_ip', to='params.ipoption', verbose_name='Степень защиты IP')),
                ('selected_safety_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_safety_position', to='params.safetypositionoption', verbose_name='Положение безопасности')),
                ('selected_springs_qty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_springs_qty', to='pneumatic_actuators.pneumaticactuatorspringsqty', verbose_name='Количество пружин')),
                ('selected_temperature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_temperature', to='pneumatic_actuators.pneumatictemperatureoption', verbose_name='Температурная опция')),
                ('sku', models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU')),
                ('source_model_line_item', models.ForeignKey(blank=True, help_text='Связь со старым model_line_item; удаляется после унификации', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Исходная модель (legacy)')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
            ],
            options={
                'verbose_name': 'Пневмопривод (каталог)',
                'verbose_name_plural': 'Пневмоприводы (каталог)',
                'ordering': ['sorting_order', 'code'],
            },
            bases=(core.models.mixins.CatalogDictMixin, core.models.mixins.CopyMixin, core.models.mixins.TemplateMixin, models.Model),
        ),
    ]
