# Generated by Django 5.2.4 on 2026-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0036_pneumaticactuatormodellineitem_extra_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='description_template',
            field=models.TextField(blank=True, help_text='Шаблон для описания пневмопривода', null=True, verbose_name='Шаблон описания'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatormodelline',
            name='name_template',
            field=models.TextField(blank=True, help_text='Шаблон для текстового названия пневмопривода', null=True, verbose_name='Шаблон названия'),
        ),
    ]
