# Generated by Django 5.2.4 on 2026-09-16 18:14
# Дополнено вручную: дата-миграция переносит exd_option (FK) в M2M exd_options
# и ремапит PneumaticActuatorConstructor.selected_exd на through-строки.

import django.db.models.deletion
from django.db import migrations, models


def migrate_exd_option_to_m2m(apps, schema_editor):
    """PneumaticExdOption: exd_option (FK) → exd_options (M2M).

    Конструктор: selected_exd хранил ID params.ExdOption — ремапим на
    through-строку серии, содержащую этот вид (или создаём строку).
    """
    PneumaticExdOption = apps.get_model('pneumatic_actuators', 'PneumaticExdOption')
    PneumaticActuatorConstructor = apps.get_model(
        'pneumatic_actuators', 'PneumaticActuatorConstructor'
    )

    # 1. Перенос FK → M2M у through-строк
    for row in PneumaticExdOption.objects.exclude(exd_option_id=None):
        row.exd_options.add(row.exd_option_id)

    # 2. Ремап selected_exd конструкторов: ExdOption id → through-строка серии
    for c in PneumaticActuatorConstructor.objects.exclude(selected_exd_id=None):
        item = c.selected_model_line_item
        if not item or not item.model_line_id:
            c.selected_exd_id = None
            c.save(update_fields=['selected_exd'])
            continue
        ml_id = item.model_line_id
        row = PneumaticExdOption.objects.filter(
            model_line_id=ml_id, exd_options__id=c.selected_exd_id
        ).first()
        if row is None:
            row = (
                PneumaticExdOption.objects.filter(
                    model_line_id=ml_id, is_default=True, is_active=True
                ).first()
                or PneumaticExdOption.objects.filter(
                    model_line_id=ml_id, is_active=True
                ).first()
            )
            if row is None:
                row = PneumaticExdOption.objects.create(
                    model_line_id=ml_id, encoding='',
                    is_default=True, is_active=True,
                )
            row.exd_options.add(c.selected_exd_id)
        c.selected_exd_id = row.id
        c.save(update_fields=['selected_exd'])


def revert_exd_option_from_m2m(apps, schema_editor):
    """Обратный перенос: exd_option (FK) строки — из первого вида M2M;
    selected_exd конструктора — обратно в id вида ExdOption.

    Точность ограничена: при нескольких видах в строке берётся первый —
    в исходных данных строка содержала ровно один вид.
    """
    PneumaticExdOption = apps.get_model('pneumatic_actuators', 'PneumaticExdOption')
    PneumaticActuatorConstructor = apps.get_model(
        'pneumatic_actuators', 'PneumaticActuatorConstructor'
    )
    first_variety = {}
    for r in PneumaticExdOption.objects.all().prefetch_related('exd_options'):
        v = r.exd_options.order_by('id').first()
        if v is not None:
            r.exd_option_id = v.id
            r.save(update_fields=['exd_option'])
        first_variety[r.id] = v
    for c in PneumaticActuatorConstructor.objects.exclude(selected_exd_id=None):
        v = first_variety.get(c.selected_exd_id)
        if v is not None:
            c.selected_exd_id = v.id
            c.save(update_fields=['selected_exd'])


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0069_add_way_switch_x2_role'),
        ('pneumatic_actuators', '0037_pneumaticactuatormodelline_description_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticexdoption',
            options={'ordering': ['is_default', 'sorting_order'], 'verbose_name': 'Опция взрывозащиты пневмопривода', 'verbose_name_plural': 'Опции взрывозащиты пневмоприводов'},
        ),
        migrations.AlterUniqueTogether(
            name='pneumaticexdoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pneumaticexdoption',
            name='exd_options',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_exd_rows', to='params.exdoption', verbose_name='Виды взрывозащиты'),
        ),
        # Временно ослабляем exd_option до NULL, чтобы обратный реверс мог
        # пересоздать колонку без NOT NULL-краха до заполнения значений.
        migrations.AlterField(
            model_name='pneumaticexdoption',
            name='exd_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='params.exdoption', verbose_name='Опция взрывозащиты'),
        ),
        migrations.RunPython(migrate_exd_option_to_m2m, revert_exd_option_from_m2m),
        migrations.AlterField(
            model_name='pneumaticactuatorconstructor',
            name='selected_exd',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты (through-строка с кодировкой и видами Ex)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticexdoption', verbose_name='Взрывозащита'),
        ),
        migrations.AlterField(
            model_name='pneumaticactuatoritem',
            name='selected_exd',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты (through-строка с кодировкой и видами Ex)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_items_exd', to='pneumatic_actuators.pneumaticexdoption', verbose_name='Взрывозащита'),
        ),
        migrations.RemoveField(
            model_name='pneumaticexdoption',
            name='exd_option',
        ),
    ]
