# Generated by Django 5.2.4 on 2026-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0039_pneumaticactuatormodelline_spec_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatorvariety',
            name='name',
            field=models.CharField(help_text='Название разновидности', max_length=150, verbose_name='Название'),
        ),
    ]
