# Generated by Django 5.2.4 on 2026-09-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0040_alter_pneumaticactuatorvariety_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticactuatorconstructionvariety',
            name='name',
            field=models.CharField(help_text='Название разновидности конструкции', max_length=150, verbose_name='Название'),
        ),
    ]
