# Generated by Django 5.2.7 on 2026-09-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0069_add_way_switch_x2_role'),
        ('pneumatic_actuators', '0042_pneumaticbodydesignoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticbodydesignoption',
            name='body_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_body_design_colors', to='params.bodycolor', verbose_name='Цвет корпуса'),
        ),
    ]
