# Generated by Django 5.2.7 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0044_add_scotch_yoke_spring_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatoritem',
            name='config_hash',
            field=models.CharField(blank=True, help_text='SHA-256 от типоразмера + опций; ключ дедупа и диффа', max_length=64, null=True, unique=True, verbose_name='Хэш конфигурации'),
        ),
        migrations.AddField(
            model_name='pneumaticactuatoritem',
            name='exclude_from_catalog',
            field=models.BooleanField(default=False, help_text='Скрыть из листингов каталога (поиск и деталка работают)', verbose_name='Не включать в каталог'),
        ),
    ]
