# Generated by Django 5.2.7 on 2026-10-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_equipmenttype_title_template'),
        ('media_library', '0015_alter_imagegallerysetitem_image'),
        ('params', '0069_add_way_switch_x2_role'),
        ('pneumatic_actuators', '0045_pneumaticactuatoritem_config_hash_and_more'),
        ('sku', '0007_alter_sku_code_sku_sku_code_uniq_nobrand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PneumaticActuatorItem',
            new_name='PneumaticActuatorCatalogItem',
        ),
    ]
