# Generated by Django 5.2.7 on 2026-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0046_rename_pneumaticactuatoritem_pneumaticactuatorcatalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatorcatalogitem',
            name='origin',
            field=models.CharField(choices=[('generated', 'Сгенерирована'), ('manual', 'Ручная')], default='generated', help_text='Кто владеет жизненным циклом карточки: генератор или человек', max_length=16, verbose_name='Происхождение'),
        ),
    ]
