# Generated by Django 5.2.7 on 2026-10-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0047_pneumaticactuatorcatalogitem_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodythrusttorquetable',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Модель корпуса привода', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_thrust_torque_table', to='pneumatic_actuators.pneumaticactuatorbody', verbose_name='Модель'),
        ),
    ]
