# Generated by Django 5.2.7 on 2026-10-02 13:22

import django.db.models.deletion
from django.db import migrations, models


def transfer_manual_override(apps, schema_editor):
    """Перенос опций ручного дублера с серии (model_line) на модель (model_line_item).

    - Серия «AIR-SY» (code='AIR-SY', кулисные SR) — копируем ВСЕ опции серии
      в каждый типоразмер.
    - Остальные серии — каждому типоразмеру единственная опция «Не установлен».
    """
    Old = apps.get_model('pneumatic_actuators', 'PneumaticHandWheelOption')
    New = apps.get_model('pneumatic_actuators', 'PneumaticManualOverrideOption')
    MLI = apps.get_model('pneumatic_actuators', 'PneumaticActuatorModelLineItem')
    HWI = apps.get_model('params', 'HandWheelInstalledOption')

    none_opt = (
        HWI.objects.filter(code='none').first()
        or HWI.objects.filter(name='Не установлен').first()
    )

    old_rows = list(Old.objects.select_related('hand_wheel_option').all())
    by_model_line = {}
    for r in old_rows:
        by_model_line.setdefault(r.model_line_id, []).append(r)

    for mli in MLI.objects.select_related('model_line').all():
        ml = mli.model_line
        if ml and ml.code == 'AIR-SY':
            for old in by_model_line.get(ml.id, []):
                New.objects.create(
                    model_line_item=mli,
                    hand_wheel_option=old.hand_wheel_option,
                    encoding=old.encoding,
                    description=old.description,
                    sorting_order=old.sorting_order,
                    is_active=old.is_active,
                    is_default=old.is_default,
                )
        else:
            if none_opt:
                New.objects.create(
                    model_line_item=mli,
                    hand_wheel_option=none_opt,
                    encoding='',
                    sorting_order=0,
                    is_active=True,
                    is_default=True,
                )


def reverse_manual_override(apps, schema_editor):
    New = apps.get_model('pneumatic_actuators', 'PneumaticManualOverrideOption')
    New.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0069_add_way_switch_x2_role'),
        ('pneumatic_actuators', '0048_alter_bodythrusttorquetable_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pneumaticactuatorselected',
            name='selected_hand_wheel',
        ),
        migrations.RenameField(
            model_name='pneumaticactuatorcatalogitem',
            old_name='selected_hand_wheel',
            new_name='selected_manual_override',
        ),
        migrations.RenameField(
            model_name='pneumaticactuatorconstructor',
            old_name='selected_hand_wheel',
            new_name='selected_manual_override',
        ),
        migrations.CreateModel(
            name='PneumaticManualOverrideOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('hand_wheel_option', models.ForeignKey(help_text='Тип установленного ручного дублера', on_delete=django.db.models.deletion.CASCADE, to='params.handwheelinstalledoption', verbose_name='Ручной дублер')),
                ('model_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_override_options', to='pneumatic_actuators.pneumaticactuatormodellineitem', verbose_name='Модель в серии')),
            ],
            options={
                'verbose_name': 'Тип установленного ручного дублера',
                'verbose_name_plural': 'Типы установленного ручного дублера пневмоприводов',
                'ordering': ['is_default', 'sorting_order'],
                'unique_together': {('model_line_item', 'encoding')},
            },
        ),
        migrations.AddField(
            model_name='pneumaticactuatorselected',
            name='selected_manual_override',
            field=models.ForeignKey(blank=True, help_text='Встроенный ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pneumatic_actuators.pneumaticmanualoverrideoption', verbose_name='Встроенный дублер'),
        ),
        migrations.RunPython(transfer_manual_override, reverse_manual_override),
        migrations.DeleteModel(
            name='PneumaticHandWheelOption',
        ),
    ]
