# Generated by Django 5.2.7 on 2026-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0049_remove_pneumaticactuatorselected_selected_hand_wheel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticmanualoverrideoption',
            name='mo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Вес ручного дублера, кг.', max_digits=6, null=True, verbose_name='Вес ручного дублера'),
        ),
        migrations.AlterField(
            model_name='pneumaticactuatorbody',
            name='weight_spring',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Вес 1 пружины, кг', max_digits=5, null=True, verbose_name='Вес пружины'),
        ),
    ]
