# Generated by Django 5.2.7 on 2026-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0050_pneumaticmanualoverrideoption_mo_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatorcatalogitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Рассчитанный вес привода (корпус + пружины + ручной дублер). Материализуется при генерации карточки, а не считается динамически.', max_digits=10, null=True, verbose_name='Вес, кг'),
        ),
    ]
