# Generated by Django 5.2.7 on 2026-10-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_actuators', '0051_pneumaticactuatorcatalogitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticactuatorcatalogitem',
            name='manual_override_option',
            field=models.ForeignKey(blank=True, help_text='Конкретная опция ручного дублера (through) с весом mo_weight; используется для расчёта веса карточки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pneumatic_actuators.pneumaticmanualoverrideoption', verbose_name='Опция ручного дублера'),
        ),
    ]
