# Generated by Django 5.2.7 on 2026-10-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0072_remove_controlunitsignalprofileentry_description_i18n_and_more'),
        ('pneumatic_actuators', '0054_pneumaticactuatormodelline_description_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticbodydesignoption',
            name='body_coating_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_body_design_coatings', to='params.bodycoatingoption', verbose_name='Опция покрытия корпуса (справочник)'),
        ),
    ]
