# Generated by Django 5.1.4 on 2025-02-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0007_mechanicalindicatorinstalledoption'),
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение (артикул)         серии арматуры производителя', max_length=20)),
                ('valve_brand', models.ForeignKey(blank=True, help_text='Бренд серии арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_brand', to='producers.brands')),
                ('valve_producer', models.ForeignKey(blank=True, help_text='Производитель серии арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_producer', to='producers.producer')),
                ('valve_type', models.ForeignKey(blank=True, help_text='Тип арматуры серии арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_type', to='params.valvetypes')),
            ],
        ),
        migrations.CreateModel(
            name='ValveModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение (артикул)     модели арматуры производителя', max_length=50)),
                ('valve_model_dn', models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True)),
                ('valve_model_pn', models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True)),
                ('valve_model_pn_delta', models.PositiveIntegerField(blank=True, help_text='Перепад Dn арматуры', null=True)),
                ('valve_model_torque_to_open', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_torque_to_close', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_rotations_to_open', models.DecimalField(decimal_places=1, help_text='Число оборотов на открытие', max_digits=5)),
                ('valve_model_model_line', models.ForeignKey(blank=True, help_text='Серия арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_model_model_line', to='valve_data.valveline')),
                ('valve_model_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='valve_data_mounting_plate', to='params.mountingplatetypes')),
                ('valve_model_pn_delta_measure_unit', models.ForeignKey(blank=True, help_text='Единица измерения перепада Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_data_pn_delta_measure_unit', to='params.measureunits')),
                ('valve_model_pn_measure_unit', models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_data_pn_measure_unit', to='params.measureunits')),
                ('valve_model_stem_size', models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_model_stem_size', to='params.stemsize')),
            ],
        ),
    ]
