# Generated by Django 5.1.4 on 2025-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveline',
            name='voltage_type',
            field=models.CharField(choices=[('Выдвижной', 'Выдвижной шток'), ('НЕвыдвижной', 'Невыдвижной шток')], default='НЕвыдвижной', max_length=30),
        ),
    ]
