# Generated by Django 5.1.4 on 2025-02-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0008_controlunitlocationoption_controlunittypeoption_and_more'),
        ('valve_data', '0002_valveline_voltage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valveline',
            name='voltage_type',
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_stem_retract_type',
            field=models.CharField(choices=[('Выдвижной', 'Выдвижной шток'), ('НЕвыдвижной', 'Невыдвижной шток')], default='НЕвыдвижной', max_length=30),
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_type',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_valve_type', to='params.valvetypes'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_mounting_plate',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='%(class)s', to='params.mountingplatetypes'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_delta_measure_unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения перепада Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_delta_measure_unit', to='params.measureunits'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_measure_unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_measure_unit', to='params.measureunits'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_stem_size',
            field=models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.stemsize'),
        ),
    ]
