# Generated by Django 5.2.4 on 2025-09-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('valve_data', '0003_remove_valveline_voltage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа арматуры', max_length=2)),
                ('actuator_gearbox_combinations', models.CharField(help_text='Символьное обозначение     подходящего типа привода и редуктора', max_length=10)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     типа арматуры', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='valveline',
            name='valve_type',
        ),
        migrations.CreateModel(
            name='ComponentAllowedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_usages', to='materials.materialspecified', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Допустимый материал для компонента арматуры',
                'verbose_name_plural': 'Допустимые материалы для компонента арматуры',
                'ordering': ['valve_component', 'material'],
            },
        ),
        migrations.CreateModel(
            name='ValveComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа арматуры', max_length=100)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа арматуры', max_length=500)),
                ('is_critical', models.BooleanField(default=False, help_text='Компонент, требующий особого подбора материалов', verbose_name='Критический компонент')),
                ('allowed_materials', models.ManyToManyField(help_text='Материалы, из которых может быть изготовлен компонент', related_name='valve_components', through='valve_data.ComponentAllowedMaterial', through_fields=('valve_component', 'material'), to='materials.materialspecified', verbose_name='Допустимые материалы')),
                ('valve_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_components', to='valve_data.valvevariety', verbose_name='Тип арматуры')),
            ],
            options={
                'verbose_name': 'Компонент арматуры',
                'verbose_name_plural': 'Компоненты арматуры',
                'ordering': ['valve_variety', 'symbolic_code'],
            },
        ),
        migrations.AddField(
            model_name='componentallowedmaterial',
            name='valve_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_materials', to='valve_data.valvecomponent', verbose_name='Компонент арматуры'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_variety',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры серии арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line', to='valve_data.valvevariety'),
        ),
        migrations.AlterUniqueTogether(
            name='componentallowedmaterial',
            unique_together={('valve_component', 'material')},
        ),
        migrations.AddIndex(
            model_name='valvecomponent',
            index=models.Index(fields=['valve_variety', 'symbolic_code'], name='valve_data__valve_v_5c98c9_idx'),
        ),
        migrations.AddIndex(
            model_name='valvecomponent',
            index=models.Index(fields=['symbolic_code'], name='valve_data__symboli_0f08e9_idx'),
        ),
        migrations.AddIndex(
            model_name='valvecomponent',
            index=models.Index(fields=['is_critical'], name='valve_data__is_crit_92b624_idx'),
        ),
    ]
