# Generated by Django 4.2.23 on 2025-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0004_valvevariety_remove_valveline_valve_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valveline',
            options={'ordering': ['valve_variety', 'valve_producer', 'symbolic_code'], 'verbose_name': 'Серия арматуры', 'verbose_name_plural': 'Серии арматуры'},
        ),
        migrations.AlterModelOptions(
            name='valvemodeldata',
            options={'ordering': ['valve_model_model_line', 'symbolic_code'], 'verbose_name': 'Тех.данные арматуры', 'verbose_name_plural': 'Тех.данные арматуры'},
        ),
        migrations.AlterModelOptions(
            name='valvevariety',
            options={'ordering': ['text_description'], 'verbose_name': 'Тип арматуры', 'verbose_name_plural': 'Типы арматуры'},
        ),
        migrations.AlterField(
            model_name='valvevariety',
            name='actuator_gearbox_combinations',
            field=models.CharField(help_text='Символьное обозначение     подходящего типа привода и редуктора', max_length=10, verbose_name='Символьное обозначение     подходящего типа привода и редуктора'),
        ),
        migrations.AlterField(
            model_name='valvevariety',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение     типа арматуры', max_length=2, verbose_name='Символьное обозначение типа арматуры'),
        ),
        migrations.AlterField(
            model_name='valvevariety',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание     типа арматуры', max_length=200, verbose_name='Текстовое описание типа арматуры'),
        ),
    ]
