# Generated by Django 4.2.23 on 2025-09-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialchemicalresistance_workingmedium_and_more'),
        ('producers', '0001_initial'),
        ('valve_data', '0005_alter_valveline_options_alter_valvemodeldata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveConnectionToPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа присоединения арматуры к трубе', max_length=200, verbose_name='Символьное обозначение     типа присоединения арматуры к трубе')),
            ],
            options={
                'verbose_name': 'Тип присоединения арматуры к трубе',
                'verbose_name_plural': 'Типы присоединения арматуры к трубе',
                'ordering': ['symbolic_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='valveline',
            options={'ordering': ['valve_variety', 'valve_producer', 'symbolic_code'], 'verbose_name': 'Семейство серий арматуры', 'verbose_name_plural': 'Семейство серий арматуры'},
        ),
        migrations.AlterField(
            model_name='valvecomponent',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение компонента', max_length=100),
        ),
        migrations.AlterField(
            model_name='valvecomponent',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание компонента арматуры', max_length=500),
        ),
        migrations.AlterField(
            model_name='valvecomponent',
            name='valve_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_components', to='valve_data.valvevariety', verbose_name='Тип арматуры для компонента'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение (артикул)         семейства серий арматуры производителя', max_length=20),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_brand',
            field=models.ForeignKey(blank=True, help_text='Бренд семейства серий  арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_brand', to='producers.brands'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_producer',
            field=models.ForeignKey(blank=True, help_text='Производитель семейства серий арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_producer', to='producers.producer'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_variety',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры семейства арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line', to='valve_data.valvevariety'),
        ),
        migrations.CreateModel(
            name='ValveLineSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение (артикул)         серии (внутри семейства) арматуры производителя', max_length=20)),
                ('temp_min', models.IntegerField(help_text='Минимально допустимая температура среды для серии арматуры, °С', verbose_name='Минимально допустимая температура среды для серии арматуры, °С')),
                ('temp_max', models.IntegerField(help_text='Максимально допустимая температура среды для серии арматуры, °С', verbose_name='Максимально допустимая температура среды для серии арматуры, °С')),
                ('work_temp_min', models.IntegerField(help_text='Минимальная рабочая температура серии арматуры, °С', verbose_name='Минимальная рабочая температура серии арматуры, °С')),
                ('work_temp_max', models.IntegerField(help_text='Максимальная рабочая температура серии арматуры, °С', verbose_name='Максимальная рабочая температура серии арматуры, °С')),
                ('body_material', models.ForeignKey(blank=True, help_text='Тип материала корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_body_material', to='materials.materialgeneral')),
                ('body_material_specified', models.ForeignKey(blank=True, help_text='Марка материала корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_body_material', to='materials.materialspecified')),
                ('pipe_connection', models.ForeignKey(blank=True, help_text='Тип присоединения арматуры к трубе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_pipe_connection', to='valve_data.valveconnectiontopipe')),
                ('sealing_element_material_specified', models.ForeignKey(blank=True, help_text='Марка материала уплотнения арматуры серии арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_sealing_element_material', to='materials.materialspecified')),
                ('shut_element_material', models.ForeignKey(blank=True, help_text='Тип материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_shut_element_material', to='materials.materialgeneral')),
                ('shut_element_material_specified', models.ForeignKey(blank=True, help_text='Марка материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_shut_element_material', to='materials.materialspecified')),
                ('valve_line', models.ForeignKey(blank=True, help_text='Тип арматуры серии арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series', to='valve_data.valveline')),
            ],
            options={
                'verbose_name': 'Серия арматуры',
                'verbose_name_plural': 'Серии арматуры',
                'ordering': ['valve_line', 'symbolic_code'],
            },
        ),
    ]
