# Generated by Django 4.2.23 on 2025-09-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0006_valveconnectiontopipe_alter_valveline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAVAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название атрибута')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код атрибута')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data_type', models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('float', 'Десятичное число'), ('boolean', 'Да/Нет')], default='string', max_length=20, verbose_name='Тип данных')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EAVValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('display_name', models.CharField(max_length=200, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_values', to='valve_data.eavattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'ordering': ['attribute', 'order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ValveVarietyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_varieties', to='valve_data.eavattribute', verbose_name='Атрибут')),
                ('valve_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_attributes', to='valve_data.valvevariety', verbose_name='Разновидность арматуры')),
            ],
            options={
                'verbose_name': 'Атрибут разновидности',
                'verbose_name_plural': 'Атрибуты разновидностей',
                'ordering': ['valve_variety', 'order'],
                'unique_together': {('valve_variety', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ValveSeriesAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Произвольное значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_values', to='valve_data.eavattribute', verbose_name='Атрибут')),
                ('predefined_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_usages', to='valve_data.eavvalue', verbose_name='Значение из справочника')),
                ('valve_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='valve_data.valvelineseries', verbose_name='Серия арматуры')),
            ],
            options={
                'verbose_name': 'Значение атрибута серии',
                'verbose_name_plural': 'Значения атрибутов серий',
                'unique_together': {('valve_series', 'attribute')},
            },
        ),
    ]
