# Generated by Django 4.2.23 on 2025-09-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0007_eavattribute_eavvalue_valvevarietyattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvecomponent',
            name='allowed_materials',
        ),
        migrations.RemoveField(
            model_name='valvecomponent',
            name='valve_variety',
        ),
        migrations.DeleteModel(
            name='ComponentAllowedMaterial',
        ),
        migrations.DeleteModel(
            name='ValveComponent',
        ),
    ]
