# Generated by Django 4.2.23 on 2025-09-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materialgeneralmoredetailed_text_description_and_more'),
        ('valve_data', '0008_remove_valvecomponent_allowed_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvelineseries',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Тип материала корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AlterField(
            model_name='valvelineseries',
            name='body_material_specified',
            field=models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_body_material', to='materials.materialspecified'),
        ),
        migrations.AlterField(
            model_name='valvelineseries',
            name='sealing_element_material_specified',
            field=models.ForeignKey(blank=True, help_text='Марка материала уплотнения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_sealing_element_material', to='materials.materialspecified', verbose_name='Материал уплотнения'),
        ),
        migrations.AlterField(
            model_name='valvelineseries',
            name='shut_element_material',
            field=models.ForeignKey(blank=True, help_text='Тип материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_shut_element_material', to='materials.materialgeneral', verbose_name='Тип материала запорного элемента'),
        ),
        migrations.AlterField(
            model_name='valvelineseries',
            name='shut_element_material_specified',
            field=models.ForeignKey(blank=True, help_text='Марка материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_shut_element_material', to='materials.materialspecified', verbose_name='Материал запорного элемента'),
        ),
        migrations.AlterField(
            model_name='valvelineseries',
            name='valve_line',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры серии арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series', to='valve_data.valveline', verbose_name='Тип арматуры'),
        ),
    ]
