# Generated by Django 4.2.23 on 2025-09-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0009_alter_valvelineseries_body_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvelineseries',
            name='valve_line',
            field=models.ForeignKey(blank=True, help_text='Семейство серии арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series', to='valve_data.valveline', verbose_name='Семейство серии арматуры'),
        ),
    ]
