# Generated by Django 4.2.23 on 2025-09-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0011_bodycolor_bodycoloroption_dnvariety_pnvariety'),
        ('valve_data', '0010_alter_valvelineseries_valve_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveLineEAVAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название атрибута')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код атрибута')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('value_type', models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('float', 'Десятичное число'), ('boolean', 'Да/Нет'), ('choice', 'Выбор из списка'), ('multi_choice', 'Множественный выбор')], default='string', max_length=20, verbose_name='Тип значения')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Атрибут ValveLine',
                'verbose_name_plural': 'Атрибуты ValveLine',
                'ordering': ['section__sorting_order', 'sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValveLineEAVChoiceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('display_name', models.CharField(max_length=200, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_values', to='valve_data.valvelineeavattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение для выбора',
                'verbose_name_plural': 'Значения для выбора',
                'ordering': ['attribute', 'sorting_order', 'display_name'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ValveSeriesDnPnTorqueMountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_model_torque_to_open', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_torque_to_close', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_rotations_to_open', models.DecimalField(decimal_places=1, help_text='Число оборотов на открытие', max_digits=5)),
                ('valve_model_model_series', models.ForeignKey(blank=True, help_text='Серия арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='valve_data.valveline', verbose_name='Серия арматуры')),
                ('valve_model_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='valve_series_dn_pn_torque_mount_data', to='params.mountingplatetypes')),
                ('valve_model_stem_size', models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='params.stemsize')),
                ('valve_series_dn', models.ForeignKey(blank=True, help_text='Dn арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='params.dnvariety', verbose_name='Dn арматуры')),
                ('valve_series_max_pn_option', models.ForeignKey(blank=True, help_text='Pn арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='params.pnvariety', verbose_name='Pn арматуры')),
            ],
        ),
        migrations.CreateModel(
            name='ValveLineSeriesBodyColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная стоимость для этого цвета и типа исполнения', max_digits=10, verbose_name='Дополнительная стоимость')),
                ('lead_time_days', models.IntegerField(default=0, help_text='Дополнительное время изготовления в днях', verbose_name='Срок изготовления (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('body_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_series_usages', to='params.bodycolor', verbose_name='Цвет корпуса')),
                ('option_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_usages', to='params.bodycoloroption', verbose_name='Тип исполнения')),
                ('valve_line_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_series_body_colors', to='valve_data.valvelineseries', verbose_name='Серия арматуры')),
            ],
            options={
                'verbose_name': 'Цвет корпуса серии',
                'verbose_name_plural': 'Цвета корпусов серий',
                'ordering': ['valve_line_series', 'option_variety__sorting_order', 'sorting_order'],
                'unique_together': {('valve_line_series', 'body_color', 'option_variety')},
            },
        ),
        migrations.CreateModel(
            name='ValveLineEAVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код раздела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('valve_varieties', models.ManyToManyField(help_text='Типы арматуры, для которых доступен этот раздел', related_name='eav_sections', to='valve_data.valvevariety', verbose_name='Типы арматуры')),
            ],
            options={
                'verbose_name': 'Раздел атрибутов ValveLine',
                'verbose_name_plural': 'Разделы атрибутов ValveLine',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='valvelineeavattribute',
            name='section',
            field=models.ForeignKey(help_text='Раздел, к которому принадлежит атрибут', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='valve_data.valvelineeavsection', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='valvelineseries',
            name='body_colors',
            field=models.ManyToManyField(blank=True, related_name='valve_series', through='valve_data.ValveLineSeriesBodyColor', to='params.bodycolor', verbose_name='Цвета корпуса'),
        ),
        migrations.CreateModel(
            name='ValveLineEAVValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(blank=True, max_length=500, verbose_name='Строковое значение')),
                ('integer_value', models.IntegerField(blank=True, null=True, verbose_name='Числовое значение')),
                ('float_value', models.FloatField(blank=True, null=True, verbose_name='Десятичное значение')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='valve_data.valvelineeavattribute', verbose_name='Атрибут')),
                ('choice_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eav_usages', to='valve_data.valvelineeavchoicevalue', verbose_name='Значение из списка')),
                ('multi_choice_values', models.ManyToManyField(blank=True, related_name='multi_eav_usages', to='valve_data.valvelineeavchoicevalue', verbose_name='Множественные значения')),
                ('valve_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eav_values', to='valve_data.valveline', verbose_name='Семейство серий арматуры')),
            ],
            options={
                'verbose_name': 'Значение атрибута ValveLine',
                'verbose_name_plural': 'Значения атрибутов ValveLine',
                'unique_together': {('valve_line', 'attribute')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='valvelineeavattribute',
            unique_together={('section', 'code')},
        ),
    ]
