# Generated by Django 5.2.4 on 2025-09-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0012_coatingvariety_optionvariety_sealingclass_and_more'),
        ('valve_data', '0011_valvelineeavattribute_valvelineeavchoicevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvelineseries',
            name='body_colors',
            field=models.ManyToManyField(blank=True, related_name='valve_series', through='valve_data.ValveLineSeriesBodyColor', through_fields=('valve_line_series', 'body_color'), to='params.bodycolor', verbose_name='Цвета корпуса'),
        ),
        migrations.AlterField(
            model_name='valvelineseriesbodycolor',
            name='option_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_series_body_color_option_variety', to='params.optionvariety', verbose_name='Стандарт или опция'),
        ),
    ]
