# Generated by Django 4.2.23 on 2025-09-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materialgeneralmoredetailed_text_description_and_more'),
        ('params', '0015_warrantytimeperiodvariety'),
        ('producers', '0001_initial'),
        ('valve_data', '0012_alter_valvelineseries_body_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveLineBodyColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная стоимость для этого цвета и типа исполнения', max_digits=10, verbose_name='Дополнительная стоимость')),
                ('lead_time_days', models.IntegerField(default=0, help_text='Дополнительное время изготовления в днях', verbose_name='Срок изготовления (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('body_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_body_color_usages', to='params.bodycolor', verbose_name='Цвет корпуса')),
                ('option_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_body_color_option_variety', to='params.optionvariety', verbose_name='Стандарт или опция')),
            ],
            options={
                'verbose_name': 'Цвет корпуса серии',
                'verbose_name_plural': 'Цвета корпусов серий',
                'ordering': ['valve_line', 'option_variety__sorting_order', 'sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ValveLineSealingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная стоимость для этого цвета и типа исполнения', max_digits=10, verbose_name='Дополнительная стоимость')),
                ('lead_time_days', models.IntegerField(default=0, help_text='Дополнительное время изготовления в днях', verbose_name='Срок изготовления (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('option_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_sealing_material_option_variety', to='params.optionvariety', verbose_name='Стандарт или опция')),
                ('sealing_element_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_sealing_material', to='materials.materialspecified', verbose_name='Материал уплотнения')),
            ],
            options={
                'verbose_name': 'Материал уплотнения серии',
                'verbose_name_plural': 'Материалы уплотнения серий',
                'ordering': ['valve_line', 'option_variety__sorting_order', 'sorting_order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='valvelineeavchoicevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='valvelineeavchoicevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='valvelineeavsection',
            name='valve_varieties',
        ),
        migrations.AlterUniqueTogether(
            name='valvelineeavvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='valvelineeavvalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='valvelineeavvalue',
            name='choice_value',
        ),
        migrations.RemoveField(
            model_name='valvelineeavvalue',
            name='multi_choice_values',
        ),
        migrations.RemoveField(
            model_name='valvelineeavvalue',
            name='valve_line',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='body_colors',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='body_material_specified',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='pipe_connection',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='sealing_element_material_specified',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='shut_element_material',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='shut_element_material_specified',
        ),
        migrations.RemoveField(
            model_name='valvelineseries',
            name='valve_line',
        ),
        migrations.AlterUniqueTogether(
            name='valvelineseriesbodycolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='valvelineseriesbodycolor',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='valvelineseriesbodycolor',
            name='option_variety',
        ),
        migrations.RemoveField(
            model_name='valvelineseriesbodycolor',
            name='valve_line_series',
        ),
        migrations.AlterUniqueTogether(
            name='valveseriesattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='valveseriesattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='valveseriesattributevalue',
            name='predefined_value',
        ),
        migrations.RemoveField(
            model_name='valveseriesattributevalue',
            name='valve_series',
        ),
        migrations.AddField(
            model_name='valveline',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Тип материала корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='body_material_specified',
            field=models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_body_material', to='materials.materialspecified'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='pipe_connection',
            field=models.ForeignKey(blank=True, help_text='Тип присоединения арматуры к трубе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_series_pipe_connection', to='valve_data.valveconnectiontopipe'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='shut_element_material',
            field=models.ForeignKey(blank=True, help_text='Тип материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_shut_element_material', to='materials.materialgeneral', verbose_name='Тип материала запорного элемента'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='shut_element_material_specified',
            field=models.ForeignKey(blank=True, help_text='Марка материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_shut_element_material', to='materials.materialspecified', verbose_name='Материал запорного элемента'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_function',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры семейства арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_function', to='params.valvefunctionvariety', verbose_name='Код текста продолжительности гарантийного срока'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_in_service_cycles',
            field=models.IntegerField(default=0, help_text='Расчетное количество циклов', verbose_name='Расчетное количество циклов'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_in_service_cycles_comment',
            field=models.CharField(help_text='Условие выработки расчетного количества циклов', max_length=500, null=True, verbose_name='Условие выработки расчетного количества циклов'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_in_service_years',
            field=models.IntegerField(default=0, help_text='Расчетный срок эксплуатации - не менее, лет', verbose_name='Расчетный срок эксплуатации - не менее, лет'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_sealing_class',
            field=models.ForeignKey(blank=True, help_text='Класс герметичности арматуры ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_sealing_class', to='params.sealingclass', verbose_name='Класс герметичности арматуры '),
        ),
        migrations.AddField(
            model_name='valveline',
            name='warranty_period_max',
            field=models.IntegerField(default=0, help_text='Гарантийный срок не более, мес', verbose_name='Гарантийный срок не более, мес'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='warranty_period_min',
            field=models.IntegerField(default=0, help_text='Гарантийный срок, мес', verbose_name='Гарантийный срок мин, мес'),
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_dn',
            field=models.ForeignKey(blank=True, help_text='Dn арматуры, бар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_valve_dn_variety', to='params.dnvariety', verbose_name='Dn арматуры, бар'),
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_model_thrust_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Усилие на закрытие, Н', max_digits=8, verbose_name='Усилие на закрытие, Н'),
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_pn',
            field=models.ForeignKey(blank=True, help_text='Pn арматуры, мм', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_valve_pn_variety', to='params.pnvariety', verbose_name='Pn арматуры, мм'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_brand',
            field=models.ForeignKey(blank=True, help_text='Бренд семейства серий  арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_brand', to='producers.brands', verbose_name='Бренд семейства серий  арматуры'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_producer',
            field=models.ForeignKey(blank=True, help_text='Производитель семейства серий арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_producer', to='producers.producer', verbose_name='Производитель семейства серий арматуры'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_variety',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры семейства арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_variety', to='valve_data.valvevariety', verbose_name='Тип арматуры семейства арматуры производителя'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_dn',
            field=models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True, verbose_name='Dn арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn',
            field=models.PositiveIntegerField(blank=True, help_text='Pn арматуры', null=True, verbose_name='Pn арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_delta',
            field=models.PositiveIntegerField(blank=True, help_text='Перепад Dn арматуры', null=True, verbose_name='Перепад Dn арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_measure_unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_measure_unit', to='params.measureunits', verbose_name='Единица измерения Pn'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Вращающий момент на закрытие,Нм', max_digits=5, verbose_name='Вращающий момент на закрытие,Нм'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_open',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Вращающий момент на открытие,Нм', max_digits=5, verbose_name='Вращающий момент на открытие,Нм'),
        ),
        migrations.DeleteModel(
            name='ValveLineEAVAttribute',
        ),
        migrations.DeleteModel(
            name='ValveLineEAVChoiceValue',
        ),
        migrations.DeleteModel(
            name='ValveLineEAVSection',
        ),
        migrations.DeleteModel(
            name='ValveLineEAVValue',
        ),
        migrations.DeleteModel(
            name='ValveLineSeries',
        ),
        migrations.DeleteModel(
            name='ValveLineSeriesBodyColor',
        ),
        migrations.DeleteModel(
            name='ValveSeriesAttributeValue',
        ),
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='valve_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_sealing_material', to='valve_data.valveline', verbose_name='Серия арматуры'),
        ),
        migrations.AddField(
            model_name='valvelinebodycolor',
            name='valve_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_body_colors', to='valve_data.valveline', verbose_name='Серия арматуры'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='body_colors',
            field=models.ManyToManyField(blank=True, related_name='valve_line_body_color', through='valve_data.ValveLineBodyColor', to='params.bodycolor', verbose_name='Цвета корпуса'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='sealing_element_options',
            field=models.ManyToManyField(blank=True, related_name='valve_series_sealing_element_options', through='valve_data.ValveLineSealingMaterial', to='materials.materialspecified', verbose_name='Варианты материалов уплотнения'),
        ),
        migrations.AlterUniqueTogether(
            name='valvelinesealingmaterial',
            unique_together={('valve_line', 'sealing_element_material', 'option_variety')},
        ),
        migrations.AlterUniqueTogether(
            name='valvelinebodycolor',
            unique_together={('valve_line', 'body_color', 'option_variety')},
        ),
    ]
