# Generated by Django 4.2.23 on 2025-09-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0013_valvelinebodycolor_valvelinesealingmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_cycles',
            field=models.IntegerField(blank=True, default=0, help_text='Расчетное количество циклов', verbose_name='Расчетное количество циклов'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_cycles_comment',
            field=models.CharField(blank=True, default=1, help_text='Условие выработки расчетного количества циклов', max_length=500, verbose_name='Условие выработки расчетного количества циклов'),
            preserve_default=False,
        ),
    ]
