# Generated by Django 4.2.23 on 2025-09-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0015_warrantytimeperiodvariety'),
        ('valve_data', '0014_alter_valveline_valve_in_service_cycles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='valve_function',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры - регулирующая, запорная', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_function', to='params.valvefunctionvariety', verbose_name='Типы арматуры - регулирующая, запорная'),
        ),
    ]
