# Generated by Django 4.2.23 on 2025-09-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0015_warrantytimeperiodvariety'),
        ('valve_data', '0015_alter_valveline_valve_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveline',
            name='valve_in_service_variety',
            field=models.ForeignKey(blank=True, help_text='Расчетный срок эксплуатации, описание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_valve_in_service_variety', to='params.warrantytimeperiodvariety', verbose_name='Расчетный срок эксплуатации, описание'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='warranty_period_max_variety',
            field=models.ForeignKey(blank=True, help_text='Гарантийный срок не более, описание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_warranty_period_max_variety', to='params.warrantytimeperiodvariety', verbose_name='Гарантийный срок не более, описание'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='warranty_period_min_variety',
            field=models.ForeignKey(blank=True, help_text='Гарантийный срок мин описание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_warranty_period_min_variety', to='params.warrantytimeperiodvariety', verbose_name='Гарантийный срок мин описание'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='pipe_connection',
            field=models.ForeignKey(blank=True, help_text='Тип присоединения арматуры к трубе', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_pipe_connection', to='valve_data.valveconnectiontopipe'),
        ),
    ]
