# Generated by Django 4.2.23 on 2025-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0016_valveline_valve_in_service_variety_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valveline',
            name='valve_in_service_variety',
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_in_service_years_comment',
            field=models.CharField(blank=True, help_text='Условие выработки расчетного срока эксплуатации', max_length=500, verbose_name='Условие выработки расчетного срока эксплуатации'),
        ),
    ]
