# Generated by Django 4.2.23 on 2025-09-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0016_valveactuationvariety'),
        ('materials', '0004_materialspecified_application_text_and_more'),
        ('valve_data', '0017_remove_valveline_valve_in_service_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код типа присоединения арматуры к трубе'),
        ),
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение     типа присоединения арматуры к трубе', max_length=100, null=True, verbose_name='Символьное обозначение     типа присоединения арматуры к трубе'),
        ),
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='application_text',
            field=models.TextField(blank=True, verbose_name='Где применяется'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код серии арматуры'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='features_text',
            field=models.TextField(blank=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение (артикул) серии арматуры', max_length=100, null=True, verbose_name='Серия арматуры'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='sealing_element_options',
            field=models.ManyToManyField(blank=True, related_name='valve_line_sealing_element_options', through='valve_data.ValveLineSealingMaterial', to='materials.materialspecified', verbose_name='Варианты материалов уплотнения'),
        ),
        migrations.CreateModel(
            name='ValveLineValveActuationVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная стоимость для этого цвета и типа исполнения', max_digits=10, verbose_name='Дополнительная стоимость')),
                ('lead_time_days', models.IntegerField(default=0, help_text='Дополнительное время изготовления в днях', verbose_name='Срок изготовления (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('option_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_valve_actuation_variety', to='params.optionvariety', verbose_name='Стандарт или опция')),
                ('valve_actuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_valve_actuation', to='params.valveactuationvariety', verbose_name='Материал уплотнения')),
                ('valve_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_valve_actuation', to='valve_data.valveline', verbose_name='Серия арматуры')),
            ],
            options={
                'verbose_name': 'Тип механизма приведения в действие арматуры в серии',
                'verbose_name_plural': 'Типы механизмов приведения в действие арматуры в серии',
                'ordering': ['valve_line', 'option_variety__sorting_order', 'sorting_order'],
                'unique_together': {('valve_line', 'valve_actuation', 'option_variety')},
            },
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_actuation_options',
            field=models.ManyToManyField(blank=True, related_name='valve_line_valve_actuation_options', through='valve_data.ValveLineValveActuationVariety', to='params.valveactuationvariety', verbose_name='Варианты типов механизмов приведения в действие арматуры'),
        ),
    ]
