# Generated by Django 4.2.23 on 2025-09-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0016_valveactuationvariety'),
        ('valve_data', '0018_valveconnectiontopipe_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valveconnectiontopipe',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип присоединения арматуры к трубе', 'verbose_name_plural': 'Типы присоединения арматуры к трубе'},
        ),
        migrations.AlterModelOptions(
            name='valveline',
            options={'ordering': ['valve_variety', 'valve_producer', 'name'], 'verbose_name': 'Семейство серий арматуры', 'verbose_name_plural': 'Семейство серий арматуры'},
        ),
        migrations.RemoveField(
            model_name='valveconnectiontopipe',
            name='symbolic_code',
        ),
        migrations.RemoveField(
            model_name='valveline',
            name='symbolic_code',
        ),
        migrations.AlterField(
            model_name='valveconnectiontopipe',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа присоединения арматуры к трубе', max_length=100, null=True, verbose_name='Символьное обозначение типа присоединения арматуры к трубе'),
        ),
        migrations.AlterField(
            model_name='valvelinevalveactuationvariety',
            name='valve_actuation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_valve_actuation', to='params.valveactuationvariety', verbose_name='Тип механизма приведения в действие арматуры'),
        ),
    ]
