# Generated by Django 4.2.23 on 2025-09-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0019_alter_valveconnectiontopipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Количество портов арматуры', max_length=100, verbose_name='Количество портов арматуры')),
                ('code', models.CharField(help_text='Код количества портов арматуры', max_length=50, unique=True, verbose_name='Код количества портов арматуры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Количество портов арматуры',
                'verbose_name_plural': 'Количество портов арматуры',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AddField(
            model_name='valvelinebodycolor',
            name='option_code_template',
            field=models.CharField(blank=True, help_text='Шаблон кодировки для опции', max_length=100, null=True, verbose_name='Шаблон кодировки для опции'),
        ),
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='option_code_template',
            field=models.CharField(blank=True, help_text='Шаблон кодировки для опции', max_length=100, null=True, verbose_name='Шаблон кодировки для опции'),
        ),
        migrations.AddField(
            model_name='valvelinevalveactuationvariety',
            name='option_code_template',
            field=models.CharField(blank=True, help_text='Шаблон кодировки для опции', max_length=100, null=True, verbose_name='Шаблон кодировки для опции'),
        ),
        migrations.AlterField(
            model_name='valveconnectiontopipe',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код типа присоединения арматуры к трубе'),
        ),
        migrations.AlterField(
            model_name='valveconnectiontopipe',
            name='name',
            field=models.CharField(help_text='Символьное обозначение типа присоединения арматуры к трубе', max_length=100, verbose_name='Символьное обозначение типа присоединения арматуры к трубе'),
        ),
        migrations.CreateModel(
            name='ConstructionVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа конструкции вида арматуры', max_length=100, verbose_name='Название типа конструкции')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа конструкции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('valve_variety', models.ForeignKey(help_text='Тип конструкции вида арматуры', on_delete=django.db.models.deletion.CASCADE, related_name='construction_variety_valve_variety', to='valve_data.valvevariety', verbose_name='Тип конструкции вида арматуры')),
            ],
            options={
                'verbose_name': 'Название типа конструкции вида арматуры',
                'verbose_name_plural': 'Названия типа конструкции вида арматуры',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AddField(
            model_name='valveline',
            name='construction_variety',
            field=models.ForeignKey(blank=True, help_text='Тип конструкции', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_port_qty', to='valve_data.constructionvariety', verbose_name='Тип конструкции'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='port_qty',
            field=models.ForeignKey(blank=True, help_text='Количество портов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_port_qty', to='valve_data.portqty', verbose_name='Количество портов'),
        ),
    ]
