# Generated by Django 4.2.23 on 2025-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0020_portqty_valvelinebodycolor_option_code_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveline',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
