# Generated by Django 4.2.23 on 2025-10-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0016_valveactuationvariety'),
        ('producers', '0001_initial'),
        ('valve_data', '0021_valveline_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorValveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный артикул вендора для этой серии', max_length=50, verbose_name='Артикул серии арматуры вендора')),
                ('name', models.CharField(blank=True, help_text='Название серии арматуры вендора', max_length=100, null=True, verbose_name='Название серии арматуры вендора')),
                ('description', models.TextField(blank=True, help_text='Описание серии арматуры вендора', verbose_name='Описание серии арматуры вендора')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Проверено')),
                ('oem_valve_line', models.ForeignKey(help_text='Оригинальная серия арматуры OEM производителя', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_valve_line_oem_valve_line', to='valve_data.valveline', verbose_name='OEM серия арматуры')),
                ('vendor', models.ForeignKey(help_text='Вендор, который продает эту серию под своим артикулом', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_valve_line_vendor', to='producers.producer', verbose_name='Вендор')),
                ('vendor_brand', models.ForeignKey(blank=True, help_text='Бренд вендора для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_valve_line_vendor_brand', to='producers.brands', verbose_name='Бренд вендора')),
            ],
            options={
                'verbose_name': 'Серия арматуры вендора',
                'verbose_name_plural': 'Серии арматуры вендоров',
                'ordering': ['vendor', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VendorValveLineBodyColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(blank=True, help_text='Артикул/код цвета у вендора', max_length=50, verbose_name='Код цвета корпуса')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительная стоимость')),
                ('lead_time_days', models.IntegerField(default=0, verbose_name='Срок изготовления (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('body_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.bodycolor', verbose_name='Цвет корпуса ')),
                ('option_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.optionvariety', verbose_name='Стандарт или опция')),
                ('valve_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_body_colors', to='valve_data.vendorvalveline')),
            ],
            options={
                'verbose_name': 'Цвет корпуса серии вендора',
                'verbose_name_plural': 'Цвета корпусов серии вендора',
                'ordering': ['valve_line', 'sorting_order'],
                'unique_together': {('valve_line', 'body_color', 'option_variety')},
            },
        ),
        migrations.CreateModel(
            name='VendorValveLineValveActuationVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code_template', models.CharField(blank=True, help_text='АШаблон кодировки для опции', max_length=50, verbose_name='Шаблон кодировки для опции')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительная стоимость')),
                ('lead_time_days', models.IntegerField(default=0, verbose_name='Срок изготовления (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('option_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.optionvariety', verbose_name='Стандарт или опция')),
                ('valve_actuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.valveactuationvariety', verbose_name='Тип механизма приведения в действие арматуры вендора')),
                ('valve_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_actuation_options', to='valve_data.vendorvalveline')),
            ],
            options={
                'verbose_name': 'Тип механизма приведения в действие арматуры в серии вендора',
                'verbose_name_plural': 'Типы механизмов приведения в действие арматуры в серии вендора',
                'ordering': ['valve_line', 'option_variety__sorting_order', 'sorting_order'],
                'unique_together': {('valve_line', 'valve_actuation', 'option_variety')},
            },
        ),
        migrations.DeleteModel(
            name='ValveSeriesDnPnTorqueMountData',
        ),
        migrations.AddField(
            model_name='vendorvalveline',
            name='vendor_specific_actuation_options',
            field=models.ManyToManyField(blank=True, help_text='Типы приводов, доступные у вендора (могут быть дополнительные варианты)', related_name='vendor_valve_line_actuation_options', through='valve_data.VendorValveLineValveActuationVariety', to='params.valveactuationvariety', verbose_name='Типы приводов серии арматуры вендора'),
        ),
        migrations.AddField(
            model_name='vendorvalveline',
            name='vendor_specific_body_colors',
            field=models.ManyToManyField(blank=True, help_text='Цвета корпуса серии арматуры вендора (могут отличаться от OEM)', related_name='vendor_valve_line_body_colors', through='valve_data.VendorValveLineBodyColor', to='params.bodycolor', verbose_name='Цвета корпуса серии арматуры вендора'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorvalveline',
            unique_together={('vendor', 'oem_valve_line', 'code')},
        ),
    ]
