# Generated by Django 5.2.4 on 2025-10-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialspecified_application_text_and_more'),
        ('params', '0016_valveactuationvariety'),
        ('valve_data', '0022_testmodel_vendorvalveline_vendorvalvelinebodycolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvemodeldata',
            name='valve_dn',
        ),
        migrations.RemoveField(
            model_name='valvemodeldata',
            name='valve_model_thrust_to_close',
        ),
        migrations.RemoveField(
            model_name='valvemodeldata',
            name='valve_pn',
        ),
        migrations.AlterField(
            model_name='valveline',
            name='body_colors',
            field=models.ManyToManyField(blank=True, related_name='valve_line_body_color', through='valve_data.ValveLineBodyColor', through_fields=('valve_line', 'body_color'), to='params.bodycolor', verbose_name='Цвета корпуса'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='sealing_element_options',
            field=models.ManyToManyField(blank=True, related_name='valve_line_sealing_element_options', through='valve_data.ValveLineSealingMaterial', through_fields=('valve_line', 'sealing_element_material'), to='materials.materialspecified', verbose_name='Варианты материалов уплотнения'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_actuation_options',
            field=models.ManyToManyField(blank=True, related_name='valve_line_valve_actuation_options', through='valve_data.ValveLineValveActuationVariety', through_fields=('valve_line', 'valve_actuation'), to='params.valveactuationvariety', verbose_name='Варианты типов механизмов приведения в действие арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_dn',
            field=models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn',
            field=models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_delta',
            field=models.PositiveIntegerField(blank=True, help_text='Перепад Dn арматуры', null=True),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_measure_unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_measure_unit', to='params.measureunits'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_close',
            field=models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_open',
            field=models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5),
        ),
    ]
