# Generated by Django 5.2.4 on 2025-10-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0016_valveactuationvariety'),
        ('valve_data', '0023_remove_valvemodeldata_valve_dn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveSeriesDnPnTorqueMountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_model_torque_to_open', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_torque_to_close', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_rotations_to_open', models.DecimalField(decimal_places=1, help_text='Число оборотов на открытие', max_digits=5)),
                ('valve_model_model_series', models.ForeignKey(blank=True, help_text='Серия арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='valve_data.valveline', verbose_name='Серия арматуры')),
                ('valve_model_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='valve_series_dn_pn_torque_mount_data', to='params.mountingplatetypes')),
                ('valve_model_stem_size', models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='params.stemsize')),
                ('valve_series_dn', models.ForeignKey(blank=True, help_text='Dn арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='params.dnvariety', verbose_name='Dn арматуры')),
                ('valve_series_max_pn_option', models.ForeignKey(blank=True, help_text='Pn арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_series_dn_pn_torque_mount_data', to='params.pnvariety', verbose_name='Pn арматуры')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
