# Generated by Django 5.2.4 on 2025-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0016_valveactuationvariety'),
        ('valve_data', '0024_valveseriesdnpntorquemountdata_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorvalveline',
            name='code',
            field=models.CharField(help_text='Уникальный артикул вендора для этой серии', max_length=50, verbose_name='Код серии вендора'),
        ),
        migrations.AlterField(
            model_name='vendorvalveline',
            name='description',
            field=models.TextField(blank=True, help_text='Описание серии арматуры вендора', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vendorvalveline',
            name='name',
            field=models.CharField(blank=True, help_text='Название серии арматуры вендора', max_length=100, null=True, verbose_name='Серия вендора'),
        ),
        migrations.AlterField(
            model_name='vendorvalveline',
            name='vendor_specific_body_colors',
            field=models.ManyToManyField(blank=True, help_text='Цвета корпуса серии арматуры вендора (могут отличаться от OEM)', related_name='vendor_valve_line_body_colors', through='valve_data.VendorValveLineBodyColor', to='params.bodycolor', verbose_name='Цвета серии вендора'),
        ),
    ]
