# Generated by Django 4.2.23 on 2025-10-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0017_alter_actuatorgearboxcombinationtypes_options_and_more'),
        ('valve_data', '0025_alter_vendorvalveline_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_dn',
            field=models.ForeignKey(blank=True, help_text='Dn арматуры, бар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_valve_dn_variety', to='params.dnvariety', verbose_name='Dn арматуры, бар'),
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_model_thrust_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Усилие на закрытие, Н', max_digits=8, verbose_name='Усилие на закрытие, Н'),
        ),
        migrations.AddField(
            model_name='valvemodeldata',
            name='valve_pn',
            field=models.ForeignKey(blank=True, help_text='Pn арматуры, мм', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_valve_pn_variety', to='params.pnvariety', verbose_name='Pn арматуры, мм'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_dn',
            field=models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True, verbose_name='Dn арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn',
            field=models.PositiveIntegerField(blank=True, help_text='Pn арматуры', null=True, verbose_name='Pn арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_delta',
            field=models.PositiveIntegerField(blank=True, help_text='Перепад Dn арматуры', null=True, verbose_name='Перепад Dn арматуры'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_pn_measure_unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_measure_unit', to='params.measureunits', verbose_name='Единица измерения Pn'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Вращающий момент на закрытие,Нм', max_digits=5, verbose_name='Вращающий момент на закрытие,Нм'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_open',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Вращающий момент на открытие,Нм', max_digits=5, verbose_name='Вращающий момент на открытие,Нм'),
        ),
    ]
