# Generated by Django 4.2.23 on 2025-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0026_valvemodeldata_valve_dn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_rotations_to_open',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Число оборотов на открытие', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_thrust_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Усилие на закрытие, Н', max_digits=8, null=True, verbose_name='Усилие на закрытие, Н'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Вращающий момент на закрытие,Нм', max_digits=5, null=True, verbose_name='Вращающий момент на закрытие,Нм'),
        ),
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_torque_to_open',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Вращающий момент на открытие,Нм', max_digits=5, null=True, verbose_name='Вращающий момент на открытие,Нм'),
        ),
    ]
