# Generated by Django 4.2.23 on 2025-10-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0017_alter_actuatorgearboxcombinationtypes_options_and_more'),
        ('valve_data', '0027_alter_valvemodeldata_valve_model_rotations_to_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvemodeldata',
            name='valve_model_model_line',
            field=models.ForeignKey(blank=True, help_text='Серия арматуры производителя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_model_model_line', to='valve_data.valveline'),
        ),
        migrations.AlterField(
            model_name='valveseriesdnpntorquemountdata',
            name='valve_model_torque_to_close',
            field=models.DecimalField(decimal_places=0, help_text='Усилие на закрытие', max_digits=5),
        ),
        migrations.CreateModel(
            name='ValveLineModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_model_torque_to_open', models.DecimalField(decimal_places=0, help_text='Момент на открытие, Н', max_digits=5, verbose_name='Момент откр')),
                ('valve_model_torque_to_close', models.DecimalField(decimal_places=0, help_text='Момент на открытие, Н', max_digits=5, verbose_name='Момент закр')),
                ('valve_model_thrust_to_close', models.DecimalField(decimal_places=0, default=0, help_text='Усилие на закрытие, Н', max_digits=8, null=True, verbose_name='Усилие закр')),
                ('valve_model_rotations_to_open', models.DecimalField(decimal_places=1, help_text='Число оборотов на открытие', max_digits=5, verbose_name='Обороты')),
                ('valve_model_stem_height', models.DecimalField(decimal_places=1, help_text='Высота штока, мм', max_digits=6, verbose_name='Высота штока')),
                ('valve_model_construction_length', models.DecimalField(decimal_places=1, help_text='Строительная длина, мм', max_digits=6, verbose_name='Строит.длина')),
                ('valve_model_dn', models.ForeignKey(blank=True, help_text='Dn арматуры, мм', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_model_dn_data', to='params.dnvariety', verbose_name='Dn')),
                ('valve_model_line', models.ForeignKey(blank=True, help_text='Серия арматуры', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_line_model_model_line', to='valve_data.valveline', verbose_name='Серия')),
                ('valve_model_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='valve_line_model_mount_data', to='params.mountingplatetypes', verbose_name='Монт.площадка')),
                ('valve_model_pn', models.ForeignKey(blank=True, help_text='Pn арматуры, бар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_model_pn_data', to='params.pnvariety', verbose_name='Pn')),
                ('valve_model_stem_size', models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_model_stem_size', to='params.stemsize', verbose_name='Шток')),
            ],
            options={
                'verbose_name': 'Данные модели арматуры',
                'verbose_name_plural': 'Данные моделей арматуры',
                'ordering': ['valve_model_line', 'valve_model_pn', 'valve_model_dn'],
            },
        ),
    ]
