# Generated by Django 4.2.23 on 2025-10-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0028_alter_valvemodeldata_valve_model_model_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvelinemodeldata',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение (артикул)         модели арматуры производителя', max_length=50, null=True, verbose_name='Артикул'),
        ),
    ]
