# Generated by Django 4.2.23 on 2025-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0029_valvelinemodeldata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvelinemodeldata',
            name='valve_model_construction_length',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Строительная длина, мм', max_digits=6, null=True, verbose_name='Строит.длина'),
        ),
        migrations.AlterField(
            model_name='valvelinemodeldata',
            name='valve_model_rotations_to_open',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Число оборотов на открытие', max_digits=5, null=True, verbose_name='Обороты'),
        ),
        migrations.AlterField(
            model_name='valvelinemodeldata',
            name='valve_model_stem_height',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Высота штока, мм', max_digits=6, null=True, verbose_name='Высота штока'),
        ),
        migrations.AlterField(
            model_name='valvelinemodeldata',
            name='valve_model_torque_to_close',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Момент на открытие, Н', max_digits=5, null=True, verbose_name='Момент закр'),
        ),
        migrations.AlterField(
            model_name='valvelinemodeldata',
            name='valve_model_torque_to_open',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Момент на открытие, Н', max_digits=5, null=True, verbose_name='Момент откр'),
        ),
    ]
