# Generated by Django 5.2.7 on 2025-10-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0006_remove_valveselection_client_request_line_item_parent_and_more'),
        ('valve_data', '0030_alter_valvelinemodeldata_valve_model_construction_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valveseriesdnpntorquemountdata',
            name='valve_model_model_series',
        ),
        migrations.RemoveField(
            model_name='valveseriesdnpntorquemountdata',
            name='valve_model_mounting_plate',
        ),
        migrations.RemoveField(
            model_name='valveseriesdnpntorquemountdata',
            name='valve_model_stem_size',
        ),
        migrations.RemoveField(
            model_name='valveseriesdnpntorquemountdata',
            name='valve_series_dn',
        ),
        migrations.RemoveField(
            model_name='valveseriesdnpntorquemountdata',
            name='valve_series_max_pn_option',
        ),
        migrations.DeleteModel(
            name='ValveModelData',
        ),
        migrations.DeleteModel(
            name='ValveSeriesDnPnTorqueMountData',
        ),
    ]
