# Generated by Django 5.2.7 on 2025-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0031_remove_valveseriesdnpntorquemountdata_valve_model_model_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_cycles',
            field=models.IntegerField(blank=True, default=0, help_text='Расчетное количество циклов', null=True, verbose_name='Расчетное количество циклов'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_cycles_comment',
            field=models.CharField(blank=True, help_text='Условие выработки расчетного количества циклов', max_length=500, null=True, verbose_name='Условие выработки расчетного количества циклов'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_years',
            field=models.IntegerField(blank=True, default=0, help_text='Расчетный срок эксплуатации - не менее, лет', null=True, verbose_name='Расчетный срок эксплуатации - не менее, лет'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_years_comment',
            field=models.CharField(blank=True, help_text='Условие выработки расчетного срока эксплуатации', max_length=500, null=True, verbose_name='Условие выработки расчетного срока эксплуатации'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='warranty_period_max',
            field=models.IntegerField(blank=True, default=0, help_text='Гарантийный срок не более, мес', null=True, verbose_name='Гарантийный срок не более, мес'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='warranty_period_min',
            field=models.IntegerField(blank=True, default=0, help_text='Гарантийный срок, мес', null=True, verbose_name='Гарантийный срок мин, мес'),
        ),
    ]
