# Generated by Django 5.2.7 on 2025-10-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
        ('valve_data', '0032_alter_valveline_valve_in_service_cycles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='valve_brand',
            field=models.ForeignKey(blank=True, help_text='Бренд семейства серий  арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_brand', to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_function',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры - регулирующая, запорная', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_function', to='params.valvefunctionvariety', verbose_name='Регулирующая/запорная'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_producer',
            field=models.ForeignKey(blank=True, help_text='Производитель семейства серий арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_producer', to='producers.producer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_sealing_class',
            field=models.ForeignKey(blank=True, help_text='Класс герметичности арматуры ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_sealing_class', to='params.sealingclass', verbose_name='Класс герметичности'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_variety',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры семейства арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_variety', to='valve_data.valvevariety', verbose_name='Тип арматуры'),
        ),
    ]
