# Generated by Django 5.2.7 on 2025-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0033_alter_valveline_valve_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='temp_max',
            field=models.IntegerField(default=0, verbose_name='Т макс, °С'),
        ),
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='temp_min',
            field=models.IntegerField(default=-10, verbose_name='Т мин, °С'),
        ),
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='work_temp_max',
            field=models.IntegerField(default=0, help_text='Максимальная рабочая температура уточненного типа материала, °С', verbose_name='Т раб макс, °С'),
        ),
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='work_temp_min',
            field=models.IntegerField(default=-10, help_text='Минимальная рабочая температура, °С', verbose_name='Т раб мин, °С'),
        ),
    ]
