# Generated by Django 5.2.7 on 2025-10-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0034_valvelinesealingmaterial_temp_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='dn',
            field=models.ManyToManyField(blank=True, help_text='Dn арматуры, мм', null=True, related_name='valve_line_sealing_material_model_dn_data', to='params.dnvariety', verbose_name='Dn'),
        ),
    ]
