# Generated by Django 4.2.23 on 2025-10-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
        ('valve_data', '0035_valvelinesealingmaterial_dn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='construction_variety',
            field=models.ForeignKey(blank=True, help_text='Тип конструкции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_port_qty', to='valve_data.constructionvariety', verbose_name='Тип конструкции'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='pipe_connection',
            field=models.ForeignKey(blank=True, help_text='Тип присоединения арматуры к трубе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_pipe_connection', to='valve_data.valveconnectiontopipe'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='port_qty',
            field=models.ForeignKey(blank=True, help_text='Количество портов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_port_qty', to='valve_data.portqty', verbose_name='Количество портов'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='warranty_period_max_variety',
            field=models.ForeignKey(blank=True, help_text='Гарантийный срок не более, описание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_warranty_period_max_variety', to='params.warrantytimeperiodvariety', verbose_name='Гарантийный срок не более, описание'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='warranty_period_min_variety',
            field=models.ForeignKey(blank=True, help_text='Гарантийный срок мин описание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_warranty_period_min_variety', to='params.warrantytimeperiodvariety', verbose_name='Гарантийный срок мин описание'),
        ),
        migrations.AlterField(
            model_name='valvelinemodeldata',
            name='valve_model_line',
            field=models.ForeignKey(blank=True, help_text='Серия арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_model_model_line', to='valve_data.valveline', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='valvelinesealingmaterial',
            name='dn',
            field=models.ManyToManyField(blank=True, help_text='Dn арматуры, мм', related_name='valve_line_sealing_material_model_dn_data', to='params.dnvariety', verbose_name='Dn'),
        ),
        migrations.CreateModel(
            name='ValveModelKvDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона Kvs для выбора в списке', max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Код шаблона Kvs', max_length=50, unique=True, verbose_name='Код шаблона')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('valve_brand', models.ForeignKey(blank=True, help_text='Бренд серии арматуры для шаблона Kvs для серии. Здесь используем для поиска', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_data_kvs_valve_brand', to='producers.brands', verbose_name='Бренд')),
                ('valve_variety', models.ForeignKey(blank=True, help_text='Тип арматуры для шаблона Kvs для серии, здесь используем для поиска', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_data_kvs_valve_variety', to='valve_data.valvevariety', verbose_name='Тип арматуры')),
            ],
            options={
                'verbose_name': 'Шаблон данных серий арматуры',
                'verbose_name_plural': 'Шаблоны данных серии  арматуры',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ValveModelDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона для выбора в списке', max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Код шаблона', max_length=50, unique=True, verbose_name='Код шаблона')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('valve_brand', models.ForeignKey(blank=True, help_text='Бренд серии арматуры для шаблона тех.данных для серии. Здесь используем для поиска', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_model_data_table_valve_brand', to='producers.brands', verbose_name='Бренд')),
                ('valve_variety', models.ForeignKey(blank=True, help_text='Тип арматуры для шаблона тех.данных для серии, здесь используем для поиска', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_model_data_table_valve_variety', to='valve_data.valvevariety', verbose_name='Тип арматуры')),
            ],
            options={
                'verbose_name': 'Шаблон данных серий арматуры',
                'verbose_name_plural': 'Шаблоны данных серии  арматуры',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AddField(
            model_name='valvelinemodeldata',
            name='valve_model_data_table',
            field=models.ForeignKey(blank=True, help_text='Шаблон моделей арматуры', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_data', to='valve_data.valvemodeldatatable', verbose_name='Шаблон моделей'),
        ),
    ]
