# Generated by Django 4.2.23 on 2025-10-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0036_alter_valveline_construction_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveline',
            name='valve_model_data_table',
            field=models.ForeignKey(blank=True, help_text='Шаблон таблицы данных моделей арматуры для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_model_data_table', to='valve_data.valvemodeldatatable', verbose_name='Шаблон таблицы данных'),
        ),
    ]
