# Generated by Django 4.2.23 on 2025-10-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0037_valveline_valve_model_data_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valvelinemodeldata',
            options={'ordering': ['valve_model_data_table', 'valve_model_pn', 'valve_model_dn'], 'verbose_name': 'Данные модели арматуры', 'verbose_name_plural': 'Данные моделей арматуры'},
        ),
        migrations.RemoveField(
            model_name='valvelinemodeldata',
            name='valve_model_line',
        ),
        migrations.CreateModel(
            name='ValveLineModelKvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_model_kv', models.DecimalField(decimal_places=1, default=0, help_text='Kv,м3/час, при открытии на угол градусов', max_digits=5, null=True, verbose_name='Kv,м3/час')),
                ('valve_model_dn', models.ForeignKey(blank=True, help_text='Dn арматуры, мм', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_model_kv_data_table_dn_data', to='params.dnvariety', verbose_name='Dn')),
                ('valve_model_kv_data_table', models.ForeignKey(help_text='Шаблон моделей арматуры', on_delete=django.db.models.deletion.CASCADE, related_name='valve_model_kv_data_table', to='valve_data.valvemodelkvdatatable', verbose_name='Шаблон моделей')),
                ('valve_model_pn', models.ForeignKey(blank=True, help_text='Pn арматуры, бар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_model_kv_data_table_pn_data', to='params.pnvariety', verbose_name='Pn')),
            ],
        ),
    ]
