# Generated by Django 5.2.7 on 2025-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0038_alter_valvelinemodeldata_options_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='vendorvalvelinevalveactuationvariety',
        #     name='valve_line',
        # ),
        # migrations.RemoveField(
        #     model_name='vendorvalvelinebodycolor',
        #     name='valve_line',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='vendorvalvelinebodycolor',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='vendorvalvelinebodycolor',
        #     name='body_color',
        # ),
        # migrations.RemoveField(
        #     model_name='vendorvalvelinebodycolor',
        #     name='option_variety',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='vendorvalvelinevalveactuationvariety',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='vendorvalvelinevalveactuationvariety',
        #     name='option_variety',
        # ),
        # migrations.RemoveField(
        #     model_name='vendorvalvelinevalveactuationvariety',
        #     name='valve_actuation',
        # ),
        migrations.CreateModel(
            name='AllowedDnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Символьное обозначение шаблона допустимых Dn', max_length=150, null=True, verbose_name='Список Dn')),
                ('code', models.CharField(blank=True, help_text='Код шаблона допустимых Dn', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('dn', models.ManyToManyField(blank=True, help_text='Dn арматуры, мм', related_name='allowed_dn_template_table', to='params.dnvariety', verbose_name='Dn')),
            ],
            options={
                'verbose_name': 'Шаблон допустимых Dn',
                'verbose_name_plural': 'Шаблоны допустимых Dn',
                'ordering': ['is_active', 'sorting_order'],
            },
        ),
        migrations.DeleteModel(
            name='VendorValveLine',
        ),
        migrations.DeleteModel(
            name='VendorValveLineBodyColor',
        ),
        migrations.DeleteModel(
            name='VendorValveLineValveActuationVariety',
        ),
    ]
