# Generated by Django 5.2.7 on 2025-10-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0039_remove_vendorvalvelinevalveactuationvariety_valve_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvelinesealingmaterial',
            name='dn',
        ),
        migrations.AddField(
            model_name='valvelinesealingmaterial',
            name='allowed_dn_table',
            field=models.ForeignKey(blank=True, help_text='Допустимые Dn для этого уплотнения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_sealing_material_allowed_dn_table', to='valve_data.alloweddntemplate', verbose_name='Dn'),
        ),
        migrations.AddField(
            model_name='valvelinevalveactuationvariety',
            name='allowed_dn_table',
            field=models.ForeignKey(blank=True, help_text='Допустимые Dn для этого механизма управления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_actuation_allowed_dn_table', to='valve_data.alloweddntemplate', verbose_name='Dn'),
        ),
        migrations.AlterField(
            model_name='alloweddntemplate',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение шаблона допустимых Dn', max_length=150, null=True, verbose_name='Название'),
        ),
    ]
