# Generated by Django 4.2.23 on 2025-10-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0040_remove_valvelinesealingmaterial_dn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valvelinemodelkvdata',
            options={'ordering': ['valve_model_kv_data_table', 'valve_model_pn', 'valve_model_dn'], 'verbose_name': 'Данные Kv серии арматуры', 'verbose_name_plural': 'Данные Kv серии арматуры'},
        ),
        migrations.AlterModelOptions(
            name='valvemodelkvdatatable',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Шаблон данных Kv для серии арматуры', 'verbose_name_plural': 'Шаблоны данных Kv для серий арматуры'},
        ),
        migrations.AddField(
            model_name='valveline',
            name='original_valve_line',
            field=models.ForeignKey(blank=True, help_text='Серия арматуры, от которой наследуются данные', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_valve_lines', to='valve_data.valveline', verbose_name='Исходная серия арматуры'),
        ),
    ]
