# Generated by Django 5.2.7 on 2025-10-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
        ('valve_data', '0041_alter_valvelinemodelkvdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='body_material_specified',
            field=models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_body_material', to='materials.materialspecified', verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='pipe_connection',
            field=models.ForeignKey(blank=True, help_text='Тип присоединения арматуры к трубе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_pipe_connection', to='valve_data.valveconnectiontopipe', verbose_name='Присоединение к трубе'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_brand',
            field=models.ForeignKey(blank=True, help_text='Бренд семейства серий арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_brand', to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_sealing_class',
            field=models.ForeignKey(blank=True, help_text='Класс герметичности арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_sealing_class', to='params.sealingclass', verbose_name='Класс герметичности'),
        ),
    ]
