# Generated by Django 5.2.7 on 2025-10-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('valve_data', '0042_alter_valveline_body_material_specified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='body_material_specified',
            field=models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_body_material_specified', to='materials.materialspecified', verbose_name='Материал корпуса'),
        ),
    ]
