# Generated by Django 4.2.23 on 2025-10-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('valve_data', '0043_alter_valveline_body_material_specified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='body_material_specified',
            field=models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_body_material', to='materials.materialspecified', verbose_name='Материал корпуса'),
        ),
    ]
