# Generated by Django 4.2.23 on 2025-10-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0044_alter_valveline_body_material_specified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valveline',
            options={'ordering': ['valve_variety', 'valve_producer', 'name'], 'verbose_name': 'Серия арматуры', 'verbose_name_plural': 'Серии арматуры'},
        ),
    ]
