# Generated by Django 4.2.23 on 2025-10-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('valve_data', '0045_alter_valveline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveline',
            name='allowed_dn_table',
            field=models.ForeignKey(blank=True, help_text='Допустимые Dn для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_allowed_dn_table', to='valve_data.alloweddntemplate', verbose_name='Dn'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='item_code_template',
            field=models.CharField(blank=True, help_text='Шаблон кодировки для артикула', max_length=100, null=True, verbose_name='Шаблон для артикула'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='option_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_option_variety', to='params.optionvariety', verbose_name='Стандарт или опция'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='sealing_element_material',
            field=models.ForeignKey(blank=True, help_text='Тип материала уплотнения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_sealing_material_general', to='materials.materialgeneral', verbose_name='Тип материала уплотнения'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='sealing_element_material_specified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_sealing_material_specified', to='materials.materialspecified', verbose_name='Материал уплотнения'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='temp_max',
            field=models.IntegerField(default=0, verbose_name='Т макс, °С'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='temp_min',
            field=models.IntegerField(default=-10, verbose_name='Т мин, °С'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_actuation',
            field=models.ForeignKey(blank=True, help_text='Управление', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_actuation_variety', to='params.valveactuationvariety', verbose_name='Тип механизма приведения в действие арматуры'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='work_temp_max',
            field=models.IntegerField(default=0, help_text='Максимальная рабочая температура уточненного типа материала, °С', verbose_name='Т раб макс, °С'),
        ),
        migrations.AddField(
            model_name='valveline',
            name='work_temp_min',
            field=models.IntegerField(default=-10, help_text='Минимальная рабочая температура, °С', verbose_name='Т раб мин, °С'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='shut_element_material_specified',
            field=models.ForeignKey(blank=True, help_text='Марка материала запорного элемента (диска, шара, ножа, клина)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_shut_element_material_specified', to='materials.materialspecified', verbose_name='Материал запорного элемента'),
        ),
    ]
