# Generated by Django 5.2.7 on 2025-10-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0046_valveline_allowed_dn_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valveline',
            name='sealing_element_options',
        ),
        migrations.AlterUniqueTogether(
            name='valvelinevalveactuationvariety',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='valvelinevalveactuationvariety',
            name='allowed_dn_table',
        ),
        migrations.RemoveField(
            model_name='valvelinevalveactuationvariety',
            name='option_variety',
        ),
        migrations.RemoveField(
            model_name='valvelinevalveactuationvariety',
            name='valve_actuation',
        ),
        migrations.RemoveField(
            model_name='valvelinevalveactuationvariety',
            name='valve_line',
        ),
        migrations.RemoveField(
            model_name='valveline',
            name='valve_actuation_options',
        ),
        migrations.DeleteModel(
            name='ValveLineSealingMaterial',
        ),
        migrations.DeleteModel(
            name='ValveLineValveActuationVariety',
        ),
    ]
