# Generated by Django 5.2.7 on 2025-10-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0047_remove_valveline_sealing_element_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='code',
            field=models.CharField(blank=True, help_text='Код серии арматуры', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение (артикул) серии арматуры', max_length=100, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='temp_max',
            field=models.IntegerField(blank=True, help_text='Максимальная температура, °С', null=True, verbose_name='Т макс, °С'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='temp_min',
            field=models.IntegerField(blank=True, help_text='Минимальная температура, °С', null=True, verbose_name='Т мин, °С'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_variety',
            field=models.ForeignKey(blank=True, help_text='Тип арматуры семейства арматуры производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_variety', to='valve_data.valvevariety', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='work_temp_max',
            field=models.IntegerField(blank=True, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб макс, °С'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='work_temp_min',
            field=models.IntegerField(blank=True, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб мин, °С'),
        ),
    ]
