# Generated by Django 5.2.7 on 2025-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0048_alter_valveline_code_alter_valveline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_cycles',
            field=models.IntegerField(blank=True, help_text='Расчетное количество циклов', null=True, verbose_name='Расчетное количество циклов'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_in_service_years',
            field=models.IntegerField(blank=True, help_text='Расчетный срок эксплуатации - не менее, лет', null=True, verbose_name='Расчетный срок эксплуатации - не менее, лет'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='warranty_period_max',
            field=models.IntegerField(blank=True, help_text='Гарантийный срок не более, мес', null=True, verbose_name='Гарантийный срок не более, мес'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='warranty_period_min',
            field=models.IntegerField(blank=True, help_text='Гарантийный срок, мес', null=True, verbose_name='Гарантийный срок мин, мес'),
        ),
    ]
