# Generated by Django 4.2.23 on 2025-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0049_alter_valveline_valve_in_service_cycles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvelinemodelkvdata',
            name='valve_model_openinig_angle',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Угол открытия арматуры, градусов С', max_digits=5, null=True, verbose_name='Угол'),
        ),
    ]
