# Generated by Django 4.2.23 on 2025-10-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0050_valvelinemodelkvdata_valve_model_openinig_angle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvelinemodelkvdata',
            name='valve_model_kv',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Kv,м3/час, при открытии на угол градусов', max_digits=8, null=True, verbose_name='Kv,м3/час'),
        ),
        migrations.AlterField(
            model_name='valvelinemodelkvdata',
            name='valve_model_openinig_angle',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Угол открытия арматуры, градусов °', max_digits=5, null=True, verbose_name='Угол'),
        ),
    ]
