# Generated by Django 4.2.23 on 2025-10-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0051_alter_valvelinemodelkvdata_valve_model_kv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveline',
            name='valve_model_kv_data_table',
            field=models.ForeignKey(blank=True, help_text='Шаблон таблицы данных Kvs моделей арматуры для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_model_kv_data_table', to='valve_data.valvemodelkvdatatable', verbose_name='Шаблон таблицы данных Kvs'),
        ),
    ]
