# Generated by Django 5.2.7 on 2025-11-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0052_valveline_valve_model_kv_data_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valveline',
            name='allowed_dn_table',
            field=models.ForeignKey(blank=True, help_text='Допустимые Dn для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_allowed_dn_table', to='valve_data.alloweddntemplate', verbose_name='Допустимые Dn'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='construction_variety',
            field=models.ForeignKey(blank=True, help_text='Тип конструкции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_port_qty', to='valve_data.constructionvariety', verbose_name='Конструкция'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='original_valve_line',
            field=models.ForeignKey(blank=True, help_text='Серия арматуры, от которой наследуются данные', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_valve_lines', to='valve_data.valveline', verbose_name='Исходная серия'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='port_qty',
            field=models.ForeignKey(blank=True, help_text='Количество портов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_port_qty', to='valve_data.portqty', verbose_name='Портов'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_actuation',
            field=models.ForeignKey(blank=True, help_text='Тип механизма приведения в действие арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_line_valve_actuation_variety', to='params.valveactuationvariety', verbose_name='Управление'),
        ),
    ]
