# Generated by Django 5.2.7 on 2025-11-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
        ('valve_data', '0053_alter_valveline_allowed_dn_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveModelDimensionDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона ВГХ', max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Код шаблона ВГХ', max_length=50, unique=True, verbose_name='Код шаблона')),
                ('valve_brand', models.ForeignKey(blank=True, help_text='Бренд серии арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_dimension_tables_valve_brand', to='producers.brands', verbose_name='Бренд')),
                ('valve_variety', models.ForeignKey(blank=True, help_text='Тип арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_dimension_tables_valve_variety', to='valve_data.valvevariety', verbose_name='Тип арматуры')),
            ],
            options={
                'verbose_name': 'Таблица ВГХ',
                'verbose_name_plural': 'Таблицы ВГХ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimensionTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.IntegerField(default=0, verbose_name='Порядок столбца')),
                ('dn', models.ForeignKey(help_text='Значение DN для столбца', on_delete=django.db.models.deletion.CASCADE, related_name='dimension_table_columns', to='params.dnvariety', verbose_name='DN')),
                ('dimension_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='valve_data.valvemodeldimensiondatatable', verbose_name='Таблица ВГХ')),
            ],
            options={
                'verbose_name': 'Столбец таблицы ВГХ',
                'verbose_name_plural': 'Столбцы таблицы ВГХ',
                'ordering': ['dimension_table', 'column_order'],
                'unique_together': {('dimension_table', 'dn')},
            },
        ),
        migrations.AddField(
            model_name='valveline',
            name='valve_model_dimension_data_table',
            field=models.ForeignKey(blank=True, help_text='Таблица весо-габаритных характеристик для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_lines', to='valve_data.valvemodeldimensiondatatable', verbose_name='Таблица ВГХ'),
        ),
        migrations.CreateModel(
            name='WeightDimensionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название параметра ВГХ', max_length=100, verbose_name='Название параметра')),
                ('code', models.CharField(help_text='Уникальный код параметра', max_length=50, unique=True, verbose_name='Код параметра')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('valve_variety', models.ForeignKey(blank=True, help_text='Тип арматуры для отбора значений в выпадающий список', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_dimension_parameters', to='valve_data.valvevariety', verbose_name='Тип арматуры')),
            ],
            options={
                'verbose_name': 'Параметр ВГХ',
                'verbose_name_plural': 'Параметры ВГХ',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DimensionTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(help_text='Название параметра как на чертеже', max_length=100, verbose_name='Название параметра')),
                ('row_order', models.IntegerField(default=0, verbose_name='Порядок строки')),
                ('dimension_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='valve_data.valvemodeldimensiondatatable', verbose_name='Таблица ВГХ')),
                ('system_parameter', models.ForeignKey(blank=True, help_text='Сопоставленный системный параметр (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_rows', to='valve_data.weightdimensionparameter', verbose_name='Системный параметр')),
            ],
            options={
                'verbose_name': 'Строка таблицы ВГХ',
                'verbose_name_plural': 'Строки таблицы ВГХ',
                'ordering': ['dimension_table', 'row_order'],
            },
        ),
        migrations.CreateModel(
            name='DimensionTableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Числовое значение характеристики', max_digits=10, null=True, verbose_name='Значение')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='valve_data.dimensiontablecolumn', verbose_name='Столбец')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='valve_data.dimensiontablerow', verbose_name='Строка')),
            ],
            options={
                'verbose_name': 'Ячейка таблицы ВГХ',
                'verbose_name_plural': 'Ячейки таблицы ВГХ',
                'unique_together': {('row', 'column')},
            },
        ),
    ]
