# Generated by Django 4.2.23 on 2025-11-01 17:38

from django.db import migrations, models
import django.db.models.deletion
import storage_manager.fields
import storage_manager.storage_backends.local


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0054_valvemodeldimensiondatatable_dimensiontablecolumn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionTableDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название чертежа (например, 'Общий вид', 'Габаритные размеры')", max_length=200, verbose_name='Название чертежа')),
                ('description', models.TextField(blank=True, help_text='Подробное описание чертежа и что на нем изображено', null=True, verbose_name='Описание чертежа')),
                ('drawing_file', storage_manager.fields.ManagedFileField(help_text='Загрузите файл чертежа (PDF, JPG, PNG, DWF)', storage=storage_manager.storage_backends.local.LocalStorage(), upload_to='', verbose_name='Файл чертежа')),
                ('file_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('PNG', 'PNG'), ('DWF', 'DWF'), ('DWG', 'DWG')], max_length=10, verbose_name='Тип файла')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Чертеж таблицы ВГХ',
                'verbose_name_plural': 'Чертежи таблиц ВГХ',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DrawingDnRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.ForeignKey(help_text='DN, для которого применим этот чертеж', on_delete=django.db.models.deletion.CASCADE, related_name='drawing_relations', to='params.dnvariety', verbose_name='DN')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dn_relations', to='valve_data.dimensiontabledrawing', verbose_name='Чертеж')),
            ],
            options={
                'verbose_name': 'Связь чертежа с DN',
                'verbose_name_plural': 'Связи чертежей с DN',
                'unique_together': {('drawing', 'dn')},
            },
        ),
        migrations.AddField(
            model_name='dimensiontabledrawing',
            name='applicable_dn',
            field=models.ManyToManyField(blank=True, help_text='DN, для которых применим этот чертеж. Если не выбрано - чертеж общий для всех DN', through='valve_data.DrawingDnRelation', to='params.dnvariety', verbose_name='Применимые DN'),
        ),
        migrations.AddField(
            model_name='dimensiontabledrawing',
            name='dimension_table',
            field=models.ForeignKey(help_text='Таблица ВГХ, которую иллюстрирует этот чертеж', on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='valve_data.valvemodeldimensiondatatable', verbose_name='Таблица ВГХ'),
        ),
    ]
