# Generated by Django 4.2.23 on 2025-11-05 17:06

from django.db import migrations, models
import storage_manager.fields
import storage_manager.storage_backends.local


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0055_dimensiontabledrawing_drawingdnrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensiontabledrawing',
            name='applicable_dn',
            field=models.ManyToManyField(blank=True, help_text='DN, для которых применим этот чертеж.', through='valve_data.DrawingDnRelation', to='params.dnvariety', verbose_name='Применимые DN'),
        ),
        migrations.AlterField(
            model_name='dimensiontabledrawing',
            name='drawing_file',
            field=storage_manager.fields.ManagedFileField(blank=True, help_text='Загрузите файл чертежа (PDF, JPG, PNG, DWF)', null=True, storage=storage_manager.storage_backends.local.LocalStorage(), upload_to='', verbose_name='Файл чертежа'),
        ),
    ]
