# Generated by Django 4.2.23 on 2025-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('valve_data', '0056_alter_dimensiontabledrawing_applicable_dn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensiontabledrawing',
            name='allowed_dn',
            field=models.ManyToManyField(blank=True, help_text='DN, для которых применим этот чертеж.', related_name='allowed_dn', to='params.dnvariety', verbose_name='Применимые DN'),
        ),
        migrations.AlterField(
            model_name='dimensiontabledrawing',
            name='applicable_dn',
            field=models.ManyToManyField(blank=True, help_text='DN, для которых применим этот чертеж.', related_name='applicable_dn', through='valve_data.DrawingDnRelation', to='params.dnvariety', verbose_name='Применимые DN'),
        ),
    ]
