# Generated by Django 4.2.23 on 2025-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0057_dimensiontabledrawing_allowed_dn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensiontabledrawing',
            name='applicable_dn',
        ),
    ]
