# Generated by Django 4.2.23 on 2025-11-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0058_remove_dimensiontabledrawing_applicable_dn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrawingDnRelation',
        ),
    ]
