# Generated by Django 5.2.7 on 2025-11-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_medialibraryitem_media_file_and_more'),
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
        ('valve_data', '0059_delete_drawingdnrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionTableParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название параметра как на чертеже', max_length=100, verbose_name='Название параметра')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок отображения в таблице', verbose_name='Порядок строки')),
            ],
            options={
                'verbose_name': 'Параметр ВГХ',
                'verbose_name_plural': 'Параметры ВГХ',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dimensiontablecolumn',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dimensiontablecolumn',
            name='dimension_table',
        ),
        migrations.RemoveField(
            model_name='dimensiontablecolumn',
            name='dn',
        ),
        migrations.RemoveField(
            model_name='dimensiontabledrawing',
            name='allowed_dn',
        ),
        migrations.RemoveField(
            model_name='dimensiontabledrawing',
            name='dimension_table',
        ),
        migrations.RemoveField(
            model_name='dimensiontablerow',
            name='dimension_table',
        ),
        migrations.RemoveField(
            model_name='dimensiontablerow',
            name='system_parameter',
        ),
        migrations.RemoveField(
            model_name='valvemodeldimensiondatatable',
            name='valve_brand',
        ),
        migrations.RemoveField(
            model_name='valvemodeldimensiondatatable',
            name='valve_variety',
        ),
        migrations.CreateModel(
            name='DimensionTableDrawingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Порядок отображения чертежа в списке', verbose_name='Порядок отображения')),
                ('description', models.TextField(blank=True, help_text='Описание чертежа в контексте этой таблицы ВГХ', verbose_name='Описание')),
                ('allowed_dn', models.ManyToManyField(blank=True, help_text='DN, для которых применим этот чертеж.', related_name='dimension_table_drawings_allowed_dn', to='params.dnvariety', verbose_name='Применимые DN')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_table_relations', to='media_library.medialibraryitem', verbose_name='Чертеж')),
            ],
            options={
                'verbose_name': 'Связь таблицы ВГХ с чертежом',
                'verbose_name_plural': 'Связи таблиц ВГХ с чертежами',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ValveDimensionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Числовое значение характеристики', max_digits=10, null=True, verbose_name='Значение')),
                ('text_value', models.CharField(blank=True, help_text='Текстовое значение (если не числовое)', max_length=50, verbose_name='Текстовое значение')),
                ('dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_data_dn', to='params.dnvariety', verbose_name='Dn')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_data', to='valve_data.dimensiontableparameter', verbose_name='Параметр')),
                ('pn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_data_pn', to='params.pnvariety', verbose_name='Pn')),
            ],
            options={
                'verbose_name': 'Данные ВГХ',
                'verbose_name_plural': 'Данные ВГХ',
                'ordering': ['pn__sorting_order', 'dn__sorting_order', 'parameter__sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ValveDimensionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название таблицы ВГХ', max_length=100, verbose_name='Название таблицы')),
                ('code', models.CharField(help_text='Код шаблона ВГХ', max_length=50, unique=True, verbose_name='Код шаблона')),
                ('description', models.TextField(blank=True, help_text='Описание таблицы ВГХ', verbose_name='Описание')),
                ('drawings', models.ManyToManyField(help_text='Чертежи, связанные с этой таблицей ВГХ', related_name='dimension_tables', through='valve_data.DimensionTableDrawingItem', through_fields=('dimension_table', 'drawing'), to='media_library.medialibraryitem', verbose_name='Чертежи')),
                ('valve_brand', models.ForeignKey(blank=True, help_text='Бренд серии арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_table_valve_brand', to='producers.brands', verbose_name='Бренд')),
                ('valve_variety', models.ForeignKey(blank=True, help_text='Тип арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_table_valve_variety', to='valve_data.valvevariety', verbose_name='Тип арматуры')),
            ],
            options={
                'verbose_name': 'Таблица ВГХ',
                'verbose_name_plural': 'Таблицы ВГХ',
            },
        ),
        migrations.AddField(
            model_name='dimensiontableparameter',
            name='dimension_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_parameters', to='valve_data.valvedimensiontable', verbose_name='Таблица ВГХ'),
        ),
        migrations.AddField(
            model_name='dimensiontabledrawingitem',
            name='dimension_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_relations', to='valve_data.valvedimensiontable', verbose_name='Таблица ВГХ'),
        ),
        migrations.AlterField(
            model_name='valveline',
            name='valve_model_dimension_data_table',
            field=models.ForeignKey(blank=True, help_text='Таблица весо-габаритных характеристик для этой серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_dimension_table', to='valve_data.valvedimensiontable', verbose_name='Таблица ВГХ'),
        ),
        migrations.CreateModel(
            name='WeightDimensionParameterVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название параметра', max_length=200, unique=True, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код параметра (латинские буквы, цифры, подчеркивания)', max_length=100, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание параметра', verbose_name='Описание')),
                ('is_predefined', models.BooleanField(default=False, editable=False, help_text='Предопределенный параметр - удалять нельзя, могут быть ссылки на него', verbose_name='Предопределенная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Параметр ВГХ',
                'verbose_name_plural': 'Параметры ВГХ',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='valve_data__code_658984_idx')],
            },
        ),
        migrations.AddField(
            model_name='dimensiontableparameter',
            name='parameter_variety',
            field=models.ForeignKey(blank=True, help_text='Сопоставленный системный параметр (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_parameter_variety', to='valve_data.weightdimensionparametervariety', verbose_name='Системный параметр'),
        ),
        migrations.DeleteModel(
            name='DimensionTableCell',
        ),
        migrations.DeleteModel(
            name='DimensionTableColumn',
        ),
        migrations.DeleteModel(
            name='DimensionTableDrawing',
        ),
        migrations.DeleteModel(
            name='DimensionTableRow',
        ),
        migrations.AddIndex(
            model_name='valvedimensiondata',
            index=models.Index(fields=['pn', 'dn'], name='valve_data__pn_id_b42b85_idx'),
        ),
        migrations.AddIndex(
            model_name='valvedimensiondata',
            index=models.Index(fields=['parameter'], name='valve_data__paramet_ef0e7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valvedimensiondata',
            unique_together={('dn', 'pn', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='dimensiontabledrawingitem',
            unique_together={('dimension_table', 'drawing')},
        ),
        migrations.DeleteModel(
            name='ValveModelDimensionDataTable',
        ),
    ]
