# Generated by Django 4.2.23 on 2025-11-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0060_dimensiontableparameter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valvedimensiondata',
            unique_together=set(),
        ),
    ]
