# Generated by Django 5.2.7 on 2025-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0061_alter_valvedimensiondata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensiontableparameter',
            name='legend',
            field=models.CharField(blank=True, help_text='Символ или обозначение параметра на чертеже', max_length=50, null=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='dimensiontableparameter',
            name='name',
            field=models.CharField(help_text='Текстовое описание параметра на чертеже', max_length=200, verbose_name='Описание'),
        ),
    ]
