# Generated by Django 4.2.23 on 2025-11-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0062_dimensiontableparameter_legend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightDimensionParameter',
        ),
    ]
