# Generated by Django 5.2.7 on 2026-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0063_delete_weightdimensionparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddntemplate',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='alloweddntemplate',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='constructionvariety',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='constructionvariety',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='dimensiontableparameter',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='dimensiontableparameter',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='eavattribute',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='eavattribute',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='portqty',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='portqty',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='valveconnectiontopipe',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='weightdimensionparametervariety',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='weightdimensionparametervariety',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
    ]
