# Generated by Django 5.2.7 on 2026-10-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve_data', '0065_valveline_description_i18n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensiontableparameter',
            name='description_i18n',
        ),
    ]
