# Generated by Django 4.2.23 on 2026-01-27 18:24

import core.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('params', '0026_threadsizeset_threadsizesetitem'),
        ('electric_actuators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricActuatorModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название серии', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код серии приводов', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса привода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('model_item_code_template', models.CharField(blank=True, help_text='Шаблон артикула для конкретной модели серии', max_length=500, null=True, verbose_name='Шаблон артикула')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_model_line_brand', to='producers.brands')),
                ('default_output_type', models.ForeignKey(blank=True, help_text='Тип работы серии приводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_model_line_default_output_type', to='params.actuatorgearboxoutputtype')),
            ],
            options={
                'verbose_name': 'Серия моделей электроприводов',
                'verbose_name_plural': 'Серии моделей электроприводов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='actualactuator',
            name='actual_cable_glands_holes',
        ),
        migrations.CreateModel(
            name='ElectricTurnAngleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('turn_angle', models.IntegerField(default=90, help_text='Угол поворота, °', verbose_name='Поворот, °')),
                ('turn_angle_deviation_limit', models.IntegerField(default=0, help_text='Предел регулировки угла поворота, °', verbose_name='Угол ±, °')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_angle_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Угол поворота ЭП',
                'verbose_name_plural': 'Углы поворота электроприводов',
                'ordering': ['is_default', 'sorting_order'],
                'unique_together': {('model_line', 'encoding')},
            },
        ),
        migrations.CreateModel(
            name='ElectricTemperatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('work_temp_min', models.IntegerField(default=0, help_text='Минимальная рабочая температура, °С', verbose_name='Т мин, °С')),
                ('work_temp_max', models.IntegerField(default=0, help_text='Максимальная рабочая температура, °С', verbose_name='Т макс, °С')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Температурная опция электропривода',
                'verbose_name_plural': 'Температурные опции электроприводов',
                'ordering': ['is_default', 'sorting_order'],
                'unique_together': {('model_line', 'encoding')},
            },
        ),
        migrations.CreateModel(
            name='ElectricIpOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('ip_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.ipoption', verbose_name='Опция IP')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция IP электропривода',
                'verbose_name_plural': 'Опции IP электроприводов',
                'ordering': ['ip_option__ip_rank', 'sorting_order'],
                'unique_together': {('model_line', 'ip_option')},
            },
        ),
        migrations.CreateModel(
            name='ElectricHandWheelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('hand_wheel_option', models.ForeignKey(help_text='Тип установленного ручного дублера', on_delete=django.db.models.deletion.CASCADE, to='params.handwheelinstalledoption', verbose_name='Ручной дублер')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_wheel_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Тип установленного ручного дублера',
                'verbose_name_plural': 'Типы установленного ручного дублера электроприводов',
                'ordering': ['is_default', 'sorting_order'],
                'unique_together': {('model_line', 'encoding')},
            },
        ),
        migrations.CreateModel(
            name='ElectricExdOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('exd_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.exdoption', verbose_name='Опция взрывозащиты')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exd_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция взрывозащиты электропривода',
                'verbose_name_plural': 'Опции взрывозащиты электроприводов',
                'ordering': ['exd_option__sorting_order', 'sorting_order'],
                'unique_together': {('model_line', 'exd_option')},
            },
        ),
        migrations.CreateModel(
            name='ElectricBodyCoatingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('body_coating_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.bodycoatingoption', verbose_name='Опция покрытия корпуса')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_coating_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция покрытия корпуса электропривода',
                'verbose_name_plural': 'Опции покрытия корпуса электроприводов',
                'ordering': ['body_coating_option__sorting_order', 'sorting_order'],
                'unique_together': {('model_line', 'body_coating_option')},
            },
        ),
    ]
