# Generated by Django 4.2.23 on 2026-02-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0026_threadsizeset_threadsizesetitem'),
        ('electric_actuators', '0002_electricactuatormodelline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricWaySwitchesOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='way_switches_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
                ('way_switches_option', models.ForeignKey(help_text='Путевые выключатели', on_delete=django.db.models.deletion.CASCADE, to='params.switchesparameters', verbose_name='Путевые выключатели')),
            ],
            options={
                'verbose_name': 'Опция путевые выключатели электропривода',
                'verbose_name_plural': 'Опции взрывозащиты электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'way_switches_option')},
            },
        ),
        migrations.CreateModel(
            name='ElectricPowerSupplyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
                ('power_supply', models.ForeignKey(help_text='Напряжение питания, В', on_delete=django.db.models.deletion.CASCADE, to='params.powersupplies', verbose_name='Напряжение:')),
            ],
            options={
                'verbose_name': 'Опция напряжения питания',
                'verbose_name_plural': 'Опции напряжения питания электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'power_supply')},
            },
        ),
        migrations.CreateModel(
            name='ElectricControlUnitInstalledOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('control_unit_option', models.ForeignKey(help_text='Тип блока управления', on_delete=django.db.models.deletion.CASCADE, to='params.powersupplies', verbose_name='Блок управления')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_unit_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция блока управления электропривода',
                'verbose_name_plural': 'Опции блока управления электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'control_unit_option')},
            },
        ),
        migrations.CreateModel(
            name='ElectricBlinkerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('blinker_option', models.ForeignKey(help_text='Тип установленного блинкера', on_delete=django.db.models.deletion.CASCADE, to='params.blinkeroption', verbose_name='Блинкер')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blinker_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция наличия блинкера электропривода',
                'verbose_name_plural': 'Опции блинкера электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'blinker_option')},
            },
        ),
    ]
