# Generated by Django 5.2.4 on 2026-02-03 07:33

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0001_initial'),
        ('electric_actuators', '0003_electricwayswitchesoption_electricpowersupplyoption_and_more'),
        ('params', '0026_threadsizeset_threadsizesetitem'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricwayswitchesoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Опция путевые выключатели электропривода', 'verbose_name_plural': 'Опции путевых выключателей электроприводов'},
        ),
        migrations.AddField(
            model_name='electricactuatormodelline',
            name='allowed_operating_mode',
            field=models.ManyToManyField(blank=True, default=1, help_text='Возможные для выбора режимы работы двигателя для серии (можно выбрать несколько)', related_name='electric_actuator_model_line_allowed_operating_mode', to='params.operatingmodeoption', verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodelline',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_model_line_brand', to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodelline',
            name='default_output_type',
            field=models.ForeignKey(blank=True, help_text='Тип работы серии приводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_model_line_default_output_type', to='params.actuatorgearboxoutputtype', verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='electriccontrolunitinstalledoption',
            name='control_unit_option',
            field=models.ForeignKey(help_text='Тип блока управления', on_delete=django.db.models.deletion.CASCADE, to='params.controlunitinstalledoption', verbose_name='Блок управления'),
        ),
        migrations.CreateModel(
            name='ElectricActuatorModelLineCertRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('cert_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='cert_doc.certdata', verbose_name='Сертификат')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_relations', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Связь сертификата с серией электроприводов',
                'verbose_name_plural': 'Связи сертификатов с сериями электроприводов',
                'ordering': ['sorting_order'],
                'abstract': False,
                'unique_together': {('cert_data', 'model_line')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ElectricMechanicalIndicatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('mechanical_indicator_option', models.ForeignKey(help_text='Тип механического индикатора', on_delete=django.db.models.deletion.CASCADE, to='params.mechanicalindicatorinstalledoption', verbose_name='Механический индикатор')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_indicator_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция механического индикатора электропривода',
                'verbose_name_plural': 'Опции механического индикатора электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'mechanical_indicator_option')},
            },
        ),
        migrations.CreateModel(
            name='ElectricOperatingModeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_mode_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
                ('operating_mode_option', models.ForeignKey(help_text='Режим работы двигателя', on_delete=django.db.models.deletion.CASCADE, to='params.operatingmodeoption', verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Опция режима работы двигателя электропривода',
                'verbose_name_plural': 'Опции режима работы двигателя электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'operating_mode_option')},
            },
        ),
    ]
