# Generated by Django 5.2.4 on 2026-02-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0004_alter_electricwayswitchesoption_options_and_more'),
        ('params', '0026_threadsizeset_threadsizesetitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricActuatorBodyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название таблицы корпусов', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код таблицы корпусов', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание таблицы корпусов', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Таблица корпусов',
                'verbose_name_plural': 'Таблица корпусов для их логического объединения для групповой обработки',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ElectricActuatorBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название модели корпуса привода', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели корпуса привода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса привода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('max_stem_height', models.PositiveIntegerField(blank=True, help_text='Глубина отверстия под шток арматуры', null=True, verbose_name='Высота штока')),
                ('max_stem_diameter', models.PositiveIntegerField(blank=True, help_text='Максимальный диаметр отверстия под шток арматуры', null=True, verbose_name='Макс шток')),
                ('weight_body', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Вес корпуса, кг', max_digits=4, null=True, verbose_name='Вес:')),
                ('model_line', models.ForeignKey(help_text='Серия приводов', on_delete=django.db.models.deletion.PROTECT, related_name='ea_body_model_line', to='electric_actuators.electricactuatormodelline')),
                ('mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка', related_name='model_body_mounting_plate_electric_model_line', to='params.mountingplatetypes', verbose_name='Монт.площадка')),
                ('stem_shape', models.ForeignKey(blank=True, help_text='Тип отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_stem_shape_electric_model_line', to='params.stemshapes', verbose_name='Тип штока')),
                ('stem_size', models.ForeignKey(blank=True, help_text='Размер отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_body_stem_size_electric_model_line', to='params.stemsize', verbose_name='Размер штока')),
                ('body_table', models.ForeignKey(help_text='Таблица корпусов для их логического объединения для групповой обработки', on_delete=django.db.models.deletion.PROTECT, related_name='model_body_body_table', to='electric_actuators.electricactuatorbodytable', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Модель корпуса электропривода',
                'verbose_name_plural': 'Модели корпусов электроприводов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='CableGlandHolesSetThroughOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('cg_set', models.ForeignKey(help_text='Отверстия под кабельные вводы', on_delete=django.db.models.deletion.CASCADE, to='electric_actuators.cableglandholesset', verbose_name='Отверстия под КВ')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cg_set_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция кабельных вводов',
                'verbose_name_plural': 'Опции кабельных вводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'cg_set')},
            },
        ),
    ]
