# Generated by Django 5.2.4 on 2026-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0005_electricactuatorbodytable_electricactuatorbody_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricactuatorbody',
            name='weight_body',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Вес корпуса, кг', max_digits=6, null=True, verbose_name='Вес:'),
        ),
    ]
