# Generated by Django 5.2.4 on 2026-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0006_alter_electricactuatorbody_weight_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricactuatorbody',
            name='max_stem_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Максимальный диаметр отверстия под шток арматуры', max_digits=6, null=True, verbose_name='Макс шток'),
        ),
        migrations.AlterField(
            model_name='electricactuatorbody',
            name='max_stem_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Глубина отверстия под шток арматуры', max_digits=6, null=True, verbose_name='Высота штока'),
        ),
    ]
