# Generated by Django 5.2.4 on 2026-02-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0007_alter_electricactuatorbody_max_stem_diameter_and_more'),
        ('params', '0026_threadsizeset_threadsizesetitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electrictemperatureoption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='electricturnangleoption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='electrichandwheeloption',
            unique_together={('model_line', 'hand_wheel_option', 'encoding')},
        ),
    ]
