# Generated by Django 4.2.23 on 2026-02-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0026_threadsizeset_threadsizesetitem'),
        ('electric_actuators', '0008_alter_electrictemperatureoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricpowersupplyoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Опция напряжения питания для модели в серии электроприводов', 'verbose_name_plural': 'Опции напряжения питания для модели в серии электроприводов'},
        ),
        migrations.AlterUniqueTogether(
            name='electricpowersupplyoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='motor_current_rated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Номинальный ток двигателя', max_digits=6, null=True, verbose_name='Ток ном,А'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='motor_current_starting',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Пусковой ток двигателя', max_digits=6, null=True, verbose_name='Ток пуск,А'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='motor_power',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Мощность двигателя, кВт', max_digits=6, null=True, verbose_name='Мощн,кВт'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='rotation_speed',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Скорость, об/мин', max_digits=3, null=True, verbose_name='Скорость'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='time_to_open',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Время поворота на 90°, сек', max_digits=5, null=True, verbose_name='Время поворота на 90°'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='torque_max',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Максимальное усилие', max_digits=5, verbose_name='Макс.усилие'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='torque_min',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Минимальное усилие', max_digits=5, verbose_name='Мин.усилие'),
        ),
        migrations.AlterField(
            model_name='electricpowersupplyoption',
            name='power_supply',
            field=models.ForeignKey(help_text='Напряжение питания модели', on_delete=django.db.models.deletion.CASCADE, related_name='electric_actuator_data_model_power_supply', to='params.powersupplies', verbose_name='Напряжение'),
        ),
        migrations.CreateModel(
            name='ElectricActuatorModelLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('body', models.ForeignKey(blank=True, help_text='Корпус модели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_model_line_item_body', to='electric_actuators.electricactuatorbody')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_line_item_model_line', to='electric_actuators.electricactuatormodelline')),
            ],
            options={
                'verbose_name': 'Модель электропривода',
                'verbose_name_plural': 'Модели электропривода в серии',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='model_line',
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='model_line_item',
            field=models.ForeignKey(default=1, help_text='Модель в серии электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='model_line_item_power_supply_option', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель'),
            preserve_default=False,
        ),
    ]
