# Generated by Django 4.2.23 on 2026-02-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0009_alter_electricpowersupplyoption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualactuator',
            name='actual_wiring_diagram',
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='rotation_speed',
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='time_to_open',
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='torque_max',
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='torque_min',
        ),
        migrations.AddField(
            model_name='electricactuatormodellineitem',
            name='rotation_speed',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Скорость, об/мин', max_digits=3, null=True, verbose_name='Скорость'),
        ),
        migrations.AddField(
            model_name='electricactuatormodellineitem',
            name='time_to_open',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Время поворота на 90°, сек', max_digits=5, null=True, verbose_name='Время поворота на 90°'),
        ),
        migrations.AddField(
            model_name='electricactuatormodellineitem',
            name='torque_max',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Максимальное усилие', max_digits=5, verbose_name='Макс.усилие'),
        ),
        migrations.AddField(
            model_name='electricactuatormodellineitem',
            name='torque_min',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Минимальное усилие', max_digits=5, verbose_name='Мин.усилие'),
        ),
        migrations.DeleteModel(
            name='WiringDiagram',
        ),
    ]
