# Generated by Django 4.2.23 on 2026-02-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0010_remove_actualactuator_actual_wiring_diagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricpowersupplyoption',
            name='motor_power',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Мощность двигателя, кВт', max_digits=7, null=True, verbose_name='Мощн,кВт'),
        ),
    ]
