# Generated by Django 4.2.23 on 2026-02-08 11:16

import core.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0027_powersupplies_encoding'),
        ('electric_actuators', '0011_alter_electricpowersupplyoption_motor_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatormodellineitem',
            name='time_to_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Время закрытия, с', max_digits=6, null=True, verbose_name='Закр, с'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodellineitem',
            name='rotation_speed',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Скорость, об/мин', max_digits=3, null=True, verbose_name='Об/мин'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodellineitem',
            name='time_to_open',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Время открытия, сек', max_digits=6, null=True, verbose_name='Откр, с'),
        ),
        migrations.CreateModel(
            name='ElectricSafetyPositionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ea_safety_position_option_model_line_item', to='electric_actuators.electricactuatormodellineitem', verbose_name='Положение безопасности')),
                ('safety_position', models.ForeignKey(help_text='Положения безопасности', on_delete=django.db.models.deletion.CASCADE, to='params.safetypositionoption', verbose_name='Положение безопасности')),
            ],
            options={
                'verbose_name': 'Положение безопасности модели электропривода',
                'verbose_name_plural': 'Положения безопасности моделей лектроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line_item', 'safety_position')},
            },
        ),
        migrations.CreateModel(
            name='ElectricActuatorSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название привода - формируется автоматически', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код привода - формируется автоматически', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание привода - формируется автоматически', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('is_unique', models.BooleanField(default=True, verbose_name='Это уникальная конфигурация')),
                ('actual_cable_glands_holes', models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_cable_glands_holes', to='electric_actuators.cableglandholesset')),
                ('actual_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка', related_name='selected_mounting_plate', to='params.mountingplatetypes')),
                ('actual_stem_shape', models.ForeignKey(blank=True, help_text='Тип отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_stem_shape', to='params.stemshapes')),
                ('actual_stem_size', models.ForeignKey(blank=True, help_text='Размер отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_stem_size', to='params.stemsize')),
                ('selected_body_coating', models.ForeignKey(blank=True, help_text='Выбранное покрытие корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricbodycoatingoption', verbose_name='Покрытие корпуса')),
                ('selected_exd', models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricexdoption', verbose_name='Взрывозащита')),
                ('selected_hand_wheel', models.ForeignKey(blank=True, help_text='Встроенный ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electrichandwheeloption', verbose_name='Встроенный дублер')),
                ('selected_ip', models.ForeignKey(blank=True, help_text='Выбранная степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricipoption', verbose_name='Степень защиты IP')),
                ('selected_model_line_item', models.ForeignKey(help_text='Модель электропривода', on_delete=django.db.models.deletion.CASCADE, related_name='selected_electric_actuator_model_line_item', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель')),
                ('selected_safety_position', models.ForeignKey(blank=True, help_text='Выбранное положение безопасности привода', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricsafetypositionoption', verbose_name='Выбранное положение безопасности')),
                ('selected_temperature', models.ForeignKey(blank=True, help_text='Выбранная температурная опция', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electrictemperatureoption', verbose_name='Температурная опция')),
            ],
            options={
                'verbose_name': 'Модель электропривода selected',
                'verbose_name_plural': 'Модели электропривода',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
