# Generated by Django 5.2.4 on 2026-02-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0012_electricactuatormodellineitem_time_to_close_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricactuatorselected',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Модель электропривода selected', 'verbose_name_plural': 'Модели электропривода selected'},
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_power_supply',
            field=models.ForeignKey(blank=True, help_text='Напряжение питания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricpowersupplyoption', verbose_name='Напряжение'),
        ),
    ]
