# Generated by Django 5.2.4 on 2026-02-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0013_alter_electricactuatorselected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='time_to_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Альтернативное время закрытия, с - 0 если совпадает с базовой моделью', max_digits=6, null=True, verbose_name='Закр, с'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='time_to_open',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Альтернативное время открытия, сек - 0 если совпадает с базовой моделью', max_digits=6, null=True, verbose_name='Откр, с'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='torque_max',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Альтернативное Максимальное усилие - 0 если совпадает с базовой моделью', max_digits=5, verbose_name='Макс.усилие'),
        ),
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='torque_min',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Минимальное усилие', max_digits=5, verbose_name='Альтернативное Мин.усилие - 0 если совпадает с базовой моделью'),
        ),
    ]
