# Generated by Django 5.2.4 on 2026-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0014_electricpowersupplyoption_time_to_close_and_more'),
        ('params', '0027_powersupplies_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpowersupplyoption',
            name='control_unit_option',
            field=models.ManyToManyField(help_text='Тип блока управления', to='params.controlunitinstalledoption', verbose_name='Блок управления'),
        ),
    ]
