# Generated by Django 5.2.4 on 2026-02-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0015_electricpowersupplyoption_control_unit_option'),
        ('params', '0027_powersupplies_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_control_unit_installed',
            field=models.ForeignKey(default=1, help_text='Тип блока управления', on_delete=django.db.models.deletion.CASCADE, to='params.controlunitinstalledoption', verbose_name='Блок управления'),
            preserve_default=False,
        ),
    ]
