# Generated by Django 5.2.4 on 2026-02-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0016_electricactuatorselected_selected_control_unit_installed'),
        ('params', '0027_powersupplies_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricactuatorselected',
            name='selected_control_unit_installed',
        ),
        migrations.RemoveField(
            model_name='electricpowersupplyoption',
            name='control_unit_option',
        ),
        migrations.CreateModel(
            name='ElectricControlUnitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('encoding', models.CharField(help_text='Код для генерации артикула', max_length=50, verbose_name='Кодировка')),
                ('is_default', models.BooleanField(default=False, help_text='Выбирать этот блок управления по умолчанию', verbose_name='По умолчанию')),
                ('power_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Мощность потребления блока управления', max_digits=6, null=True, verbose_name='Потребляемая мощность, Вт')),
                ('control_unit', models.ForeignKey(help_text='Тип блока управления', on_delete=django.db.models.deletion.CASCADE, to='params.controlunitinstalledoption', verbose_name='Блок управления')),
                ('power_supply_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_unit_options', to='electric_actuators.electricpowersupplyoption', verbose_name='Опция напряжения питания')),
            ],
            options={
                'verbose_name': 'Опция блока управления для напряжения',
                'verbose_name_plural': 'Опции блоков управления для напряжений',
                'ordering': ['sorting_order'],
                'unique_together': {('power_supply_option', 'control_unit')},
            },
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_control_unit_option',
            field=models.ForeignKey(blank=True, help_text='Выбранный блок управления с кодировкой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electriccontrolunitoption', verbose_name='Блок управления'),
        ),
    ]
