# Generated by Django 5.2.4 on 2026-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0017_remove_electricactuatorselected_selected_control_unit_installed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccontrolunitoption',
            name='power_consumption',
        ),
        migrations.AlterField(
            model_name='electriccontrolunitoption',
            name='encoding',
            field=models.CharField(blank=True, default='', help_text='Код для генерации артикула', max_length=50, null=True, verbose_name='Кодировка'),
        ),
    ]
