# Generated by Django 5.2.4 on 2026-02-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0018_remove_electriccontrolunitoption_power_consumption_and_more'),
        ('params', '0027_powersupplies_encoding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electriccontrolunitoption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='electricsafetypositionoption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='electricwayswitchesoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_turn_angle_option',
            field=models.ForeignKey(blank=True, help_text='Угол поворота', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricturnangleoption', verbose_name='Угол поворота'),
        ),
        migrations.AddField(
            model_name='electricsafetypositionoption',
            name='power_supply_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='control_unit_options', to='electric_actuators.electricpowersupplyoption', verbose_name='Опция напряжения питания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricwayswitchesoption',
            name='model_line_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='way_switches_options', to='electric_actuators.electricactuatormodellineitem', verbose_name='Серия электроприводов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electriccontrolunitoption',
            name='control_unit',
            field=models.ForeignKey(help_text='Тип блока управления', on_delete=django.db.models.deletion.CASCADE, related_name='ea_model_lene_item_options_control_unit_options', to='params.controlunitinstalledoption', verbose_name='Блок управления'),
        ),
        migrations.AlterField(
            model_name='electriccontrolunitoption',
            name='power_supply_option',
            field=models.ForeignKey(help_text='Опция напряжения питания', on_delete=django.db.models.deletion.CASCADE, related_name='ea_model_lene_item_options_power_supply_options', to='electric_actuators.electricpowersupplyoption', verbose_name='Опция напряжения питания'),
        ),
        migrations.AlterField(
            model_name='electricsafetypositionoption',
            name='encoding',
            field=models.CharField(blank=True, default='', help_text='Код для генерации артикула', max_length=50, null=True, verbose_name='Кодировка'),
        ),
        migrations.AlterField(
            model_name='electricsafetypositionoption',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Выбирать этот блок управления по умолчанию', verbose_name='По умолчанию'),
        ),
        migrations.RemoveField(
            model_name='electricsafetypositionoption',
            name='model_line_item',
        ),
        migrations.RemoveField(
            model_name='electricwayswitchesoption',
            name='model_line',
        ),
    ]
