# Generated by Django 5.2.4 on 2026-02-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0019_alter_electriccontrolunitoption_unique_together_and_more'),
        ('params', '0027_powersupplies_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricactuatorselected',
            name='actual_mounting_plate',
        ),
        migrations.AlterField(
            model_name='electricpowersupplyoption',
            name='torque_min',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Альтернативное Мин.усилие - 0 если совпадает с базовой моделью', max_digits=5, verbose_name='Мин. усилие'),
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='actual_mounting_plate',
            field=models.ForeignKey(blank=True, help_text='Монтажная площадка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_mounting_plate', to='params.mountingplatetypes'),
        ),
    ]
