# Generated by Django 4.2.23 on 2026-02-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0020_remove_electricactuatorselected_actual_mounting_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableGlandHolesSetBodyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cg_set_options', to='electric_actuators.electricactuatorbody', verbose_name='Модель корпуса')),
            ],
            options={
                'ordering': ['sorting_order'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='cableglandholessetthroughoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cableglandholessetthroughoption',
            name='cg_set',
        ),
        migrations.RemoveField(
            model_name='cableglandholessetthroughoption',
            name='model_line',
        ),
        migrations.DeleteModel(
            name='ActualActuator',
        ),
        migrations.DeleteModel(
            name='CableGlandHolesSetThroughOption',
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_cable_glands_holes',
            field=models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.cableglandholessetbodyoption', verbose_name='Кабельные вводы'),
        ),
    ]
