# Generated by Django 5.2.4 on 2026-02-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0021_cableglandholessetbodyoption_and_more'),
        ('params', '0029_alter_controlunitinstalledoption_feature_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_mechanical_indicator_option',
            field=models.ForeignKey(blank=True, help_text='Выбранный механический индикатор с кодировкой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.mechanicalindicatorinstalledoption', verbose_name='Механический индикатор'),
        ),
    ]
