# Generated by Django 4.2.23 on 2026-02-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0030_bodycolor_ral_name_en_bodycolor_ral_name_ru'),
        ('electric_actuators', '0022_electricactuatorselected_selected_mechanical_indicator_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_blinker_option',
            field=models.ForeignKey(blank=True, help_text='Тип установленного блинкера', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.blinkeroption', verbose_name='Блинкер'),
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_body_color_option',
            field=models.ForeignKey(blank=True, help_text='Цвет корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.bodycolor', verbose_name='Цвет'),
        ),
        migrations.CreateModel(
            name='ElectricBodyColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('color_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.bodycolor', verbose_name='Опция цвета')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_color_options', to='electric_actuators.electricactuatormodelline', verbose_name='Серия электроприводов')),
            ],
            options={
                'verbose_name': 'Опция цвета корпуса электропривода',
                'verbose_name_plural': 'Опции цвета корпуса электроприводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'color_option')},
            },
        ),
    ]
