# Generated by Django 5.2.4 on 2026-02-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0023_electricactuatorselected_selected_blinker_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricactuatorselected',
            name='selected_blinker_option',
            field=models.ForeignKey(blank=True, help_text='Тип установленного блинкера', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricblinkeroption', verbose_name='Блинкер'),
        ),
        migrations.AlterField(
            model_name='electricactuatorselected',
            name='selected_body_color_option',
            field=models.ForeignKey(blank=True, help_text='Цвет корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricbodycoloroption', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='electricactuatorselected',
            name='selected_mechanical_indicator_option',
            field=models.ForeignKey(blank=True, help_text='Выбранный механический индикатор с кодировкой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricmechanicalindicatoroption', verbose_name='Механический индикатор'),
        ),
    ]
