# Generated by Django 4.2.23 on 2026-02-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0024_alter_electricactuatorselected_selected_blinker_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricsafetypositionoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Положение безопасности модели электропривода', 'verbose_name_plural': 'Положения безопасности моделей электроприводов'},
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_way_switches_option',
            field=models.ForeignKey(blank=True, help_text='Путевые выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricwayswitchesoption', verbose_name='Путевые выключатели'),
        ),
        migrations.AlterField(
            model_name='electricwayswitchesoption',
            name='model_line_item',
            field=models.ForeignKey(help_text='Модель в серии электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='way_switches_options', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель'),
        ),
    ]
