# Generated by Django 4.2.23 on 2026-02-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0030_bodycolor_ral_name_en_bodycolor_ral_name_ru'),
        ('electric_actuators', '0025_alter_electricsafetypositionoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricactuatorselected',
            name='selected_way_switches_option',
            field=models.ForeignKey(blank=True, help_text='Путевые выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='way_switches_model_line_item', to='electric_actuators.electricwayswitchesoption', verbose_name='Путевые выключатели'),
        ),
        migrations.CreateModel(
            name='ElectricTorqueSwitchesOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line_item', models.ForeignKey(help_text='Модель в серии электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='torque_switches_options', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель')),
                ('torque_switches_option', models.ForeignKey(help_text='Путевые выключатели', on_delete=django.db.models.deletion.CASCADE, to='params.switchesparameters', verbose_name='Путевые выключатели')),
            ],
            options={
                'verbose_name': 'Опция моментные выключатели электропривода',
                'verbose_name_plural': 'Опции моментных выключателей электроприводов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ElectricEndSwitchesOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('end_switches_option', models.ForeignKey(help_text='Путевые выключатели', on_delete=django.db.models.deletion.CASCADE, to='params.switchesparameters', verbose_name='Путевые выключатели')),
                ('model_line_item', models.ForeignKey(help_text='Модель в серии электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='end_switches_options', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Опция конечные выключатели электропривода',
                'verbose_name_plural': 'Опции конечных выключателей электроприводов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_end_switches_option',
            field=models.ForeignKey(blank=True, help_text='Конечные выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_switches_model_line_item', to='electric_actuators.electricendswitchesoption', verbose_name='Конечные выключатели'),
        ),
        migrations.AddField(
            model_name='electricactuatorselected',
            name='selected_torque_switches_option',
            field=models.ForeignKey(blank=True, help_text='Моментные выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torque_switches_model_line_item', to='electric_actuators.electrictorqueswitchesoption', verbose_name='Моментные выключатели'),
        ),
    ]
