# Generated by Django 4.2.23 on 2026-02-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0030_bodycolor_ral_name_en_bodycolor_ral_name_ru'),
        ('electric_actuators', '0026_alter_electricactuatorselected_selected_way_switches_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricendswitchesoption',
            name='end_switches_option',
            field=models.ForeignKey(help_text='Концевые выключатели', on_delete=django.db.models.deletion.CASCADE, to='params.switchesparameters', verbose_name='Концевые выключатели'),
        ),
        migrations.AlterField(
            model_name='electrictorqueswitchesoption',
            name='torque_switches_option',
            field=models.ForeignKey(help_text='Моментные выключатели', on_delete=django.db.models.deletion.CASCADE, to='params.switchesparameters', verbose_name='Моментные выключатели'),
        ),
    ]
