# Generated by Django 5.2.4 on 2026-02-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0027_alter_electricendswitchesoption_end_switches_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatormodelline',
            name='motor_thermal_protection',
            field=models.CharField(blank=True, help_text='Тепловая защита двигателя', max_length=200, null=True, verbose_name='Теплозащита'),
        ),
    ]
