# Generated by Django 5.2.4 on 2026-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0028_electricactuatormodelline_motor_thermal_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricactuatormodelline',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание серии электроприводов', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodelline',
            name='model_item_code_template',
            field=models.CharField(blank=True, help_text='Шаблон артикула для конкретной модели в серии', max_length=500, null=True, verbose_name='Шаблон артикула'),
        ),
    ]
