# Generated by Django 5.2.4 on 2026-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0029_alter_electricactuatormodelline_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cableglandholessetbodyoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cableglandholessetbodyoption',
            name='encoding',
        ),
        migrations.RemoveField(
            model_name='cableglandholessetbodyoption',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cableglandholessetbodyoption',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cableglandholessetbodyoption',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='cableglandholessetbodyoption',
            name='sorting_order',
        ),
    ]
