# Generated by Django 5.2.4 on 2026-02-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0030_cablegland_through_model'),
        ('options', '0001_cablegland_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandholessetbodyoption',
            name='cableglandholessetthroughoption_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.cableglandholessetthroughoption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cableglandholessetbodyoption',
            name='model_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cg_set_options_through', to='electric_actuators.electricactuatorbody', verbose_name='Модель корпуса'),
        ),
    ]
