# Generated by Django 4.2.23 on 2026-03-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0031_cablegland_through_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricsafetypositionoption',
            name='power_supply_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_position_power_supply_option', to='electric_actuators.electricpowersupplyoption', verbose_name='Опция напряжения питания'),
        ),
    ]
