# Generated by Django 5.2.4 on 2026-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0032_alter_electricsafetypositionoption_power_supply_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatorselected',
            name='ext_code',
            field=models.CharField(blank=True, help_text='Расширенный код привода - формируется автоматически', max_length=500, null=True, verbose_name='Код ext'),
        ),
    ]
