# Generated by Django 5.2.4 on 2026-03-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0033_electricactuatorselected_ext_code'),
        ('params', '0030_bodycolor_ral_name_en_bodycolor_ral_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cableglandholesset',
            options={'verbose_name': 'Набор резьб отверстий кабельных вводов', 'verbose_name_plural': 'Наборы резьб отверстий кабельных вводов'},
        ),
        migrations.AlterField(
            model_name='cableglandholesset',
            name='cg1',
            field=models.ForeignKey(blank=True, help_text='Отверстие под КВ1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland1', to='params.threadsize', verbose_name='КВ1'),
        ),
        migrations.AlterField(
            model_name='cableglandholesset',
            name='cg2',
            field=models.ForeignKey(blank=True, help_text='Отверстие под КВ2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland2', to='params.threadsize', verbose_name='КВ2'),
        ),
        migrations.AlterField(
            model_name='cableglandholesset',
            name='cg3',
            field=models.ForeignKey(blank=True, help_text='Отверстие под КВ3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland3', to='params.threadsize', verbose_name=' КВ3'),
        ),
        migrations.AlterField(
            model_name='cableglandholesset',
            name='cg4',
            field=models.ForeignKey(blank=True, help_text='Отверстие под КВ4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland4', to='params.threadsize', verbose_name='КВ4'),
        ),
        migrations.AlterField(
            model_name='cableglandholesset',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание набора отверстий под КВ', max_length=200, verbose_name='Описание'),
        ),
    ]
