# Generated by Django 4.2.23 on 2026-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0034_alter_cableglandholesset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatormodellineitem',
            name='torque_work',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Рабочий момент, Нм', max_digits=5, verbose_name='Раб.момент'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodellineitem',
            name='torque_max',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Максимальное момент, Нм', max_digits=5, verbose_name='Макс.момент'),
        ),
        migrations.AlterField(
            model_name='electricactuatormodellineitem',
            name='torque_min',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Минимальное момент, Нм', max_digits=5, verbose_name='Мин.момент'),
        ),
    ]
