# Generated by Django 4.2.23 on 2026-03-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0035_electricactuatormodellineitem_torque_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electriccontrolunitoption',
            name='power_supply_option',
            field=models.ForeignKey(help_text='Опция напряжения питания', on_delete=django.db.models.deletion.CASCADE, related_name='ea_model_line_item_options_power_supply_options', to='electric_actuators.electricpowersupplyoption', verbose_name='Опция напряжения питания'),
        ),
    ]
