# Generated by Django 5.2.4 on 2026-06-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0036_alter_electriccontrolunitoption_power_supply_option'),
        ('params', '0056_alter_climaticplacementcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricActuatorConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название привода - формируется автоматически', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код привода - формируется автоматически', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание привода - формируется автоматически', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('work_temp_min', models.IntegerField(default=0, help_text='Минимальная рабочая температура, °С', verbose_name='Т мин, °С')),
                ('work_temp_max', models.IntegerField(default=0, help_text='Максимальная рабочая температура, °С', verbose_name='Т макс, °С')),
                ('is_unique', models.BooleanField(default=True, verbose_name='Это уникальная конфигурация')),
                ('actual_cable_glands_holes', models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_cable_glands_holes', to='electric_actuators.cableglandholesset', verbose_name='Отверстия под кабельные вводы')),
                ('actual_mounting_plate', models.ForeignKey(blank=True, help_text='Монтажная площадка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_mounting_plate', to='params.mountingplatetypes', verbose_name='Монтажная площадка')),
                ('actual_stem_shape', models.ForeignKey(blank=True, help_text='Тип отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_stem_shape', to='params.stemshapes', verbose_name='Тип отверстия под шток')),
                ('actual_stem_size', models.ForeignKey(blank=True, help_text='Размер отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_stem_size', to='params.stemsize', verbose_name='Размер отверстия под шток')),
                ('selected_blinker_option', models.ForeignKey(blank=True, help_text='Тип установленного блинкера', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.blinkeroption', verbose_name='Блинкер')),
                ('selected_body_coating', models.ForeignKey(blank=True, help_text='Выбранное покрытие корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.bodycoatingoption', verbose_name='Покрытие корпуса')),
                ('selected_body_color_option', models.ForeignKey(blank=True, help_text='Цвет корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.bodycolor', verbose_name='Цвет')),
                ('selected_cable_glands_holes', models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_cg_option', to='electric_actuators.cableglandholesset', verbose_name='Кабельные вводы')),
                ('selected_control_unit_option', models.ForeignKey(blank=True, help_text='Выбранный блок управления', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.controlunitinstalledoption', verbose_name='Блок управления')),
                ('selected_end_switches_option', models.ForeignKey(blank=True, help_text='Конечные выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_end_switches', to='params.switchesparameters', verbose_name='Конечные выключатели')),
                ('selected_exd', models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.exdoption', verbose_name='Взрывозащита')),
                ('selected_hand_wheel', models.ForeignKey(blank=True, help_text='Встроенный ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.handwheelinstalledoption', verbose_name='Встроенный дублер')),
                ('selected_ip', models.ForeignKey(blank=True, help_text='Выбранная степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.ipoption', verbose_name='Степень защиты IP')),
                ('selected_mechanical_indicator_option', models.ForeignKey(blank=True, help_text='Выбранный механический индикатор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.mechanicalindicatorinstalledoption', verbose_name='Механический индикатор')),
                ('selected_model_line', models.ForeignKey(blank=True, help_text='Серия электроприводов — фильтрует доступные модели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_model_lines', to='electric_actuators.electricactuatormodelline', verbose_name='Серия')),
                ('selected_model_line_item', models.ForeignKey(blank=True, help_text='Модель электропривода', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor_model_line_items', to='electric_actuators.electricactuatormodellineitem', verbose_name='Модель')),
                ('selected_power_supply', models.ForeignKey(blank=True, help_text='Выбранное напряжение питания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricpowersupplyoption', verbose_name='Напряжение питания')),
                ('selected_safety_position', models.ForeignKey(blank=True, help_text='Выбранное положение безопасности привода', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.safetypositionoption', verbose_name='Положение безопасности')),
                ('selected_temperature', models.ForeignKey(blank=True, help_text='Выбранная температурная опция', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electrictemperatureoption', verbose_name='Температурная опция')),
                ('selected_torque_switches_option', models.ForeignKey(blank=True, help_text='Моментные выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_torque_switches', to='params.switchesparameters', verbose_name='Моментные выключатели')),
                ('selected_turn_angle_option', models.ForeignKey(blank=True, help_text='Угол поворота', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_actuators.electricturnangleoption', verbose_name='Угол поворота')),
                ('selected_way_switches_option', models.ForeignKey(blank=True, help_text='Путевые выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_way_switches', to='params.switchesparameters', verbose_name='Путевые выключатели')),
            ],
            options={
                'verbose_name': 'Конструктор электропривода',
                'verbose_name_plural': 'Конструктор электроприводов',
                'ordering': ['sorting_order'],
            },
        ),
    ]
