# Generated by Django 5.2.4 on 2026-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0037_electricactuatorconstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedControlUnitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(help_text='Код опции для подстановки в артикул, например «L», «N», «M1»', max_length=50, verbose_name='Кодировка')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли в списках выбора', verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Разрешённый БУ для серии',
                'verbose_name_plural': 'Разрешённые БУ для серий',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='AllowedSignalProfileOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(help_text='Код для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Разрешённый профиль сигналов для серии',
                'verbose_name_plural': 'Разрешённые профили сигналов для серий',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='AllowedTurnCounterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(help_text='Код для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Разрешённый счётчик для серии',
                'verbose_name_plural': 'Разрешённые счётчики для серий',
                'ordering': ['sorting_order'],
            },
        ),
    ]
