# Generated by Django 5.2.4 on 2026-06-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0038_allowedcontrolunitoption_allowedsignalprofileoption_and_more'),
        ('params', '0058_controlunitsignalprofile_signalrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electriccontrolunitoption',
            name='allowed_signal_profiles',
            field=models.ManyToManyField(blank=True, help_text='Все допустимые профили сигналов для этой пары БУ×напряжение', related_name='allowed_in_control_unit_options', to='params.controlunitsignalprofile', verbose_name='Доступные профили сигналов'),
        ),
        migrations.AddField(
            model_name='electriccontrolunitoption',
            name='allowed_turn_counters',
            field=models.ManyToManyField(blank=True, help_text='Все допустимые счётчики для этой пары БУ×напряжение', related_name='allowed_in_control_unit_options', to='params.turncounteroption', verbose_name='Доступные счётчики оборотов'),
        ),
        migrations.AddField(
            model_name='electriccontrolunitoption',
            name='default_signal_profile',
            field=models.ForeignKey(blank=True, help_text='Значение по умолчанию для этой пары БУ×напряжение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_control_unit_options', to='params.controlunitsignalprofile', verbose_name='Профиль сигналов по умолчанию'),
        ),
        migrations.AddField(
            model_name='electriccontrolunitoption',
            name='default_turn_counter',
            field=models.ForeignKey(blank=True, help_text='Значение по умолчанию для этой пары БУ×напряжение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_control_unit_options', to='params.turncounteroption', verbose_name='Счётчик оборотов по умолчанию'),
        ),
        migrations.AddField(
            model_name='allowedcontrolunitoption',
            name='control_unit',
            field=models.ForeignKey(help_text='Модель блока управления', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_in_model_lines', to='params.controlunitinstalledoption', verbose_name='Блок управления'),
        ),
        migrations.AddField(
            model_name='allowedcontrolunitoption',
            name='model_line',
            field=models.ForeignKey(help_text='Серия электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_control_units', to='electric_actuators.electricactuatormodelline', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='allowedsignalprofileoption',
            name='model_line',
            field=models.ForeignKey(help_text='Серия электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_signal_profiles', to='electric_actuators.electricactuatormodelline', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='allowedsignalprofileoption',
            name='signal_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_in_model_lines', to='params.controlunitsignalprofile', verbose_name='Профиль сигналов'),
        ),
        migrations.AddField(
            model_name='allowedturncounteroption',
            name='model_line',
            field=models.ForeignKey(help_text='Серия электроприводов', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_turn_counters', to='electric_actuators.electricactuatormodelline', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='allowedturncounteroption',
            name='turn_counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_in_model_lines', to='params.turncounteroption', verbose_name='Счётчик оборотов'),
        ),
        migrations.AlterUniqueTogether(
            name='allowedcontrolunitoption',
            unique_together={('model_line', 'control_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='allowedsignalprofileoption',
            unique_together={('model_line', 'signal_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='allowedturncounteroption',
            unique_together={('model_line', 'turn_counter')},
        ),
    ]
