# Generated by Django 5.1.4 on 2026-06-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0039_electriccontrolunitoption_allowed_signal_profiles_and_more'),
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('params', '0061_add_input_signal_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccontrolunitoption',
            name='allowed_signal_profiles',
        ),
        migrations.RemoveField(
            model_name='electriccontrolunitoption',
            name='default_signal_profile',
        ),
        migrations.CreateModel(
            name='ControlUnitWiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название схемы, например «INT 380В станд. (обогрев отд.кабель)»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код схемы, например «I38-STD-SEP»', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание особенностей схемы', verbose_name='Описание')),
                ('cached_json', models.JSONField(blank=True, help_text='Автоматически собираемые данные для быстрого чтения фронтом', null=True, verbose_name='Кешированные данные')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать в списках выбора', verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('control_unit', models.ForeignKey(help_text='Тип блока управления', on_delete=django.db.models.deletion.CASCADE, related_name='control_unit_wirings', to='params.controlunitinstalledoption', verbose_name='Блок управления')),
                ('power_supply', models.ForeignKey(help_text='Напряжение питания, для которого актуальна схема', on_delete=django.db.models.deletion.CASCADE, related_name='control_unit_wirings', to='params.powersupplies', verbose_name='Напряжение питания')),
                ('signal_profile', models.ForeignKey(help_text='Профиль сигналов, отражённый на схеме', on_delete=django.db.models.deletion.CASCADE, related_name='control_unit_wirings', to='params.controlunitsignalprofile', verbose_name='Профиль сигналов')),
                ('wiring_diagram', models.ForeignKey(blank=True, help_text='Изображение из медиабиблиотеки (категория «Схема»)', limit_choices_to={'category__code': 'SCHEMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_unit_wirings', to='media_library.medialibraryitem', verbose_name='Изображение схемы')),
            ],
            options={
                'verbose_name': 'Схема подключения БУ',
                'verbose_name_plural': 'Схемы подключения БУ',
                'ordering': ['sorting_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='electriccontrolunitoption',
            name='control_unit_wiring',
            field=models.ForeignKey(blank=True, help_text='Связка БУ+напряжение+профиль+изображение из справочника ControlUnitWiring', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_unit_options', to='electric_actuators.controlunitwiring', verbose_name='Схема подключения'),
        ),
        migrations.AddIndex(
            model_name='controlunitwiring',
            index=models.Index(fields=['control_unit', 'power_supply'], name='electric_ac_control_722b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='controlunitwiring',
            index=models.Index(fields=['signal_profile'], name='electric_ac_signal__fd3373_idx'),
        ),
    ]
