import pathlib

lines = []
lines.append('"""Token tracking and latency estimation."""')
lines.append('import logging')
lines.append('')
lines.append('logger = logging.getLogger(__name__)')
lines.append('')
lines.append('MAX_LATENCY_SAMPLES = 5')
lines.append('')
lines.append('')
lines.append('def save_token_usage(message, usage_data, customer=None):')
lines.append('    from ..models import AITokenUsage')
lines.append('    lat = usage_data.get("latency_ms")')
lines.append('    if lat is None:')
lines.append('        lat = getattr(message, "latency_ms", None)')
lines.append('    t = AITokenUsage(')
lines.append('        message=message,')
lines.append('        customer=customer,')
lines.append('        model=usage_data.get("model", "unknown"),')
lines.append('        prompt_tokens=usage_data.get("prompt_tokens", 0),')
lines.append('        completion_tokens=usage_data.get("completion_tokens", 0),')
lines.append('        reasoning_tokens=usage_data.get("reasoning_tokens", 0),')
lines.append('        total_tokens=usage_data.get("total_tokens", 0),')
lines.append('        cost_estimate=usage_data.get("cost_estimate"),')
lines.append('        latency_ms=lat,')
lines.append('    )')
lines.append('    t.save()')
lines.append('    return t')
lines.append('')
lines.append('')
lines.append('def estimate_cost(model, pt, ct):')
lines.append('    if "deepseek" in model.lower():')
lines.append('        return (pt / 1_000_000) * 2.0 + (ct / 1_000_000) * 8.0')
lines.append('    return 0.0')
lines.append('')
lines.append('')
lines.append('def update_skill_latency(skill, lat):')
lines.append('    if lat is None:')
lines.append('        return')
lines.append('    old_avg = skill.avg_latency_ms or 0')
lines.append('    cnt = min(skill.latency_sample_count or 0, MAX_LATENCY_SAMPLES - 1)')
lines.append('    new_avg = round((old_avg * cnt + lat) / (cnt + 1))')
lines.append('    skill.avg_latency_ms = new_avg')
lines.append('    skill.latency_sample_count = cnt + 1')
lines.append('    skill.save(update_fields=["avg_latency_ms", "latency_sample_count"])')
lines.append('')
lines.append('')
lines.append('def get_estimated_latency(skill):')
lines.append('    return skill.avg_latency_ms or 5000')

pathlib.Path('ai_assistant/services/token_tracker.py').write_text('\n'.join(lines), encoding='utf-8')
print('done')
