# Generated by Django 5.2.4 on 2025-10-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код бренда'),
        ),
        migrations.AddField(
            model_name='brands',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='brands',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='brands',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='producer',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код производителя'),
        ),
        migrations.AddField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name',
            field=models.CharField(default=122, max_length=100, verbose_name='Название производителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='sorting_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
