# Generated by Django 5.2.4 on 2025-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ['sorting_order', 'name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['sorting_order', 'name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='code',
            field=models.CharField(blank=True, help_text='Уникальный код бренда', max_length=50, null=True, verbose_name='Код бренда'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='description',
            field=models.TextField(blank=True, help_text='Описание бренда и его особенностей', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли бренд для использования', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(help_text='Название бренда производителя', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списках', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterModelTable(
            name='brands',
            table='producers_brands',
        ),
    ]
