# Generated by Django 5.2.4 on 2026-05-12 14:57

import core.models.mixins
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(blank=True, help_text='Основное название объекта', max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код объекта', max_length=100, null=True, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('icon', models.CharField(blank=True, help_text='Иконка для отображения (emoji или название класса CSS)', max_length=50, verbose_name='Иконка')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень иерархии')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский тип оборудования для иерархии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.equipmenttype', verbose_name='Родительский тип')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'core_equipmenttype',
                'ordering': ['level', 'sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
