# Generated by Django 5.2.4 on 2026-05-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Django-модель товара этого типа (для цен, документов)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Модель товара'),
        ),
    ]
