# Generated by Django 5.2.7 on 2026-07-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipmenttype_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='filter_endpoint',
            field=models.CharField(blank=True, help_text='Используется AI Assistant (Фаза 3: filter) — TreeProcessor вызывает этот эндпоинт для получения списка вариантов оборудования по извлечённым параметрам. Пример: "/api/pneumatic_actuators/selector/search/". Заполняется только для типов оборудования, участвующих в AI-подборе.', max_length=256, null=True, verbose_name='API-эндпоинт фильтра (AI)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='param_semantics',
            field=models.JSONField(blank=True, help_text='Используется AI Assistant (Фаза 5: compare) для определения направления сравнения требований пользователя с фактическими характеристиками. Пример: {"torque_nm": {"direction": "min", "label": "не менее"}, "ip": {"direction": "min", "label": "не хуже"}}. direction: min (чем больше, тем лучше), max, exact (точное совпадение). Заполняется только для типов оборудования, участвующих в AI-подборе.', null=True, verbose_name='Семантика параметров (AI)'),
        ),
    ]
