# Generated by Django 5.2.7 on 2026-07-27 06:49

from django.db import migrations

# Маппинг кодов AI-типов на коды core-типов
MAPPING = {
    "actuator": "pneumatic-actuator",
    "solenoid": "directional-valve",
    "bkv": "lsb",
    "cable_gland": "cable-gland",
    "filter_regulator": "fr",
    "manual_override": "manual-override",
    "pneumatic_fitting": "fittings",
    # mounting_kit — нет соответствия в core.EquipmentType, пропускается
}


def migrate_ai_equipment_types(apps, schema_editor):
    """Перенос param_semantics и filter_endpoint из AI EquipmentType в core.EquipmentType."""
    AIEquipmentType = apps.get_model('ai_assistant', 'EquipmentType')
    CoreEquipmentType = apps.get_model('core', 'EquipmentType')

    migrated = 0
    skipped_no_match = []
    skipped_no_core = []

    for ai_eq in AIEquipmentType.objects.all():
        core_code = MAPPING.get(ai_eq.code)
        if not core_code:
            skipped_no_match.append(ai_eq.code)
            continue

        try:
            core_eq = CoreEquipmentType.objects.get(code=core_code)
        except CoreEquipmentType.DoesNotExist:
            skipped_no_core.append(ai_eq.code)
            continue

        core_eq.param_semantics = ai_eq.param_semantics or {}
        core_eq.filter_endpoint = ai_eq.filter_endpoint
        core_eq.save(update_fields=['param_semantics', 'filter_endpoint'])
        migrated += 1

    if skipped_no_match:
        print(f"  ⚠️  Пропущены (нет в MAPPING): {skipped_no_match}")
    if skipped_no_core:
        print(f"  ⚠️  Пропущены (нет в core.EquipmentType): {skipped_no_core}")
    print(f"  ✅  Перенесено: {migrated} записей")


def reverse_migrate(apps, schema_editor):
    """Очистка AI-полей (откат)."""
    CoreEquipmentType = apps.get_model('core', 'EquipmentType')
    count = CoreEquipmentType.objects.exclude(
        param_semantics__isnull=True,
        filter_endpoint__isnull=True,
    ).update(param_semantics=None, filter_endpoint=None)
    print(f"  ↩  Очищено: {count} записей")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_ai_fields'),
        ('ai_assistant', '0007_equipmenttype_aiconversation_selection_tree_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_ai_equipment_types, reverse_migrate),
    ]
