# Generated by Django 5.2.4 on 2026-07-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migrate_ai_equipment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='title_template',
            field=models.TextField(blank=True, help_text='Шаблон для generate_title(). Плейсхолдеры: {model_code}, {brand}, {sensor_variety}, {ip}, {exd}, {work_temp_min}, {work_temp_max}, {body_material}, {points}, {weight}, и др. из _get_data_dict(). Оставьте пустым — используется дефолтный шаблон из кода модели.', null=True, verbose_name='Шаблон заголовка'),
        ),
    ]
