# Generated by Django 5.2.7 on 2026-07-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0019_add_prompt_template_to_composition_group'),
        ('core', '0005_add_title_template_to_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='output_schema',
            field=models.ForeignKey(blank=True, help_text='JSON-схема выходного формата (extract)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_types', to='ai_assistant.jsonschema', verbose_name='JSON Schema'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон промпта для extract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_types', to='ai_assistant.aiprompttemplate', verbose_name='Prompt Template'),
        ),
    ]
