# Generated by Django 5.2.4 on 2026-07-30 17:08

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_ai_schema_prompt_to_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(blank=True, help_text='Основное название объекта', max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код объекта', max_length=100, null=True, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('steps_json', models.JSONField(default=dict, help_text='JSON-конфигурация: {"pages": [...], "filters": [...]}. pages: step_number, title, description. filters: param_name, page (номер шага), order, label, default_value.', verbose_name='Шаги мастера (JSON)')),
                ('equipment_type', models.ForeignKey(help_text='Тип оборудования, для которого создан мастер подбора', on_delete=django.db.models.deletion.CASCADE, related_name='selection_wizards', to='core.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Мастер подбора',
                'verbose_name_plural': 'Мастера подбора',
                'db_table': 'core_selectionwizard',
                'ordering': ['sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='active_selection_wizard',
            field=models.ForeignKey(blank=True, help_text='Мастер подбора для страницы каталога', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_types', to='core.selectionwizard', verbose_name='Активный мастер подбора'),
        ),
    ]
