# Generated by Django 5.2.7 on 2026-08-05 11:24

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_selectionwizard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код графа')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('graph_json', models.JSONField(default=dict, help_text='Структура: {"entry_node": "...", "nodes": {...}, "edges": [...]}', verbose_name='Граф (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_graphs', to='core.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Граф вопросов-ответов',
                'verbose_name_plural': 'Графы вопросов-ответов',
                'ordering': ['code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
