# Generated by Django 5.2.7 on 2026-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='ai_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='AI title'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='ai_description',
            field=models.TextField(blank=True, default='', verbose_name='AI description'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='ai_placeholder',
            field=models.CharField(blank=True, default='Опишите, какое оборудование вам нужно...', max_length=200, verbose_name='AI placeholder'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='ai_hints',
            field=models.JSONField(blank=True, default=list, verbose_name='AI hints'),
        ),
    ]
