# Generated by Django 5.2.7 on 2026-08-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ai_catalog_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='ai_placeholder',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='AI placeholder'),
        ),
    ]
