# Generated by Django 5.2.7 on 2026-08-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_equipmenttype_ai_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='output_schema',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='prompt_template',
        ),
    ]
