# Generated by Django 5.2.7 on 2026-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_et_prompt_and_schema_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionGraph',
        ),
    ]
