# Generated by Django 5.2.7 on 2026-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_questiongraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='spec_template',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: группы и поля спецификации (приоритет ниже, чем spec_template серии). Формат: {"groups": [{"key", "title", "fields": [...]}]}. Оставьте пустым — используется реестр SPEC_FIELD_KEYS модели.', verbose_name='Шаблон спецификации'),
        ),
    ]
