# Generated by Django 5.2.4 on 2026-09-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cablegland_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='spec_template',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: спецификация в виде {группа: {подпись: ключ_поля}} (приоритет ниже, чем spec_template серии). Пример: {"Основные": {"IP": "ip"}}. Оставьте пустым — фоллбэк на {model_code} (только артикул).', verbose_name='Шаблон спецификации'),
        ),
    ]
