# Generated by Django 5.2.7 on 2026-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_populate_equipment_type_title_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='list_params',
            field=models.JSONField(blank=True, default=list, help_text='JSON-список ключей полей (реестра *_item_fields), выводимых дополнительными строками в SelectionResultGrid. Пример: ["brand", "ip", "exd_short"]', verbose_name='Список выводимых в списке параметров'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='list_title_template',
            field=models.TextField(blank=True, help_text='Первая строка карточки в списке (SelectionResultGrid). Плейсхолдеры те же, что в title_template. Пусто — фоллбэк на title_template.', null=True, verbose_name='Шаблон заголовка в списке'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='spec_title_template',
            field=models.TextField(blank=True, help_text='Заголовок в .docx-спецификации (item.title). Плейсхолдеры те же, что в title_template. Пусто — фоллбэк на title_template, затем {model_code}.', null=True, verbose_name='Шаблон заголовка в спецификации'),
        ),
    ]
