# Generated by Django 5.2.7 on 2026-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_equipmenttype_list_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='title_template',
            field=models.TextField(blank=True, help_text='Заголовок карточки товара (шапка страницы товара, generate_title()). Приоритет: model_line.title_template → EquipmentType.title_template → фоллбэк {model_code}. Плейсхолдеры: {model_code}, {brand}, {sensor_variety}, {ip}, {exd}, {work_temp_min}, {work_temp_max}, {body_material}, {points}, {weight}, и др. из _get_data_dict().', null=True, verbose_name='Шаблон заголовка'),
        ),
    ]
