# Generated by Django 5.2.4 on 2026-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_equipmenttype_title_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='description_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с description_template.', verbose_name='Переводы шаблона описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='list_title_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с list_title_template.', verbose_name='Переводы заголовка в списке (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='name_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с name_template.', verbose_name='Переводы шаблона названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='spec_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Локаль — внешний ключ: {"ru": {группа: {подпись: ключ}}, "en": {...}, "cn": {...}}. "ru" синхронизируется с spec_template.', verbose_name='Переводы шаблона спецификации (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='spec_title_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с spec_title_template.', verbose_name='Переводы заголовка спецификации (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='title_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с title_template.', verbose_name='Переводы шаблона заголовка (ru/en/cn)'),
        ),
    ]
