# Generated by Django 5.2.4 on 2026-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_backfill_equipmenttype_template_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с description.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с name.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
    ]
