# Generated by Django 4.2.23 on 2026-04-25 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_customers', '0002_userparameter'),
        ('clients', '0004_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(help_text='Уникальный номер заявки (генерируется автоматически)', max_length=50, unique=True, verbose_name='Номер заявки')),
                ('client_request_number', models.CharField(blank=True, help_text='Номер заявки в системе клиента (если предоставлен)', max_length=100, null=True, verbose_name='Номер заявки клиента')),
                ('symbolic_code', models.CharField(blank=True, help_text='Краткое название для идентификации', max_length=100, null=True, verbose_name='Название заявки')),
                ('end_customer', models.CharField(blank=True, help_text='Название конечного заказчика', max_length=200, null=True, verbose_name='Конечный заказчик')),
                ('request_text', models.TextField(blank=True, null=True, verbose_name='Текст запроса')),
                ('request_date', models.DateField(help_text='Дата поступления запроса', verbose_name='Дата запроса')),
                ('required_by_date', models.DateField(blank=True, null=True, verbose_name='Требуемая дата')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('onec_orders', models.TextField(blank=True, help_text='Номера заказов в 1С (можно несколько, разделитель - запятая)', null=True, verbose_name='Заказы в 1С')),
                ('bitrix_deal_id', models.CharField(blank=True, help_text='Идентификатор сделки в Битрикс24', max_length=50, null=True, verbose_name='ID сделки в Битрикс24')),
                ('request_from_client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.company', verbose_name='Компания клиента')),
                ('request_responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.companyperson', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Запрос клиента',
                'verbose_name_plural': 'Запросы клиентов',
                'ordering': ['-request_date', 'request_number'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий к заявке',
                'verbose_name_plural': 'Комментарии к заявкам',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_no', models.IntegerField(default=0, help_text='Номер позиции в заявке (1, 2, 3...)', verbose_name='Номер позиции')),
                ('source_request_line_number', models.IntegerField(blank=True, help_text='Номер строки в первичном тексте запроса', null=True, verbose_name='Номер строки в исходном запросе')),
                ('request_line_ol', models.CharField(blank=True, help_text='Идентификатор (номер) опросного листа', max_length=255, null=True, verbose_name='Номер ОЛ')),
                ('request_line_text', models.TextField(blank=True, help_text='Исходный текст запроса по этой позиции', null=True, verbose_name='Исходный текст')),
                ('version', models.IntegerField(default=1, help_text='Версия требований по этой позиции', verbose_name='Версия')),
                ('is_current', models.BooleanField(default=True, help_text='Отмечает текущую активную версию', verbose_name='Актуальная версия')),
                ('change_comment', models.TextField(blank=True, help_text='Что и почему изменилось в этой версии', null=True, verbose_name='Комментарий к изменению')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('deleted', 'Удалена'), ('replaced', 'Заменена'), ('merged', 'Объединена'), ('split', 'Разделена')], default='active', help_text='Текущий статус позиции', max_length=20, verbose_name='Статус позиции')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Сотрудник, внесший изменение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.companyperson', verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Позиция запроса',
                'verbose_name_plural': 'Позиции запроса',
                'ordering': ['item_no', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название статуса запроса для отображения', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Символьное обозначение статуса запроса (new, in_progress, processed, archived, deleted)', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание статуса запроса для отображения', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Статус запроса клиента',
                'verbose_name_plural': 'Статусы запросов клиентов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа комментария для отображения', max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Код типа комментария (email, internal, change, approval)', max_length=30, unique=True, verbose_name='Символьный код')),
                ('description', models.TextField(blank=True, help_text='Описание типа комментария', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип комментария',
                'verbose_name_plural': 'Типы комментариев',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='RequestItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Код типа подбора (valve_only, actuator_only, full_set)', max_length=50, unique=True, verbose_name='Символьный код')),
                ('name', models.CharField(help_text='Название типа подбора для отображения', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('need_valve_selection', models.BooleanField(default=False, verbose_name='Подбор арматуры')),
                ('need_pneumatic_actuator_selection', models.BooleanField(default=False, verbose_name='Подбор пневмопривода')),
                ('need_electric_actuator_selection', models.BooleanField(default=False, verbose_name='Подбор электропривода')),
                ('need_mounting_kit', models.BooleanField(default=False, verbose_name='Монтажный комплект')),
                ('need_fittings', models.BooleanField(default=False, verbose_name='Фитинги')),
                ('need_positioner', models.BooleanField(default=False, verbose_name='Позиционер/распределитель')),
                ('need_air_preparation', models.BooleanField(default=False, verbose_name='Пневмоподготовка')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип подбора позиции',
                'verbose_name_plural': 'Типы подбора позиций',
                'ordering': ['sort_order', 'symbolic_code'],
            },
        ),
        migrations.CreateModel(
            name='RequestSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_number', models.IntegerField(help_text='Порядковый номер версии (1, 2, 3...)', verbose_name='Номер снапшота')),
                ('snapshot_comment', models.TextField(help_text="Что зафиксировано в этой версии (например, 'Предварительное согласование')", verbose_name='Комментарий')),
                ('is_approved', models.BooleanField(default=False, help_text='Означает, что эта версия согласована с клиентом', verbose_name='Утвержден')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('snapshot_data', models.JSONField(blank=True, help_text='Полная копия всех актуальных версий позиций на момент снимка', null=True, verbose_name='Данные снапшота')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='client_requests.clientrequest', verbose_name='Запрос клиента')),
            ],
            options={
                'verbose_name': 'Снимок заявки',
                'verbose_name_plural': 'Снимки заявок',
                'ordering': ['-snapshot_number'],
                'unique_together': {('request', 'snapshot_number')},
            },
        ),
        migrations.CreateModel(
            name='RequestItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_requests.commenttype', verbose_name='Тип комментария')),
                ('parent_request_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='client_requests.clientrequestcomment', verbose_name='Родительский комментарий к заявке')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='client_requests.clientrequestitem', verbose_name='Позиция запроса')),
                ('resulting_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_comments', to='client_requests.clientrequestitem', verbose_name='Результирующая версия')),
            ],
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='client_requests/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('questionnaire', 'Опросный лист'), ('drawing', 'Чертеж'), ('specification', 'Спецификация'), ('photo', 'Фотография'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип файла')),
                ('description', models.CharField(blank=True, help_text="Например: 'Опросный лист от 10.04.2025'", max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='client_requests.clientrequest', verbose_name='Запрос клиента')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.companyperson', verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_comment', models.TextField(help_text='Что и почему изменилось', verbose_name='Комментарий изменения')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('change_type', models.CharField(choices=[('create_request', 'Создание заявки'), ('add_item', 'Добавление позиции'), ('modify_item', 'Изменение позиции'), ('delete_item', 'Удаление позиции'), ('restore_item', 'Восстановление позиции'), ('create_snapshot', 'Создание снапшота'), ('approve_snapshot', 'Утверждение снапшота'), ('change_status', 'Изменение статуса'), ('general_edit', 'Общее редактирование')], default='general_edit', max_length=30, verbose_name='Тип изменения')),
                ('affected_items', models.ManyToManyField(blank=True, help_text='Позиции, которые были изменены в этом логе', related_name='change_logs', to='client_requests.clientrequestitem', verbose_name='Затронутые позиции')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='client_requests.clientrequest', verbose_name='Запрос клиента')),
                ('resulting_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_change_logs', to='client_requests.requestsnapshot', verbose_name='Результирующий снапшот')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='clientrequestitem',
            name='item_type',
            field=models.ForeignKey(blank=True, help_text='Что нужно подобрать для этой позиции (арматура, привод, полностью)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_requests.requestitemtype', verbose_name='Тип подбора'),
        ),
        migrations.AddField(
            model_name='clientrequestitem',
            name='parent_version',
            field=models.ForeignKey(blank=True, help_text='Ссылка на предыдущую версию этой позиции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='client_requests.clientrequestitem', verbose_name='Предыдущая версия'),
        ),
        migrations.AddField(
            model_name='clientrequestitem',
            name='request_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_lines', to='client_requests.clientrequest', verbose_name='Запрос клиента'),
        ),
        migrations.AddField(
            model_name='clientrequestcomment',
            name='comment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_requests.commenttype', verbose_name='Тип комментария'),
        ),
        migrations.AddField(
            model_name='clientrequestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='client_requests.clientrequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='request_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_requests.clientrequeststatus', verbose_name='Статус запроса'),
        ),
        migrations.CreateModel(
            name='RequestNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_customer_request_number', models.IntegerField(default=0, verbose_name='Счетчик запросов компании')),
                ('project_customer_user_request_number', models.IntegerField(default=0, verbose_name='Счетчик запросов пользователя в компании')),
                ('project_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_counter', to='project_customers.projectcustomer', verbose_name='Компания')),
                ('project_customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_counter', to='project_customers.projectcustomeruser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Нумератор запросов',
                'verbose_name_plural': 'Нумераторы запросов',
                'unique_together': {('project_customer', 'project_customer_user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientrequestitem',
            unique_together={('request_parent', 'item_no', 'version')},
        ),
    ]
