# Generated by Django 5.1.4 on 2025-04-28 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('electric_actuators', '0001_initial'),
        ('params', '0008_controlunitlocationoption_controlunittypeoption_and_more'),
        ('valve_data', '0003_remove_valveline_voltage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Название типа запроса', max_length=100)),
                ('need_valve_selection', models.BooleanField(default=False)),
                ('need_electric_actuator_selection', models.BooleanField(default=False)),
                ('need_pneumatic_actuator_selection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('New', 'Новый'), ('In progress', 'В работе'), ('Processed', 'Обработан'), ('Archived', 'Архив'), ('Deleted', 'Удален')], default='New', max_length=15)),
                ('symbolic_code', models.CharField(blank=True, help_text='Название запроса', max_length=100, null=True)),
                ('request_text', models.TextField(blank=True, help_text='Текст запроса клиента', null=True, verbose_name='Текст запроса клиента')),
                ('request_date', models.DateField()),
                ('request_from_client_company', models.ForeignKey(blank=True, help_text='Выбор компании клиента - для кого подбираем', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.company')),
                ('request_responsible_person', models.ForeignKey(blank=True, help_text='Выбор ответственного лица компании клиента', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.companyperson')),
                ('request_type', models.ForeignKey(blank=True, help_text='Выбор типа запроса - что подбираем', null=True, on_delete=django.db.models.deletion.CASCADE, to='client_requests.clientrequeststype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(default=0, help_text='Номер строки в таблице запроса', verbose_name='Номер строки в таблице запроса')),
                ('request_line_number', models.IntegerField(blank=True, help_text='Номер строки в запросе клиента', null=True, verbose_name='Номер строки в запросе клиента')),
                ('request_line_ol', models.CharField(blank=True, help_text='Идентификатор (номер) ОЛ для этой строки в запросе клиента', max_length=255, null=True, verbose_name='Идентификатор (номер) ОЛ для этой строки в запросе клиента')),
                ('source_request_line_number', models.IntegerField(blank=True, help_text='Номер строки в запросе клиента', null=True, verbose_name='Номер строки в запросе клиента')),
                ('request_line_text', models.TextField(blank=True, help_text='Текстовое описание строки запроса. Сюда можно скопировать текст, чтобы потом перенести в поля требований', null=True, verbose_name='Текстовое описание строки запроса. Сюда можно скопировать текст, чтобы потом перенести в поля требований')),
                ('request_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_lines', to='client_requests.clientrequests', verbose_name='Запрос клиента')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricActuatorRequirement',
            fields=[
                ('time_to_open', models.PositiveIntegerField(blank=True, help_text='Время поворота', null=True)),
                ('rotations_to_open', models.PositiveIntegerField(blank=True, help_text='Скорость', null=True)),
                ('rotations_angle', models.PositiveIntegerField(blank=True, help_text='Угол поворота', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blinker', models.ForeignKey(blank=True, help_text='Блинкер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.blinkeroption')),
                ('body_coating', models.ForeignKey(blank=True, help_text='Покрытие корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.bodycoatingoption')),
                ('cable_glands_holes', models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='electric_actuators.cableglandholesset')),
                ('client_request_line_item_parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electric_actuator_requirement_for_request_line', to='client_requests.clientrequestitem', verbose_name='Запрос клиента')),
                ('control_unit_installed', models.ForeignKey(blank=True, help_text='Блок управления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.controlunitinstalledoption')),
                ('control_unit_location', models.ForeignKey(blank=True, help_text='Размещение блока управления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.controlunitlocationoption')),
                ('control_unit_type', models.ForeignKey(blank=True, help_text='Тип блока управления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.controlunittypeoption')),
                ('digital_protocol_support', models.ForeignKey(blank=True, help_text='Поддержка цифровых протоколов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.digitalprotocolssupportoption')),
                ('end_switches', models.ForeignKey(blank=True, help_text='Концевые выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_end_switches', to='params.switchesparameters')),
                ('exd', models.ForeignKey(blank=True, help_text='Степень exd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.exdoption')),
                ('hand_wheel', models.ForeignKey(blank=True, help_text='Ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.handwheelinstalledoption')),
                ('ip', models.ForeignKey(blank=True, help_text='Степень IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.ipoption')),
                ('mechanical_indicator', models.ForeignKey(blank=True, help_text='Установленный механический индикатор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.mechanicalindicatorinstalledoption')),
                ('mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка', related_name='%(class)s', to='params.mountingplatetypes')),
                ('operating_mode', models.ForeignKey(blank=True, help_text='Режим работы электропривода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.operatingmodeoption')),
                ('output_type', models.ForeignKey(blank=True, help_text='Вид привода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.actuatorgearboxoutputtype')),
                ('rotations_to_open_measure_unit', models.ForeignKey(blank=True, help_text='Ед.изм. времени поворота', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_to_open_measure_unit_%(class)s', to='params.measureunits')),
                ('safety_position', models.ForeignKey(blank=True, help_text='Положение безопасности привода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.safetypositionoption')),
                ('stem_shape', models.ForeignKey(blank=True, help_text='Тип отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.stemshapes')),
                ('stem_size', models.ForeignKey(blank=True, help_text='Размер отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.stemsize')),
                ('temperature', models.ForeignKey(blank=True, help_text='Температурное исполнение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.envtempparameters')),
                ('time_to_open_measure_unit', models.ForeignKey(blank=True, help_text='Ед.изм. времени поворота', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_to_open_measure_unit_%(class)s', to='params.measureunits')),
                ('torque_switches', models.ForeignKey(blank=True, help_text='Ограничители момента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_torque_switches', to='params.switchesparameters')),
                ('way_switches', models.ForeignKey(blank=True, help_text='Путевые выключатели', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_way_switches', to='params.switchesparameters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValveRequirement',
            fields=[
                ('valve_model_dn', models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True)),
                ('valve_model_pn', models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True)),
                ('valve_model_pn_delta', models.PositiveIntegerField(blank=True, help_text='Перепад Dn арматуры', null=True)),
                ('valve_model_torque_to_open', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_torque_to_close', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_rotations_to_open', models.DecimalField(decimal_places=1, help_text='Число оборотов на открытие', max_digits=5)),
                ('valve_stem_retract_type', models.CharField(choices=[('Выдвижной', 'Выдвижной шток'), ('НЕвыдвижной', 'Невыдвижной шток')], default='НЕвыдвижной', max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valve_model_model_line_str', models.CharField(blank=True, help_text='Серия арматуры (строковое значение)', max_length=255, null=True)),
                ('client_request_line_item_parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valve_requirement_for_request_line', to='client_requests.clientrequestitem', verbose_name='Запрос клиента')),
                ('valve_model_model_line', models.ForeignKey(blank=True, help_text='Требования к арматуре', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_model_model_line_for_request_line', to='valve_data.valvemodeldata')),
                ('valve_model_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='%(class)s', to='params.mountingplatetypes')),
                ('valve_model_pn_delta_measure_unit', models.ForeignKey(blank=True, help_text='Единица измерения перепада Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_delta_measure_unit', to='params.measureunits')),
                ('valve_model_pn_measure_unit', models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_measure_unit', to='params.measureunits')),
                ('valve_model_stem_size', models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.stemsize')),
                ('valve_type', models.ForeignKey(blank=True, help_text='Тип арматуры ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_valve_type', to='params.valvetypes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValveSelection',
            fields=[
                ('valve_model_dn', models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True)),
                ('valve_model_pn', models.PositiveIntegerField(blank=True, help_text='Dn арматуры', null=True)),
                ('valve_model_pn_delta', models.PositiveIntegerField(blank=True, help_text='Перепад Dn арматуры', null=True)),
                ('valve_model_torque_to_open', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_torque_to_close', models.DecimalField(decimal_places=0, help_text='Усилие на открытие', max_digits=5)),
                ('valve_model_rotations_to_open', models.DecimalField(decimal_places=1, help_text='Число оборотов на открытие', max_digits=5)),
                ('valve_stem_retract_type', models.CharField(choices=[('Выдвижной', 'Выдвижной шток'), ('НЕвыдвижной', 'Невыдвижной шток')], default='НЕвыдвижной', max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valve_model_model_line_str', models.CharField(blank=True, help_text='Серия арматуры (строковое значение)', max_length=255, null=True)),
                ('client_request_line_item_parent', models.ManyToManyField(related_name='valve_selection_for_request_line', to='client_requests.clientrequestitem', verbose_name='Запрос клиента')),
                ('valve_model_model_line', models.ForeignKey(blank=True, help_text='Требования к арматуре', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valve_selection_for_request_line', to='valve_data.valvemodeldata')),
                ('valve_model_mounting_plate', models.ManyToManyField(blank=True, help_text='Монтажная площадка модели арматуры', related_name='%(class)s', to='params.mountingplatetypes')),
                ('valve_model_pn_delta_measure_unit', models.ForeignKey(blank=True, help_text='Единица измерения перепада Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_delta_measure_unit', to='params.measureunits')),
                ('valve_model_pn_measure_unit', models.ForeignKey(blank=True, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pn_measure_unit', to='params.measureunits')),
                ('valve_model_stem_size', models.ForeignKey(blank=True, help_text='Размер штока модели арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.stemsize')),
                ('valve_type', models.ForeignKey(blank=True, help_text='Тип арматуры ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_valve_type', to='params.valvetypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
