# Generated by Django 5.1.4 on 2025-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequests',
            name='end_customer',
            field=models.CharField(blank=True, help_text='Конечный заказчик', max_length=200, null=True),
        ),
    ]
