# Generated by Django 4.2.23 on 2026-04-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0002_userparameter'),
        ('client_requests', '0002_clientrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='project_customer_request_owner',
            field=models.ForeignKey(blank=True, help_text='Наша компания, которая обрабатывает запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_requests', to='project_customers.projectcustomer', verbose_name='Владелец заявки'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='project_customer_user_request_owner',
            field=models.ForeignKey(blank=True, help_text='Пользователь, создавший заявку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_requests', to='project_customers.projectcustomeruser', verbose_name='Владелец (пользователь)'),
        ),
    ]
