# Generated by Django 5.1.4 on 2025-04-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0002_clientrequests_end_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение статуса запроса ', max_length=30)),
                ('text_description', models.CharField(help_text='Название статуса запроса для отображения', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientrequests',
            name='status',
        ),
        migrations.AddField(
            model_name='clientrequests',
            name='request_status',
            field=models.ForeignKey(blank=True, help_text='Выбор статуса запроса', null=True, on_delete=django.db.models.deletion.CASCADE, to='client_requests.clientrequestsstatus'),
        ),
    ]
