# Generated by Django 4.2.23 on 2026-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0003_clientrequest_project_customer_request_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'ordering': ['-request_date', 'code'], 'verbose_name': 'Запрос клиента', 'verbose_name_plural': 'Запросы клиентов'},
        ),
        migrations.RenameField(
            model_name='clientrequest',
            old_name='symbolic_code',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='clientrequest',
            old_name='onec_orders',
            new_name='orders_1c',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='request_number',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='code',
            field=models.CharField(default=1, help_text='Уникальный номер заявки (генерируется автоматически)', max_length=50, verbose_name='Номер заявки'),
            preserve_default=False,
        ),
    ]
