# Generated by Django 4.2.23 on 2025-07-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0009_climaticequipmentplacementclassifier_and_more'),
        ('client_requests', '0003_clientrequestsstatus_remove_clientrequests_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricactuatorrequirement',
            name='climatic_conditions',
            field=models.ForeignKey(blank=True, help_text='Климатическое исполнение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='params.climaticconditions'),
        ),
    ]
