# Generated by Django 4.2.23 on 2026-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0004_alter_clientrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='client_request_number',
            field=models.CharField(blank=True, help_text='Название заявки в системе клиента (если предоставлен)', max_length=100, null=True, verbose_name='Название заявки клиента'),
        ),
    ]
