# Generated by Django 5.2.7 on 2025-10-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0005_valverequirement_valve_dn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valveselection',
            name='client_request_line_item_parent',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_dn',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_model_model_line',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_model_mounting_plate',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_model_pn_delta_measure_unit',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_model_pn_measure_unit',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_model_stem_size',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_pn',
        ),
        migrations.RemoveField(
            model_name='valveselection',
            name='valve_type',
        ),
        migrations.DeleteModel(
            name='ValveRequirement',
        ),
        migrations.DeleteModel(
            name='ValveSelection',
        ),
    ]
