# Generated by Django 4.2.23 on 2026-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0005_alter_clientrequest_client_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Внутренние заметки'),
        ),
    ]
