# Generated by Django 4.2.23 on 2026-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0006_alter_clientrequest_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequestitem',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
    ]
