# Generated by Django 4.2.23 on 2026-04-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0007_clientrequestitem_sorting_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequestitem',
            name='sorting_order',
        ),
        migrations.RemoveField(
            model_name='clientrequestitem',
            name='source_request_line_number',
        ),
    ]
