# Generated by Django 5.2.4 on 2026-06-03 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0008_remove_clientrequestitem_sorting_order_and_more'),
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('pa_controls', '0032_remove_limitswitchbox_images_and_more'),
        ('params', '0054_alter_threadsize_thread_diameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterRegulatorRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_min', models.IntegerField(default=-60, verbose_name='Мин. температура, °C')),
                ('temp_max', models.IntegerField(default=120, verbose_name='Макс. температура, °C')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Расход не менее, л/мин')),
                ('filtration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тонкость фильтрации, мкм')),
                ('body_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialgeneral', verbose_name='Материал корпуса')),
                ('ip_protection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.ipoption', verbose_name='IP защита')),
                ('request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='client_requests.clientrequestitem', verbose_name='Позиция запроса')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.threadsize', verbose_name='Резьба портов')),
            ],
            options={
                'verbose_name': 'Требование к фильтр-регулятору',
                'verbose_name_plural': 'Требования к фильтр-регуляторам',
            },
        ),
        migrations.CreateModel(
            name='GearboxRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_min', models.IntegerField(default=-60, verbose_name='Мин. температура, °C')),
                ('temp_max', models.IntegerField(default=120, verbose_name='Макс. температура, °C')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('torque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рабочий момент не менее, Нм')),
                ('body_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialgeneral', verbose_name='Материал корпуса')),
                ('ip_protection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.ipoption', verbose_name='IP защита')),
                ('mounting_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.mountingplatetypes', verbose_name='Монтажная площадка')),
                ('request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='client_requests.clientrequestitem', verbose_name='Позиция запроса')),
            ],
            options={
                'verbose_name': 'Требование к редуктору',
                'verbose_name_plural': 'Требования к редукторам',
            },
        ),
        migrations.CreateModel(
            name='LimitSwitchRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_min', models.IntegerField(default=-60, verbose_name='Мин. температура, °C')),
                ('temp_max', models.IntegerField(default=120, verbose_name='Макс. температура, °C')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('points', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Количество датчиков')),
                ('body_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialgeneral', verbose_name='Материал корпуса')),
                ('exd_protection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.exdoption', verbose_name='Взрывозащита')),
                ('ip_protection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.ipoption', verbose_name='IP защита')),
                ('request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='client_requests.clientrequestitem', verbose_name='Позиция запроса')),
                ('sensor_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_controls.limitswitchsensorvariety', verbose_name='Тип сенсора')),
                ('signal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_controls.signaltype', verbose_name='Тип сигнала')),
            ],
            options={
                'verbose_name': 'Требование к БКВ',
                'verbose_name_plural': 'Требования к БКВ',
            },
        ),
    ]
