# Generated by Django 4.2.23 on 2026-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0009_filterregulatorrequirement_gearboxrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterregulatorrequirement',
            name='climatic_designation',
            field=models.CharField(blank=True, help_text='Обозначение по ГОСТ 15150, например «УХЛ4», «У2»', max_length=20, verbose_name='Климатическое исполнение'),
        ),
        migrations.AddField(
            model_name='gearboxrequirement',
            name='climatic_designation',
            field=models.CharField(blank=True, help_text='Обозначение по ГОСТ 15150, например «УХЛ4», «У2»', max_length=20, verbose_name='Климатическое исполнение'),
        ),
        migrations.AddField(
            model_name='limitswitchrequirement',
            name='climatic_designation',
            field=models.CharField(blank=True, help_text='Обозначение по ГОСТ 15150, например «УХЛ4», «У2»', max_length=20, verbose_name='Климатическое исполнение'),
        ),
    ]
