# Generated by Django 5.2.7 on 2026-08-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0010_add_climatic_designation'),
        ('configurator', '0003_parameterrule_combine_parameterrule_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequestitem',
            name='assembly',
            field=models.ForeignKey(blank=True, help_text='Сессия подбора для этой позиции (AssemblyRequirements)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='configurator.assemblyrequirements', verbose_name='Сборка'),
        ),
    ]
