# Generated by Django 5.2.7 on 2026-08-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0011_add_assembly_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequestitem',
            name='assembly',
        ),
    ]
