# Generated by Django 5.2.7 on 2026-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0012_remove_clientrequestitem_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearboxrequirement',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='gearboxrequirement',
            name='ip_protection',
        ),
        migrations.RemoveField(
            model_name='gearboxrequirement',
            name='mounting_plate',
        ),
        migrations.RemoveField(
            model_name='gearboxrequirement',
            name='request_item',
        ),
        migrations.RemoveField(
            model_name='limitswitchrequirement',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='limitswitchrequirement',
            name='exd_protection',
        ),
        migrations.RemoveField(
            model_name='limitswitchrequirement',
            name='ip_protection',
        ),
        migrations.RemoveField(
            model_name='limitswitchrequirement',
            name='request_item',
        ),
        migrations.RemoveField(
            model_name='limitswitchrequirement',
            name='sensor_variety',
        ),
        migrations.RemoveField(
            model_name='limitswitchrequirement',
            name='signal_type',
        ),
        migrations.DeleteModel(
            name='FilterRegulatorRequirement',
        ),
        migrations.DeleteModel(
            name='GearboxRequirement',
        ),
        migrations.DeleteModel(
            name='LimitSwitchRequirement',
        ),
    ]
