# Generated by Django 5.2.4 on 2025-09-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Общее название типа материала', max_length=50, verbose_name='Общее название типа материала')),
            ],
            options={
                'verbose_name': 'Общее название типа материала',
                'verbose_name_plural': 'Общие названия типов материалов',
                'ordering': ['symbolic_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название стандарта')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код стандарта')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание стандарта')),
            ],
            options={
                'verbose_name': 'Стандарт материала',
                'verbose_name_plural': 'Стандарты материалов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGeneralMoreDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение уточненного типа материала', max_length=50, verbose_name='Символьное обозначение уточненного типа материала')),
                ('text_description', models.CharField(blank=True, help_text='Текстовое обозначение уточненного типа материала', max_length=200, verbose_name='Текстовое обозначение уточненного типа материала')),
                ('full_description', models.CharField(blank=True, help_text='Текстовое описание уточненного типа материала и его свойств', max_length=200, verbose_name='Текстовое описание уточненного типа материала и его свойств')),
                ('temp_min', models.IntegerField(default=-50, help_text='Минимальная рабочая температура уточненного типа материала, °С', verbose_name='Минимальная рабочая температура уточненного типа материала, °С')),
                ('temp_max', models.IntegerField(default=150, help_text='Максимальная рабочая температура уточненного типа материала, °С', verbose_name='Максимальная рабочая температура уточненного типа материала, °С')),
                ('material_general', models.ForeignKey(help_text='Общая категория материала', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_materials', to='materials.materialgeneral', verbose_name='Общий тип материала')),
            ],
            options={
                'verbose_name': 'Уточненный тип материала',
                'verbose_name_plural': 'Уточненные типы материалов',
                'ordering': ['symbolic_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSpecified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(blank=True, help_text='Автоматически генерируется из основной кодировки', max_length=50, verbose_name='Символьное обозначение')),
                ('text_description', models.CharField(blank=True, max_length=200, verbose_name='Текстовое обозначение')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('temp_min', models.IntegerField(default=-50, verbose_name='Минимальная температура, °C')),
                ('temp_max', models.IntegerField(default=150, verbose_name='Максимальная температура, °C')),
                ('material_detailed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specified_materials', to='materials.materialgeneralmoredetailed', verbose_name='Уточненный тип материала')),
                ('material_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specified_materials', to='materials.materialgeneral', verbose_name='Общий тип материала')),
            ],
            options={
                'verbose_name': 'Спецификация материала',
                'verbose_name_plural': 'Спецификации материалов',
                'ordering': ['material_general', 'material_detailed', 'symbolic_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_type', models.CharField(choices=[('exact', 'Точный аналог'), ('similar', 'Похожий аналог'), ('replacement', 'Замена в определенных условиях')], max_length=20, verbose_name='Тип аналогии')),
                ('confidence_level', models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=80, verbose_name='Уровень уверенности')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия замены')),
                ('analog_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_for', to='materials.materialspecified', verbose_name='Материал-аналог')),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_analogs', to='materials.materialspecified', verbose_name='Исходный материал')),
            ],
            options={
                'verbose_name': 'Аналог материала',
                'verbose_name_plural': 'Аналоги материалов',
                'ordering': ['source_material', '-confidence_level'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код в стандарте')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная кодировка')),
                ('material_specified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_codes', to='materials.materialspecified', verbose_name='Спецификация материала')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_codes', to='materials.materialstandard', verbose_name='Стандарт')),
            ],
            options={
                'verbose_name': 'Код материала в стандарте',
                'verbose_name_plural': 'Коды материалов в стандартах',
                'ordering': ['standard', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='materialspecified',
            index=models.Index(fields=['material_general'], name='materials_m_materia_4529ad_idx'),
        ),
        migrations.AddIndex(
            model_name='materialspecified',
            index=models.Index(fields=['material_detailed'], name='materials_m_materia_212286_idx'),
        ),
        migrations.AddIndex(
            model_name='materialspecified',
            index=models.Index(fields=['symbolic_code'], name='materials_m_symboli_c0f9ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialanalog',
            unique_together={('source_material', 'analog_material')},
        ),
        migrations.AlterUniqueTogether(
            name='materialcode',
            unique_together={('material_specified', 'standard', 'code')},
        ),
    ]
