# Generated by Django 4.2.23 on 2025-09-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialChemicalResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistance_type', models.CharField(choices=[('4', 'Отлично'), ('3', 'Хорошо'), ('2', 'Нежелательно, но возможно'), ('1', 'Не применяется'), ('0', 'Не указано')], default='0', max_length=20, verbose_name='Применимость')),
            ],
            options={
                'verbose_name': 'Возможность применения материала в рабочей среде',
                'verbose_name_plural': 'Применимость материалов к рабочей среде',
            },
        ),
        migrations.CreateModel(
            name='WorkingMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Название рабочей среды', max_length=500, verbose_name='Название рабочей среды')),
            ],
            options={
                'verbose_name': 'Название рабочей среды',
                'verbose_name_plural': 'Название рабочей среды',
                'ordering': ['symbolic_code'],
            },
        ),
        migrations.RemoveField(
            model_name='materialgeneralmoredetailed',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='materialgeneralmoredetailed',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='materialgeneralmoredetailed',
            name='temp_min',
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='work_temp_max',
            field=models.IntegerField(default=150, help_text='Максимальная рабочая температура уточненного типа материала, °С', verbose_name='Максимальная рабочая температура уточненного типа материала, °С'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='work_temp_min',
            field=models.IntegerField(default=-50, help_text='Минимальная рабочая температура уточненного типа материала, °С', verbose_name='Минимальная рабочая температура уточненного типа материала, °С'),
        ),
        migrations.AlterField(
            model_name='materialgeneralmoredetailed',
            name='symbolic_code',
            field=models.CharField(help_text='Название уточненного типа материала', max_length=50, verbose_name='Название уточненного типа материала'),
        ),
        migrations.AlterField(
            model_name='materialgeneralmoredetailed',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание уточненного типа материала', max_length=200, verbose_name='Текстовое описание уточненного типа материала'),
        ),
        migrations.AlterField(
            model_name='materialspecified',
            name='temp_max',
            field=models.IntegerField(default=150, verbose_name='Максимальная температура уточненного типа материала, °С'),
        ),
        migrations.AlterField(
            model_name='materialspecified',
            name='temp_min',
            field=models.IntegerField(default=-50, verbose_name='Минимальная температура уточненного типа материала, °С'),
        ),
        migrations.DeleteModel(
            name='MaterialAnalog',
        ),
        migrations.AddField(
            model_name='materialchemicalresistance',
            name='material_specified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_chemical_resistance', to='materials.materialspecified', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='materialchemicalresistance',
            name='working_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_chemical_resistance', to='materials.workingmedium', verbose_name='Рабочая среда'),
        ),
    ]
