# Generated by Django 4.2.23 on 2025-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialchemicalresistance_workingmedium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgeneralmoredetailed',
            name='text_description',
            field=models.TextField(blank=True, help_text='Текстовое описание уточненного типа материала', verbose_name='Текстовое описание уточненного типа материала'),
        ),
        migrations.AlterField(
            model_name='materialspecified',
            name='symbolic_code',
            field=models.CharField(blank=True, help_text='Автоматически генерируется из основной кодировки, если указан стандарт', max_length=50, verbose_name='Символьное обозначение'),
        ),
    ]
