# Generated by Django 4.2.23 on 2025-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materialgeneralmoredetailed_text_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialspecified',
            name='application_text',
            field=models.TextField(blank=True, verbose_name='Где применяется'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='features_text',
            field=models.TextField(blank=True, verbose_name='Особенности'),
        ),
    ]
