# Generated by Django 5.2.7 on 2025-10-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialspecified_application_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgeneral',
            name='code',
            field=models.CharField(blank=True, help_text='Кодтипа материала', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа материала', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='name',
            field=models.CharField(blank=True, help_text='Общее название типа материала', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='materialgeneralmoredetailed',
            name='code',
            field=models.CharField(blank=True, help_text='Код уточненного типа материала', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='materialgeneralmoredetailed',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание уточненного типа материала', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialgeneralmoredetailed',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='materialgeneralmoredetailed',
            name='name',
            field=models.CharField(blank=True, help_text='Название уточненного типа материала', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='materialgeneralmoredetailed',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа материала', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа материала', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='name',
            field=models.CharField(blank=True, help_text='Автоматически генерируется из основной кодировки, если указан стандарт', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='materialspecified',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='materialstandard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='materialstandard',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='workingmedium',
            name='code',
            field=models.CharField(blank=True, help_text='Код рабочей среды', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='workingmedium',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание рабочей среды', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='workingmedium',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='workingmedium',
            name='name',
            field=models.CharField(blank=True, help_text='Название рабочей среды', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='workingmedium',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
    ]
