# Generated by Django 5.2.7 on 2025-10-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialgeneral_code_materialgeneral_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialspecified',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа материала', max_length=100, null=True, verbose_name='Код'),
        ),
    ]
