# Generated by Django 5.2.7 on 2025-10-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_materialspecified_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialspecified',
            name='symbolic_code',
            field=models.CharField(blank=True, help_text='Автоматически генерируется из основной кодировки, если указан стандарт', max_length=100, verbose_name='Символьное обозначение'),
        ),
    ]
