# Generated by Django 5.2.7 on 2025-10-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_materialspecified_symbolic_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialgeneral',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Общее название типа материала', 'verbose_name_plural': 'Общие названия типов материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialgeneralmoredetailed',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Уточненный тип материала', 'verbose_name_plural': 'Уточненные типы материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialspecified',
            options={'ordering': ['sorting_order', 'material_general', 'material_detailed'], 'verbose_name': 'Спецификация материала', 'verbose_name_plural': 'Спецификации материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialstandard',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Стандарт материала', 'verbose_name_plural': 'Стандарты материалов'},
        ),
        migrations.AlterModelOptions(
            name='workingmedium',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Название рабочей среды', 'verbose_name_plural': 'Название рабочей среды'},
        ),
        migrations.RemoveIndex(
            model_name='materialspecified',
            name='materials_m_symboli_c0f9ad_idx',
        ),
        migrations.RemoveField(
            model_name='materialgeneral',
            name='symbolic_code',
        ),
        migrations.RemoveField(
            model_name='materialgeneralmoredetailed',
            name='symbolic_code',
        ),
        migrations.RemoveField(
            model_name='materialgeneralmoredetailed',
            name='text_description',
        ),
        migrations.RemoveField(
            model_name='materialspecified',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='materialspecified',
            name='symbolic_code',
        ),
        migrations.RemoveField(
            model_name='materialspecified',
            name='text_description',
        ),
        migrations.RemoveField(
            model_name='workingmedium',
            name='symbolic_code',
        ),
        migrations.AlterField(
            model_name='materialgeneral',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа материала', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddIndex(
            model_name='materialspecified',
            index=models.Index(fields=['name'], name='materials_m_name_5d78e6_idx'),
        ),
    ]
