# Generated by Django 5.2.7 on 2026-08-13 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0020_remove_cascade_rule'),
        ('client_requests', '0012_remove_clientrequestitem_assembly'),
        ('core', '0011_remove_et_prompt_and_schema_fields'),
        ('sku', '0005_mbom_mbomitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('global_requirements', models.JSONField(blank=True, default=dict, help_text='Общие требования: temperature_min, exd, pressure, ...')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('fixed', 'Зафиксирована')], db_index=True, default='draft', max_length=16)),
                ('revision', models.PositiveIntegerField(blank=True, help_text='Итерация состава внутри одной версии требований', null=True)),
                ('is_template', models.BooleanField(db_index=True, default=False, help_text='Типовая/каталожная сборка')),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('fixation_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition_group', models.ForeignKey(help_text='Шаблон сборки (pa-kit, ea-kit, ...)', on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='ai_assistant.compositiongroup')),
                ('conversation', models.ForeignKey(blank=True, help_text='Сессия AI, если подбор инициирован через LLM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='ai_assistant.aiconversation')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assemblies', to=settings.AUTH_USER_MODEL)),
                ('parent_assembly', models.ForeignKey(blank=True, help_text='Состав-линия: предыдущая сборка под теми же требованиями', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assemblies', to='assemblies.assemblyrequirements')),
                ('requirement_version', models.ForeignKey(blank=True, help_text='Версия требований, которую удовлетворяет сборка (null у шаблона)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='client_requests.clientrequestitem')),
                ('root_node', models.ForeignKey(blank=True, help_text='Точка входа — если указана, дерево обрезается до этой ветки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_point_assemblies', to='ai_assistant.compositiongroup')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
                'db_table': 'assemblies_assembly',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=256)),
                ('level', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('included', models.BooleanField(default=True, help_text='Нужен ли узел в сборке (False → status=skipped)')),
                ('own_requirements', models.JSONField(blank=True, default=dict)),
                ('effective_requirements', models.JSONField(blank=True, default=dict)),
                ('cascade_params', models.JSONField(blank=True, null=True)),
                ('filter_results', models.JSONField(blank=True, null=True)),
                ('selected_product_type', models.CharField(blank=True, max_length=128, null=True)),
                ('selected_product_id', models.IntegerField(blank=True, null=True)),
                ('selected_product_specs', models.JSONField(blank=True, help_text='Фактические характеристики выбранного продукта (снапшот)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('requirements_filled', 'Требования заданы'), ('filtered', 'Варианты получены'), ('selected', 'Выбран'), ('skipped', 'Пропущен (не нужен)')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assemblies.assemblyrequirements')),
                ('composition_group_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_requirements', to='ai_assistant.compositiongroup')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_requirements', to='core.equipmenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assemblies.componentrequirement')),
                ('selected_sku', models.ForeignKey(blank=True, help_text='Выбранная номенклатурная позиция (базовый тип)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_requirements', to='sku.sku')),
            ],
            options={
                'verbose_name': 'Component Requirement',
                'verbose_name_plural': 'Component Requirements',
                'db_table': 'assemblies_component',
                'ordering': ['assembly', 'path'],
            },
        ),
        migrations.AddIndex(
            model_name='assemblyrequirements',
            index=models.Index(fields=['status'], name='assemblies__status_876b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyrequirements',
            index=models.Index(fields=['is_template'], name='assemblies__is_temp_1f9db1_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyrequirements',
            index=models.Index(fields=['requirement_version', 'status'], name='assemblies__require_95973d_idx'),
        ),
        migrations.AddIndex(
            model_name='componentrequirement',
            index=models.Index(fields=['assembly', 'status'], name='assemblies__assembl_c4f3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='componentrequirement',
            index=models.Index(fields=['equipment_type', 'status'], name='assemblies__equipme_2bde6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentrequirement',
            constraint=models.UniqueConstraint(fields=('assembly', 'path'), name='uq_component_assembly_path'),
        ),
    ]
