# Generated by Django 5.2.7 on 2026-08-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentrequirement',
            name='selected_product_id',
        ),
        migrations.RemoveField(
            model_name='componentrequirement',
            name='selected_product_type',
        ),
    ]
