# Generated by Django 4.1.6 on 2025-01-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorGearBoxCombinationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа комбинации привода и редуктора', max_length=2)),
                ('electric_actuator_type', models.CharField(blank=True, help_text='Символьное обозначение     типа комбинации электропривода и редуктора', max_length=2)),
                ('gearbox_type', models.CharField(blank=True, help_text='Символьное обозначение     типа редуктора', max_length=2)),
                ('pneumatic_actuator_type', models.CharField(blank=True, help_text='Символьное обозначение     типа комбинации пневмопривода', max_length=2)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     типа комбинации привода и редуктора', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorGearboxOutputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа привода', max_length=2)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     типа привода', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlinkerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение наличия блинкера', max_length=15)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание наличия блинкера', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BodyCoatingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа защиты     оболочки привода от коррозии', max_length=4)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа защиты     оболочки привода от коррозии', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ControlUnitInstalledOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     установленного на приводе блока управления', max_length=5)),
                ('encoding', models.CharField(help_text='Кодировка         поддерживаемого цифрового протокола', max_length=10)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     установленного на приводе блока управления', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProtocolsSupportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     поддерживаемого цифрового протокола', max_length=4)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     поддерживаемого цифрового протокола', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnvTempParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа температурного исполнения', max_length=4)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     типа температурного исполнения', max_length=200)),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExdOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение вида взрывозащиты', max_length=10)),
                ('exd_full_code', models.CharField(help_text='Полный код вида взрывозащиты', max_length=200)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание вида взрывозащиты', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HandWheelInstalledOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     установленного на приводе ручного дублера', max_length=5)),
                ('encoding', models.CharField(help_text='Кодировка         установленного на приводе ручного дублера', max_length=10)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     установленного на приводе ручного дублера', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IpOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение исполнения IP', max_length=4)),
                ('ip_rank', models.IntegerField(help_text='Приоритет исполнения IP (выше - лучше')),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание исполнения IP', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение единицы измерения', max_length=5)),
                ('measure_type', models.CharField(choices=[('length', 'Длина'), ('weight', 'Вес'), ('square', 'Площадь'), ('volume', 'Объем'), ('torque', 'Усилие'), ('pressure', 'Давление'), ('speed', 'Скорость'), ('temperature', 'Температура'), ('frequency', 'Частота'), ('power', 'Мощность'), ('time', 'Время')], max_length=15)),
                ('symbolic_description', models.CharField(blank=True, help_text='Символьное отображение единицы измерения в документах', max_length=5)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание единицы измерения', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MountingPlateTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа монтажной площадки', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingModeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     режима работы электропривода', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     режима работы электропривода', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа напряжения', max_length=10)),
                ('voltage_value', models.IntegerField()),
                ('voltage_type', models.CharField(choices=[('AC', 'AC - Переменный ток'), ('DC', 'DC - Постоянный ток')], default='AC', max_length=2)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа напряжения', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StemShapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа штока', max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа штока', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchesParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     характеристик выключателей', max_length=15)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     характеристик выключателей', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа резьбы', max_length=5)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа резьбы', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ValveTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа арматуры', max_length=2)),
                ('actuator_gearbox_combinations', models.CharField(help_text='Символьное обозначение     подходящего типа привода и редуктора', max_length=10)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     типа арматуры', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа резьбы', max_length=25)),
                ('thread_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thread_pitch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа резьбы', max_length=200)),
                ('measure_units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.measureunits')),
                ('thread_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.threadtypes')),
            ],
        ),
        migrations.CreateModel(
            name='StemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение размера штока', max_length=20)),
                ('stem_diameter', models.DecimalField(decimal_places=0, max_digits=3)),
                ('chunk_x', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('chunk_y', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('chunk_z', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('thread_pitch', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа штока', max_length=200)),
                ('stem_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.stemshapes')),
            ],
        ),
    ]
