# Generated by Django 5.1.4 on 2025-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_add_params_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwheelinstalledoption',
            name='encoding',
            field=models.CharField(blank=True, help_text='Кодировка         установленного на приводе ручного дублера', max_length=10),
        ),
    ]
