# Generated by Django 5.1.4 on 2025-01-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('params', '0003_alter_handwheelinstalledoption_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа сертификата', max_length=25)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа сертификата', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(blank=True, help_text='Номер сертификата', max_length=200)),
                ('valid_from', models.DateField(blank=True, help_text='Срок действия с', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Срок действия до', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('certificate_type', models.ForeignKey(help_text='Тип сертификата', on_delete=django.db.models.deletion.CASCADE, to='params.certificatetype')),
            ],
        ),
    ]
