# Generated by Django 5.1.4 on 2025-01-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0004_certificatetype_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunits',
            name='symbolic_description',
            field=models.CharField(blank=True, help_text='Символьное отображение единицы измерения в документах', max_length=10),
        ),
    ]
