# Generated by Django 5.1.5 on 2025-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0005_alter_measureunits_symbolic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exdoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение вида взрывозащиты', max_length=50),
        ),
    ]
