# Generated by Django 5.1.4 on 2025-02-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0006_alter_exdoption_symbolic_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicalIndicatorInstalledOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     установленного механического индикатора положения', max_length=15)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     установленного механического индикатора положения', max_length=200)),
            ],
        ),
    ]
