# Generated by Django 5.1.4 on 2025-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0007_mechanicalindicatorinstalledoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlUnitLocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа размещения блока управления', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа размещения блока управления', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ControlUnitTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа блока управления', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа блока управления', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPositionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение положения функции безопасности', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание положения функции безопасности', max_length=200)),
            ],
        ),
    ]
