# Generated by Django 5.2.4 on 2025-07-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0008_controlunitlocationoption_controlunittypeoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='climaticEquipmentPlacementClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     категории размещения оборудования', max_length=4)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     категории размещения оборудования', max_length=200)),
            ],
            options={
                'verbose_name': 'Категория размещения оборудования по ГОСТ 15150-69',
                'verbose_name_plural': 'Категории размещения оборудования по ГОСТ 15150-69',
            },
        ),
        migrations.CreateModel(
            name='climaticZoneClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение     типа климатической зоны', max_length=4)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание     типа климатической зоны', max_length=200)),
            ],
            options={
                'verbose_name': 'Тип климатической зоны размещения оборудования по ГОСТ 15150-69',
                'verbose_name_plural': 'Тип климатической зоны размещения оборудования по ГОСТ 15150-69',
            },
        ),
        migrations.CreateModel(
            name='climaticConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(blank=True, help_text='Символьное обозначение         категории размещения оборудования', max_length=4)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание         категории размещения оборудования', max_length=200)),
                ('min_temp_work', models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Рабочее, мин, °С')),
                ('max_temp_work', models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Рабочее, макс, °С')),
                ('min_temp_extremal', models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Предельное, мин, °С')),
                ('max_temp_extremal', models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Предельное, макс, °С')),
                ('climaticPlacement', models.ForeignKey(help_text='Тип климатической зоны', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.climaticequipmentplacementclassifier')),
                ('climaticZone', models.ForeignKey(help_text='Тип климатической зоны', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.climaticzoneclassifier')),
            ],
            options={
                'verbose_name': 'Значения температуры по климатическому исполнению по ГОСТ 15150-69',
                'verbose_name_plural': 'Значения температуры по климатическому исполнению по ГОСТ 15150-69',
            },
        ),
    ]
