# Generated by Django 5.2.4 on 2025-09-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0009_climaticequipmentplacementclassifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа сертификата', max_length=25, verbose_name='Символьный код')),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа сертификата', max_length=200, verbose_name='Текстовое описание')),
            ],
            options={
                'verbose_name': 'Тип сертификата',
                'verbose_name_plural': 'Типы сертификатов',
                'ordering': ['symbolic_code'],
            },
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='actuatorgearboxcombinationtypes',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип комбинации привода и редуктора', 'verbose_name_plural': 'Типы комбинаций привода и редуктора'},
        ),
        migrations.AlterModelOptions(
            name='actuatorgearboxoutputtype',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип выхода привода/редуктора', 'verbose_name_plural': 'Типы выходов привода/редуктора'},
        ),
        migrations.AlterModelOptions(
            name='blinkeroption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Опция блинкера', 'verbose_name_plural': 'Опции блинкера'},
        ),
        migrations.AlterModelOptions(
            name='bodycoatingoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Опция покрытия корпуса', 'verbose_name_plural': 'Опции покрытия корпуса'},
        ),
        migrations.AlterModelOptions(
            name='climaticconditions',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Значения температуры по климатическому исполнению по ГОСТ 15150-69', 'verbose_name_plural': 'Значения температуры по климатическому исполнению по ГОСТ 15150-69'},
        ),
        migrations.AlterModelOptions(
            name='climaticequipmentplacementclassifier',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Классификатор размещения оборудования', 'verbose_name_plural': 'Классификаторы размещения оборудования'},
        ),
        migrations.AlterModelOptions(
            name='climaticzoneclassifier',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Классификатор климатической зоны', 'verbose_name_plural': 'Классификаторы климатических зон'},
        ),
        migrations.AlterModelOptions(
            name='controlunitinstalledoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Вид блока управления', 'verbose_name_plural': 'Виды блоков управления'},
        ),
        migrations.AlterModelOptions(
            name='controlunitlocationoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Место размещения блока управления', 'verbose_name_plural': 'Места размещения блока управления'},
        ),
        migrations.AlterModelOptions(
            name='controlunittypeoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип блока управления', 'verbose_name_plural': 'Типы блоков управления'},
        ),
        migrations.AlterModelOptions(
            name='digitalprotocolssupportoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Поддерживаемый цифровой протокол', 'verbose_name_plural': 'Поддерживаемые цифровые протоколы'},
        ),
        migrations.AlterModelOptions(
            name='envtempparameters',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Параметр температурной среды', 'verbose_name_plural': 'Параметры температурной среды'},
        ),
        migrations.AlterModelOptions(
            name='exdoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип взрывозащиты', 'verbose_name_plural': 'Типы взрывозащиты'},
        ),
        migrations.AlterModelOptions(
            name='handwheelinstalledoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Опция ручного дублера', 'verbose_name_plural': 'Опции ручных дублеров'},
        ),
        migrations.AlterModelOptions(
            name='ipoption',
            options={'ordering': ['ip_rank'], 'verbose_name': 'Вид защиты IP', 'verbose_name_plural': 'Виды защиты IP'},
        ),
        migrations.AlterModelOptions(
            name='measureunits',
            options={'ordering': ['measure_type', 'symbolic_code'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='mechanicalindicatorinstalledoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Вид механического индикатора', 'verbose_name_plural': 'Виды механических индикаторов'},
        ),
        migrations.AlterModelOptions(
            name='mountingplatetypes',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип монтажной площадки', 'verbose_name_plural': 'Типы монтажных площадок'},
        ),
        migrations.AlterModelOptions(
            name='operatingmodeoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Опция режима работы', 'verbose_name_plural': 'Опции режимов работы'},
        ),
        migrations.AlterModelOptions(
            name='powersupplies',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип напряжения питания', 'verbose_name_plural': 'Типы напряжения питания'},
        ),
        migrations.AlterModelOptions(
            name='safetypositionoption',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Безопасное положение при отсутствии питания', 'verbose_name_plural': 'Безопасные положения при отсутствии питания'},
        ),
        migrations.AlterModelOptions(
            name='stemshapes',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Форма штока', 'verbose_name_plural': 'Формы штоков'},
        ),
        migrations.AlterModelOptions(
            name='stemsize',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Размер штока', 'verbose_name_plural': 'Размеры штоков'},
        ),
        migrations.AlterModelOptions(
            name='switchesparameters',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Вид выключателей', 'verbose_name_plural': 'Параметры выключателей'},
        ),
        migrations.AlterModelOptions(
            name='threadsize',
            options={'ordering': ['thread_type', 'thread_diameter'], 'verbose_name': 'Размер резьбы', 'verbose_name_plural': 'Размеры резьб'},
        ),
        migrations.AlterModelOptions(
            name='threadtypes',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип резьбы', 'verbose_name_plural': 'Типы резьб'},
        ),
        migrations.AlterModelOptions(
            name='valvetypes',
            options={'ordering': ['symbolic_code'], 'verbose_name': 'Тип арматуры', 'verbose_name_plural': 'Типы арматуры'},
        ),
        migrations.AlterField(
            model_name='actuatorgearboxcombinationtypes',
            name='electric_actuator_type',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа комбинации электропривода и редуктора', max_length=2, verbose_name='Тип электропривода'),
        ),
        migrations.AlterField(
            model_name='actuatorgearboxcombinationtypes',
            name='gearbox_type',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа редуктора', max_length=2, verbose_name='Тип редуктора'),
        ),
        migrations.AlterField(
            model_name='actuatorgearboxcombinationtypes',
            name='pneumatic_actuator_type',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа комбинации пневмопривода', max_length=2, verbose_name='Тип пневмопривода'),
        ),
        migrations.AlterField(
            model_name='actuatorgearboxcombinationtypes',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа комбинации привода и редуктора', max_length=2, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='actuatorgearboxcombinationtypes',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа комбинации привода и редуктора', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='actuatorgearboxoutputtype',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа привода', max_length=2, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='actuatorgearboxoutputtype',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа привода', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='blinkeroption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение наличия блинкера', max_length=15, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='blinkeroption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание наличия блинкера', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='bodycoatingoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа защиты оболочки привода от коррозии', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='bodycoatingoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа защиты оболочки привода от коррозии', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='climaticPlacement',
            field=models.ForeignKey(help_text='Тип климатической зоны', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.climaticequipmentplacementclassifier', verbose_name='Категория размещения'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='climaticZone',
            field=models.ForeignKey(help_text='Тип климатической зоны', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.climaticzoneclassifier', verbose_name='Климатическая зона'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='max_temp_extremal',
            field=models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Предельное, макс, °С', verbose_name='Макс. предельная температура, °С'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='max_temp_work',
            field=models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Рабочее, макс, °С', verbose_name='Макс. рабочая температура, °С'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='min_temp_extremal',
            field=models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Предельное, мин, °С', verbose_name='Мин. предельная температура, °С'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='min_temp_work',
            field=models.IntegerField(help_text='Значение температуры воздуха при эксплуатации Рабочее, мин, °С', verbose_name='Мин. рабочая температура, °С'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='symbolic_code',
            field=models.CharField(blank=True, help_text='Символьное обозначение категории размещения оборудования', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание категории размещения оборудования', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='climaticequipmentplacementclassifier',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение категории размещения оборудования', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='climaticequipmentplacementclassifier',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание категории размещения оборудования', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='climaticzoneclassifier',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа климатической зоны', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='climaticzoneclassifier',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа климатической зоны', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='controlunitinstalledoption',
            name='encoding',
            field=models.CharField(help_text='Кодировка поддерживаемого цифрового протокола', max_length=10, verbose_name='Кодировка'),
        ),
        migrations.AlterField(
            model_name='controlunitinstalledoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение установленного на приводе блока управления', max_length=5, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='controlunitinstalledoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание установленного на приводе блока управления', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='controlunitlocationoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа размещения блока управления', max_length=50, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='controlunitlocationoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа размещения блока управления', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='controlunittypeoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа блока управления', max_length=50, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='controlunittypeoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа блока управления', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='digitalprotocolssupportoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение поддерживаемого цифрового протокола', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='digitalprotocolssupportoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание поддерживаемого цифрового протокола', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='envtempparameters',
            name='max_temp',
            field=models.IntegerField(verbose_name='Максимальная температура'),
        ),
        migrations.AlterField(
            model_name='envtempparameters',
            name='min_temp',
            field=models.IntegerField(verbose_name='Минимальная температура'),
        ),
        migrations.AlterField(
            model_name='envtempparameters',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа температурного исполнения', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='envtempparameters',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа температурного исполнения', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='exd_full_code',
            field=models.CharField(help_text='Полный код вида взрывозащиты', max_length=200, verbose_name='Полный код взрывозащиты'),
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение вида взрывозащиты', max_length=50, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание вида взрывозащиты', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='handwheelinstalledoption',
            name='encoding',
            field=models.CharField(blank=True, help_text='Кодировка установленного на приводе ручного дублера', max_length=10, verbose_name='Кодировка'),
        ),
        migrations.AlterField(
            model_name='handwheelinstalledoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение установленного на приводе ручного дублера', max_length=5, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='handwheelinstalledoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание установленного на приводе ручного дублера', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='ipoption',
            name='ip_rank',
            field=models.IntegerField(help_text='Приоритет исполнения IP (выше - лучше)', verbose_name='Ранг IP'),
        ),
        migrations.AlterField(
            model_name='ipoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение исполнения IP', max_length=4, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='ipoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание исполнения IP', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='measure_type',
            field=models.CharField(choices=[('length', 'Длина'), ('weight', 'Вес'), ('square', 'Площадь'), ('volume', 'Объем'), ('torque', 'Усилие'), ('pressure', 'Давление'), ('speed', 'Скорость'), ('temperature', 'Температура'), ('frequency', 'Частота'), ('power', 'Мощность'), ('time', 'Время')], max_length=15, verbose_name='Тип измерения'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение единицы измерения', max_length=5, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='symbolic_description',
            field=models.CharField(blank=True, help_text='Символьное отображение единицы измерения в документах', max_length=10, verbose_name='Символьное обозначение'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание единицы измерения', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='mechanicalindicatorinstalledoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение установленного механического индикатора положения', max_length=15, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='mechanicalindicatorinstalledoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание установленного механического индикатора положения', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='mountingplatetypes',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа монтажной площадки', max_length=20, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='operatingmodeoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение режима работы электропривода', max_length=50, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='operatingmodeoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание режима работы электропривода', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='powersupplies',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа напряжения', max_length=10, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='powersupplies',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа напряжения', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='powersupplies',
            name='voltage_type',
            field=models.CharField(choices=[('AC', 'AC - Переменный ток'), ('DC', 'DC - Постоянный ток')], default='AC', max_length=2, verbose_name='Тип напряжения'),
        ),
        migrations.AlterField(
            model_name='powersupplies',
            name='voltage_value',
            field=models.IntegerField(verbose_name='Значение напряжения'),
        ),
        migrations.AlterField(
            model_name='safetypositionoption',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение положения функции безопасности', max_length=50, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='safetypositionoption',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание положения функции безопасности', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='stemshapes',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа штока', max_length=20, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='stemshapes',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа штока', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='chunk_x',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Шпонка размер X'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='chunk_y',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Шпонка размер Y'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='chunk_z',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Шпонка размер Z'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='stem_diameter',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Диаметр штока'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='stem_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.stemshapes', verbose_name='Тип штока'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение размера штока', max_length=20, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа штока', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='stemsize',
            name='thread_pitch',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Шаг резьбы'),
        ),
        migrations.AlterField(
            model_name='switchesparameters',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение характеристик выключателей', max_length=15, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='switchesparameters',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание характеристик выключателей', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='measure_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.measureunits', verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа резьбы', max_length=25, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа резьбы', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='thread_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Диаметр резьбы'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='thread_pitch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Шаг резьбы'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='thread_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.threadtypes', verbose_name='Тип резьбы'),
        ),
        migrations.AlterField(
            model_name='threadtypes',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа резьбы', max_length=5, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='threadtypes',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа резьбы', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.AlterField(
            model_name='valvetypes',
            name='actuator_gearbox_combinations',
            field=models.CharField(help_text='Символьное обозначение подходящего типа привода и редуктора', max_length=10, verbose_name='Комбинации привода/редуктора'),
        ),
        migrations.AlterField(
            model_name='valvetypes',
            name='symbolic_code',
            field=models.CharField(help_text='Символьное обозначение типа арматуры', max_length=2, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='valvetypes',
            name='text_description',
            field=models.CharField(blank=True, help_text='Текстовое описание типа арматуры', max_length=200, verbose_name='Текстовое описание'),
        ),
        migrations.CreateModel(
            name='CertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(blank=True, help_text='Номер сертификата', max_length=200, verbose_name='Номер сертификата')),
                ('valid_from', models.DateField(blank=True, help_text='Срок действия с', null=True, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, help_text='Срок действия до', null=True, verbose_name='Действует до')),
                ('cert_variety', models.ForeignKey(help_text='Тип сертификата', on_delete=django.db.models.deletion.CASCADE, to='params.certvariety', verbose_name='Тип сертификата')),
            ],
            options={
                'verbose_name': 'Сертификата',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-valid_until', 'cert_variety'],
            },
        ),
        migrations.DeleteModel(
            name='CertificateType',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
