# Generated by Django 4.2.23 on 2025-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0010_certvariety_remove_certificate_certificate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код цвета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hex_code', models.CharField(blank=True, help_text='Например: #FF0000 для красного', max_length=7, verbose_name='HEX код цвета')),
                ('ral_code', models.CharField(blank=True, help_text='Например: RAL 3000', max_length=20, verbose_name='RAL код')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Цвет корпуса',
                'verbose_name_plural': 'Цвета корпусов',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BodyColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа исполнения')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа исполнения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип исполнения цвета корпуса',
                'verbose_name_plural': 'Типы исполнения цвета корпуса',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DnVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Условный диаметр Dn (Ду)', max_length=4, verbose_name='Символьный код Dn (Ду)')),
                ('diameter_metric', models.IntegerField(default=0, verbose_name='Диаметр в мм')),
                ('diameter_inches', models.CharField(max_length=30, verbose_name='Диаметр в дюймах')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Размер DN',
                'verbose_name_plural': 'Размер DN',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='PnVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Давление PN в бар', max_length=4, verbose_name='Символьный код PN')),
                ('pressure_bar', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Давление в бар')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Давление PN',
                'verbose_name_plural': 'Давление PN',
                'ordering': ['sorting_order'],
            },
        ),
    ]
