# Generated by Django 5.2.4 on 2025-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0011_bodycolor_bodycoloroption_dnvariety_pnvariety'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип и толщина покрытия')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа и толщины покрытия')),
                ('thickness', models.IntegerField(default=0, help_text='Толщина покрытия в мкм', verbose_name='Толщина покрытия в мкм')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип и толщина покрытия',
                'verbose_name_plural': 'Типы и толщина покрытия',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OptionVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта исполнения изделия')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код варианта исполнения изделия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип варианта исполнения изделия',
                'verbose_name_plural': 'Типы вариантов исполнения изделия',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SealingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса герметичности арматуры')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код класса герметичности арматуры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Класс герметичности арматуры',
                'verbose_name_plural': 'Классы герметичности арматуры',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValveFunctionVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа назначения арматуры - регулирование и запорное')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа назначения арматуры - регулирование и запорное')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип назначения арматуры - регулирование и запорное',
                'verbose_name_plural': 'Типы назначения арматуры - регулирование и запорное',
                'ordering': ['sorting_order', 'name'],
            },
        ),
    ]
