# Generated by Django 5.2.4 on 2025-09-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0012_coatingvariety_optionvariety_sealingclass_and_more'),
        ('valve_data', '0012_alter_valvelineseries_body_colors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyColorOption',
        ),
        migrations.AddField(
            model_name='sealingclass',
            name='valve_function_variety',
            field=models.ForeignKey(help_text='Тип назначения арматуры - регулирование и запорное', on_delete=django.db.models.deletion.CASCADE, related_name='sealing_class_valve_function_variety', to='params.valvefunctionvariety', verbose_name='Тип назначения арматуры - регулирование и запорное'),
        ),
    ]
