# Generated by Django 5.2.4 on 2025-09-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0013_delete_bodycoloroption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sealingclass',
            name='valve_function_variety',
        ),
        migrations.AddField(
            model_name='sealingclass',
            name='valve_function_variety',
            field=models.ManyToManyField(help_text='Тип назначения арматуры - регулирование и запорное', related_name='sealing_class_valve_function_variety', to='params.valvefunctionvariety', verbose_name='Тип назначения арматуры - регулирование и запорное'),
        ),
    ]
