# Generated by Django 4.2.23 on 2025-09-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0014_remove_sealingclass_valve_function_variety_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyTimePeriodVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Текст продолжительности гарантийного срока')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код текста продолжительности гарантийного срока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Описание продолжительности гарантийного срока',
                'verbose_name_plural': 'Варианты продолжительности гарантийного срока',
                'ordering': ['sorting_order', 'name'],
            },
        ),
    ]
