# Generated by Django 4.2.23 on 2025-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0015_warrantytimeperiodvariety'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveActuationVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа механизма приведения в действие арматуры - ручка/редуктор/привод', max_length=100, verbose_name='Название типа механизма приведения в действие арматуры - ручка/редуктор/привод')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа механизма приведения в действие арматуры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип механизма приведения в действие арматуры - ручка/редуктор/привод',
                'verbose_name_plural': 'Типы механизмов приведения в действие арматуры',
                'ordering': ['sorting_order', 'name'],
            },
        ),
    ]
