# Generated by Django 5.2.4 on 2025-10-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0016_valveactuationvariety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuatorgearboxcombinationtypes',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип комбинации привода и редуктора', 'verbose_name_plural': 'Типы комбинаций привода и редуктора'},
        ),
        migrations.AlterModelOptions(
            name='actuatorgearboxoutputtype',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип выхода привода/редуктора', 'verbose_name_plural': 'Типы выходов привода/редуктора'},
        ),
        migrations.AlterModelOptions(
            name='blinkeroption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Опция блинкера', 'verbose_name_plural': 'Опции блинкера'},
        ),
        migrations.AlterModelOptions(
            name='bodycoatingoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Опция покрытия корпуса', 'verbose_name_plural': 'Опции покрытия корпуса'},
        ),
        migrations.AlterModelOptions(
            name='certvariety',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип сертификата', 'verbose_name_plural': 'Типы сертификатов'},
        ),
        migrations.AlterModelOptions(
            name='climaticconditions',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Значения температуры по климатическому исполнению по ГОСТ 15150-69', 'verbose_name_plural': 'Значения температуры по климатическому исполнению по ГОСТ 15150-69'},
        ),
        migrations.AlterModelOptions(
            name='climaticequipmentplacementclassifier',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Классификатор размещения оборудования', 'verbose_name_plural': 'Классификаторы размещения оборудования'},
        ),
        migrations.AlterModelOptions(
            name='climaticzoneclassifier',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Классификатор климатической зоны', 'verbose_name_plural': 'Классификаторы климатических зон'},
        ),
        migrations.AlterModelOptions(
            name='controlunitinstalledoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Вид блока управления', 'verbose_name_plural': 'Виды блоков управления'},
        ),
        migrations.AlterModelOptions(
            name='controlunitlocationoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Место размещения блока управления', 'verbose_name_plural': 'Места размещения блока управления'},
        ),
        migrations.AlterModelOptions(
            name='controlunittypeoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип блока управления', 'verbose_name_plural': 'Типы блоков управления'},
        ),
        migrations.AlterModelOptions(
            name='digitalprotocolssupportoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Поддерживаемый цифровой протокол', 'verbose_name_plural': 'Поддерживаемые цифровые протоколы'},
        ),
        migrations.AlterModelOptions(
            name='envtempparameters',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Параметр температурной среды', 'verbose_name_plural': 'Параметры температурной среды'},
        ),
        migrations.AlterModelOptions(
            name='exdoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип взрывозащиты', 'verbose_name_plural': 'Типы взрывозащиты'},
        ),
        migrations.AlterModelOptions(
            name='handwheelinstalledoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Опция ручного дублера', 'verbose_name_plural': 'Опции ручных дублеров'},
        ),
        migrations.AlterModelOptions(
            name='ipoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Вид защиты IP', 'verbose_name_plural': 'Виды защиты IP'},
        ),
        migrations.AlterModelOptions(
            name='mechanicalindicatorinstalledoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Вид механического индикатора', 'verbose_name_plural': 'Виды механических индикаторов'},
        ),
        migrations.AlterModelOptions(
            name='mountingplatetypes',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип монтажной площадки', 'verbose_name_plural': 'Типы монтажных площадок'},
        ),
        migrations.AlterModelOptions(
            name='operatingmodeoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Опция режима работы', 'verbose_name_plural': 'Опции режимов работы'},
        ),
        migrations.AlterModelOptions(
            name='powersupplies',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип напряжения питания', 'verbose_name_plural': 'Типы напряжения питания'},
        ),
        migrations.AlterModelOptions(
            name='safetypositionoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Безопасное положение при отсутствии питания', 'verbose_name_plural': 'Безопасные положения при отсутствии питания'},
        ),
        migrations.AlterModelOptions(
            name='stemshapes',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Форма штока', 'verbose_name_plural': 'Формы штоков'},
        ),
        migrations.AlterModelOptions(
            name='stemsize',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Размер штока', 'verbose_name_plural': 'Размеры штоков'},
        ),
        migrations.AlterModelOptions(
            name='switchesparameters',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Вид выключателей', 'verbose_name_plural': 'Параметры выключателей'},
        ),
        migrations.AlterModelOptions(
            name='threadsize',
            options={'ordering': ['thread_type', 'thread_diameter'], 'verbose_name': 'Тип и размер резьбы', 'verbose_name_plural': 'Типы и размеры резьб'},
        ),
        migrations.AlterModelOptions(
            name='threadtypes',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип резьбы', 'verbose_name_plural': 'Типы резьб'},
        ),
        migrations.AlterModelOptions(
            name='valvetypes',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип арматуры', 'verbose_name_plural': 'Типы арматуры'},
        ),
        migrations.AddField(
            model_name='actuatorgearboxcombinationtypes',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа комбинации привода и редуктора', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxcombinationtypes',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа комбинации привода и редуктора', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxcombinationtypes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxcombinationtypes',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа комбинации привода и редуктора', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxcombinationtypes',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxoutputtype',
            name='code',
            field=models.CharField(blank=True, help_text='Код обозначения типа выхода привода/редуктора', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxoutputtype',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа выхода привода/редуктора', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxoutputtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxoutputtype',
            name='name',
            field=models.CharField(blank=True, help_text='Название обозначения типа выхода привода/редуктора', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='actuatorgearboxoutputtype',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='blinkeroption',
            name='code',
            field=models.CharField(blank=True, help_text='Код наличия блинкера', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='blinkeroption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание наличия блинкера', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blinkeroption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='blinkeroption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение наличия блинкера', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='blinkeroption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='bodycoatingoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа покрытия оболочки привода от коррозии', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='bodycoatingoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа покрытия оболочки привода от коррозии', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bodycoatingoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='bodycoatingoption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное название типа покрытия оболочки привода от коррозии', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='bodycoatingoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='certdata',
            name='code',
            field=models.CharField(blank=True, help_text='Код сертификата', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='certdata',
            name='description',
            field=models.TextField(blank=True, help_text='Номер сертификата', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='certdata',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='certdata',
            name='name',
            field=models.CharField(blank=True, help_text='Название сертификата', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='certdata',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='certvariety',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа сертификата', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='certvariety',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа сертификата', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='certvariety',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='certvariety',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа сертификата', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='certvariety',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='climaticconditions',
            name='code',
            field=models.CharField(blank=True, help_text='Код значения температуры по климатическому исполнению', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='climaticconditions',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание значения температуры по климатическому исполнению', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='climaticconditions',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='climaticconditions',
            name='name',
            field=models.CharField(blank=True, help_text='Название значения температуры по климатическому исполнению', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='climaticconditions',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='climaticequipmentplacementclassifier',
            name='code',
            field=models.CharField(blank=True, help_text='Код категории размещения оборудования', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='climaticequipmentplacementclassifier',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание категории размещения оборудования', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='climaticequipmentplacementclassifier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='climaticequipmentplacementclassifier',
            name='name',
            field=models.CharField(blank=True, help_text='Название категории размещения оборудования', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='climaticequipmentplacementclassifier',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='climaticzoneclassifier',
            name='code',
            field=models.CharField(blank=True, help_text='Код климатической зоны', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='climaticzoneclassifier',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа климатической зоны', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='climaticzoneclassifier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='climaticzoneclassifier',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа климатической зоны', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='climaticzoneclassifier',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='controlunitinstalledoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код обозначения установленного на приводе блока управления', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='controlunitinstalledoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание установленного на приводе блока управления', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='controlunitinstalledoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='controlunitinstalledoption',
            name='name',
            field=models.CharField(blank=True, help_text='Название обозначения установленного на приводе блока управления', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='controlunitinstalledoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='controlunitlocationoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа размещения блока управления', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='controlunitlocationoption',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='controlunitlocationoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='controlunitlocationoption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа размещения блока управления', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='controlunitlocationoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='controlunittypeoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа размещения блока управления', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='controlunittypeoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа блока управления', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='controlunittypeoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='controlunittypeoption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа размещения блока управления', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='controlunittypeoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='digitalprotocolssupportoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код обозначения поддерживаемого цифрового протокола', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='digitalprotocolssupportoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание поддерживаемого цифрового протокола', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='digitalprotocolssupportoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='digitalprotocolssupportoption',
            name='name',
            field=models.CharField(blank=True, help_text='Название обозначения поддерживаемого цифрового протокола', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='digitalprotocolssupportoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='dnvariety',
            name='code',
            field=models.CharField(blank=True, help_text='Символьный код Dn (Ду)', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='dnvariety',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='dnvariety',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='dnvariety',
            name='name',
            field=models.CharField(blank=True, help_text='Условный диаметр Dn (Ду)', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='envtempparameters',
            name='code',
            field=models.CharField(blank=True, help_text='Код температурного исполнения', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='envtempparameters',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа температурного исполнения', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='envtempparameters',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='envtempparameters',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа температурного исполнения', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='envtempparameters',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код вида взрывозащиты', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание вида взрывозащиты', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение вида взрывозащиты', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='handwheelinstalledoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа установленного на приводе ручного дублера', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='handwheelinstalledoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа установленного на приводе ручного дублера', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='handwheelinstalledoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='handwheelinstalledoption',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа установленного на приводе ручного дублера', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handwheelinstalledoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='ipoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код исполнения IP', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='ipoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание исполнения IP', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ipoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='ipoption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение исполнения IP', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ipoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='measureunits',
            name='code',
            field=models.CharField(blank=True, help_text='Код единицы измерения', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='measureunits',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание единицы измерения', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='measureunits',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='measureunits',
            name='name',
            field=models.CharField(blank=True, help_text='Название единицы измерения', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='measureunits',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='mechanicalindicatorinstalledoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код обозначения установленного механического индикатора положения', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='mechanicalindicatorinstalledoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание установленного механического индикатора положения', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mechanicalindicatorinstalledoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mechanicalindicatorinstalledoption',
            name='name',
            field=models.CharField(blank=True, help_text='Название обозначения установленного механического индикатора положения', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mechanicalindicatorinstalledoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='mountingplatetypes',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа монтажной площадки', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='mountingplatetypes',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа монтажной площадки', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mountingplatetypes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mountingplatetypes',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа монтажной площадки', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mountingplatetypes',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='operatingmodeoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа режима работы электропривода', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='operatingmodeoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа режима работы электропривода', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='operatingmodeoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='operatingmodeoption',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа режима работы электропривода', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='operatingmodeoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='pnvariety',
            name='code',
            field=models.CharField(blank=True, help_text='Символьный код PN', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='pnvariety',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pnvariety',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='pnvariety',
            name='name',
            field=models.CharField(blank=True, help_text='Название давления PN в бар', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='powersupplies',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа напряжения', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='powersupplies',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='powersupplies',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='powersupplies',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение типа напряжения', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='powersupplies',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='safetypositionoption',
            name='code',
            field=models.CharField(blank=True, help_text='Код обозначение положения функции безопасности', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='safetypositionoption',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание положения функции безопасности', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='safetypositionoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='safetypositionoption',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение положения функции безопасности', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='safetypositionoption',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='stemshapes',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа штока', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='stemshapes',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа штока', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stemshapes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='stemshapes',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа штока', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stemshapes',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='stemsize',
            name='code',
            field=models.CharField(blank=True, help_text='Код типоразмера штока', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='stemsize',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типоразмера штока', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stemsize',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='stemsize',
            name='name',
            field=models.CharField(blank=True, help_text='Название типоразмера штока', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stemsize',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='switchesparameters',
            name='code',
            field=models.CharField(blank=True, help_text='Код характеристик выключателей', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='switchesparameters',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание характеристик выключателей', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='switchesparameters',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='switchesparameters',
            name='name',
            field=models.CharField(blank=True, help_text='Символьное обозначение характеристик выключателей', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='switchesparameters',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='threadsize',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа и размера резьбы', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='threadsize',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа и размера резьбы', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='threadsize',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='threadsize',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа и размера резьбы', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='threadsize',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='threadtypes',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа резьбы', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='threadtypes',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа резьбы', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='threadtypes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='threadtypes',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа резьбы', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='threadtypes',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='valvetypes',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа арматуры', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='valvetypes',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа арматуры', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='valvetypes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='valvetypes',
            name='name',
            field=models.CharField(blank=True, help_text='Название типа арматуры', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='valvetypes',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='dnvariety',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='pnvariety',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
    ]
