# Generated by Django 5.2.7 on 2025-10-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0017_alter_actuatorgearboxcombinationtypes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exdoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
    ]
