# Generated by Django 4.2.23 on 2025-11-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0019_alter_bodycolor_options_alter_measureunits_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Общее название температурного диапазона', max_length=100, verbose_name='Название диапазона')),
                ('temp_min', models.IntegerField(help_text='Минимальная рабочая температура, °С', verbose_name='Т мин, °С')),
                ('temp_max', models.IntegerField(help_text='Максимальная рабочая температура, °С', verbose_name='Т макс, °С')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Температурный диапазон',
                'verbose_name_plural': 'Температурные диапазоны',
                'ordering': ['sorting_order'],
            },
        ),
    ]
