# Generated by Django 4.2.23 on 2025-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0020_temperaturerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticAirSupplyPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Давление в пневмосистеме, бар', max_length=10, verbose_name='Давление, бар')),
                ('code', models.CharField(blank=True, help_text='Код давления в пневмосистеме, бар', max_length=10, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание давления питания', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('pressure_bar', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Давление в бар')),
            ],
            options={
                'verbose_name': 'Давление питания в пневмосистеме',
                'verbose_name_plural': 'Давления питания в пневмосистеме',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.DeleteModel(
            name='TemperatureRange',
        ),
    ]
