# Generated by Django 4.2.23 on 2025-11-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0022_create_initial_pneumatic_pressure_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название пневмоподключения', max_length=10, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код пневмоподключения', max_length=10, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание пневмоподключения', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип пневмоподключение',
                'verbose_name_plural': 'Типы пневмоподключений',
                'ordering': ['sorting_order'],
            },
        ),
    ]
