# Generated by Django 4.2.23 on 2025-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0023_pneumaticconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticconnection',
            name='name',
            field=models.CharField(help_text='Название пневмоподключения', max_length=50, verbose_name='Название'),
        ),
    ]
