# Generated by Django 4.2.23 on 2025-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0024_alter_pneumaticconnection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticconnection',
            name='code',
            field=models.CharField(blank=True, help_text='Код пневмоподключения', max_length=20, null=True, verbose_name='Код'),
        ),
    ]
