# Generated by Django 4.2.23 on 2026-01-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0025_alter_pneumaticconnection_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSizeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название набора резьбовых соединений', max_length=200, verbose_name='Название набора')),
                ('code', models.CharField(blank=True, help_text='Код набора резьбовых соединений', max_length=50, null=True, verbose_name='Код набора')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание набора резьбовых соединений', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Набор резьбовых соединений',
                'verbose_name_plural': 'Наборы резьбовых соединений',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThreadSizeSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Порядковый номер в наборе', verbose_name='Позиция в наборе')),
                ('thread_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_items', to='params.threadsizeset', verbose_name='Набор резьбовых соединений')),
                ('thread_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.threadsize', verbose_name='Резьбовое соединение')),
            ],
            options={
                'verbose_name': 'Элемент набора резьб',
                'verbose_name_plural': 'Элементы наборов резьб',
                'ordering': ['thread_set', 'position'],
                'unique_together': {('thread_set', 'position')},
            },
        ),
    ]
