# Generated by Django 4.2.23 on 2026-02-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0026_threadsizeset_threadsizesetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersupplies',
            name='encoding',
            field=models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=20, verbose_name='Кодировка'),
        ),
    ]
