# Generated by Django 5.2.4 on 2026-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0027_powersupplies_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlunitinstalledoption',
            name='feature_list',
            field=models.JSONField(blank=True, default=list, help_text="Список параметров в формате [{'title': '...', 'value': '...'}]", null=True, verbose_name='Параметры блока управления'),
        ),
    ]
