# Generated by Django 5.2.4 on 2026-02-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0028_controlunitinstalledoption_feature_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlunitinstalledoption',
            name='feature_list',
            field=models.JSONField(blank=True, default=list, help_text="Список параметров в формате [{'display_name': '...', 'value': '...'}]", null=True, verbose_name='Параметры блока управления'),
        ),
    ]
