# Generated by Django 4.2.23 on 2026-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0029_alter_controlunitinstalledoption_feature_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycolor',
            name='ral_name_en',
            field=models.CharField(blank=True, help_text='Color name in english', max_length=100, verbose_name='Name (eng'),
        ),
        migrations.AddField(
            model_name='bodycolor',
            name='ral_name_ru',
            field=models.CharField(blank=True, help_text='Название цвета на русском', max_length=100, verbose_name='Название на русском'),
        ),
    ]
