# Generated by Django 5.2.4 on 2026-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0030_bodycolor_ral_name_en_bodycolor_ral_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadInnerOuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название расположения резьбы - внутренняя или наружная', max_length=30, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа резьбы', max_length=20, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание расположения резьбы - внутренняя или наружная', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Расположения резьбы',
                'verbose_name_plural': 'Расположения резьбы',
                'ordering': ['sorting_order'],
            },
        ),
    ]
