# Generated by Django 5.2.4 on 2026-04-28 15:07

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0031_threadinnerouter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа пыли',
                'verbose_name_plural': 'Группы пыли',
            },
            bases=(models.Model, core.models.mixins.TextDescriptionMixin),
        ),
        migrations.CreateModel(
            name='ExplosionProtectionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('equipment_category', models.CharField(choices=[('MINING', 'Горнорудная'), ('SURFACE', 'Поверхностная')], max_length=20, verbose_name='Категория оборудования')),
                ('zone', models.CharField(blank=True, help_text='Зона взрывоопасности', max_length=10)),
            ],
            options={
                'verbose_name': 'Уровень взрывозащиты',
                'verbose_name_plural': 'Уровни взрывозащиты',
            },
            bases=(models.Model, core.models.mixins.TextDescriptionMixin),
        ),
        migrations.CreateModel(
            name='ExplosionProtectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('GAS', 'Газ'), ('DUST', 'Пыль'), ('BOTH', 'Газ и пыль')], default='GAS', max_length=10, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип взрывозащиты',
                'verbose_name_plural': 'Типы взрывозащиты',
            },
            bases=(models.Model, core.models.mixins.TextDescriptionMixin),
        ),
        migrations.CreateModel(
            name='GasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа газа',
                'verbose_name_plural': 'Группы газов',
            },
            bases=(models.Model, core.models.mixins.TextDescriptionMixin),
        ),
        migrations.CreateModel(
            name='TemperatureClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_class', models.CharField(max_length=5, verbose_name='Класс')),
                ('max_surface_temp', models.IntegerField(verbose_name='Макс. температура поверхности, °C')),
                ('gas_ignition_temp', models.IntegerField(blank=True, null=True, verbose_name='Температура воспламенения газа, °C')),
            ],
            options={
                'verbose_name': 'Температурный класс',
                'verbose_name_plural': 'Температурные классы',
            },
            bases=(models.Model, core.models.mixins.TextDescriptionMixin),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='dust_group',
            field=models.ForeignKey(blank=True, help_text="IIIA, IIIB, IIIC (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dust_group_for', to='params.exdoption', verbose_name='Группа пыли'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='dust_protection_level',
            field=models.ForeignKey(blank=True, help_text="Da, Db, Dc (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dust_level_for', to='params.exdoption', verbose_name='Уровень взрывозащиты (пыль)'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='dust_protection_types',
            field=models.ManyToManyField(blank=True, help_text='Ex t, Ex p, Ex i и т.д.', related_name='dust_protection_for', to='params.exdoption', verbose_name='Типы взрывозащиты (пыль)'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='dust_temperature',
            field=models.IntegerField(blank=True, help_text='Максимальная температура поверхности (например, 85, 95, 100)', null=True, verbose_name='Температура для пыли, °C'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='equipment_type',
            field=models.CharField(choices=[('GAS', 'Газовое оборудование'), ('DUST', 'Пылевое оборудование'), ('BOTH', 'Газовое и пылевое (двойная маркировка)'), ('SIMPLE', 'Простая маркировка')], default='SIMPLE', max_length=10, verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='gas_group',
            field=models.ForeignKey(blank=True, help_text="IIA, IIB, IIC (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_group_for', to='params.exdoption', verbose_name='Группа газа'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='gas_protection_level',
            field=models.ForeignKey(blank=True, help_text="Ga, Gb, Gc (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_level_for', to='params.exdoption', verbose_name='Уровень взрывозащиты (газ)'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='gas_protection_types',
            field=models.ManyToManyField(blank=True, help_text='Ex d, Ex e, Ex i, Ex n, Ex m и т.д.', related_name='gas_protection_for', to='params.exdoption', verbose_name='Типы взрывозащиты (газ)'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='generated_full_code',
            field=models.CharField(blank=True, help_text='Автоматически сгенерированная маркировка', max_length=500, verbose_name='Сгенерированный полный код'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='has_u_suffix',
            field=models.BooleanField(default=False, help_text='Добавить U для компонентов', verbose_name='Только компонент (U)'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='has_x_suffix',
            field=models.BooleanField(default=False, help_text='Добавить X в конце маркировки', verbose_name='Специальные условия (X)'),
        ),
        migrations.AddField(
            model_name='exdoption',
            name='temperature_class',
            field=models.ForeignKey(blank=True, help_text="T1-T6 (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_class_for', to='params.exdoption', verbose_name='Температурный класс'),
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='exd_full_code',
            field=models.CharField(blank=True, help_text='Полный код вида взрывозащиты', max_length=200, verbose_name='Полный код взрывозащиты'),
        ),
    ]
