# Generated by Django 5.2.4 on 2026-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0032_dustgroup_explosionprotectionlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exdoption',
            name='equipment_type',
            field=models.CharField(choices=[('GAS', 'Газовое оборудование'), ('DUST', 'Пылевое оборудование'), ('SIMPLE', 'Простая маркировка')], default='SIMPLE', max_length=10, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='explosionprotectiontype',
            name='category',
            field=models.CharField(choices=[('GAS', 'Газ'), ('DUST', 'Пыль')], default='GAS', max_length=10, verbose_name='Категория'),
        ),
    ]
