# Generated by Django 4.2.23 on 2026-04-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0033_alter_exdoption_equipment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardousGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Текстовое группы взрывоопасной среды', verbose_name='Описание')),
                ('group_type', models.CharField(choices=[('GAS', 'Газ'), ('DUST', 'Пыль')], max_length=5)),
                ('rating', models.IntegerField(help_text='Чем выше рейтинг, тем более опасная среда')),
            ],
            options={
                'ordering': ['group_type', 'rating'],
            },
        ),
    ]
