# Generated by Django 4.2.23 on 2026-04-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0034_hazardousgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='exdoption',
            name='hazardous_group',
            field=models.ForeignKey(blank=True, help_text='Группа взрывоопасной среды (газ и пыль в одном справочнике)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazardous_group', to='params.hazardousgroup', verbose_name='Группа взрывоопасной среды'),
        ),
    ]
