# Generated by Django 5.2.4 on 2026-04-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0035_exdoption_hazardous_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exdoption',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='exdoption',
            name='gas_group',
        ),
        migrations.RemoveField(
            model_name='exdoption',
            name='gas_protection_types',
        ),
        migrations.AddField(
            model_name='exdoption',
            name='explosion_protection_class',
            field=models.ForeignKey(blank=True, help_text="T1-T6 (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explosion_protection_class_for_exd', to='params.explosionprotectiontype', verbose_name='Температурный класс'),
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='temperature_class',
            field=models.ForeignKey(blank=True, help_text="T1-T6 (хранятся как отдельные записи с equipment_type='SIMPLE')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_class_for_exd', to='params.temperatureclass', verbose_name='Температурный класс'),
        ),
    ]
