# Generated by Django 5.2.4 on 2026-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0036_remove_exdoption_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exdoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип взрывозащиты', 'verbose_name_plural': 'Exd Типы взрывозащиты'},
        ),
        migrations.AlterModelOptions(
            name='explosionprotectionlevel',
            options={'verbose_name': 'Уровень взрывозащиты', 'verbose_name_plural': 'Exd Уровни взрывозащиты'},
        ),
        migrations.AlterModelOptions(
            name='explosionprotectiontype',
            options={'verbose_name': 'Тип взрывозащиты', 'verbose_name_plural': 'Exd Типы взрывозащиты'},
        ),
    ]
