# Generated by Django 5.2.4 on 2026-04-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0037_alter_exdoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dustgroup',
            options={'verbose_name': 'Группа пыли', 'verbose_name_plural': 'Exd Группы пыли'},
        ),
        migrations.AlterModelOptions(
            name='gasgroup',
            options={'verbose_name': 'Группа газа', 'verbose_name_plural': 'Exd Группы газов'},
        ),
        migrations.AlterModelOptions(
            name='hazardousgroup',
            options={'ordering': ['group_type', 'rating'], 'verbose_name': 'Группа опасности', 'verbose_name_plural': 'Exd Группа опасности'},
        ),
        migrations.AlterModelOptions(
            name='temperatureclass',
            options={'verbose_name': 'Температурный класс', 'verbose_name_plural': 'Exd Температурные классы'},
        ),
    ]
