# Generated by Django 5.2.4 on 2026-04-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0038_alter_dustgroup_options_alter_gasgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exdoption',
            name='dust_group',
        ),
        migrations.RemoveField(
            model_name='exdoption',
            name='dust_protection_level',
        ),
        migrations.RemoveField(
            model_name='exdoption',
            name='dust_protection_types',
        ),
        migrations.RemoveField(
            model_name='exdoption',
            name='gas_protection_level',
        ),
    ]
