# Generated by Django 5.2.4 on 2026-04-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0039_remove_exdoption_dust_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exdoption',
            name='explosion_protection_class',
            field=models.ForeignKey(blank=True, help_text='Тип взрывозащиты (Ex d, Ex ia...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explosion_protection_class_for_exd', to='params.explosionprotectiontype', verbose_name='Тип взрывозащиты'),
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='temperature_class',
            field=models.ForeignKey(blank=True, help_text='Температурный класс', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_class_for_exd', to='params.temperatureclass', verbose_name='Температурный класс'),
        ),
    ]
