# Generated by Django 5.2.4 on 2026-04-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0040_alter_exdoption_explosion_protection_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exdoption',
            name='explosion_protection_level',
            field=models.ForeignKey(blank=True, help_text='Уровень взрывозащиты(Gb,Db ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explosion_protection_level_for_exd', to='params.explosionprotectionlevel', verbose_name='Уровень взрывозащиты'),
        ),
    ]
