# Generated by Django 5.2.4 on 2026-04-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0041_exdoption_explosion_protection_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explosionprotectiontype',
            options={'verbose_name': 'Разновидность вида взрывозащиты', 'verbose_name_plural': 'Exd Разновидности вида взрывозащиты'},
        ),
        migrations.AlterField(
            model_name='exdoption',
            name='explosion_protection_class',
            field=models.ForeignKey(blank=True, help_text='Разновидность вида взрывозащиты (Ex d, Ex ia...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explosion_protection_class_for_exd', to='params.explosionprotectiontype', verbose_name='Разновидность вида взрывозащиты'),
        ),
    ]
