# Generated by Django 5.2.4 on 2026-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0042_alter_explosionprotectiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explosionprotectiontype',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Разновидность вида взрывозащиты', 'verbose_name_plural': 'Exd Разновидности вида взрывозащиты'},
        ),
        migrations.AddField(
            model_name='explosionprotectiontype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='explosionprotectiontype',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
    ]
