# Generated by Django 5.2.4 on 2026-04-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0043_alter_explosionprotectiontype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplosionProtectionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Общий метод (Вид) взрывозащиты',
                'verbose_name_plural': 'Exd Общие методы (Виды) взрывозащиты',
                'ordering': ['sorting_order'],
            },
        ),

    ]
