# Generated by Django 5.2.4 on 2026-04-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0044_explosionprotectionmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosionprotectiontype',
            name='method',
            field=models.ForeignKey(blank=True, help_text='Разновидность вида взрывозащиты (Ex d, Ex ia...)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explosion_protection_class_for_exd', to='params.explosionprotectionmethod', verbose_name='Разновидность вида взрывозащиты'),
        ),
    ]
