# Generated by Django 5.2.4 on 2026-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0045_explosionprotectiontype_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DustGroup',
        ),
        migrations.DeleteModel(
            name='GasGroup',
        ),
        migrations.AddField(
            model_name='temperatureclass',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatureclass',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='temperatureclass',
            name='name',
            field=models.CharField(default=1, max_length=10, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
