# Generated by Django 5.2.4 on 2026-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0046_delete_dustgroup_delete_gasgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperatureclass',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Температурный класс', 'verbose_name_plural': 'Exd Температурные классы'},
        ),
        migrations.AddField(
            model_name='temperatureclass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='temperatureclass',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
    ]
