# Generated by Django 5.2.4 on 2026-05-04 14:59

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0047_alter_temperatureclass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Символьное обозначение cтепени очистки)', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код cтепени очистки', max_length=50, null=True, verbose_name='Код')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Размер частиц (мкм)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Степень очистки (мкм)',
                'verbose_name_plural': 'Степень очистки (мкм)',
                'ordering': ['sorting_order'],
            },
            bases=(models.Model, core.models.mixins.OptionListToSelectMixin),
        ),
    ]
