# Generated by Django 5.2.4 on 2026-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0048_filtrationgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockingMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название способа блокировки дублера/переключателя', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код способа блокировки дублера/переключателя', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание способа блокировки дублера/переключателя', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Способ блокировки дублера/переключателя',
                'verbose_name_plural': 'Способы блокировки дублера/переключателя',
            },
        ),
    ]
