# Generated by Django 5.2.4 on 2026-05-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0049_lockingmechanism'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiltrationGrade',
        ),
    ]
