# Generated by Django 5.2.4 on 2026-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exdoption',
            name='temperature_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatureclass',
            name='strictness_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
