# Generated by Django 5.2.4 on 2026-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0051_exdoption_temperature_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosionprotectionlevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='explosionprotectionlevel',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
        migrations.AddField(
            model_name='hazardousgroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='hazardousgroup',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
    ]
