# Generated by Django 4.2.23 on 2026-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0052_explosionprotectionlevel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadtypes',
            name='compatible_thread_types',
            field=models.ManyToManyField(blank=True, help_text='Например: G совместим с R (BSPT)', to='params.threadtypes', verbose_name='Совместимые типы резьб'),
        ),
    ]
