# Generated by Django 4.2.23 on 2026-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0053_threadtypes_compatible_thread_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadsize',
            name='thread_diameter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Диаметр резьбы'),
        ),
        migrations.AlterField(
            model_name='threadsize',
            name='thread_pitch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Шаг резьбы'),
        ),
    ]
