# Generated by Django 5.2.7 on 2026-06-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0054_alter_threadsize_thread_diameter_and_more'),
    ]

    operations = [
        # Swap FK values in ClimaticConditions: the column names stay,
        # but the target tables swapped → swap the stored IDs
        migrations.RunSQL(
            sql="""
                UPDATE params_climaticconditions
                SET climaticPlacement_id = climaticZone_id,
                    climaticZone_id = climaticPlacement_id
            """,
            reverse_sql="""
                UPDATE params_climaticconditions
                SET climaticPlacement_id = climaticZone_id,
                    climaticZone_id = climaticPlacement_id
            """,
        ),
        # Rename models (keeps existing data via table rename)
        migrations.RenameModel(
            old_name='ClimaticZoneClassifier',
            new_name='ClimaticPlacementCategory',
        ),
        migrations.RenameModel(
            old_name='ClimaticEquipmentPlacementClassifier',
            new_name='ClimaticZoneCategory',
        ),
        # Update FK fields in ClimaticConditions (now point to correct models)
        migrations.AlterField(
            model_name='climaticconditions',
            name='climaticPlacement',
            field=models.ForeignKey(
                help_text='Категория размещения оборудования',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='climatic_placement_conditions',
                to='params.climaticplacementcategory',
                verbose_name='Категория размещения',
            ),
        ),
        migrations.AlterField(
            model_name='climaticconditions',
            name='climaticZone',
            field=models.ForeignKey(
                help_text='Климатическая зона по ГОСТ',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='climatic_zone_conditions',
                to='params.climaticzonecategory',
                verbose_name='Климатическая зона',
            ),
        ),
    ]