# Generated by Django 5.2.4 on 2026-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0055_rename_climate_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climaticplacementcategory',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Категория размещения оборудования', 'verbose_name_plural': 'Категории размещения оборудования'},
        ),
        migrations.AlterModelOptions(
            name='climaticzonecategory',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Климатическая зона', 'verbose_name_plural': 'Климатические зоны'},
        ),
        migrations.AlterField(
            model_name='climaticplacementcategory',
            name='code',
            field=models.CharField(blank=True, help_text='Код категории размещения: 1, 2, 3, 4, 5', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='climaticplacementcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание категории размещения', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='climaticplacementcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Название категории размещения', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='climaticzonecategory',
            name='code',
            field=models.CharField(blank=True, help_text='Код климатической зоны: u, hl, uhl, t...', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='climaticzonecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание климатической зоны', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='climaticzonecategory',
            name='name',
            field=models.CharField(blank=True, help_text='Название климатической зоны: У, ХЛ, УХЛ, Т...', max_length=100, null=True, verbose_name='Название'),
        ),
    ]
