# Generated by Django 5.2.1 on 2026-06-16 18:36

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0032_remove_limitswitchbox_images_and_more'),
        ('params', '0056_alter_climaticplacementcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnCounterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Механический 187 оборотов»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код, например «MECH-187T»', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Примечания по применению счётчика', verbose_name='Описание')),
                ('counter_type', models.CharField(choices=[('mechanical', 'Механический'), ('electronic', 'Электронный')], default='mechanical', help_text='Механический (кулачковый) или электронный (энкодерный)', max_length=20, verbose_name='Тип счётчика')),
                ('max_turns', models.PositiveSmallIntegerField(help_text='Предел счётчика по оборотам (0 … 32 000). Например: 4, 187, 1600.', verbose_name='Максимальное число оборотов')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках выбора', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли в списках выбора', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Счётчик оборотов',
                'verbose_name_plural': 'Счётчики оборотов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.OptionListToSelectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeedbackSignalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название набора сигналов, например «Стандартные механические SPDT»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код набора, например «MECH-SPDT-STD»', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Состав набора и примечания', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списке наборов сигналов', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли этот набор в списках выбора', verbose_name='Активно')),
                ('sensors', models.ManyToManyField(blank=True, help_text='Конкретные датчики из базы pa_controls. Каждый уже содержит тип сигнала, форму и состояние контакта.', to='pa_controls.sensorcomponent', verbose_name='Датчики в наборе')),
            ],
            options={
                'verbose_name': 'Набор сигналов обратной связи',
                'verbose_name_plural': 'Наборы сигналов обратной связи',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.OptionListToSelectMixin, models.Model),
        ),
    ]
