# Generated by Django 5.2.4 on 2026-06-18 05:22

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0032_remove_limitswitchbox_images_and_more'),
        ('params', '0057_turncounteroption_feedbacksignalset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlUnitSignalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название профиля, например «Стандартные механические SPDT»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код профиля, например «MECH-SPDT-STD»', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Состав профиля и примечания', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списке профилей сигналов', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли этот профиль в списках выбора', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Профиль сигналов БУ',
                'verbose_name_plural': 'Профили сигналов БУ',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.OptionListToSelectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SignalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Конечный Открыто»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код, например «OPEN_LIMIT»', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Примечания к роли сигнала', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках выбора', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли в списках выбора', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Роль сигнала',
                'verbose_name_plural': 'Роли сигналов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ControlUnitSignalProfileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_calibration', models.BooleanField(default=True, help_text='Используется ли заводская калибровка для этого датчика', verbose_name='Стандартная калибровка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='params.controlunitsignalprofile', verbose_name='Профиль сигналов')),
                ('sensor', models.ForeignKey(help_text='Конкретный датчик из базы pa_controls', on_delete=django.db.models.deletion.PROTECT, to='pa_controls.sensorcomponent', verbose_name='Датчик')),
                ('signal_role', models.ForeignKey(help_text='Назначение сигнала: «Конечный Открыто», «Авария» и т.д.', on_delete=django.db.models.deletion.PROTECT, to='params.signalrole', verbose_name='Роль сигнала')),
            ],
            options={
                'verbose_name': 'Запись профиля сигналов',
                'verbose_name_plural': 'Записи профиля сигналов',
                'ordering': ['profile', 'signal_role__sorting_order'],
                'unique_together': {('profile', 'signal_role')},
            },
        ),
    ]
