# Generated by Django 5.2.4 on 2026-06-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0032_remove_limitswitchbox_images_and_more'),
        ('params', '0058_controlunitsignalprofile_signalrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSignalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Дискретный вход БУ, 24В DC, оптронная развязка»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код, например «CU_DI_24V_OPTO»', max_length=50, unique=True, verbose_name='Код')),
                ('signal_category', models.CharField(choices=[('discrete', 'Дискретный'), ('analog', 'Аналоговый')], help_text='Дискретный (вкл/выкл) или аналоговый (4-20мА, 0-10В)', max_length=20, verbose_name='Категория сигнала')),
                ('electrical_specs', models.CharField(blank=True, help_text='Например: «24В DC, оптронная развязка, ~10мА» или «4-20мА, 250Ом»', max_length=255, verbose_name='Электрические характеристики')),
                ('wires_count', models.PositiveSmallIntegerField(default=2, help_text='Количество жил для подключения этого входного сигнала', verbose_name='Кол-во проводов')),
                ('description', models.TextField(blank=True, help_text='Примечания к входному сигналу', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли в списках выбора', verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках выбора', verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Спецификация входного сигнала',
                'verbose_name_plural': 'Спецификации входных сигналов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AddField(
            model_name='signalrole',
            name='direction',
            field=models.CharField(choices=[('input', 'Входной (команда приводу)'), ('output', 'Выходной (от привода)')], default='output', help_text='Входной — команда приводу от контроллера. Выходной — обратная связь от привода.', max_length=10, verbose_name='Направление сигнала'),
        ),
        migrations.AlterField(
            model_name='controlunitsignalprofileentry',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Конкретный датчик из базы pa_controls (только для выходных ролей)', null=True, on_delete=django.db.models.deletion.PROTECT, to='pa_controls.sensorcomponent', verbose_name='Датчик'),
        ),
        migrations.AddField(
            model_name='controlunitsignalprofileentry',
            name='input_signal',
            field=models.ForeignKey(blank=True, help_text='Спецификация входного канала БУ (только для входных ролей)', null=True, on_delete=django.db.models.deletion.PROTECT, to='params.inputsignalspec', verbose_name='Входной сигнал'),
        ),
        migrations.DeleteModel(
            name='FeedbackSignalSet',
        ),
    ]
