# Generated by Django 5.2.7 on 2026-10-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0071_backfill_params_i18n_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlunitsignalprofileentry',
            name='description_i18n',
        ),
        migrations.RemoveField(
            model_name='threadsizesetitem',
            name='description_i18n',
        ),
    ]
