# Generated by Django 5.1.4 on 2025-02-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Рабочее название компании', max_length=200)),
                ('company_name', models.CharField(help_text='Официальное название компании (для документов)', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='ФИО сотрудника', max_length=200)),
                ('phone_number_office', models.CharField(blank=True, help_text='Телефон сотрудника офисный (городской)', max_length=15, null=True)),
                ('phone_number_cell', models.CharField(blank=True, help_text='Телефон сотрудника сотовый', max_length=15, null=True)),
                ('person_email', models.EmailField(blank=True, help_text='Email сотрудника', max_length=255, null=True)),
                ('employee_company', models.ForeignKey(help_text='Компания сотрудника', on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='clients.company')),
            ],
        ),
    ]
