# Generated by Django 5.1.4 on 2025-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyperson',
            name='phone_number_cell',
            field=models.CharField(blank=True, help_text='Телефон сотрудника сотовый', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyperson',
            name='phone_number_office',
            field=models.CharField(blank=True, help_text='Телефон сотрудника офисный (городской)', max_length=50, null=True),
        ),
    ]
