# Generated by Django 5.1.4 on 2025-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_companyperson_phone_number_cell_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyperson',
            options={'verbose_name': 'Ответственный сотрудник клиента', 'verbose_name_plural': 'Ответственные сотрудники клиентов'},
        ),
    ]
