# Generated by Django 4.2.23 on 2026-04-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0002_userparameter'),
        ('clients', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bitrix_id',
            field=models.CharField(blank=True, help_text='Идентификатор партнера в Битрикс24', max_length=50, null=True, verbose_name='ID в Битрикс24'),
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, help_text='Код компании', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание компании', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, help_text='Официальное название компании (для документов)', max_length=500, null=True, verbose_name='Название компании для документов'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, help_text='Рабочее название компании', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='company',
            name='partner_1c',
            field=models.TextField(blank=True, help_text='Идентификатор партнера ID партнера в 1С', null=True, verbose_name='ID в 1С'),
        ),
        migrations.AddField(
            model_name='company',
            name='project_customer_request_owner',
            field=models.ForeignKey(blank=True, help_text='Наша компания, которая обрабатывает запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project_customer', to='project_customers.projectcustomer', verbose_name='Владелец заявки'),
        ),
        migrations.AddField(
            model_name='company',
            name='project_customer_user_request_owner',
            field=models.ForeignKey(blank=True, help_text='Пользователь, создавший заявку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project_customer_user', to='project_customers.projectcustomeruser', verbose_name='Владелец (пользователь)'),
        ),
        migrations.AddField(
            model_name='company',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='bitrix_id',
            field=models.CharField(blank=True, help_text='Идентификатор контактного лица в Битрикс24', max_length=50, null=True, verbose_name='ID в Битрикс24'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='code',
            field=models.CharField(blank=True, help_text='Код сотрудника', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание сотрудника', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='full_name',
            field=models.CharField(blank=True, help_text='ФИО сотрудника', max_length=500, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='name',
            field=models.CharField(blank=True, help_text='Рабочее название сотрудника для выбора в списке', max_length=100, null=True, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='partner_1c',
            field=models.TextField(blank=True, help_text='Идентификатор партнера ID партнера в 1С', null=True, verbose_name='ID в 1С'),
        ),
        migrations.AddField(
            model_name='companyperson',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки'),
        ),
    ]
