# Generated by Django 4.2.23 on 2026-04-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_company_bitrix_id_company_code_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='symbolic_code',
        ),
        migrations.RemoveField(
            model_name='companyperson',
            name='symbolic_code',
        ),
    ]
