# Generated by Django 4.2.23 on 2026-05-29 20:12

from django.db import migrations, models
import storage_manager.fields
import storage_manager.storage_backends.cloudru


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCropSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', storage_manager.fields.ManagedFileField(storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='image_processor/originals/', verbose_name='Оригинал')),
                ('crop_x', models.FloatField(blank=True, null=True, verbose_name='X рамки')),
                ('crop_y', models.FloatField(blank=True, null=True, verbose_name='Y рамки')),
                ('crop_size', models.FloatField(blank=True, null=True, verbose_name='Размер рамки (квадрат)')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=9, verbose_name='Цвет фона')),
                ('result_sm', storage_manager.fields.ManagedFileField(blank=True, null=True, storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='image_processor/results/sm/')),
                ('result_md', storage_manager.fields.ManagedFileField(blank=True, null=True, storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='image_processor/results/md/')),
                ('result_lg', storage_manager.fields.ManagedFileField(blank=True, null=True, storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='image_processor/results/lg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сессия обрезки',
                'verbose_name_plural': 'Сессии обрезки',
            },
        ),
    ]
