# Generated by Django 4.2.23 on 2026-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecropsession',
            name='remove_background',
            field=models.BooleanField(default=False, verbose_name='Убрать фон (нейросеть)'),
        ),
    ]
