# Generated by Django 5.2.4 on 2026-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_imagecropsession_remove_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecropsession',
            name='background_color',
            field=models.CharField(default='#F0F0F0', max_length=9, verbose_name='Цвет фона'),
        ),
    ]
