# pneumatic_actuators/models/py_options_constants.py

SAFETY_POSITION_NC_DEFAULT_CODE = 'nc'
SAFETY_POSITION_NO_DEFAULT_CODE = 'no'
SAFETY_POSITION_FL_DEFAULT_CODE = 'fl'
ACTUATOR_VARIETY_RP_DEFAULT_CODE = 'RP'
ACTUATOR_VARIETY_SY_DEFAULT_CODE = 'SY'

SPRINGS_DA_DEFAULT_CODE = 'DA'
SPRINGS_SR_DEFAULT_CODE = 'SR'