# Generated by Django 5.2.7 on 2026-09-08 12:21

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cert_doc', '0004_alter_certdata_media_item'),
        ('core', '0012_delete_questiongraph'),
        ('media_library', '0015_alter_imagegallerysetitem_image'),
        ('params', '0069_add_way_switch_x2_role'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('sku', '0005_mbom_mbomitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableGlandBodyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=200)),
                ('name', models.CharField(help_text='Название материала корпуса КВ', max_length=50, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код материала корпуса КВ', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание материала корпуса КВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип материала корпуса кабельного ввода',
                'verbose_name_plural': 'Типы материала корпуса кабельных вводов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='CableGlandItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=200)),
                ('name', models.CharField(help_text='Название типа КВ', max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа КВ', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа КВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип кабельного ввода',
                'verbose_name_plural': 'Типы кабельных вводов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='MetalSleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название металлорукава', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код металлорукава', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание металлорукава', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип и диаметр металлорукава',
                'verbose_name_plural': 'Типы и диаметры металлорукавов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='CableGlandBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели корпуса кабельного ввода', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели корпуса кабельного ввода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса КВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('cable_diameter_inner_min', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный диаметр обжимаемого кабеля', max_digits=5, null=True, verbose_name='Кабель мин')),
                ('cable_diameter_inner_max', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Максимальный диаметр обжимаемого кабеля', max_digits=5, null=True, verbose_name='Кабель макс')),
                ('thread_lenght', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Длина резьбы,мм', max_digits=5, null=True, verbose_name='Резьба,мм')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд (производитель) кабельных вводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_brand', to='producers.brands', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Корпус кабельного ввода',
                'verbose_name_plural': 'Корпуса кабельных вводов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandMetalSleeveBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели устройства для подключения металлорукава', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели устройства для подключения металлорукава', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели устройства для подключения металлорукава', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('metal_sleeve_inner', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Внутренний диаметр металлорукава)', max_digits=5, null=True, verbose_name='МР внутр')),
                ('metal_sleeve_outer', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Внешний диаметр металлорукава', max_digits=5, null=True, verbose_name='МР внеш')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд (производитель) кабельных вводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cg_metal_sleeve_body_brand', to='producers.brands', verbose_name='Бренд')),
                ('metal_sleeve', models.ManyToManyField(blank=True, help_text='Металлорукава, подходящие для этого корпуса', to='cable_glands.metalsleeve', verbose_name='Металлорукав')),
            ],
            options={
                'verbose_name': 'Устройство для подключения металлорукава',
                'verbose_name_plural': 'Устройства для подключения металлорукава',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название серии кабельных вводов', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код серии кабельных вводов', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса КВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('name_template', models.TextField(blank=True, help_text='Шаблон для текстового названия серии КВ', null=True, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания КВ', null=True, verbose_name='Шаблон описания')),
                ('model_item_code_template', models.CharField(blank=True, help_text='Шаблон артикула', max_length=500, null=True, verbose_name='Шаблон артикула')),
                ('for_armored_cable', models.BooleanField(blank=True, help_text='Для бронированного кабеля', null=True, verbose_name='Бронированный кабель')),
                ('for_metal_sleeve_cable', models.BooleanField(blank=True, help_text='Для кабеля в металлорукаве', null=True, verbose_name='Металлорукав')),
                ('for_pipelines_cable', models.BooleanField(blank=True, help_text='Для кабеля в трубопроводе', null=True, verbose_name='Трубопровод')),
                ('thread_external', models.BooleanField(blank=True, help_text='Наружная резьба для внешнего присоединения', null=True, verbose_name='Наружная резьба')),
                ('thread_internal', models.BooleanField(blank=True, help_text='Внутренняя резьба для внешнего присоединения', null=True, verbose_name='Внутренняя резьба')),
                ('temp_min', models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True, verbose_name='Темп.мин')),
                ('temp_max', models.SmallIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True, verbose_name='Темп.макс')),
                ('gost', models.CharField(blank=True, help_text='Соответствие ГОСТ, ТУ, другим стандартам - перечень', max_length=1000, null=True, verbose_name='ГОСТ')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры серии', verbose_name='Параметры')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд (производитель) КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.brands', verbose_name='Бренд')),
                ('cert_docs', models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты')),
                ('equipment_type', models.ForeignKey(blank=True, help_text='Тип оборудования для SKU/каталога', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('exd', models.ManyToManyField(blank=True, help_text='Тип взрывозащиты', related_name='cable_gland_model_line_exd', to='params.exdoption', verbose_name='Взрывозащита')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('ip', models.ForeignKey(blank=True, help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_model_line_ip', to='params.ipoption', verbose_name='IP')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cg_model_line_producer', to='producers.producer', verbose_name='Производитель')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
            ],
            options={
                'verbose_name': 'Серия кабельных вводов',
                'verbose_name_plural': 'Серии кабельных вводов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.CopyMixin, core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandModelLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели кабельного ввода', max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели кабельного ввода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели кабельного ввода', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Вес,кг', max_digits=5, null=True, verbose_name='Вес,кг')),
                ('body', models.ForeignKey(blank=True, help_text='Модель корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cable_glands.cableglandbody', verbose_name='Корпус')),
                ('metal_sleeve_body', models.ForeignKey(blank=True, help_text='Модель устройства для подключения металлорукава', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cable_glands.cableglandmetalsleevebody', verbose_name='Крепление МР')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия кабельных вводов/адаптеров', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_model_line', to='cable_glands.cableglandmodelline')),
            ],
            options={
                'verbose_name': 'Модель КВ в серии',
                'verbose_name_plural': 'Модели КВ в серии',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Название модели кабельного ввода (генерируется из шаблона серии)', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели кабельного ввода', max_length=150, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели кабельного ввода (генерируется из шаблона серии)', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('sku', models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
                ('thread', models.ForeignKey(blank=True, help_text='Резьба', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.threadsize', verbose_name='Резьба')),
                ('body_material', models.ForeignKey(blank=True, help_text='Материал корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cable_glands.cableglandbodymaterial')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия кабельных вводов (источник шаблонов названия/описания/артикула)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_articles', to='cable_glands.cableglandmodelline', verbose_name='Серия')),
                ('model_line_item', models.ForeignKey(blank=True, help_text='Серия кабельных вводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_model_line', to='cable_glands.cableglandmodellineitem')),
            ],
            options={
                'verbose_name': 'Кабельный ввод',
                'verbose_name_plural': 'Кабельные вводы',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.TemplateMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandModelLineCertRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('cert_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='cert_doc.certdata', verbose_name='Сертификат')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_data_cg_model_line', to='cable_glands.cableglandmodelline', verbose_name='Серия кабельных вводов')),
            ],
            options={
                'verbose_name': 'Связь сертификата с серией кабельных вводов',
                'verbose_name_plural': 'Связи сертификатов с сериями кабельных вводов',
                'ordering': ['sorting_order'],
                'abstract': False,
                'unique_together': {('cert_data', 'model_line')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandThreadOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('cable_gland_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cg_thread_body', to='cable_glands.cableglandbody', verbose_name='Корпус кабельного ввода')),
                ('thread_size', models.ForeignKey(help_text='Размер и тип резьбы', on_delete=django.db.models.deletion.CASCADE, to='params.threadsize', verbose_name='Размер и тип резьбы')),
            ],
            options={
                'verbose_name': 'Резьба модели корпуса кабельного ввода',
                'verbose_name_plural': 'Типы резьбы модели корпуса кабельного ввода',
                'ordering': ['sorting_order'],
                'unique_together': {('cable_gland_body', 'thread_size')},
            },
        ),
    ]
