# Generated by Django 5.1.4 on 2025-02-18 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0007_mechanicalindicatorinstalledoption'),
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableGlandBodyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CableGlandItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CableGlandModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(max_length=20)),
                ('for_armored_cable', models.BooleanField(blank=True, help_text='Для бронированного кабеля', null=True)),
                ('for_metal_sleeve_cable', models.BooleanField(blank=True, help_text='Для кабеля в металлорукаве', null=True)),
                ('for_pipelines_cable', models.BooleanField(blank=True, help_text='Для кабеля в трубопроводе', null=True)),
                ('thread_external', models.BooleanField(blank=True, help_text='Наружная резьба для внешнего присоединения', null=True)),
                ('thread_internal', models.BooleanField(blank=True, help_text='Внутренняя резьба для внешнего присоединения', null=True)),
                ('temp_min', models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True)),
                ('temp_max', models.SmallIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True)),
                ('gost', models.CharField(blank=True, help_text='Соответвие ГОСТ, ТУ, другим стандартам - перечень', max_length=1000, null=True)),
                ('text_description', models.CharField(blank=True, help_text='Описание серии', max_length=500, null=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд (производитель) кабельных вводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_brand', to='producers.brands')),
                ('cable_gland_type', models.ForeignKey(blank=True, help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_type', to='cable_glands.cableglanditemtype')),
                ('exd', models.ManyToManyField(blank=True, default=1, help_text='Степень взрывозащиты', related_name='cable_gland_model_line_exd', to='params.exdoption')),
                ('ip', models.ManyToManyField(blank=True, default=1, help_text='Степень защиты IP (можно выбрать несколько)', related_name='cable_gland_model_line_ip', to='params.ipoption')),
            ],
        ),
        migrations.CreateModel(
            name='CableGlandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exd_same_as_model_line', models.BooleanField(default=True, help_text='Взрывозащита такая же, как у всей серии. Если да, то новое значение Exd вводить не надо')),
                ('temp_min', models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True)),
                ('temp_max', models.PositiveIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True)),
                ('cable_diameter_inner_min', models.SmallIntegerField(blank=True, help_text='Минимальный внутренний диаметр обжимаего кабеля', null=True)),
                ('cable_diameter_inner_max', models.SmallIntegerField(blank=True, help_text='Минимальный внутренний диаметр обжимаего кабеля', null=True)),
                ('cable_diameter_outer_min', models.PositiveIntegerField(blank=True, help_text='Минимальный внешний диаметр обжимаего кабеля (Здесь указываем значения для кабеля без бронирования)', null=True)),
                ('cable_diameter_outer_max', models.PositiveIntegerField(blank=True, help_text='Минимальный внешний диаметр обжимаего кабеля (Здесь указываем значения для кабеля без бронирования)', null=True)),
                ('dn_metal_sleeve', models.PositiveIntegerField(blank=True, help_text='Диаметр металлорукава', null=True)),
                ('cable_gland_body_material', models.ForeignKey(blank=True, help_text='Материал', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_body_material', to='cable_glands.cableglandbodymaterial')),
                ('exd', models.ManyToManyField(blank=True, default=1, help_text='Степень взрывозащиты', related_name='cable_gland_item_exd', to='params.exdoption')),
                ('parent', models.ForeignKey(blank=True, help_text='Состав комплекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cable_glands.cableglanditem')),
                ('thread_a', models.ForeignKey(blank=True, help_text='Резьба под привод', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_a_items', to='params.threadsize')),
                ('thread_b', models.ForeignKey(blank=True, help_text='Резьба под другой КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_b_items', to='params.threadsize')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия кабельных вводов/адаптеров', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_model_line', to='cable_glands.cableglandmodelline')),
            ],
        ),
    ]
