# Generated by Django 5.2.7 on 2026-09-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablegland',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Материал корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cable_glands.cableglandbodymaterial', verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='cablegland',
            name='code',
            field=models.CharField(blank=True, help_text='Код артикула (автогенерируется из шаблона серии, если пуст)', max_length=150, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='cablegland',
            name='model_line_item',
            field=models.ForeignKey(blank=True, help_text='Модель в серии (корпус/металлорукав/вес)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_model_line', to='cable_glands.cableglandmodellineitem'),
        ),
    ]
