# Generated by Django 5.2.4 on 2025-12-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0001_initial'),
        ('params', '0025_alter_pneumaticconnection_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalSleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название металлорукава', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код металлорукава', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание металлорукава', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
        ),
        migrations.AddField(
            model_name='cableglandbodymaterial',
            name='code',
            field=models.CharField(blank=True, help_text='Код материала корпуса КВ', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='cableglandbodymaterial',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание материала корпуса КВ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cableglandbodymaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='cableglandbodymaterial',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
        migrations.AddField(
            model_name='cableglanditemtype',
            name='code',
            field=models.CharField(blank=True, help_text='Код типа КВ', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='cableglanditemtype',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание типа КВ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cableglanditemtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='cableglanditemtype',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='code',
            field=models.CharField(blank=True, help_text='Код серии кабельных вводов', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание модели корпуса КВ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='name',
            field=models.CharField(default=1, help_text='Название серии кабельных вводов', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
        migrations.AlterField(
            model_name='cableglandbodymaterial',
            name='name',
            field=models.CharField(help_text='Название материала корпуса КВ', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cableglanditemtype',
            name='name',
            field=models.CharField(help_text='Название типа КВ', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='cable_gland_type',
            field=models.ForeignKey(blank=True, help_text='Тип КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_type', to='cable_glands.cableglanditemtype'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='exd',
            field=models.ManyToManyField(blank=True, default=1, help_text='Тип взрывозащиты', related_name='cable_gland_model_line_exd', to='params.exdoption'),
        ),
    ]
