# Generated by Django 5.2.7 on 2026-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0002_alter_cablegland_body_material_alter_cablegland_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablegland',
            name='code',
            field=models.CharField(blank=True, help_text='Код артикула (автогенерируется из шаблона серии, если пуст); уникален', max_length=150, null=True, unique=True, verbose_name='Код'),
        ),
    ]
