# Generated by Django 5.2.4 on 2025-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0002_metalsleeve_cableglandbodymaterial_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cableglanditem',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Модель кабельного ввода', 'verbose_name_plural': 'Модели кабельных вводов'},
        ),
        migrations.AlterModelOptions(
            name='cableglandmodelline',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Серия кабельных вводов', 'verbose_name_plural': 'Серии кабельных вводов'},
        ),
        migrations.AlterModelOptions(
            name='metalsleeve',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип и диаметр металлорукава', 'verbose_name_plural': 'Типы и диаметры металлорукавов'},
        ),
        migrations.AddField(
            model_name='cableglanditem',
            name='code',
            field=models.CharField(blank=True, help_text='Код модели кабельного ввода', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='cableglanditem',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание модели кабельного ввода', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cableglanditem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='cableglanditem',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
        migrations.AlterField(
            model_name='cableglanditem',
            name='name',
            field=models.CharField(help_text='Название модели кабельного ввода', max_length=255, verbose_name='Название'),
        ),
    ]
