# Generated by Django 5.2.7 on 2026-09-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0003_alter_cablegland_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableGlandBodyMaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('body_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_glands.cableglandbodymaterial', verbose_name='Материал корпуса')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_material_options', to='cable_glands.cableglandmodelline', verbose_name='Серия кабельных вводов')),
            ],
            options={
                'verbose_name': 'Материал корпуса для серии кабельных вводов',
                'verbose_name_plural': 'Материалы корпуса для серий кабельных вводов',
                'ordering': ['sorting_order'],
                'unique_together': {('model_line', 'body_material', 'encoding')},
            },
        ),
    ]
