# Generated by Django 5.2.4 on 2025-12-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0003_alter_cableglanditem_options_and_more'),
        ('params', '0025_alter_pneumaticconnection_code'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд (производитель) кабельных вводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_brand', to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='cable_gland_type',
            field=models.ForeignKey(blank=True, help_text='Тип КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_type', to='cable_glands.cableglanditemtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='exd',
            field=models.ManyToManyField(blank=True, default=1, help_text='Тип взрывозащиты', related_name='cable_gland_model_line_exd', to='params.exdoption', verbose_name='Взрывозащита'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='for_armored_cable',
            field=models.BooleanField(blank=True, help_text='Для бронированного кабеля', null=True, verbose_name='Бронированный кабель'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='for_metal_sleeve_cable',
            field=models.BooleanField(blank=True, help_text='Для кабеля в металлорукаве', null=True, verbose_name='Металлорукав'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='for_pipelines_cable',
            field=models.BooleanField(blank=True, help_text='Для кабеля в трубопроводе', null=True, verbose_name='Трубопровод'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='gost',
            field=models.CharField(blank=True, help_text='Соответвие ГОСТ, ТУ, другим стандартам - перечень', max_length=1000, null=True, verbose_name='ГОСТ'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='ip',
            field=models.ManyToManyField(blank=True, default=1, help_text='Степень защиты IP (можно выбрать несколько)', related_name='cable_gland_model_line_ip', to='params.ipoption', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='temp_max',
            field=models.SmallIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True, verbose_name='Темп.макс'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='temp_min',
            field=models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True, verbose_name='Темп.мин'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='thread_external',
            field=models.BooleanField(blank=True, help_text='Наружная резьба для внешнего присоединения', null=True, verbose_name='Наружная резьба'),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='thread_internal',
            field=models.BooleanField(blank=True, help_text='Внутренняя резьба для внешнего присоединения', null=True, verbose_name='Внутренняя резьба'),
        ),
    ]
