# Generated by Django 5.2.4 on 2025-12-23 11:26

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0004_alter_cableglandmodelline_brand_and_more'),
        ('cert_doc', '0001_initial'),
        ('params', '0025_alter_pneumaticconnection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableglanditem',
            name='cable_diameter_inner_max',
            field=models.SmallIntegerField(blank=True, help_text='Минимальный внутренний диаметр обжимаемого кабеля', null=True),
        ),
        migrations.AlterField(
            model_name='cableglanditem',
            name='cable_diameter_inner_min',
            field=models.SmallIntegerField(blank=True, help_text='Минимальный внутренний диаметр обжимаемого кабеля', null=True),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='gost',
            field=models.CharField(blank=True, help_text='Соответствие ГОСТ, ТУ, другим стандартам - перечень', max_length=1000, null=True, verbose_name='ГОСТ'),
        ),
        migrations.CreateModel(
            name='CableGlandBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модели корпуса кабельного ввода', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели корпуса кабельного ввода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели корпуса КВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('metal_sleeve', models.ManyToManyField(blank=True, help_text='Металлорукава, подходящие для этого корпуса', related_name='metal_sleeve_cg_model_body', to='cable_glands.metalsleeve', verbose_name='Металлорукав')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия модели корпуса кабельного ввода', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cg_body_model_line', to='cable_glands.cableglandmodelline', verbose_name='Серия')),
            ],
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandModelLineCertRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('cert_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='cert_doc.certdata', verbose_name='Сертификат')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_data_cg_model_line', to='cable_glands.cableglandmodelline', verbose_name='Серия кабельных вводов')),
            ],
            options={
                'verbose_name': 'Связь сертификата с серией кабельных вводов',
                'verbose_name_plural': 'Связи сертификатов с сериями кабельных вводов',
                'ordering': ['sorting_order'],
                'abstract': False,
                'unique_together': {('cert_data', 'model_line')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CableGlandThreadOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('cable_gland_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cg_thread_body', to='cable_glands.cableglandbody', verbose_name='Корпус кабельного ввода')),
                ('thread_size', models.ForeignKey(help_text='Размер и тип резьбы', on_delete=django.db.models.deletion.CASCADE, to='params.threadsize', verbose_name='Размер и тип резьбы')),
            ],
            options={
                'verbose_name': 'Резьба модели корпуса кабельного ввода',
                'verbose_name_plural': 'Типы резьбы модели корпуса кабельного ввода',
                'ordering': ['sorting_order'],
                'unique_together': {('cable_gland_body', 'thread_size')},
            },
        ),
    ]
