# Generated by Django 5.2.7 on 2026-09-09 15:17

import django.db.models.deletion
import options.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0004_cableglandbodymaterialoption'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='exd',
        ),
        migrations.CreateModel(
            name='CableGlandExdOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('exd_options', models.ManyToManyField(blank=True, related_name='%(class)s_exd_rows', to='params.exdoption', verbose_name='Виды взрывозащиты')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exd_options', to='cable_glands.cableglandmodelline', verbose_name='Серия кабельных вводов')),
            ],
            options={
                'verbose_name': 'Взрывозащита для серии кабельных вводов',
                'verbose_name_plural': 'Взрывозащита для серий кабельных вводов',
                'ordering': ['sorting_order'],
            },
            bases=(models.Model, options.models.ExdFormattingMixin),
        ),
    ]
