# Generated by Django 5.2.4 on 2025-12-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0005_alter_cableglanditem_cable_diameter_inner_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cableglandbody',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Корпус кабельного ввода', 'verbose_name_plural': 'Корпуса кабельных вводов'},
        ),
        migrations.AlterModelOptions(
            name='cableglandbodymaterial',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип материала корпуса кабельного ввода', 'verbose_name_plural': 'Типы материала корпуса кабельных вводов'},
        ),
        migrations.AlterModelOptions(
            name='cableglanditemtype',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Тип кабельного ввода', 'verbose_name_plural': 'Типы кабельных вводов'},
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='cable_diameter_inner_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Максимальный диаметр обжимаемого кабеля', max_digits=5, null=True, verbose_name='Кабель макс'),
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='cable_diameter_inner_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный диаметр обжимаемого кабеля', max_digits=5, null=True, verbose_name='Кабель мин'),
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='metal_sleeve_inner',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Внутренний диаметр металлорукава)', max_digits=5, null=True, verbose_name='МР внутр'),
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='metal_sleeve_outer',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Внешний диаметр металлорукава', max_digits=5, null=True, verbose_name='МР внеш'),
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='thread_lenght',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Длина резьбы,мм', max_digits=5, null=True, verbose_name='Резьба,мм'),
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='total_lenght',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Общая длина, мм', max_digits=5, null=True, verbose_name='Длина,мм'),
        ),
        migrations.AddField(
            model_name='cableglandbody',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Вес,кг', max_digits=5, null=True, verbose_name='Вес,кг'),
        ),
        migrations.AlterField(
            model_name='cableglanditem',
            name='cable_diameter_inner_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный внутренний диаметр обжимаемого кабеля', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cableglanditem',
            name='cable_diameter_inner_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный внутренний диаметр обжимаемого кабеля', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cableglanditem',
            name='cable_diameter_outer_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный внешний диаметр обжимаего кабеля (Здесь указываем значения для кабеля без бронирования)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cableglanditem',
            name='cable_diameter_outer_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный внешний диаметр обжимаего кабеля (Здесь указываем значения для кабеля без бронирования)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cableglandmodelline',
            name='symbolic_code',
            field=models.CharField(help_text='symbolic_code', max_length=20, verbose_name='symbolic_code'),
        ),
    ]
