# Generated by Django 5.2.4 on 2026-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0005_remove_cableglandmodelline_exd_cableglandexdoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandmodellineitem',
            name='cable_diameter_outer_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Максимальный внешний диаметр обжимаемого кабеля (Здесь указываем значения для бронирования)', max_digits=5, null=True, verbose_name='Макс внешний диаметр (броня)'),
        ),
        migrations.AddField(
            model_name='cableglandmodellineitem',
            name='cable_diameter_outer_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Минимальный внешний диаметр обжимаемого кабеля (Здесь указываем значения для бронирования)', max_digits=5, null=True, verbose_name='Мин внешний диаметр (броня)'),
        ),
    ]
