# Generated by Django 5.2.4 on 2025-12-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0006_alter_cableglandbody_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='symbolic_code',
        ),
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='text_description',
        ),
    ]
