# Generated by Django 5.2.7 on 2026-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0007_fix_model_line_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablegland',
            name='body_material_option',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция материала корпуса (through-строка)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_body_material_articles', to='cable_glands.cableglandbodymaterialoption', verbose_name='Опция материала корпуса'),
        ),
        migrations.AddField(
            model_name='cablegland',
            name='exd_option',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты серии; пусто — наследуется дефолт серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_exd_articles', to='cable_glands.cableglandexdoption', verbose_name='Опция взрывозащиты'),
        ),
        migrations.AddField(
            model_name='cablegland',
            name='thread_option',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция резьбы корпуса (through-строка)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_gland_thread_articles', to='cable_glands.cableglandthreadoption', verbose_name='Опция резьбы'),
        ),
    ]
