# Generated by Django 5.2.7 on 2026-09-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0009_migrate_cablegland_to_option_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablegland',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='cablegland',
            name='thread',
        ),
    ]
