# Generated by Django 5.2.7 on 2026-09-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0010_remove_cablegland_body_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableGlandConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название кабельного ввода — формируется автоматически', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код кабельного ввода — формируется автоматически', max_length=150, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Описание кабельного ввода — формируется автоматически', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('is_unique', models.BooleanField(default=True, help_text='Есть ли уже такая же конфигурация', verbose_name='Уникальная конфигурация')),
                ('selected_body_material_option', models.ForeignKey(blank=True, help_text='Выбранная опция материала корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_configs', to='cable_glands.cableglandbodymaterialoption', verbose_name='Опция материала корпуса')),
                ('selected_exd_option', models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_configs', to='cable_glands.cableglandexdoption', verbose_name='Опция взрывозащиты')),
                ('selected_model_line', models.ForeignKey(blank=True, help_text='Серия кабельных вводов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_configs', to='cable_glands.cableglandmodelline', verbose_name='Серия')),
                ('selected_model_line_item', models.ForeignKey(blank=True, help_text='Модель кабельного ввода (корпус/металлорукав/вес)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_configs', to='cable_glands.cableglandmodellineitem', verbose_name='Модель')),
                ('selected_thread_option', models.ForeignKey(blank=True, help_text='Выбранная опция резьбы корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_configs', to='cable_glands.cableglandthreadoption', verbose_name='Опция резьбы')),
            ],
            options={
                'verbose_name': 'Конструктор кабельного ввода',
                'verbose_name_plural': 'Конструктор кабельных вводов',
                'ordering': ['sorting_order'],
            },
        ),
    ]
