# Generated by Django 5.2.7 on 2026-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0011_cableglandconstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandmodelline',
            name='spec_template',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: группы и поля спецификации; пусто — используется реестр CableGland', verbose_name='Шаблон спецификации'),
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='title_template',
            field=models.TextField(blank=True, help_text='Шаблон короткого заголовка для карточки (плейсхолдеры из реестра CableGland)', null=True, verbose_name='Шаблон заголовка'),
        ),
    ]
