# Generated by Django 5.2.7 on 2026-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0012_cableglandmodelline_spec_template_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='ip',
        ),
        migrations.AddField(
            model_name='cableglandmodelline',
            name='ip',
            field=models.ManyToManyField(blank=True, help_text='Степени защиты IP', related_name='cable_gland_model_lines', to='params.ipoption', verbose_name='IP'),
        ),
    ]
