# Generated by Django 5.2.4 on 2026-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0014_populate_cableglandmodelline_ip_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа кабеля', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа кабеля', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа кабеля', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('for_armored_cable', models.BooleanField(default=False, help_text='Тип подходит для бронированного кабеля', verbose_name='Бронированный кабель')),
                ('for_metal_sleeve_cable', models.BooleanField(default=False, help_text='Тип подходит для кабеля в металлорукаве', verbose_name='Металлорукав')),
                ('for_pipelines_cable', models.BooleanField(default=False, help_text='Тип подходит для кабеля в трубопроводе', verbose_name='Трубопровод')),
            ],
            options={
                'verbose_name': 'Тип кабеля',
                'verbose_name_plural': 'Типы кабеля',
                'ordering': ['sorting_order'],
            },
        ),
    ]
