# Generated by Django 5.2.4 on 2026-09-15 18:42
# + RunPython: перенос булевых флагов серии в справочник CableType.

import django.db.models.deletion
from django.db import migrations, models


CABLE_TYPE_DEFINITIONS = [
    # (code, name, armored, metal_sleeve, pipeline)
    ('unarmored', 'Под небронированный кабель', False, False, False),
    ('unarmored_ms', 'Под небронированный кабель в металлорукаве', False, True, False),
    ('armored', 'Под бронированный кабель', True, False, False),
    ('armored_ms', 'Под бронированный кабель в металлорукаве', True, True, False),
]


def backfill_cable_types(apps, schema_editor):
    """Создать записи справочника CableType и проставить FK сериям по старым флагам."""
    CableType = apps.get_model('cable_glands', 'CableType')
    ModelLine = apps.get_model('cable_glands', 'CableGlandModelLine')

    types = {}
    for order, (code, name, armored, ms, pipeline) in enumerate(CABLE_TYPE_DEFINITIONS, start=1):
        types[(armored, ms, pipeline)] = CableType.objects.create(
            code=code,
            name=name,
            sorting_order=order,
            for_armored_cable=armored,
            for_metal_sleeve_cable=ms,
            for_pipelines_cable=pipeline,
        )

    for ml in ModelLine.objects.all():
        armored = bool(ml.for_armored_cable)
        ms = bool(ml.for_metal_sleeve_cable)
        pipeline = bool(ml.for_pipelines_cable)
        key = (armored, ms, pipeline)
        ct = types.get(key)
        if ct is None:
            # Неизвестная комбинация (в текущих данных таких нет) — заводим запись на лету,
            # чтобы серия не потеряла признак.
            suffix = ' в металлорукаве' if ms else ''
            suffix += ' в трубопроводе' if pipeline else ''
            ct = CableType.objects.create(
                code=f'combo_{int(armored)}{int(ms)}{int(pipeline)}',
                name=('Под бронированный кабель' if armored else 'Под небронированный кабель') + suffix,
                sorting_order=100,
                for_armored_cable=armored,
                for_metal_sleeve_cable=ms,
                for_pipelines_cable=pipeline,
            )
            types[key] = ct
        ml.cable_type = ct
        ml.save(update_fields=['cable_type'])


def reverse_backfill(apps, schema_editor):
    """Откат: вернуть булевы флаги серии из CableType и удалить записи справочника."""
    CableType = apps.get_model('cable_glands', 'CableType')
    ModelLine = apps.get_model('cable_glands', 'CableGlandModelLine')

    for ml in ModelLine.objects.all():
        ct = ml.cable_type
        ml.for_armored_cable = bool(ct.for_armored_cable) if ct else None
        ml.for_metal_sleeve_cable = bool(ct.for_metal_sleeve_cable) if ct else None
        ml.for_pipelines_cable = bool(ct.for_pipelines_cable) if ct else None
        ml.save(update_fields=['for_armored_cable', 'for_metal_sleeve_cable', 'for_pipelines_cable'])
    CableType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0015_cabletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandmodelline',
            name='cable_type',
            field=models.ForeignKey(blank=True, help_text='Тип кабеля из справочника (заменяет булевы флаги бронированного/МР/трубопровода)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_lines', to='cable_glands.cabletype', verbose_name='Тип кабеля'),
        ),
        migrations.RunPython(backfill_cable_types, reverse_backfill),
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='for_armored_cable',
        ),
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='for_metal_sleeve_cable',
        ),
        migrations.RemoveField(
            model_name='cableglandmodelline',
            name='for_pipelines_cable',
        ),
    ]
