# Generated by Django 5.2.7 on 2026-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0017_cablegland_config_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandbodymaterial',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='cableglandbodymaterial',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='cableglanditemtype',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='cableglanditemtype',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='cabletype',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='cabletype',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='metalsleeve',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='metalsleeve',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
    ]
