# Generated by Django 5.2.4 on 2026-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0020_cableglandmodelline_description_template_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandmodelline',
            name='spec_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Локаль — внешний ключ: {"ru": {группа: {подпись: ключ}}, "en": {...}, "cn": {...}}. "ru" синхронизируется с spec_template.', verbose_name='Переводы шаблона спецификации (ru/en/cn)'),
        ),
    ]
