# Generated by Django 5.2.4 on 2026-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_glands', '0021_cableglandmodelline_spec_template_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableglandmodelline',
            name='title_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона заголовка (ru/en/cn)'),
        ),
    ]
