"""
Django settings for djangoProject12 project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Локальное хранилище для фалов (картинки и т.п.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR , 'media')
# Настройки хранилища
FILE_STORAGE_BACKEND = 'local'  # 'local' или 'yandex_cloud'
# Настройки для Yandex Cloud (для будущего использования)
# YC_BUCKET_NAME = os.getenv('YC_BUCKET_NAME', '')
# YC_ACCESS_KEY = os.getenv('YC_ACCESS_KEY', '')
# YC_SECRET_KEY = os.getenv('YC_SECRET_KEY', '')
# YC_ENDPOINT_URL = 'https://storage.yandexcloud.net'
# YC_REGION = 'ru-central1'


STATIC_URL = '/static/'  # URL для статических файлов
# Папки, где искать статические файлы
STATICFILES_DIRS = [
    os.path.join(BASE_DIR , 'static') ,
]
# Папка для collectstatic (может быть любой)
STATIC_ROOT = os.path.join(BASE_DIR , 'staticfiles')  # Директория для сбора статических файлов

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&p1sohqzki&0xrh2w8q%2ic^7f2@)z5rj=y^33c(&ou2wsj8%7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*' ,  # Для теста (не для продакшена!)
    'localhost' ,
    '127.0.0.1' ,
    'host.docker.internal'  # Важно!

]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173" ,  # URL вашего приложения на Vite
    "http://localhost:3000" ,
    "http://127.0.0.1:3000" ,
    "http://host.docker.internal" ,
]
CORS_ALLOW_METHODS = [
    "GET" ,
    "POST" ,
    "PUT" ,
    "PATCH" ,
    "DELETE" ,
    "OPTIONS" ,
]

CORS_ALLOW_HEADERS = [
    "content-type" ,
    "authorization" ,
    "x-csrf-token" ,
    "x-requested-with" ,
    "accept" ,
    "origin" ,
    "user-agent" ,
    "x-custom-header" ,
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Путь к папке для хранения скомпилированных файлов Vue
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'frontend/dist/static'),
# ]

# Application definition

INSTALLED_APPS = [
    'admin_interface' ,
    'colorfield' ,
    'nested_admin' ,
    'django.contrib.admin' ,
    'django.contrib.auth' ,
    'django.contrib.contenttypes' ,
    'django.contrib.sessions' ,
    'django.contrib.messages' ,
    'django.contrib.staticfiles' ,
    'rest_framework' ,
    'corsheaders' ,
    'core' ,
    # 'django_filters',
    'graphene_django' ,
    'cert_doc.apps.CertDocConfig',
    'params.apps.ParamsConfig' ,
    'options.apps.OptionsConfig' ,
    'producers.apps.ProducersConfig' ,
    'electric_actuators.apps.ElectricActuatorsConfig' ,
    'data_processor.apps.DataProcessorConfig' ,
    'cable_glands.apps.CableGlandConfig' ,
    'ett.apps.EttConfig' ,
    'valve_data.apps.ValveDataConfig' ,
    'materials.apps.MaterialsConfig' ,
    'clients.apps.ClientsConfig' ,
    'client_requests.apps.ClientRequestsConfig' ,
    'media_library.apps.MediaLibraryConfig' ,
    'pneumatic_actuators.apps.PneumaticActuatorConfig' ,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware' ,
    'django.contrib.sessions.middleware.SessionMiddleware' ,
    'django.middleware.common.CommonMiddleware' ,
    'django.middleware.csrf.CsrfViewMiddleware' ,
    'django.contrib.auth.middleware.AuthenticationMiddleware' ,
    'django.contrib.messages.middleware.MessageMiddleware' ,
    'django.middleware.locale.LocaleMiddleware' ,
    'django.middleware.clickjacking.XFrameOptionsMiddleware' ,
    'corsheaders.middleware.CorsMiddleware' ,
    'django.middleware.common.CommonMiddleware' ,
]

# Настройки медиабиблиотеки
MEDIA_LIBRARY = {
    'MAX_FILE_SIZE': 100 * 1024 * 1024,  # 100MB
    'ALLOWED_EXTENSIONS': [
        # Изображения
        'jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg',
        # Документы
        'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
        'txt', 'rtf', 'csv',
        # Видео
        'mp4', 'avi', 'mov', 'mkv', 'webm',
        # Аудио
        'mp3', 'wav', 'ogg',
        # Архивы
        'zip', 'rar', '7z',
    ],
    'AUTO_TAG_SEPARATORS': ['_', '-', '.', ',', ';', '—', '–', ' '],
    'PREVIEW_SIZE': (300, 300),  # Размер превью
    'PREVIEW_QUALITY': 85,  # Качество превью (0-100)
}

ROOT_URLCONF = 'djangoProject1.urls'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.PageNumberPagination' ,
    'PAGE_SIZE' : 15
}
TEMPLATES = [
    {
        'BACKEND' : 'django.template.backends.django.DjangoTemplates' ,
        'DIRS' : [BASE_DIR / 'templates']
        ,
        'APP_DIRS' : True ,
        'OPTIONS' : {
            'context_processors' : [
                'django.template.context_processors.debug' ,
                'django.template.context_processors.request' ,
                'django.contrib.auth.context_processors.auth' ,
                'django.contrib.messages.context_processors.messages' ,
            ] ,
        } ,
    } ,
]

WSGI_APPLICATION = 'djangoProject1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.sqlite3' ,
        'NAME' : BASE_DIR / 'db.sqlite3' ,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME' : 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' ,
    } ,
    {
        'NAME' : 'django.contrib.auth.password_validation.MinimumLengthValidator' ,
    } ,
    {
        'NAME' : 'django.contrib.auth.password_validation.CommonPasswordValidator' ,
    } ,
    {
        'NAME' : 'django.contrib.auth.password_validation.NumericPasswordValidator' ,
    } ,
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'valve_data': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # ВКЛЮЧАЕМ DEBUG для нашего приложения
            'propagate': False,
        },
        'storage_manager': {
                    'handlers': ['console', 'file'],
                    'level': 'DEBUG',  # ВКЛЮЧАЕМ DEBUG для нашего приложения
                    'propagate': False,
                },
    },
}

GRAPHENE = {
    'SCHEMA' : 'djangoProject1.graphql.schema.schema' ,
    # 'MIDDLEWARE': 'graphql_jwt.middleware.JSONWebTokenMiddleware',  # Отключите аутентификацию на время тестов
}
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
