"""
Django settings for djangoProject12 project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'  # URL для статических файлов
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # Директория для сбора статических файлов

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&p1sohqzki&0xrh2w8q%2ic^7f2@)z5rj=y^33c(&ou2wsj8%7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # URL вашего приложения на Vite
]
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrf-token",
    "x-requested-with",
    "accept",
    "origin",
    "user-agent",
    "x-custom-header",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
# Путь к папке для хранения скомпилированных файлов Vue
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'frontend/dist/static'),
# ]

# Application definition

INSTALLED_APPS = [
    'admin_interface' ,
    'colorfield',
    'nested_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_extensions',
    'rest_framework',
    # 'drf_generators',
    'corsheaders',
    'params.apps.ParamsConfig',
    'producers.apps.ProducersConfig',
    'electric_actuators.apps.ElectricActuatorsConfig',
    'data_processor.apps.DataProcessorConfig',
    'cable_glands.apps.CableGlandConfig',
    'ett.apps.EttConfig',
    'valve_data.apps.ValveDataConfig',
    'clients.apps.ClientsConfig',
    'client_request.apps.ClientRequestConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'djangoProject1.urls'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Не отключать существующие логгеры
    'handlers': {
        'console': {
            'level': 'CRITICAL',  # Логировать все сообщения уровня DEBUG и выше
            'class': 'logging.StreamHandler',  # Вывод в консоль
        },
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': 'debug.log',  # Логи будут записываться в файл debug.log
        # },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],  # Использовать обработчик 'console'
            'level': 'INFO',  # Логировать все сообщения уровня DEBUG и выше
            'propagate': True,  # Передавать логи родителям (например, в root logger)
        },
        'django' : {
            'handlers' : ['console'] ,
            'level' : 'CRITICAL' ,
            'propagate' : True ,
        } ,
        'django.request' : {
            'handlers' : ['console'] ,
            'level' : 'ERROR' ,
            'propagate' : True ,
        } ,
        'django.db.backends' : {
            'handlers' : ['console'] ,
            'level' : 'DEBUG' ,
            'propagate' : True ,
        } ,
    },
    'django.db.migrations': {
        'handlers': ['console'],
        'level': 'WARNING',  # Подавляем миграции
        'propagate': False,  # Не передаем в другие логеры
    },
    'watchdog': {
        'handlers': ['console'],
        'level': 'WARNING',  # Устанавливаем уровень логирования для watchdog
        'propagate': False,  # Останавливаем распространение
    },
    'django.middleware': {
        'handlers': ['console'],
        'level': 'WARNING',  # Подавляем сообщения от middleware (например, corsheaders)
        'propagate': False,
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
