# Generated by Django 5.2.1 on 2026-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Буквенная часть кода: ДОК, ЦЕН, ЗАП, ...', max_length=10, verbose_name='Префикс')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Текущее значение (увеличивается автоматически)', verbose_name='Счётчик')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Если указан — нумерация своя для каждого года', null=True, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Если указан — нумерация своя для каждого месяца', null=True, verbose_name='Месяц')),
                ('pad_length', models.PositiveSmallIntegerField(default=6, help_text='До какой длины дополнить номер нулями', verbose_name='Ширина номера')),
            ],
            options={
                'verbose_name': 'Нумератор документов',
                'verbose_name_plural': 'Нумераторы документов',
                'indexes': [models.Index(fields=['prefix', 'year', 'month'], name='documents_d_prefix_a41ad6_idx')],
                'unique_together': {('prefix', 'year', 'month')},
            },
        ),
    ]
