# Generated by Django 5.2.7 on 2026-07-24 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_customers', '0012_projectcustomeruser_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClientProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('custom', 'Custom')], default='deepseek', max_length=32)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='project_customers.projectcustomer')),
            ],
            options={
                'verbose_name': 'AI Client Provider',
                'verbose_name_plural': 'AI Client Providers',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('incoming', 'Incoming'), ('processing', 'Processing'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('error', 'Error')], db_index=True, default='incoming', max_length=16)),
                ('intent', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source', models.CharField(choices=[('web_form', 'Web Form'), ('email', 'Email'), ('messenger', 'Messenger'), ('api', 'External API')], default='web_form', max_length=32)),
                ('context_window_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='project_customers.projectcustomer')),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_text', models.TextField()),
                ('version', models.CharField(max_length=16)),
                ('intent', models.CharField(blank=True, max_length=64, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant (LLM)'), ('classifier', 'Classifier'), ('orchestrator', 'Orchestrator'), ('system', 'System')], db_index=True, max_length=16)),
                ('content', models.TextField()),
                ('structured_content', models.JSONField(blank=True, null=True)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=64, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ai_assistant.aimessage')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ai_assistant.aiprompttemplate')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuerySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('expected_intent', models.CharField(blank=True, max_length=64, null=True)),
                ('expected_filters', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('actuator_selection', 'Подбор привода'), ('price_check', 'Запрос цены'), ('replacement', 'Замена/аналог'), ('specs', 'Характеристики'), ('general', 'Общий')], default='general', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Query Sample',
                'verbose_name_plural': 'AI Query Samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('reasoning_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField()),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='ai_assistant.aimessage')),
            ],
            options={
                'verbose_name': 'AI Token Usage',
                'verbose_name_plural': 'AI Token Usages',
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['customer', 'status'], name='ai_assistan_custome_29c972_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['session_key'], name='ai_assistan_session_6b1f75_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_assistan_convers_8fde2e_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['intent'], name='ai_assistan_intent_2a296f_idx'),
        ),
    ]
