# Generated by Django 5.2.7 on 2026-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconversation',
            name='context_window_summary',
        ),
        migrations.AddField(
            model_name='aimessage',
            name='context_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
