# Generated by Django 5.2.7 on 2026-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_remove_aiconversation_context_window_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprompttemplate',
            name='schema_json',
            field=models.JSONField(blank=True, help_text='JSON Schema для structured output (Instructor)', null=True),
        ),
    ]
