# Generated by Django 5.2.7 on 2026-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aiprompttemplate_schema_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
