# Generated by Django 5.2.7 on 2026-07-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_alter_aiprompttemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerysample',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiquerysample',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiquerysample',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_samples', to='ai_assistant.aiprompttemplate'),
        ),
        migrations.AddField(
            model_name='aiquerysample',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
