# Generated by Django 5.2.7 on 2026-07-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_aiquerysample_comment_aiquerysample_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('api_key', models.CharField(max_length=512)),
                ('base_url', models.URLField(default='https://api.deepseek.com/v1')),
                ('model_mapping', models.JSONField(default=dict, help_text='{"classification": "deepseek-chat", "extraction": "deepseek-v4-flash", "debug": "deepseek-v4-pro"}')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiprompttemplate',
            options={'ordering': ['name', '-version'], 'verbose_name': 'AI Prompt Template', 'verbose_name_plural': 'AI Prompt Templates'},
        ),
        migrations.AlterField(
            model_name='aiclientprovider',
            name='api_key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='reasoning_tokens',
            field=models.IntegerField(default=0, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
