# Generated by Django 5.2.4 on 2026-07-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_aiprovider_alter_aiprompttemplate_options_and_more'),
        ('project_customers', '0012_projectcustomeruser_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Уникальный код: 'actuator', 'solenoid', 'bkv', 'cable_gland', ...", max_length=64, unique=True)),
                ('label', models.CharField(help_text='Человекочитаемое название: «Пневмопривод», «Соленоидный клапан», ...', max_length=128)),
                ('level', models.IntegerField(default=1, help_text='Типичный уровень вложенности (1=позиция, 2=компонент, 3=субкомпонент)')),
                ('param_semantics', models.JSONField(blank=True, default=dict, help_text='Семантика параметров для сравнения требований и факта. Пример: {"torque_nm": {"direction": "min", "label": "не менее"}, "ip": {"direction": "min", "label": "не хуже"}}. direction: min (чем больше тем лучше), max, exact.')),
                ('filter_endpoint', models.CharField(blank=True, help_text='API-эндпоинт для Фазы 3: POST /api/pneumatic_actuators/selector/search/', max_length=256, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='selection_tree',
            field=models.JSONField(blank=True, help_text='Кеш полного дерева SelectionNode для быстрой отдачи на фронт', null=True),
        ),
        migrations.AddField(
            model_name='aiquerysample',
            name='final_selections_json',
            field=models.JSONField(blank=True, help_text='Эталонные выборы пользователя (для обучения)', null=True),
        ),
        migrations.AddField(
            model_name='aiquerysample',
            name='tree_json',
            field=models.JSONField(blank=True, help_text='Эталонное дерево SelectionNode (для обучения)', null=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='reasoning_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='JSONSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Имя схемы: 'tree_schema', 'actuator_filters', 'solenoid_filters', ...", max_length=128)),
                ('version', models.CharField(help_text="Версия: '1', '2', ...", max_length=16)),
                ('description', models.TextField(blank=True, help_text='Описание назначения схемы', null=True)),
                ('schema_json', models.JSONField(help_text='JSON Schema для Instructor structured output. Пример: {"type": "object", "properties": {"torque_nm": {"type": "number"}}, "required": ["torque_nm"]}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JSON Schema',
                'verbose_name_plural': 'JSON Schemas',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='StepConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('decompose', 'Decompose — текст → дерево'), ('extract', 'Extract — дерево → фильтры'), ('filter', 'Filter — фильтры → варианты'), ('select', 'Select — выбор + каскад'), ('compare', 'Compare — требования vs факт'), ('format', 'Format — EBOM + результат')], db_index=True, help_text='Шаг конвейера', max_length=32)),
                ('model_role', models.CharField(default='extraction', help_text="Роль модели из AIProvider.model_mapping: 'classification', 'extraction', 'debug'", max_length=32)),
                ('priority', models.IntegerField(default=10, help_text='Приоритет (меньше = выше). Используется при нескольких конфигах на один шаг.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(blank=True, help_text='Тип оборудования (null = общий, для decompose)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_configs', to='ai_assistant.equipmenttype')),
                ('output_schema', models.ForeignKey(blank=True, help_text='JSON-схема выхода для Instructor (null = без structured output)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_configs', to='ai_assistant.jsonschema')),
                ('prompt_template', models.ForeignKey(blank=True, help_text='Промпт для этого шага (null = без ИИ, как filter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_configs', to='ai_assistant.aiprompttemplate')),
            ],
            options={
                'verbose_name': 'Step Config',
                'verbose_name_plural': 'Step Configs',
                'ordering': ['step', 'priority'],
                'unique_together': {('step', 'equipment_type')},
            },
        ),
        migrations.CreateModel(
            name='CascadeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.JSONField(help_text='Маппинг: {"поле_родителя": "поле_дочернего_фильтра", ...}. Ключ — имя поля в спецификации родительского продукта, значение — имя поля в фильтре дочернего узла.')),
                ('is_active', models.BooleanField(default=True)),
                ('child_type', models.ForeignKey(help_text='Дочерний тип (куда пробрасываем параметры)', on_delete=django.db.models.deletion.CASCADE, related_name='cascade_rules_to', to='ai_assistant.equipmenttype')),
                ('parent_type', models.ForeignKey(help_text='Родительский тип (откуда берём параметры)', on_delete=django.db.models.deletion.CASCADE, related_name='cascade_rules_from', to='ai_assistant.equipmenttype')),
            ],
            options={
                'verbose_name': 'Cascade Rule',
                'verbose_name_plural': 'Cascade Rules',
                'unique_together': {('parent_type', 'child_type')},
            },
        ),
        migrations.CreateModel(
            name='SelectionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('selection', 'Подбор оборудования'), ('price_check', 'Запрос цены'), ('cert_search', 'Поиск сертификата'), ('specs', 'Характеристики'), ('general', 'Общий')], db_index=True, default='selection', help_text='Тип задачи: подбор, запрос цены, поиск сертификата, ...', max_length=32)),
                ('level', models.IntegerField(db_index=True, default=1, help_text='Уровень вложенности: 1=позиция, 2=компонент, 3=субкомпонент, ...')),
                ('order', models.IntegerField(default=0, help_text='Порядок среди siblings')),
                ('path', models.CharField(db_index=True, help_text="Materialized path: '1', '1/1', '1/1/2', ... — для быстрой навигации по дереву", max_length=256)),
                ('label', models.CharField(help_text='Человекочитаемая метка: «Пневмопривод DA, 150Нм»', max_length=256)),
                ('quantity', models.FloatField(default=1.0, help_text='Количество для данного узла')),
                ('quantity_unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('kg', 'кг'), ('set', 'комплект'), ('lot', 'партия')], default='pcs', help_text='Единица измерения: шт, м, кг, комплект, партия', max_length=8)),
                ('decompose_output', models.JSONField(blank=True, help_text='Сырой вывод decompose-промпта для данного узла', null=True)),
                ('extract_output', models.JSONField(blank=True, help_text='Структурированные фильтры из исходных требований пользователя. НЕИЗМЕННЫ после extract.', null=True)),
                ('cascade_params', models.JSONField(blank=True, help_text='Параметры, проброшенные от выбора родительского продукта через CascadeRule', null=True)),
                ('filter_output', models.JSONField(blank=True, help_text="Результат API-фильтра: {'options': [...], 'total': 20}", null=True)),
                ('selected_product_type', models.CharField(blank=True, help_text='Тип выбранного продукта (app_label.ModelName)', max_length=128, null=True)),
                ('selected_product_id', models.IntegerField(blank=True, help_text='ID выбранного продукта', null=True)),
                ('selected_product_specs', models.JSONField(blank=True, help_text='Фактические характеристики выбранного продукта (загружаются при select)', null=True)),
                ('compare_output', models.JSONField(blank=True, help_text="Сравнение требований и факта: [{'param': 'IP', 'required': 'IP54', 'actual': 'IP67', 'match': True, 'note': 'выше требуемого'}]", null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('decomposed', 'Декомпозирован'), ('extracting', 'Извлечение...'), ('extracted', 'Параметры извлечены'), ('filtering', 'Подбор...'), ('filtered', 'Варианты получены'), ('selected', 'Выбран вариант'), ('compared', 'Сравнение готово'), ('needs_info', 'Нужны уточнения'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=32)),
                ('status_message', models.TextField(blank=True, help_text='Сообщение о статусе (ошибка, причина needs_info)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='Сессия/диалог, в рамках которого ведётся подбор', on_delete=django.db.models.deletion.CASCADE, related_name='selection_nodes', to='ai_assistant.aiconversation')),
                ('equipment_type', models.ForeignKey(blank=True, help_text='Тип оборудования (null для узла-контейнера без собственного подбора)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_nodes', to='ai_assistant.equipmenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский узел в дереве (null = корень — позиция)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ai_assistant.selectionnode')),
            ],
            options={
                'verbose_name': 'Selection Node',
                'verbose_name_plural': 'Selection Nodes',
                'ordering': ['conversation', 'level', 'order'],
                'indexes': [models.Index(fields=['conversation', 'path'], name='ai_assistan_convers_a98dcd_idx'), models.Index(fields=['conversation', 'status'], name='ai_assistan_convers_9cabd0_idx'), models.Index(fields=['equipment_type', 'status'], name='ai_assistan_equipme_80124e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StepConfigOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_suffix', models.TextField(blank=True, help_text='Текст, добавляемый в конец промпта (например, «Учитывай только продукцию ABRA»)', null=True)),
                ('model_role', models.CharField(blank=True, help_text='Другая роль модели (null = дефолтная из StepConfig)', max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Клиент, для которого действует переопределение', on_delete=django.db.models.deletion.CASCADE, related_name='step_overrides', to='project_customers.projectcustomer')),
                ('output_schema', models.ForeignKey(blank=True, help_text='Другая схема выхода (null = дефолтная)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_assistant.jsonschema')),
                ('prompt_template', models.ForeignKey(blank=True, help_text='Другой промпт (null = использовать дефолтный из StepConfig)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_assistant.aiprompttemplate')),
                ('step_config', models.ForeignKey(help_text='Базовая конфигурация, которую переопределяем', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='ai_assistant.stepconfig')),
            ],
            options={
                'verbose_name': 'Step Config Override',
                'verbose_name_plural': 'Step Config Overrides',
                'unique_together': {('customer', 'step_config')},
            },
        ),
    ]
