# Generated by Django 5.2.7 on 2026-07-27 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_equipmenttype_aiconversation_selection_tree_and_more'),
        ('core', '0004_migrate_ai_equipment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionnode',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Тип оборудования (null для узла-контейнера без собственного подбора)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_selection_nodes', to='core.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='cascaderule',
            name='parent_type',
            field=models.ForeignKey(help_text='Родительский тип (откуда берём параметры)', on_delete=django.db.models.deletion.CASCADE, related_name='ai_cascade_rules_from', to='core.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='cascaderule',
            name='child_type',
            field=models.ForeignKey(help_text='Дочерний тип (куда пробрасываем параметры)', on_delete=django.db.models.deletion.CASCADE, related_name='ai_cascade_rules_to', to='core.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='stepconfig',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Тип оборудования (null = общий, для decompose)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_step_configs', to='core.equipmenttype'),
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
    ]
