# Generated by Django 5.2.7 on 2026-07-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_switch_equipment_type_to_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprompttemplate',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Уникальный код шаблона для подстановки в другие шаблоны через {code}. Пример: 'system_prompt', 'decompose_v2', 'extract_actuator'. Используется в template_text других промптов для композиции.", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stepconfig',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Уникальный код конфигурации шага. Используется для ссылки на StepConfig из кода вместо поиска по паре (step, equipment_type). Пример: 'decompose_default', 'extract_actuator', 'extract_solenoid'.", max_length=64, null=True, unique=True),
        ),
    ]
