# Generated by Django 5.2.7 on 2026-07-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_create_anonymous_customer'),
        ('project_customers', '0012_projectcustomeruser_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprompttemplate',
            options={'ordering': ['sorting_order', 'name', '-version'], 'verbose_name': 'AI Prompt Template', 'verbose_name_plural': 'AI Prompt Templates'},
        ),
        migrations.AlterModelOptions(
            name='jsonschema',
            options={'ordering': ['sorting_order', 'name', '-version'], 'verbose_name': 'JSON Schema', 'verbose_name_plural': 'JSON Schemas'},
        ),
        migrations.AlterModelOptions(
            name='pipelineskill',
            options={'ordering': ['step', 'priority'], 'verbose_name': 'Pipeline Skill', 'verbose_name_plural': 'Pipeline Skills'},
        ),
        migrations.AlterModelOptions(
            name='skilloverride',
            options={'verbose_name': 'Skill Override', 'verbose_name_plural': 'Skill Overrides'},
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='jsonschema',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='completion_tokens',
            field=models.IntegerField(default=0, verbose_name='Completion Tokens'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer for billing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='project_customers.projectcustomer'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='prompt_tokens',
            field=models.IntegerField(default=0, verbose_name='Prompt Tokens'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='reasoning_tokens',
            field=models.IntegerField(default=0, verbose_name='Reasoning Tokens'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='Total Tokens'),
        ),
        migrations.AlterField(
            model_name='pipelineskill',
            name='avg_latency_ms',
            field=models.IntegerField(blank=True, help_text='Скользящее среднее времени отклика LLM для этого скилла (мс). Рассчитывается по последним 5 запросам. Используется для оценки времени ожидания на фронте.', null=True),
        ),
        migrations.AlterField(
            model_name='pipelineskill',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Уникальный код скилла. Используется для ссылки на PipelineSkill из кода вместо поиска по паре (step, equipment_type). Пример: 'decompose_default', 'extract_actuator', 'extract_solenoid'.", max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pipelineskill',
            name='latency_sample_count',
            field=models.IntegerField(default=0, help_text='Количество замеров, использованных для расчёта avg_latency_ms'),
        ),
        migrations.AlterField(
            model_name='skilloverride',
            name='customer',
            field=models.ForeignKey(help_text='Клиент, для которого действует переопределение', on_delete=django.db.models.deletion.CASCADE, related_name='skill_overrides', to='project_customers.projectcustomer'),
        ),
        migrations.AlterField(
            model_name='skilloverride',
            name='model_role',
            field=models.CharField(blank=True, help_text='Другая роль модели (null = дефолтная из PipelineSkill)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='skilloverride',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Другой промпт (null = использовать дефолтный из PipelineSkill)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_assistant.aiprompttemplate'),
        ),
        migrations.AlterField(
            model_name='skilloverride',
            name='step_config',
            field=models.ForeignKey(help_text='Базовый скилл, который переопределяем', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='ai_assistant.pipelineskill'),
        ),
        migrations.AddIndex(
            model_name='aitokenusage',
            index=models.Index(fields=['customer', '-id'], name='ai_assistan_custome_d9d79b_idx'),
        ),
    ]
