# Generated by Django 5.2.4 on 2026-07-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0015_add_sorting_order'),
        ('core', '0005_add_title_template_to_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Символьное обозначение группы композиции', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код группы композиции', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('group_type', models.CharField(choices=[('required', 'Обязательный'), ('optional', 'Опциональный'), ('xor', 'XOR — ровно один из')], default='required', help_text='required / optional / xor', max_length=16, verbose_name='Тип группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('equipment_types', models.ManyToManyField(blank=True, help_text='EquipmentType, входящие в эту группу', related_name='composition_groups', to='core.equipmenttype', verbose_name='Типы оборудования')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская CompositionGroup для вложенности', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ai_assistant.compositiongroup', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Composition Group',
                'verbose_name_plural': 'Composition Groups',
                'db_table': 'ai_composition_group',
                'ordering': ['sorting_order', 'name'],
            },
        ),
    ]
