# Generated by Django 5.2.7 on 2026-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0016_compositiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositiongroup',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='CompositionGroup, на которые ссылается эта группа (не вложенность)', related_name='referenced_by', to='ai_assistant.compositiongroup', verbose_name='Ссылки на группы'),
        ),
    ]
