# Generated by Django 5.2.7 on 2026-07-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0017_add_references_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositiongroup',
            name='output_schema',
            field=models.ForeignKey(blank=True, help_text='JSON-схема выходного формата для этой группы (MBOM/подбор)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composition_groups', to='ai_assistant.jsonschema', verbose_name='JSON Schema'),
        ),
    ]
