# Generated by Django 5.2.7 on 2026-07-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0018_add_output_schema_to_composition_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositiongroup',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон промпта для этой группы (MBOM/подбор)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composition_groups', to='ai_assistant.aiprompttemplate', verbose_name='Prompt Template'),
        ),
    ]
