# Generated by Django 5.2.7 on 2026-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0019_add_prompt_template_to_composition_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionnode',
            name='cascade_params',
            field=models.JSONField(blank=True, help_text='Параметры, проброшенные от выбора родительского продукта через DerivationRule', null=True),
        ),
        migrations.DeleteModel(
            name='CascadeRule',
        ),
    ]
