# Generated by Django 4.2.23 on 2026-04-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=200, verbose_name='Краткое наименование')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('postal_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счет')),
                ('checking_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
                ('ceo_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО директора')),
                ('ceo_position', models.CharField(blank=True, default='Генеральный директор', max_length=100)),
                ('accountant_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО Главный бухгалтер')),
                ('accountant_position', models.CharField(blank=True, default='Генеральный директор', max_length=100)),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='ProjectCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('access_until', models.DateField(blank=True, null=True, verbose_name='Доступ до')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ProjectCustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='project_customers.projectcustomer', verbose_name='Клиент')),
                ('default_legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_customers.legalentity', verbose_name='Юридическое лицо по умолчанию')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Пользователь клиента',
                'verbose_name_plural': 'Пользователи клиентов',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_text', models.CharField(blank=True, max_length=500, verbose_name='Текст подписи')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (личный)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон (личный)')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='project_customers.projectcustomeruser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='project_customers.projectcustomer', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number_template', models.CharField(default='{year}-{seq:04d}', max_length=100, verbose_name='Шаблон номера заявки')),
                ('request_prefix', models.CharField(blank=True, max_length=20, verbose_name='Префикс заявки')),
                ('request_suffix', models.CharField(blank=True, max_length=20, verbose_name='Суффикс заявки')),
                ('last_request_seq', models.IntegerField(default=0, verbose_name='Последний номер заявки')),
                ('last_request_year', models.IntegerField(blank=True, null=True)),
                ('last_request_month', models.IntegerField(blank=True, null=True)),
                ('bitrix_webhook', models.CharField(blank=True, max_length=500, verbose_name='Bitrix webhook')),
                ('onec_api_url', models.CharField(blank=True, max_length=500, verbose_name='1C API URL')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='project_customers.projectcustomer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Настройки клиента',
                'verbose_name_plural': 'Настройки клиентов',
            },
        ),
    ]
