# Generated by Django 4.2.23 on 2026-04-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название параметра')),
                ('code', models.CharField(max_length=100, verbose_name='Код параметра')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='project_customers.projectcustomeruser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметр пользователя',
                'verbose_name_plural': 'Параметры пользователей',
                'unique_together': {('user', 'code')},
            },
        ),
    ]
