# Generated by Django 5.2.4 on 2026-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0003_customersettings_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomeruser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь системы'), ('viewer', 'Any (только каталоги)')], default='viewer', max_length=20, verbose_name='Роль'),
        ),
    ]
