# Generated by Django 5.2.7 on 2026-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0004_projectcustomeruser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код (limit_switch, gearbox, llm_agent, ...)', max_length=50, unique=True, verbose_name='Код приложения')),
                ('name', models.CharField(help_text='Человекочитаемое название мини-приложения', max_length=100, verbose_name='Название')),
                ('has_brand_filter', models.BooleanField(default=True, help_text='Применяется ли фильтрация по брендам (для LLM-агента — False)', verbose_name='Фильтр по брендам')),
                ('is_active', models.BooleanField(default=True, help_text='Доступно ли приложение для назначения', verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Мини-приложение (API)',
                'verbose_name_plural': 'Мини-приложения (API)',
                'ordering': ['sorting_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код раздела (catalog, configurator, ...)', max_length=50, unique=True, verbose_name='Код раздела')),
                ('name', models.CharField(help_text='Человекочитаемое название раздела', max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен ли раздел для назначения', verbose_name='Активен')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Раздел сайта',
                'verbose_name_plural': 'Разделы сайта',
                'ordering': ['sorting_order', 'code'],
            },
        ),
    ]
