# Generated by Django 5.2.7 on 2026-07-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('project_customers', '0005_allowedapp_sitesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomer',
            name='visible_brands',
            field=models.ManyToManyField(blank=True, help_text='Бренды, отображаемые на сайте для этой организации', related_name='visible_for_customers', to='producers.brands', verbose_name='Видимые бренды'),
        ),
        migrations.AddField(
            model_name='projectcustomer',
            name='visible_sections',
            field=models.ManyToManyField(blank=True, help_text='Разделы, доступные пользователям этой организации', related_name='customers', to='project_customers.sitesection', verbose_name='Видимые разделы сайта'),
        ),
        migrations.CreateModel(
            name='CustomerAppAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_filter', models.CharField(choices=[('all', 'Все бренды'), ('selected', 'Выбранные бренды')], default='all', max_length=10, verbose_name='Фильтр брендов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_access', to='project_customers.allowedapp', verbose_name='Мини-приложение')),
                ('brands', models.ManyToManyField(blank=True, help_text="Учитывается только при brand_filter='selected'", to='producers.brands', verbose_name='Бренды')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_access', to='project_customers.projectcustomer', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Доступ к мини-приложению',
                'verbose_name_plural': 'Доступ к мини-приложениям',
                'unique_together': {('customer', 'app')},
            },
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('requests', 'Заявки'), ('invoices', 'Счета'), ('support', 'Техподдержка')], max_length=30, verbose_name='Тип уведомлений')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_emails', to='project_customers.projectcustomer', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Email для уведомлений',
                'verbose_name_plural': 'Email-адреса для уведомлений',
                'unique_together': {('customer', 'email_type', 'email')},
            },
        ),
    ]
