# Generated by Django 5.2.7 on 2026-07-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0006_projectcustomer_visible_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcustomeruser',
            name='role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('code', models.CharField(help_text='Машинное имя (латиница, без пробелов)', max_length=50, verbose_name='Код роли')),
                ('is_default', models.BooleanField(default=False, help_text='Назначается новым пользователям автоматически', verbose_name='По умолчанию')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='project_customers.projectcustomer', verbose_name='Организация')),
                ('section_permissions', models.ManyToManyField(blank=True, to='project_customers.sitesection', verbose_name='Доступ к разделам сайта')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['sorting_order', 'name'],
                'unique_together': {('customer', 'code')},
            },
        ),
        migrations.AddField(
            model_name='projectcustomeruser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='project_customers.role', verbose_name='Роли'),
        ),
    ]
