# Generated by Django 5.2.7 on 2026-07-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('project_customers', '0007_remove_projectcustomeruser_role_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomeruser',
            name='section_permissions',
            field=models.ManyToManyField(blank=True, help_text='Дополнительные разрешения поверх ролей (не могут превысить права организации)', related_name='users', to='project_customers.sitesection', verbose_name='Индивидуальный доступ к разделам'),
        ),
        migrations.CreateModel(
            name='FavoriteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Приоритет')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored_by_users', to='producers.brands', verbose_name='Бренд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_brands', to='project_customers.projectcustomeruser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Любимый бренд',
                'verbose_name_plural': 'Любимые бренды',
                'ordering': ['priority', 'brand__name'],
                'unique_together': {('user', 'brand')},
            },
        ),
    ]
