# Generated by Django 5.2.7 on 2026-07-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0008_projectcustomeruser_section_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Виджет НТА-Пром» или «LLM-агент Архимед»', max_length=100, verbose_name='Название ключа')),
                ('key_hash', models.CharField(help_text='SHA-256(raw_key)', max_length=128, verbose_name='Хэш ключа')),
                ('key_prefix', models.CharField(default='proj_live_', max_length=12, verbose_name='Префикс ключа')),
                ('brand_filters', models.JSONField(blank=True, default=dict, help_text='{"app_code": "all" | [brand_id, ...]} — сужает org-level доступ', verbose_name='Фильтры брендов')),
                ('ip_whitelist', models.TextField(blank=True, help_text='Список IP/подсетей через запятую. Пусто = без ограничений.', verbose_name='IP whitelist')),
                ('access_until', models.DateField(blank=True, help_text='Ограничение по времени действия ключа', null=True, verbose_name='Доступ до')),
                ('llm_endpoint', models.URLField(blank=True, help_text='URL своей LLM клиента (заготовка на будущее)', verbose_name='LLM endpoint')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('allowed_apps', models.ManyToManyField(blank=True, help_text='Подмножество от CustomerAppAccess организации', to='project_customers.allowedapp', verbose_name='Разрешённые мини-приложения')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='project_customers.projectcustomer', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'API-ключ',
                'verbose_name_plural': 'API-ключи',
            },
        ),
    ]
