# Generated by Django 5.2.7 on 2026-07-23 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0009_customerapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AddField(
            model_name='projectcustomeruser',
            name='password',
            field=models.CharField(blank=True, help_text='Хранится в хэшированном виде', max_length=128, verbose_name='Пароль (хэш)'),
        ),
        migrations.AlterField(
            model_name='projectcustomeruser',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Только для администраторов системы. Для клиентских пользователей — пусто.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
    ]
