# Generated by Django 5.2.7 on 2026-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0011_role_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomeruser',
            name='login',
            field=models.CharField(default='', help_text='Используется для входа в систему', max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='projectcustomeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
