# Generated by Django 5.2.4 on 2026-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0012_projectcustomeruser_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Machine name (latin, no spaces)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('object_permissions', models.JSONField(blank=True, default=dict, help_text='{codename: [view,edit,delete,manage]}', verbose_name='Object permissions')),
                ('is_default', models.BooleanField(default=False, help_text='Assign to new users automatically', verbose_name='Default')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Sorting order')),
            ],
            options={
                'verbose_name': 'System Group',
                'verbose_name_plural': 'System Groups',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectcustomeruser',
            name='system_groups',
            field=models.ManyToManyField(blank=True, to='project_customers.systemgroup', verbose_name='Системные группы'),
        ),
    ]
