# Generated by Django 5.2.4 on 2026-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0013_system_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcustomeruser',
            name='system_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='project_customers.systemgroup', verbose_name='Системные группы'),
        ),
    ]
