# Generated by Django 5.2.4 on 2026-08-04 18:54
# Data migration: split coarse SiteSections into granular ones.
# Runs BEFORE 0016_site_section_category which adds the category field.

from django.db import migrations

# Mapping: old_section_code → [(new_code, new_name)]
SECTION_SPLIT = {
    'catalog': [
        ('catalog_gearbox',      'Ручные дублёры'),
        ('catalog_pa',           'Пневмоприводы'),
        ('catalog_ea',           'Электроприводы'),
        ('catalog_lsb',          'Блоки концевых выключателей'),
        ('catalog_sv',           'Соленоидные клапаны'),
        ('catalog_fr',           'Фильтр-регуляторы'),
        ('catalog_pf',           'Пневмофитинги'),
        ('catalog_cg',           'Кабельные вводы'),
    ],
    'configurator': [
        ('configurator_pa',      'Конфигуратор ПП'),
        ('configurator_ea',      'Конфигуратор ЭП'),
        ('configurator_cab',     'Шкафы управления ЭП'),
    ],
}


def split_sections(apps, schema_editor):
    SiteSection = apps.get_model('project_customers', 'SiteSection')

    for old_code, new_sections in SECTION_SPLIT.items():
        try:
            old_section = SiteSection.objects.get(code=old_code)
        except SiteSection.DoesNotExist:
            continue

        for i, (new_code, new_name) in enumerate(new_sections):
            new_section, created = SiteSection.objects.get_or_create(
                code=new_code,
                defaults={
                    'name': new_name,
                    'is_active': True,
                    'sorting_order': i + 1,
                }
            )
            if not created:
                new_section.name = new_name
                new_section.is_active = True
                new_section.save()

            # Migrate: everyone who had old_section now also gets new_section
            for role in old_section.role_set.all():
                role.section_permissions.add(new_section)
            for user in old_section.users.all():
                user.section_permissions.add(new_section)
            for customer in old_section.customers.all():
                customer.visible_sections.add(new_section)

        # Deactivate old section
        old_section.is_active = False
        old_section.save()


def reverse_split(apps, schema_editor):
    SiteSection = apps.get_model('project_customers', 'SiteSection')

    # Reactivate old sections
    for old_code in SECTION_SPLIT:
        SiteSection.objects.filter(code=old_code).update(is_active=True)

    # Delete new granular sections
    for old_code, new_sections in SECTION_SPLIT.items():
        for new_code, _ in new_sections:
            SiteSection.objects.filter(code=new_code).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('project_customers', '0014_system_group_related_name'),
    ]
    operations = [
        migrations.RunPython(split_sections, reverse_split),
    ]
