# Generated by Django 5.2.4 on 2026-08-04 18:54

from django.db import migrations, models

CATEGORY_MAP = {
    # New granular sections
    'catalog_gearbox':    'catalog',
    'catalog_pa':         'catalog',
    'catalog_ea':         'catalog',
    'catalog_lsb':        'catalog',
    'catalog_sv':         'catalog',
    'catalog_fr':         'catalog',
    'catalog_pf':         'catalog',
    'catalog_cg':         'catalog',
    'configurator_pa':    'configurator',
    'configurator_ea':    'configurator',
    'configurator_cab':   'configurator',
    # Deactivated old sections
    'catalog':            'catalog',
    'configurator':       'configurator',
    # Sections that stay
    'admin_section':      'admin',
    'certificates':       'catalog',
    'llm_agent':          'ai',
    'requests':           'requests',
}


def populate_categories(apps, schema_editor):
    SiteSection = apps.get_model('project_customers', 'SiteSection')
    for code, cat in CATEGORY_MAP.items():
        SiteSection.objects.filter(code=code).update(category=cat)


def clear_categories(apps, schema_editor):
    SiteSection = apps.get_model('project_customers', 'SiteSection')
    SiteSection.objects.all().update(category='')


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0015_split_site_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='category',
            field=models.CharField(
                default='', max_length=50,
                help_text='Группировка разделов в UI (catalog, configurator, admin, ai)',
                verbose_name='Категория',
            ),
        ),
        migrations.RunPython(populate_categories, clear_categories),
    ]
