# Generated by Django 5.2.4 on 2026-08-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_customers', '0016_site_section_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='django_user',
        ),
    ]
