# Generated by DeepSeek TUI on 2026-05-21
# sku/migrations/0002_sku_description.py
#
# Добавление поля description в SKU.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание', help_text='Описание номенклатурной позиции'),
        ),
    ]
