# Generated by Django 4.2.23 on 2026-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_sku_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sku',
            new_name='sku_sku_code_2a026c_idx',
            old_name='sku_sku_code_idx',
        ),
        migrations.RenameIndex(
            model_name='sku',
            new_name='sku_sku_equipme_04256d_idx',
            old_name='sku_sku_eq_type_idx',
        ),
        migrations.RenameIndex(
            model_name='sku',
            new_name='sku_sku_brand_i_767028_idx',
            old_name='sku_sku_brand_idx',
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.TextField(help_text='Наименование товара/услуги', verbose_name='Наименование'),
        ),
    ]
