# Generated by Django 4.2.23 on 2026-05-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('sku', '0003_rename_sku_sku_code_idx_sku_sku_code_2a026c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Производитель / бренд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.brands', verbose_name='Бренд'),
        ),
    ]
