# Generated by Django 5.2.4 on 2026-07-30 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0016_compositiongroup'),
        ('core', '0005_add_title_template_to_equipment_type'),
        ('project_customers', '0012_projectcustomeruser_login_and_more'),
        ('sku', '0004_alter_sku_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название спецификации', max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код MBOM', max_length=100, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('conversation', models.ForeignKey(blank=True, help_text='Связанная сессия AI-ассистента (если создана через подбор)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mboms', to='ai_assistant.aiconversation', verbose_name='Сессия AI-подбора')),
                ('customer', models.ForeignKey(blank=True, help_text='Привязка к клиенту (null = системная спецификация)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mboms', to='project_customers.projectcustomer', verbose_name='Клиент проекта')),
                ('user', models.ForeignKey(blank=True, help_text='Приватная спецификация пользователя (null = общая/клиентская)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mboms', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'MBOM (Спецификация)',
                'verbose_name_plural': 'MBOM (Спецификации)',
                'db_table': 'sku_mbom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('quantity_unit', models.CharField(blank=True, default='шт', max_length=32, verbose_name='Ед. изм.')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition_group', models.ForeignKey(blank=True, help_text='Группа композиции, к которой относится элемент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mbom_items', to='ai_assistant.compositiongroup', verbose_name='Composition Group')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mbom_items', to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('mbom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sku.mbom', verbose_name='Спецификация')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский элемент для иерархии', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sku.mbomitem', verbose_name='Родительский элемент')),
                ('sku', models.ForeignKey(blank=True, help_text='Выбранная номенклатурная позиция', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mbom_items', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Элемент MBOM',
                'verbose_name_plural': 'Элементы MBOM',
                'db_table': 'sku_mbom_item',
                'ordering': ['mbom', 'position'],
            },
        ),
    ]
