# Generated by Django 5.2.7 on 2026-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0005_mbom_mbomitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(help_text='Уникальный артикул номенклатуры', max_length=255, unique=True, verbose_name='Код'),
        ),
    ]
