# Generated by Django 5.2.7 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0022_alter_equipmenttype_title_template'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('sku', '0006_alter_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(help_text='Уникальный артикул номенклатуры (внутри бренда)', max_length=255, verbose_name='Код'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('code',), name='sku_code_uniq_nobrand'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', False)), fields=('code', 'brand'), name='sku_code_brand_uniq'),
        ),
    ]
