# Generated by Django 5.1.4 on 2024-12-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzra1', '000X_auto_add_initial_data'),
    ]

    operations = [
    ]
