# Generated by Django 5.1.4 on 2024-12-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzra1', '0001_auto_20241229_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_value', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_value', models.CharField(max_length=3, unique=True)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzra1.ipchoice')),
                ('temp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzra1.tempchoice')),
            ],
        ),
    ]
