# Generated by Django 5.2.7 on 2026-08-10 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_requests', '0010_add_climatic_designation'),
        ('project_customers', '0017_remove_role_django_user'),
        ('sku', '0005_mbom_mbomitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_type', models.CharField(choices=[('cart', 'Корзина'), ('favorites', 'Избранное')], default='cart', max_length=20, verbose_name='Тип')),
                ('name', models.CharField(blank=True, help_text='Например, «Подбор для объекта X»', max_length=200, verbose_name='Название')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('ordered', 'Оформлена'), ('abandoned', 'Брошена')], default='active', max_length=20, verbose_name='Статус')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Для неавторизованных пользователей', max_length=40, null=True, verbose_name='Ключ сессии')),
                ('client_request', models.ForeignKey(blank=True, help_text='Заявка, созданная из этой корзины при оформлении', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carts', to='client_requests.clientrequest', verbose_name='Созданная заявка')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='project_customers.projectcustomeruser', verbose_name='Сотрудник')),
                ('project_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='project_customers.projectcustomer', verbose_name='Клиент (компания)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Корзина создана'), ('item_added', 'Позиция добавлена'), ('item_removed', 'Позиция удалена'), ('item_qty', 'Количество изменено'), ('renamed', 'Переименована'), ('ordered', 'Оформлена'), ('abandoned', 'Удалена')], max_length=20, verbose_name='Тип события')),
                ('data', models.JSONField(blank=True, default=dict, help_text='item_id, old_name, new_name, quantity и т.д.', verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cart.cart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Событие корзины',
                'verbose_name_plural': 'События корзин',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Корзина')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
                'ordering': ['added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'cart_type', 'status'], name='cart_cart_user_id_521b60_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'cart_type'], name='cart_cart_session_e5062d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['project_customer', 'status'], name='cart_cart_project_3ab018_idx'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['cart', '-created_at'], name='cart_cartev_cart_id_008c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['event_type', '-created_at'], name='cart_cartev_event_t_2cf6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['sku'], name='cart_cartit_sku_id_f3faac_idx'),
        ),
    ]
