# Generated by Django 5.2.7 on 2026-08-10 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('client_requests', '0010_add_climatic_designation'),
        ('project_customers', '0017_remove_role_django_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание/назначение корзины (например, ОЛ, объект)', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active_cart',
            field=models.BooleanField(default=False, help_text='Указатель — в какую корзину добавлять товары. Только одна на пользователя.', verbose_name='Активная корзина'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, help_text='Краткое название для идентификации среди других корзин', max_length=200, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active_cart'], name='cart_cart_user_id_0b0dc1_idx'),
        ),
    ]
