# Generated by Django 5.2.7 on 2026-08-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_description_cart_is_active_cart_alter_cart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_currency',
            field=models.CharField(blank=True, help_text='RUB — после конвертации из USD по курсу.', max_length=3, verbose_name='Валюта цены'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_date',
            field=models.DateField(blank=True, help_text='Если < сегодня → пересчитать по курсу.', null=True, verbose_name='Дата цены'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена в RUB на дату price_date. Обновляется раз в день.', max_digits=12, null=True, verbose_name='Цена (кеш)'),
        ),
    ]
