# Generated by Django 5.2.4 on 2026-09-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_price_currency_cartitem_price_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_snapshot',
        ),
    ]
