# Generated by Django 4.2.23 on 2026-01-27 18:33

import core.models.mixins
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(blank=True, help_text='Основное название объекта', max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код объекта', max_length=100, null=True, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('icon', models.CharField(blank=True, help_text='Иконка для отображения (emoji или название класса CSS)', max_length=50, verbose_name='Иконка')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень иерархии')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский тип оборудования для иерархии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='features.equipmenttype', verbose_name='Родительский тип')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['level', 'sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeatureVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(blank=True, help_text='Основное название объекта', max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код объекта', max_length=100, null=True, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('data_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('select', 'Выбор из списка'), ('range', 'Диапазон'), ('file', 'Файл'), ('link', 'Ссылка')], default='text', max_length=20, verbose_name='Тип данных')),
                ('choices', models.TextField(blank=True, help_text="Для типа 'select'. Каждый вариант с новой строки", verbose_name='Варианты выбора')),
                ('unit', models.CharField(blank=True, help_text='Например: В, А, МПа, кг, мм и т.д.', max_length=50, verbose_name='Единица измерения')),
                ('is_required', models.BooleanField(default=False, help_text='Характеристика обязательна для заполнения', verbose_name='Обязательное поле')),
                ('min_value', models.FloatField(blank=True, help_text='Минимальное значение (для чисел)', null=True, verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(blank=True, help_text='Максимальное значение (для чисел)', null=True, verbose_name='Максимальное значение')),
                ('validation_regex', models.CharField(blank=True, help_text='Регулярное выражение для валидации текста', max_length=200, verbose_name='Регулярное выражение')),
                ('default_value', models.TextField(blank=True, help_text='Значение по умолчанию для этой характеристики', verbose_name='Значение по умолчанию')),
                ('help_text', models.TextField(blank=True, help_text='Подсказка для пользователя при заполнении', verbose_name='Подсказка для заполнения')),
                ('equipment_types', models.ManyToManyField(blank=True, help_text='Типы оборудования, для которых применяется эта характеристика', related_name='feature_varieties', to='features.equipmenttype', verbose_name='Типы оборудования')),
            ],
            options={
                'verbose_name': 'Вид характеристики',
                'verbose_name_plural': 'Виды характеристик',
                'ordering': ['sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(blank=True, help_text='Основное название объекта', max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код объекта', max_length=100, null=True, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('features_data', models.JSONField(default=list, help_text="Список характеристик: [{'type_id': X, 'default_value': '...', 'order': X}]", verbose_name='Характеристики шаблона')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать этот шаблон по умолчанию для данного типа оборудования', verbose_name='Шаблон по умолчанию')),
                ('equipment_type', models.ForeignKey(help_text='Тип оборудования, для которого создается шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='feature_templates', to='features.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Шаблон характеристик',
                'verbose_name_plural': 'Шаблоны характеристик',
                'ordering': ['equipment_type', 'is_default', 'sorting_order', 'name'],
                'unique_together': {('equipment_type', 'is_default')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(blank=True, help_text='Основное название объекта', max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Уникальный код объекта', max_length=100, null=True, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('object_id', models.PositiveIntegerField(help_text='ID объекта, к которому привязан набор характеристик', verbose_name='ID объекта')),
                ('feature_values', models.JSONField(default=dict, help_text='Словарь {feature_id: value}', verbose_name='Значения характеристик')),
                ('is_approved', models.BooleanField(default=False, help_text='Набор характеристик утвержден и не подлежит изменению', verbose_name='Утвержден')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_feature_sets', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('content_type', models.ForeignKey(help_text='Тип объекта, к которому привязан набор характеристик', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('feature_template', models.ForeignKey(help_text='Шаблон, на основе которого создается набор', on_delete=django.db.models.deletion.CASCADE, related_name='feature_sets', to='features.featuretemplate', verbose_name='Шаблон характеристик')),
            ],
            options={
                'verbose_name': 'Набор характеристик',
                'verbose_name_plural': 'Наборы характеристик',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('content_type', 'object_id', 'feature_template')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
