# Generated by Django 5.2.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretemplate',
            name='equipment_type',
            field=models.ForeignKey(help_text='Тип оборудования, для которого создается шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='feature_templates', to='core.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='featurevariety',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, help_text='Типы оборудования, для которых применяется эта характеристика', related_name='feature_varieties', to='core.equipmenttype', verbose_name='Типы оборудования'),
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
    ]
