# Generated by Django 5.2.4 on 2026-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SvgConversionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='svg_converter/originals/', verbose_name='Исходный файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя исходного файла')),
                ('original_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('original_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('region_x', models.FloatField(blank=True, null=True, verbose_name='X области')),
                ('region_y', models.FloatField(blank=True, null=True, verbose_name='Y области')),
                ('region_w', models.FloatField(blank=True, null=True, verbose_name='Ширина области')),
                ('region_h', models.FloatField(blank=True, null=True, verbose_name='Высота области')),
                ('color_mode', models.CharField(choices=[('bw', 'Чёрно-белый'), ('color', 'Цветной')], default='bw', max_length=20, verbose_name='Режим цвета')),
                ('threshold', models.PositiveSmallIntegerField(default=128, help_text='0–255, по умолчанию 128', verbose_name='Порог бинаризации')),
                ('svg_content', models.TextField(blank=True, verbose_name='SVG-содержимое')),
                ('svg_file', models.FileField(blank=True, null=True, upload_to='svg_converter/results/', verbose_name='SVG-файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Сессия SVG-конвертации',
                'verbose_name_plural': 'Сессии SVG-конвертации',
            },
        ),
    ]
