# Generated by Django 5.2.4 on 2026-07-13 17:31

import storage_manager.fields
import storage_manager.storage_backends.cloudru
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svg_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgconversionsession',
            name='original_file',
            field=storage_manager.fields.ManagedFileField(storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='svg_converter/originals/', verbose_name='Исходный файл'),
        ),
        migrations.AlterField(
            model_name='svgconversionsession',
            name='svg_file',
            field=storage_manager.fields.ManagedFileField(blank=True, null=True, storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='svg_converter/results/', verbose_name='SVG-файл'),
        ),
    ]
