# Generated by Django 5.1.4 on 2025-02-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0007_mechanicalindicatorinstalledoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='EttDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Короткое название ЕТТ для отображения на экране', max_length=50)),
                ('full_name', models.CharField(blank=True, help_text='Полное название ЕТТ по документам владельца', max_length=50)),
                ('ett_code', models.CharField(blank=True, help_text='Код ЕТТ по кодировке владельца', max_length=200)),
                ('owner_name', models.CharField(blank=True, help_text='Название компании владельца ЕТТ', max_length=50)),
                ('applies_to', models.ManyToManyField(blank=True, help_text='Вид арматуры, к которой применимы ett', related_name='ett_applies_to_valve_type', to='params.valvetypes')),
            ],
        ),
        migrations.CreateModel(
            name='EttControlUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Наличие блока управления и его расположение', max_length=20)),
                ('param_name', models.CharField(default='Наличие блока управления и его расположение', help_text='Название параметра Наличие блока управления и его расположение', max_length=100)),
                ('text_description', models.CharField(blank=True, help_text='Наличие блока управления и его расположение ', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_control_unit_type', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttControlUnitHeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Наличие встроенного электрообогрева блока управления', max_length=20)),
                ('param_name', models.CharField(default='Наличие встроенного электрообогрева блока управления', help_text='Название параметра Наличие встроенного электрообогрева блока управления', max_length=100)),
                ('text_description', models.CharField(blank=True, help_text='Полное описание описание встроенного электрообогрева блока управления', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_control_unit_heater', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttControlUnitDisplayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Наличие графического дисплея', max_length=20)),
                ('param_name', models.CharField(default='Наличие графического дисплея', help_text='Название параметра Наличие графического дисплея', max_length=100)),
                ('text_description', models.CharField(blank=True, help_text='Наличие графического дисплея', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_control_unit_display_type', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttControlSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Краткое описание сигнала управления Открыть/Закрыть/Стоп', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Полное описание описание сигнала управления Открыть/Закрыть/Стоп тип управляющего сигнала/протокол передачи ', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_control_signal', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttClimaticOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка климатического исполнения', max_length=5)),
                ('work_temp_min', models.IntegerField(help_text='НИЖНЕЕ РАБОЧЕЕ ЗНАЧЕНИЕ ТЕМПЕРАТУРЫ ОКРУЖАЮЩЕГО ВОЗДУХА, ºС')),
                ('work_temp_max', models.IntegerField(help_text='ВЕРХНЕЕ РАБОЧЕЕ ЗНАЧЕНИЕ ТЕМПЕРАТУРЫ ОКРУЖАЮЩЕГО ВОЗДУХА, ºС')),
                ('extremal_temp_min', models.IntegerField(help_text='НИЖНЕЕ ПРЕДЕЛЬНОЕ ЗНАЧЕНИЕ ТЕМПЕРАТУРЫ ОКРУЖАЮЩЕГО ВОЗДУХА, ºС')),
                ('extremal_temp_max', models.IntegerField(help_text='ВЕРХНЕЕ ПРЕДЕЛЬНОЕ ЗНАЧЕНИЕ ТЕМПЕРАТУРЫ ОКРУЖАЮЩЕГО ВОЗДУХА, ºС')),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание климатического исполнения', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_climatic_option', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttCableGlandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка типа кабельного ввода', max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Наличие графического дисплея', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_cable_gland_type', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttActuatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка типа привода', max_length=5)),
                ('actuator_type', models.CharField(choices=[('Электро', 'Электро'), ('Пневмо', 'Пневмо'), ('Электро-гидро', 'Электро-гидро'), ('Пневмо-гидро', 'Пневмо-гидро'), ('Ручной', 'Ручной')], max_length=20)),
                ('actuator_speed', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Быстродействующий', 'Быстродействующий')], max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа привода', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_actuator_type', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='DnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Dn', max_length=5)),
                ('valve_dn_value', models.IntegerField(help_text='Dn, мм')),
                ('pipe_dn_value', models.IntegerField(blank=True, help_text='Наружный диаметр присоединяемого трубопровода, мм')),
                ('comment', models.CharField(blank=True, help_text='Комментарий', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_dn_type', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttElectricOptionsCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка ЭЛЕКТРОТЕХНИЧЕСКИЕ ХАРАКТЕРИСТИКИ', max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание кодировки ЭЛЕКТРОТЕХНИЧЕСКИЕ ХАРАКТЕРИСТИКИ', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ForeignKey(blank=True, help_text='Документ технических требований, где описаны эти требования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_document_electric_combination', to='ett.ettdocument')),
                ('exd_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_electric_combination_exd_choice', to='params.exdoption')),
                ('ip_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_electric_combination_exd_choice', to='params.ipoption')),
                ('power_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_electric_combination_power_choice', to='params.powersupplies')),
            ],
        ),
        migrations.CreateModel(
            name='EttFeedbackSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка сигнала обратной связи', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Полное описание описание сигнала сигнала обратной связи', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_feedback_signal', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttMediumMaxTempOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Температура рабочей среды (стенки) максимальная расчетная, ºС', max_length=5)),
                ('work_temp_max', models.IntegerField(blank=True, help_text='Температура рабочей среды (стенки) максимальная расчетная, ºС')),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание Температура рабочей среды (стенки) максимальная расчетная, ºС', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_medium_max_temp', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttOtherOptionsCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка ОПЦИИ/КОМПЛЕКТУЮЩИЕ', max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание кодировки ОПЦИИ/КОМПЛЕКТУЮЩИЕ', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('cg1_choice', models.ForeignKey(help_text='КВ1, КАБЕЛЬНЫЙ ВВОД ДЛЯ СИЛОВОГО КАБЕЛЯ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_other_options_combination_cg1_choice', to='ett.ettcableglandtype')),
                ('cg23_choice', models.ForeignKey(help_text='КАБЕЛЬНЫЙ ВВОД КВ2/КВ3 ДЛЯ КОНТРОЛЬНОГО И ИНТЕРФЕЙСНОГО КАБЕЛЕЙ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_other_options_combination_cg23_choice', to='ett.ettcableglandtype')),
                ('cu_heater_choice', models.ForeignKey(help_text='НАЛИЧИЕ ВСТРОЕННОГО ЭЛЕКТРООБОГРЕВА БЛОКА УПРАВЛЕНИЯ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_other_options_combination_cu_heater_choice', to='ett.ettcontrolunitheater')),
                ('cu_location_choice', models.ForeignKey(help_text='НАЛИЧИЕ БЛОКА УПРАВЛЕНИЯ И ЕГО РАСПОЛОЖЕНИЕ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_other_options_combination_cu_location_type_choice', to='ett.ettcontrolunittype')),
                ('display_choice', models.ForeignKey(help_text='ГРАФИЧЕСКИЙ ДИСПЛЕЙ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_other_options_combination_display_choice', to='ett.ettcontrolunitdisplaytype')),
                ('ett_doc', models.ForeignKey(blank=True, help_text='Документ технических требований, где описаны эти требования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_document_other_option_combination', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttSeismicOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Исполнения по сейсмостойкости', max_length=5)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание Исполнения по сейсмостойкости', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_seismic_option', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttStatusSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Краткое описание сигнала состояния Открыто/Закрыто/Стоп/Авария/Дистанционный режим/Готовность', max_length=50)),
                ('text_description', models.CharField(blank=True, help_text='Полное описание описание сигнала состояния Открыто/Закрыто/Стоп/Авария/Дистанционный режим/Готовность, тип сигнала и напряжение/протокол передачи ', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_status_signal', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttControlOptionsCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Контроль и Управление', max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание кодировки Контроль и управление', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('control_signal_choice', models.ForeignKey(blank=True, help_text='Сигналы управления Открыть/Закрыть/Стоп', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_control_combination_control_signal_choice', to='ett.ettcontrolsignal')),
                ('ett_doc', models.ForeignKey(blank=True, help_text='Документ технических требований, где описаны эти требования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_document_control_combination', to='ett.ettdocument')),
                ('feedback_signal_choice', models.ForeignKey(blank=True, help_text='Сигнал обратной связи ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_control_combination_feedback_signal_choice', to='ett.ettfeedbacksignal')),
                ('status_signal_choice', models.ForeignKey(blank=True, help_text='Сигналы состояния Открыто/Закрыто/Стоп/Авария/Дистанционный режим/Готовность', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_control_combination_status_signal_choice', to='ett.ettstatussignal')),
            ],
        ),
        migrations.CreateModel(
            name='MtrType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьное обозначение типа арматуры', max_length=5)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание типа арматуры', max_length=500)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_mtr_type', to='ett.ettdocument')),
            ],
        ),
        migrations.CreateModel(
            name='EttOpenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(blank=True, help_text='Символьная кодировка времени открытия/закрытия', max_length=35)),
                ('dn_from', models.IntegerField(help_text='Dn свыше, мм')),
                ('dn_up_to', models.IntegerField(help_text='DN до, включительно, мм')),
                ('time_to_open_min', models.IntegerField(help_text='Минимальное время открытия, с')),
                ('time_to_open_max', models.IntegerField(help_text='Максимальное время открытия, с')),
                ('actuator_speed', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Быстродействующий', 'Быстродействующий')], help_text='Тип привода (быстродействующий или стандартный)', max_length=20)),
                ('text_description', models.CharField(blank=True, help_text='Текстовое описание времени открытия', max_length=200)),
                ('source_table_number', models.CharField(blank=True, help_text='Номер таблицы в документе, где описан этот параметр', max_length=50)),
                ('source_table_name', models.CharField(blank=True, help_text='Название таблицы в документе, где описан этот параметр', max_length=300)),
                ('ett_doc', models.ManyToManyField(blank=True, help_text='Документ технических требований, где описаны эти требования', related_name='ett_document_open_time', to='ett.ettdocument')),
                ('mtr_type', models.ManyToManyField(help_text='Тип арматуры, для которой установлено это время открытия/закрытия', related_name='ett_open_time_mtr_type', to='ett.mtrtype')),
            ],
        ),
        migrations.CreateModel(
            name='PnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_code', models.CharField(help_text='Символьная кодировка Pn', max_length=5)),
                ('valve_pn_value', models.IntegerField(help_text='PN, кгс/см²')),
                ('pn_measure_unit', models.ForeignKey(default=11, help_text='Единица измерения Pn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.measureunits')),
            ],
        ),
    ]
