# Generated by Django 5.2.4 on 2026-05-05 14:52

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pa_controls', '0016_alter_limitswitchbody_description_and_more'),
        ('params', '0049_lockingmechanism'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название тип механизма отключения', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код механизма отключения', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа механизма отключения', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Механизм отключения (вид дублера)',
                'verbose_name_plural': 'Механизмы отключения (виды дублеров)',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название тип механизма передачи', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код серии редукторов', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа механизма отключения', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Механизм передачи',
                'verbose_name_plural': 'Механизмы передачи',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='GearBoxBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Текстовое название модели редуктора', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели редуктора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели редуктора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('reduction_ratio', models.DecimalField(decimal_places=2, help_text='Передаточное число (i) - изменение скорости', max_digits=7, verbose_name='Передат.число (i)')),
                ('reduction_ratio_text', models.CharField(help_text='Передаточное число (текст - Например, "40:1")', max_length=20, verbose_name='Передаточное число (текст)')),
                ('reduction_ratio_verified', models.DecimalField(decimal_places=2, help_text='Передаточное число (i) проверенное - изменение скорости', max_digits=7, verbose_name='Передат.число проверенное')),
                ('amplification_factor', models.DecimalField(decimal_places=2, help_text='Коэффициент усиления момента (MA)', max_digits=7, verbose_name='К усиления')),
                ('amplification_factor_verified', models.DecimalField(decimal_places=2, help_text='Коэффициент усиления момента (MA)', max_digits=7, verbose_name='К усиления')),
                ('efficiency', models.DecimalField(decimal_places=3, default=0.4, help_text='КПД (η) Учитывает потери на трение в передаче', max_digits=4, verbose_name='КПД (η)')),
                ('max_input_torque', models.DecimalField(decimal_places=2, help_text='Момент, который можно приложить к штурвалу', max_digits=10, verbose_name='Макс. входной момент (Нм)')),
                ('max_output_torque', models.DecimalField(decimal_places=2, help_text='Критический момент, который выдержит редуктор', max_digits=10, verbose_name='Макс. выходной момент (Нм)')),
                ('handwheel_force_nominal', models.DecimalField(blank=True, decimal_places=2, help_text='Усилие на ободе штурвала при достижении макс. выходного момента', max_digits=7, null=True, verbose_name='Усилие на штурвале (Н)')),
                ('handwheel_diameter', models.PositiveIntegerField(help_text='Монтажная площадка', verbose_name='Диаметр штурвала (мм)')),
                ('stem_height_top', models.PositiveIntegerField(blank=True, help_text='Глубина отверстия под шток арматуры', null=True, verbose_name='Высота штока')),
                ('stem_height_bottom', models.PositiveIntegerField(blank=True, help_text='Глубина отверстия под шток арматуры', null=True, verbose_name='Высота штока')),
                ('max_stem_diameter_bottom', models.PositiveIntegerField(blank=True, help_text='Максимальный диаметр отверстия под шток арматуры', null=True, verbose_name='Макс шток')),
                ('mechanical_advantage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Механическое преимущество')),
                ('mounting_plate_bottom', models.ManyToManyField(blank=True, help_text='Монтажная площадка к приводу', related_name='mounting_plate_bottom', to='params.mountingplatetypes', verbose_name='Монт.площадка к приводу')),
                ('mounting_plate_top', models.ManyToManyField(blank=True, help_text='Монтажная площадка', related_name='mounting_plate_top', to='params.mountingplatetypes', verbose_name='Монт.площадка')),
                ('stem_shape_bottom', models.ForeignKey(blank=True, help_text='Тип штока к арматуре', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_shape_bottom', to='params.stemshapes', verbose_name='Тип штока к арматуре')),
                ('stem_shape_top', models.ForeignKey(blank=True, help_text='Тип отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_shape_top', to='params.stemshapes', verbose_name='Тип штока')),
                ('stem_size_bottom', models.ForeignKey(blank=True, help_text='Размер отверстия к арматуре', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_size_bottom', to='params.stemsize', verbose_name='Размер штока')),
                ('stem_size_top', models.ForeignKey(blank=True, help_text='Размер отверстия под шток арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_size_top', to='params.stemsize', verbose_name='Размер штока')),
                ('transmission_variety', models.ForeignKey(blank=True, help_text='Тип передачи (трансмисии)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmission_variety', to='gearbox.transmissionvariety', verbose_name='Тип передачи')),
            ],
            options={
                'verbose_name': 'Корпус редуктора',
                'verbose_name_plural': 'Корпуса редукторов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.CopyMixin, core.models.mixins.TemplateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GearBoxInterlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Текстовое название модели интерлока редуктора', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели редуктора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели интерлока редуктора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('interlock_points', models.IntegerField(default=2, help_text='Количество точек переключения (датчиков) интерлока', verbose_name='Количество датчиков')),
                ('interlock_exd', models.ManyToManyField(blank=True, help_text='Степень взрывозащиты интерлока (можно выбрать несколько вариантов)', related_name='gearbox_interlock_exd', to='params.exdoption', verbose_name='Взрывозащита')),
                ('interlock_ip', models.ForeignKey(help_text='Степень защиты IP интерлока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_interlock_ip', to='params.ipoption', verbose_name='IP')),
                ('interlock_sensor_components', models.ManyToManyField(blank=True, help_text='Установленные датчики интерлока', related_name='interlock_sensor_components', to='pa_controls.sensorcomponent', verbose_name='Датчики')),
                ('interlock_sensor_variety', models.ForeignKey(help_text='Тип сенсора интерлока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interlock_sensor_variety', to='pa_controls.limitswitchsensorvariety', verbose_name='Тип сенсора')),
            ],
            bases=(core.models.mixins.CopyMixin, core.models.mixins.TemplateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GearBoxModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название серии редуктора', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код серии редукторов', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности серии редукторов', verbose_name='Описание')),
                ('name_template', models.TextField(blank=True, help_text='Шаблон для текстового названия редуктора', null=True, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания редуктора', null=True, verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд серии редукторов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_line_brand', to='producers.brands', verbose_name='Бренд')),
                ('gearbox_output_variety', models.ForeignKey(blank=True, help_text='Тип выхода редуктора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_variety_model_line', to='params.actuatorgearboxoutputtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Серия редукторов',
                'verbose_name_plural': 'Серии редукторов',
                'ordering': ['brand', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GearBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Текстовое название модели редуктора', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели редуктора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели редуктора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('body_material_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал корпуса')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С')),
                ('is_declutchable', models.BooleanField(default=True, help_text='Можно ли физически отсоединить штурвал от привода', verbose_name='Выключаемый (Declutchable)')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('ip', models.ForeignKey(help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_ip', to='params.ipoption', verbose_name='IP')),
                ('locking_mechanism', models.ForeignKey(help_text='Механизм блокировки дублера/переключателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.lockingmechanism', verbose_name='Механизм блокировки')),
                ('body', models.ForeignKey(help_text='Корпус редуктора с писанием свойств', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gearbox.gearboxbody', verbose_name='Корпус редуктора')),
                ('interlock', models.ForeignKey(blank=True, help_text='Модель интерлока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_interlock', to='gearbox.gearboxinterlock', verbose_name='Модель интерлока')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия модели редуктора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_box_model_line', to='gearbox.gearboxmodelline', verbose_name='Серия')),
                ('override_mechanism', models.ForeignKey(help_text='Механизм отключения дублера', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gearbox.overridemechanism', verbose_name='Механизм отключения')),
            ],
            options={
                'verbose_name': 'Редуктор',
                'verbose_name_plural': 'Редукторы',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.CopyMixin, core.models.mixins.TemplateMixin, models.Model),
        ),
    ]
