# Generated by Django 5.2.4 on 2026-05-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gearboxinterlock',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Интерлок', 'verbose_name_plural': 'Механизмы интерлоков'},
        ),
    ]
