# Generated by Django 5.2.4 on 2026-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0002_alter_gearboxinterlock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearboxbody',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес', max_digits=5, null=True, verbose_name='Вес, кг'),
        ),
    ]
