# Generated by Django 4.2.23 on 2026-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0003_gearboxbody_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxbody',
            name='amplification_factor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Коэффициент усиления момента (MA)', max_digits=7, null=True, verbose_name='К усиления'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='amplification_factor_verified',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Коэффициент усиления момента (MA)', max_digits=7, null=True, verbose_name='К усиления'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.4, help_text='КПД (η) Учитывает потери на трение в передаче', max_digits=4, null=True, verbose_name='КПД (η)'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='handwheel_diameter',
            field=models.PositiveIntegerField(blank=True, help_text='Монтажная площадка', null=True, verbose_name='Диаметр штурвала (мм)'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='max_input_torque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Момент, который можно приложить к штурвалу', max_digits=10, null=True, verbose_name='Макс. входной момент (Нм)'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='max_output_torque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Критический момент, который выдержит редуктор', max_digits=10, null=True, verbose_name='Макс. выходной момент (Нм)'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='name',
            field=models.CharField(blank=True, help_text='Текстовое название модели редуктора', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='reduction_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Передаточное число (i) - изменение скорости', max_digits=7, null=True, verbose_name='Передат.число (i)'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='reduction_ratio_text',
            field=models.CharField(blank=True, help_text='Передаточное число (текст - Например, "40:1")', max_length=20, null=True, verbose_name='Передаточное число (текст)'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='reduction_ratio_verified',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Передаточное число (i) проверенное - изменение скорости', max_digits=7, null=True, verbose_name='Передат.число проверенное'),
        ),
    ]
