# Generated by Django 4.2.23 on 2026-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0004_alter_gearboxbody_amplification_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxbody',
            name='amplification_factor_verified',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Коэффициент усиления момента (MA)проверенное', max_digits=7, null=True, verbose_name='К усиления проверенное'),
        ),
    ]
