# Generated by Django 4.2.23 on 2026-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0005_alter_gearboxbody_amplification_factor_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxbody',
            name='max_stem_diameter_bottom',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальный диаметр отверстия под шток арматуры', max_digits=5, null=True, verbose_name='Макс шток'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_height_bottom',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Глубина отверстия под шток арматуры', max_digits=5, null=True, verbose_name='Высота штока'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_height_top',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Глубина отверстия под шток арматуры', max_digits=5, null=True, verbose_name='Высота штока'),
        ),
    ]
