# Generated by Django 4.2.23 on 2026-05-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
        ('gearbox', '0006_alter_gearboxbody_max_stem_diameter_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxbody',
            name='mounting_plate_bottom',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка к арматуре', related_name='mounting_plate_bottom', to='params.mountingplatetypes', verbose_name='Монт.площадка к арматуре'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='mounting_plate_top',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка к приводу', related_name='mounting_plate_top', to='params.mountingplatetypes', verbose_name='Монт.площадка'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_height_bottom',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Глубина отверстия под шток арматуры', max_digits=5, null=True, verbose_name='Глубина под шток'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_height_top',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Высота штока к приводу', max_digits=5, null=True, verbose_name='Высота штока'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_shape_top',
            field=models.ForeignKey(blank=True, help_text='Тип отверстия к приводу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_shape_top', to='params.stemshapes', verbose_name='Тип штока'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_size_top',
            field=models.ForeignKey(blank=True, help_text='Размер отверстия к приводу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_size_top', to='params.stemsize', verbose_name='Размер штока'),
        ),
    ]
