# Generated by Django 4.2.23 on 2026-05-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
        ('gearbox', '0007_alter_gearboxbody_mounting_plate_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxbody',
            name='mounting_plate_top',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка к приводу', related_name='mounting_plate_top', to='params.mountingplatetypes', verbose_name='Монт.площадка к приводу'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_shape_top',
            field=models.ForeignKey(blank=True, help_text='Тип отверстия к приводу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_shape_top', to='params.stemshapes', verbose_name='Тип штока к приводу'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='stem_size_top',
            field=models.ForeignKey(blank=True, help_text='Размер отверстия к приводу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stem_size_top', to='params.stemsize', verbose_name='Размер штока к приводу'),
        ),
    ]
