# Generated by Django 4.2.23 on 2026-05-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
        ('gearbox', '0008_alter_gearboxbody_mounting_plate_top_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbox',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Корпус редуктора с писанием свойств', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gearbox.gearboxbody', verbose_name='Корпус редуктора'),
        ),
        migrations.AlterField(
            model_name='gearbox',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', null=True, verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='gearbox',
            name='ip',
            field=models.ForeignKey(blank=True, help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_ip', to='params.ipoption', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='gearbox',
            name='locking_mechanism',
            field=models.ForeignKey(blank=True, help_text='Механизм блокировки дублера/переключателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.lockingmechanism', verbose_name='Механизм блокировки'),
        ),
        migrations.AlterField(
            model_name='gearbox',
            name='override_mechanism',
            field=models.ForeignKey(blank=True, help_text='Механизм отключения дублера', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gearbox.overridemechanism', verbose_name='Механизм отключения'),
        ),
    ]
