# Generated by Django 4.2.23 on 2026-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0009_alter_gearbox_body_alter_gearbox_extra_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxmodelline',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание разновидности серии редукторов', null=True, verbose_name='Описание'),
        ),
    ]
