# Generated by Django 4.2.23 on 2026-05-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
        ('gearbox', '0010_alter_gearboxmodelline_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearboxVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название разновидности редуктора', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код разновидности редуктора', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности редуктора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Разновидность редуктора',
                'verbose_name_plural': 'Разновидности редукторов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AlterField(
            model_name='gearboxmodelline',
            name='gearbox_output_variety',
            field=models.ForeignKey(blank=True, help_text='Тип выхода редуктора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_output_variety_model_line', to='params.actuatorgearboxoutputtype', verbose_name='Тип выхода'),
        ),
        migrations.AddField(
            model_name='gearboxmodelline',
            name='gearbox_variety',
            field=models.ForeignKey(blank=True, help_text='Тип редуктора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_variety_model_line', to='gearbox.gearboxvariety', verbose_name='Тип'),
        ),
    ]
