# Generated by Django 4.2.23 on 2026-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0011_gearboxvariety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearboxmodelline',
            name='turn_angle',
            field=models.CharField(blank=True, help_text='Угол поворота', max_length=50, null=True, verbose_name='Угол поворота'),
        ),
        migrations.AddField(
            model_name='gearboxmodelline',
            name='turn_tuning_limit',
            field=models.CharField(blank=True, help_text='Настройка ограничителя на ±1° (об.)', max_length=50, null=True, verbose_name='Ограничитель'),
        ),
    ]
