# Generated by Django 4.2.23 on 2026-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0012_gearboxmodelline_turn_angle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbox',
            name='is_declutchable',
            field=models.CharField(choices=[('yes', 'расцепляемый'), ('no', 'не расцепляемый')], default='yes', help_text='Можно ли физически отсоединить штурвал от привода', max_length=3, verbose_name='Расцепляемый (Declutchable)'),
        ),
    ]
