# Generated by Django 5.2.4 on 2026-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0013_alter_gearbox_is_declutchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearboxbody',
            name='max_work_torque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальный рабочий выходной момент (Нм)', max_digits=10, null=True, verbose_name='Макс. рабочий выходной момент (Нм)'),
        ),
    ]
