# Generated by Django 4.2.23 on 2026-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
        ('gearbox', '0014_gearboxbody_max_work_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearboxbody',
            name='mounting_plate_bottom',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка к арматуре', related_name='gearbox_body_mounting_plate_bottom', to='params.mountingplatetypes', verbose_name='Монт.площадка к арматуре'),
        ),
        migrations.AlterField(
            model_name='gearboxbody',
            name='mounting_plate_top',
            field=models.ManyToManyField(blank=True, help_text='Монтажная площадка к приводу', related_name='gearbox_body_mounting_plate_top', to='params.mountingplatetypes', verbose_name='Монт.площадка к приводу'),
        ),
    ]
