# Generated by Django 4.2.23 on 2026-05-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('gearbox', '0015_alter_gearboxbody_mounting_plate_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbox',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearbox_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
    ]
