# Generated by Django 5.2.4 on 2026-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0016_gearbox_body_material'),
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbox',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='gearboxmodelline',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
    ]
