# Generated by Django 5.2.4 on 2026-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0017_gearbox_images_gearboxmodelline_images'),
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbox',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Images from the media library', related_name='+', to='media_library.medialibraryitem', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='gearboxmodelline',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Images from the media library', related_name='+', to='media_library.medialibraryitem', verbose_name='Images'),
        ),
    ]
