# Generated by Django 5.2.4 on 2026-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0018_alter_gearbox_images_alter_gearboxmodelline_images'),
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearboxmodelline',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AlterField(
            model_name='gearbox',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='gearboxmodelline',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
    ]
