# Generated by Django 4.2.23 on 2026-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0003_remove_certdata_equipment_type_and_more'),
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
        ('gearbox', '0019_gearboxmodelline_tech_docs_alter_gearbox_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbox',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AddField(
            model_name='gearboxmodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
    ]
