# Generated by Django 4.2.23 on 2026-05-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0003_rename_sku_sku_code_idx_sku_sku_code_2a026c_idx_and_more'),
        ('gearbox', '0021_gearbox_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbox',
            name='sku',
            field=models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU'),
        ),
    ]
