# Generated by Django 5.2.7 on 2026-05-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0023_gearboxmodelline_equipment_type'),
        ('media_library', '0012_imagegalleryset_imagegallerysetitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearbox',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gearboxmodelline',
            name='images',
        ),
        migrations.AddField(
            model_name='gearbox',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='gearboxmodelline',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
    ]
