# Generated by Django 5.2.7 on 2026-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0024_remove_gearbox_images_remove_gearboxmodelline_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbox',
            name='config_hash',
            field=models.CharField(blank=True, help_text='SHA-256 от типоразмера + опций; ключ дедупа и диффа', max_length=64, null=True, unique=True, verbose_name='Хэш конфигурации'),
        ),
    ]
