# Generated by Django 5.2.7 on 2026-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0028_gearboxmodelline_description_template_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbox',
            name='body_material_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с полем «Материал корпуса».', verbose_name='Переводы материала корпуса (ru/en/cn)'),
        ),
    ]
