# Generated by Django 5.2.7 on 2026-10-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbox', '0029_gearbox_body_material_text_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbox',
            name='body_material_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с body_material_text.', verbose_name='Переводы материала корпуса (ru/en/cn)'),
        ),
    ]
