# Generated by Django 4.2.23 on 2026-04-01 18:47

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValveActuationVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр: Моностабильный 24V', max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код для API')),
                ('return_category', models.CharField(choices=[('spring', 'Пружинный возврат (Spring Return)'), ('spring_centered', 'Пружинный возврат в центр (Spring Centered)'), ('pneumatic', 'Пневматический возврат (Pneumatic Return)'), ('none', 'Без возврата / Импульсный (No Return / Impulse)')], default='spring', max_length=20, verbose_name='Категория возврата')),
                ('solenoids_count', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во соленоидов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вариант управления',
                'verbose_name_plural': 'Варианты управления',
                'ordering': ['sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ValveDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа конструкции', max_length=50, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа конструкции', max_length=20, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа конструкции клапана', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип конструкции клапана',
                'verbose_name_plural': 'Типы конструкции клапанов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ValveFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обозначение схемы, например, 5/2 или 3/2', max_length=20, verbose_name='Схема (Функция)')),
                ('code', models.CharField(blank=True, help_text='Внутренний код или артикул типа схемы', max_length=20, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Например: "5-линейный 2-позиционный"', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('ports_count', models.IntegerField(help_text='Первое число в схеме (линейность)', verbose_name='Кол-во портов')),
                ('positions_count', models.IntegerField(help_text='Второе число в схеме (позиционность)', verbose_name='Кол-во положений')),
            ],
            options={
                'verbose_name': 'Схема распределения (Функция)',
                'verbose_name_plural': 'Схемы распределения (Функции)',
                'ordering': ['sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ValveOperationVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип действия', max_length=50, verbose_name='Тип')),
                ('code', models.CharField(blank=True, help_text='Код типа действия', max_length=20, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа действия клапана', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип действия клапана',
                'verbose_name_plural': 'Типы действия клапанов',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
