# Generated by Django 4.2.23 on 2026-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveactuationvariety',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание варианта управления', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='valveactuationvariety',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
    ]
