# Generated by Django 4.2.23 on 2026-04-02 02:59

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0002_valveactuationvariety_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр: С фиксацией, Кнопка без фиксации', max_length=100, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код для API')),
                ('mechanism', models.CharField(choices=[('push', 'Нажимной (Push)'), ('twist', 'Поворотный (Twist/Lock)'), ('screw', 'Под отвертку (Slot)'), ('lever', 'Рычажный (Lever)'), ('none', 'Отсутствует')], default='push', max_length=20, verbose_name='Тип механизма')),
                ('has_fixation', models.BooleanField(default=False, help_text='Удерживает ли дублер клапан в рабочем состоянии без участия оператора', verbose_name='С фиксацией')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ручной дублер',
                'verbose_name_plural': 'Ручные дублеры',
                'ordering': ['sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
