# Generated by Django 4.2.23 on 2026-04-02 03:52

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0004_alter_manualoverride_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValvePilotVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр: Электромагнитный, Пневмопривод', max_length=100, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('category', models.CharField(choices=[('electric', 'Электрический (Соленоид)'), ('pneumatic', 'Пневматический (Воздух)'), ('mechanical', 'Механический (Ролик/Рычаг)'), ('manual', 'Ручной (Кнопка/Педаль)')], default='electric', max_length=20, verbose_name='Категория сигнала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип управления (Пилот)',
                'verbose_name_plural': 'Типы управления (Пилот)',
                'ordering': ['sorting_order', 'name'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
