# Generated by Django 4.2.23 on 2026-04-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0005_valvepilotvariety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvepilotvariety',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
    ]
