# Generated by Django 4.2.23 on 2026-04-05 15:57

import core.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('params', '0031_threadinnerouter'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('solenoid_valves', '0006_alter_valvepilotvariety_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionalValveModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название фитинга', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код фитинга', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности серии фитингов', verbose_name='Описание')),
                ('name_template', models.CharField(help_text='Шаблон для текстового названия фитинга', max_length=300, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания фитинга', verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('solenoid_insulation_class', models.CharField(blank=True, help_text='Класс изоляции катушки: H, F', max_length=50, null=True, verbose_name='Класс изоляции')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд фитингов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_brand', to='producers.brands', verbose_name='Бренд')),
                ('construction', models.ForeignKey(blank=True, help_text='Конструкция', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_construction', to='solenoid_valves.valvedesign', verbose_name='Тип конструкции клапана')),
                ('exd', models.ForeignKey(blank=True, help_text='Степень взрывозащиты для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_exd', to='params.exdoption', verbose_name='Exd')),
                ('ip', models.ForeignKey(blank=True, default=65, help_text='Степень IP для серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_ip', to='params.ipoption', verbose_name='IP')),
                ('operation', models.ForeignKey(blank=True, help_text='Принцип действия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_construction_operation', to='solenoid_valves.valveoperationvariety', verbose_name='Принцип действия клапана')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель фитингов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_producer', to='producers.producer', verbose_name='Производитель')),
                ('working_medium', models.ForeignKey(blank=True, help_text='Рабочая среда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_working_medium', to='materials.workingmedium', verbose_name='Среда')),
            ],
            options={
                'verbose_name': 'Серия распределительных клапанов',
                'verbose_name_plural': 'Серии пневматических фитингов',
                'ordering': ['sorting_order', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DirectionValveBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Вес', max_digits=5, null=True, verbose_name='Вес, кг')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд клапанов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_brand', to='producers.brands', verbose_name='Бренд')),
                ('pneumatic_connection', models.ForeignKey(blank=True, help_text='Тип пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_pneumatic_connection', to='params.pneumaticconnection', verbose_name='Пневмоподключения')),
                ('pneumatic_connection_thread', models.ForeignKey(blank=True, help_text='Резьба выходного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_thread', to='params.threadsize', verbose_name='Пневмовыход')),
            ],
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DirectionValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_consumption_start', models.DecimalField(blank=True, decimal_places=2, help_text='Мощность хол, Вт', max_digits=5, null=True, verbose_name='Мощность номинальная, Вт')),
                ('power_consumption_hot', models.DecimalField(blank=True, decimal_places=2, help_text='Мощность ном, Вт', max_digits=5, null=True, verbose_name='Мощность номинальная, Вт')),
                ('kv', models.DecimalField(blank=True, decimal_places=2, help_text='Kv, м3/ч', max_digits=5, null=True, verbose_name='Kv, м3/ч')),
                ('dn', models.DecimalField(blank=True, decimal_places=2, help_text='Dn', max_digits=5, null=True, verbose_name='Диаметр, мм')),
                ('name', models.CharField(help_text='Текстовое название клапана', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код клапана', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности клапана', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С')),
                ('pressure_min', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Минимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.мин, бар')),
                ('pressure_max', models.DecimalField(blank=True, decimal_places=2, default=40, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар')),
                ('actuation', models.ForeignKey(blank=True, help_text='Управление', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_actuation', to='solenoid_valves.valveactuationvariety', verbose_name='Вариант управления')),
                ('body', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body', to='solenoid_valves.directionvalvebody', verbose_name='Корпус модели клапана')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('body_material_specified', models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_material_specified', to='materials.materialspecified', verbose_name='Материал корпуса')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд клапанов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_brand', to='producers.brands', verbose_name='Бренд')),
                ('function', models.ForeignKey(blank=True, help_text='Схема (Функция)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_function', to='solenoid_valves.valvefunction', verbose_name='Схема (Функция) клапана')),
                ('manual_override', models.ForeignKey(blank=True, help_text='Ручной дублер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_manual_override', to='solenoid_valves.manualoverride', verbose_name='Ручной дублер')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line', to='solenoid_valves.directionalvalvemodelline', verbose_name='Серия')),
                ('power_supply', models.ForeignKey(blank=True, help_text='Напряжение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_power_supply', to='params.powersupplies', verbose_name='Напряжение питания')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_producer', to='producers.producer', verbose_name='Производитель')),
                ('sealing_material', models.ForeignKey(blank=True, help_text='Трубка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_sealing_material', to='params.sealingclass', verbose_name='Тип материала трубки')),
                ('solenoid_body_material', models.ForeignKey(blank=True, help_text='Трубка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_solenoid_body_material', to='materials.materialgeneral', verbose_name='Тип материала трубки')),
            ],
            options={
                'verbose_name': 'Пневматический фитинг',
                'verbose_name_plural': 'Пневматические фитинги',
                'ordering': ['sorting_order', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
