# Generated by Django 4.2.23 on 2026-04-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0031_threadinnerouter'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('solenoid_valves', '0007_directionalvalvemodelline_directionvalvebody_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionalvalvemodelline',
            options={'ordering': ['sorting_order', 'code'], 'verbose_name': 'Серия распределительных клапанов', 'verbose_name_plural': 'Серии распределительных клапанов'},
        ),
        migrations.AlterModelOptions(
            name='directionvalve',
            options={'ordering': ['sorting_order', 'code'], 'verbose_name': 'Распределительный клапан', 'verbose_name_plural': 'Распределительные клапаны'},
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд клапанов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_brand', to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='code',
            field=models.CharField(blank=True, help_text='Код клапана', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание серии клапанов', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='description_template',
            field=models.TextField(blank=True, help_text='Шаблон для описания клапана', verbose_name='Шаблон описания'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='exd',
            field=models.ForeignKey(blank=True, help_text='Степень взрывозащиты для серии клапанов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_exd', to='params.exdoption', verbose_name='Exd'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='name',
            field=models.CharField(help_text='Текстовое название серии клапанов', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='name_template',
            field=models.CharField(help_text='Шаблон для текстового названия клапана', max_length=300, verbose_name='Шаблон названия'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='producer',
            field=models.ForeignKey(blank=True, help_text='Производитель клапанов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_model_line_producer', to='producers.producer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='directionvalvebody',
            name='pneumatic_connection',
            field=models.ForeignKey(blank=True, help_text='Корпус распределительного клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_pneumatic_connection', to='params.pneumaticconnection', verbose_name='Корпус распределительного клапана'),
        ),
    ]
