# Generated by Django 4.2.23 on 2026-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0008_alter_directionalvalvemodelline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='description_template',
            field=models.TextField(blank=True, help_text='Шаблон для описания клапана', null=True, verbose_name='Шаблон описания'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='name_template',
            field=models.CharField(blank=True, help_text='Шаблон для текстового названия клапана', max_length=300, null=True, verbose_name='Шаблон названия'),
        ),
    ]
