# Generated by Django 4.2.23 on 2026-04-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('solenoid_valves', '0009_alter_directionalvalvemodelline_description_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionvalvebody',
            options={'ordering': ['sorting_order', 'code'], 'verbose_name': 'Корпус распределительного клапана', 'verbose_name_plural': 'Корпуса распределительных клапанов'},
        ),
        migrations.AddField(
            model_name='directionvalvebody',
            name='code',
            field=models.CharField(blank=True, help_text='Код клапана', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='directionvalvebody',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание корпуса клапана', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='directionvalvebody',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='directionvalvebody',
            name='name',
            field=models.CharField(default=1, help_text='Текстовое название корпуса клапана', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directionvalvebody',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
        migrations.AlterField(
            model_name='directionvalvebody',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд корпуса клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_brand', to='producers.brands', verbose_name='Бренд'),
        ),
    ]
