# Generated by Django 4.2.23 on 2026-04-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0031_threadinnerouter'),
        ('solenoid_valves', '0010_alter_directionvalvebody_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionalvalvemodelline',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='directionvalvebody',
            name='pneumatic_connection',
        ),
        migrations.RemoveField(
            model_name='directionvalvebody',
            name='pneumatic_connection_thread',
        ),
        migrations.RemoveField(
            model_name='directionvalvebody',
            name='weight',
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='ip',
            field=models.ForeignKey(blank=True, default=65, help_text='Степень IP для модели клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_ip', to='params.ipoption', verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='medium_density_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вязкость среды, сСт', max_digits=5, null=True, verbose_name='Вязкость среды, сСт (мм2/с)'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='pneumatic_connection',
            field=models.ForeignKey(blank=True, help_text='Корпус распределительного клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_pneumatic_connection', to='params.pneumaticconnection', verbose_name='Корпус распределительного клапана'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='pneumatic_connection_thread',
            field=models.ForeignKey(blank=True, help_text='Резьба выходного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_body_thread', to='params.threadsize', verbose_name='Пневмовыход'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес', max_digits=5, null=True, verbose_name='Вес, кг'),
        ),
    ]
