# Generated by Django 4.2.23 on 2026-04-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0036_alter_electriccontrolunitoption_power_supply_option'),
        ('params', '0031_threadinnerouter'),
        ('solenoid_valves', '0011_remove_directionalvalvemodelline_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionvalve',
            name='cable_glands_holes',
            field=models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_cable_glands_holes', to='electric_actuators.cableglandholesset', verbose_name='Отверстия КВ'),
        ),
        migrations.AlterField(
            model_name='directionvalve',
            name='pneumatic_connection',
            field=models.ForeignKey(blank=True, help_text='Корпус распределительного клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_pneumatic_connection', to='params.pneumaticconnection', verbose_name='Корпус распределительного клапана'),
        ),
    ]
