# Generated by Django 5.2.4 on 2026-04-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('params', '0031_threadinnerouter'),
        ('solenoid_valves', '0012_directionvalve_cable_glands_holes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionvalve',
            name='sealing_material',
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='sealing_material_specified',
            field=models.ForeignKey(blank=True, help_text='Уплотнение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_sealing_material_specified', to='materials.materialspecified', verbose_name='Материал уплотнения'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='solenoid_body_material_specified',
            field=models.ForeignKey(blank=True, help_text='Материал соленоида', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_solenoid_body_material_specified', to='materials.materialgeneral', verbose_name='Материал соленоида'),
        ),
        migrations.AlterField(
            model_name='directionvalve',
            name='pneumatic_connection',
            field=models.ForeignKey(blank=True, help_text='Тип пневмоприсоединений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_pneumatic_connection', to='params.pneumaticconnection', verbose_name='Пневмоприсоединение'),
        ),
        migrations.AlterField(
            model_name='directionvalve',
            name='solenoid_body_material',
            field=models.ForeignKey(blank=True, help_text='Тип материала соленоида', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_solenoid_body_material', to='materials.materialgeneral', verbose_name='Тип материала соленоида'),
        ),
    ]
