# Generated by Django 5.2.4 on 2026-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0013_remove_directionvalve_sealing_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='name_template',
            field=models.CharField(blank=True, help_text='Шаблон для текстового названия клапана', null=True, verbose_name='Шаблон названия'),
        ),
        migrations.AlterField(
            model_name='directionvalve',
            name='code',
            field=models.CharField(blank=True, help_text='Код клапана', max_length=150, null=True, verbose_name='Код'),
        ),
    ]
