# Generated by Django 5.2.4 on 2026-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0014_alter_directionalvalvemodelline_name_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionvalve',
            name='name',
            field=models.TextField(help_text='Текстовое название клапана', verbose_name='Название'),
        ),
    ]
