# Generated by Django 5.2.4 on 2026-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0015_alter_directionvalve_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionvalve',
            name='power_consumption_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Мощность хол, Вт', max_digits=5, null=True, verbose_name='Мощность пусковая, Вт'),
        ),
    ]
