# Generated by Django 4.2.23 on 2026-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0016_alter_directionvalve_power_consumption_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionvalve',
            name='power_consumption_hold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Мощность удерж, Вт', max_digits=5, null=True, verbose_name='Мощность удержания, Вт'),
        ),
        migrations.AlterField(
            model_name='directionalvalvemodelline',
            name='name_template',
            field=models.TextField(blank=True, help_text='Шаблон для текстового названия клапана', null=True, verbose_name='Шаблон названия'),
        ),
    ]
