# Generated by Django 5.2.4 on 2026-04-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0031_threadinnerouter'),
        ('solenoid_valves', '0017_directionvalve_power_consumption_hold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionalvalvemodelline',
            name='exd',
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='exd',
            field=models.ForeignKey(blank=True, help_text='Степень взрывозащиты для модели клапана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_exd', to='params.exdoption', verbose_name='Exd'),
        ),
    ]
