# Generated by Django 5.2.4 on 2026-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solenoid_valves', '0018_remove_directionalvalvemodelline_exd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvefunction',
            name='compatible_functions',
            field=models.ManyToManyField(blank=True, help_text='Например: 3/2 ↔ 5/2', to='solenoid_valves.valvefunction', verbose_name='Совместимые схемы'),
        ),
    ]
