# Generated by Django 5.2.7 on 2026-06-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0004_alter_certdata_media_item'),
        ('core', '0002_equipmenttype_content_type'),
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('sku', '0004_alter_sku_brand'),
        ('solenoid_valves', '0019_valvefunction_compatible_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionalvalvemodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='directionalvalvemodelline',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='directionalvalvemodelline',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='directionalvalvemodelline',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='sku',
            field=models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
    ]
