# Generated by Django 5.2.4 on 2026-06-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipmenttype_content_type'),
        ('solenoid_valves', '0020_catalog_mixins_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionvalve',
            name='equipment_type',
            field=models.ForeignKey(default=1, help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования'),
            preserve_default=False,
        ),
    ]
