# Generated by Django 5.2.4 on 2026-09-16 18:02
# Дополнено вручную: дата-миграция переносит FK exd в through-строки
# DirectionValveExdOption (паттерн кабельных вводов/позиционеров).

import django.db.models.deletion
import options.models
from django.db import migrations, models


def migrate_exd_to_through(apps, schema_editor):
    """Перенос exd (FK → ExdOption) в through-строки серии + привязка артикулов.

    Для каждой пары (серия, вид взрывозащиты) создаётся одна through-строка
    (кодировка пустая — артикул у DV не генерируется), в её M2M переносится вид,
    артикулы получают ссылку на строку. Пустые exd остаются пустыми —
    отображение наследует дефолтную строку серии.
    """
    DirectionValve = apps.get_model('solenoid_valves', 'DirectionValve')
    DirectionValveExdOption = apps.get_model('solenoid_valves', 'DirectionValveExdOption')

    rows = {}
    for dv in DirectionValve.objects.exclude(exd_id=None):
        key = (dv.model_line_id, dv.exd_id)
        row = rows.get(key)
        if row is None:
            row, _created = DirectionValveExdOption.objects.get_or_create(
                model_line_id=dv.model_line_id,
                encoding='',
                defaults={'is_default': True, 'is_active': True, 'sorting_order': 0},
            )
            row.exd_options.add(dv.exd_id)
            rows[key] = row
        dv.exd_option_id = row.id
        dv.save(update_fields=['exd_option'])


def revert_exd_to_fk(apps, schema_editor):
    """Обратный перенос: exd (FK) артикула — из первого вида M2M-строки.

    Точность ограничена: если в строке несколько видов, возвращается первый —
    в исходных данных строка содержала ровно один вид.
    """
    DirectionValve = apps.get_model('solenoid_valves', 'DirectionValve')
    DirectionValveExdOption = apps.get_model('solenoid_valves', 'DirectionValveExdOption')
    first_variety = {
        r.id: r.exd_options.order_by('id').first()
        for r in DirectionValveExdOption.objects.all().prefetch_related('exd_options')
    }
    for dv in DirectionValve.objects.exclude(exd_option_id=None):
        variety = first_variety.get(dv.exd_option_id)
        if variety is not None:
            dv.exd_id = variety.id
            dv.save(update_fields=['exd'])


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0069_add_way_switch_x2_role'),
        ('solenoid_valves', '0021_directionvalve_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionValveExdOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('exd_options', models.ManyToManyField(blank=True, related_name='%(class)s_exd_rows', to='params.exdoption', verbose_name='Виды взрывозащиты')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exd_options', to='solenoid_valves.directionalvalvemodelline', verbose_name='Серия распределительных клапанов')),
            ],
            options={
                'verbose_name': 'Взрывозащита для серии распределительных клапанов',
                'verbose_name_plural': 'Взрывозащита для серий распределительных клапанов',
                'ordering': ['sorting_order'],
            },
            bases=(models.Model, options.models.ExdFormattingMixin),
        ),
        migrations.AddField(
            model_name='directionvalve',
            name='exd_option',
            field=models.ForeignKey(blank=True, help_text='Выбранная опция взрывозащиты серии; пусто — наследуется дефолт серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_valve_exd_articles', to='solenoid_valves.directionvalveexdoption', verbose_name='Опция взрывозащиты'),
        ),
        migrations.RunPython(migrate_exd_to_through, revert_exd_to_fk),
        migrations.RemoveField(
            model_name='directionvalve',
            name='exd',
        ),
    ]
