# Generated by Django 5.2.4 on 2026-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitSwitchOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название типа выходного сигнала БКВ', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа выходного сигнала БКВ', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа выходного сигнала БКВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('contact_form', models.CharField(blank=True, choices=[('SPST', 'SPST'), ('SPDT', 'SPDT'), ('DPST', 'DPST'), ('DPDT', 'DPDT')], max_length=10, null=True, verbose_name='Форма контактов')),
                ('wire_count', models.PositiveSmallIntegerField(default=2, verbose_name='Количество проводов')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Тип выхода БКВ',
                'verbose_name_plural': 'Типы выходов БКВ',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LimitSwitchSensorVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название типа сенсора БКВ', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа сенсора БКВ', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание типа сенсораа БКВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип сенсора БКВ',
                'verbose_name_plural': 'Типы сенсоров БКВ',
            },
        ),
    ]
