# Generated by Django 5.2.4 on 2026-04-27 14:29

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0036_alter_electriccontrolunitoption_power_supply_option'),
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('pa_controls', '0001_initial'),
        ('params', '0031_threadinnerouter'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaControlMountingStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название стандарта', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код стандарта', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание стандарта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('standard_type', models.CharField(choices=[('namur', 'NAMUR VDI/VDE 3845'), ('namur_custom', 'NAMUR нестандартный'), ('din', 'DIN 3337'), ('iso', 'ISO 5211'), ('custom', 'Нестандартный')], default='namur', max_length=30, verbose_name='Тип стандарта')),
                ('size', models.CharField(blank=True, help_text='Размер: 1, 2, 3, 4, 80x130', max_length=20, null=True, verbose_name='Размер')),
                ('square_size_mm', models.PositiveSmallIntegerField(blank=True, help_text='Размер квадратного отверстия под шток', null=True, verbose_name='Квадрат (мм)')),
                ('screw_thread', models.CharField(blank=True, help_text='M5, M6, M8, M10', max_length=20, null=True, verbose_name='Резьба крепления')),
                ('mounting_holes_x_mm', models.PositiveSmallIntegerField(blank=True, help_text='Межосевое расстояние по горизонтали', null=True, verbose_name='Расстояние по оси X (мм)')),
                ('mounting_holes_y_mm', models.PositiveSmallIntegerField(blank=True, help_text='Межосевое расстояние по вертикали', null=True, verbose_name='Расстояние по оси Y (мм)')),
                ('has_additional_holes', models.BooleanField(default=False, help_text='Наличие дополнительных крепежных отверстий', verbose_name='Дополнительные отверстия')),
                ('additional_holes_pattern', models.CharField(blank=True, help_text='Например: 40x40, 60x60', max_length=50, null=True, verbose_name='Схема доп. отверстий')),
                ('compatible_sizes', models.CharField(blank=True, help_text='Через запятую: 1,2,80x130', max_length=100, null=True, verbose_name='Совместимые размеры')),
                ('extra_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Стандарт присоединения',
                'verbose_name_plural': 'Стандарты присоединения',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='LimitSwitchModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название серии БКВ', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код клапана', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание серии БКВ', verbose_name='Описание')),
                ('name_template', models.TextField(blank=True, help_text='Шаблон для текстового названия БКВ', null=True, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания БКВ', null=True, verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_model_line_brand', to='producers.brands', verbose_name='Бренд')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_model_line_producer', to='producers.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Серия распределительных клапанов',
                'verbose_name_plural': 'Серии распределительных клапанов',
                'ordering': ['sorting_order', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LimitSwitchBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Текстовое название БКВ', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код БКВ', max_length=150, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание БКВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('points', models.IntegerField(default=2, help_text='Количество точек переключения (датчиков)', verbose_name='Количество датчиков')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Вес', max_digits=5, null=True, verbose_name='Вес, кг')),
                ('is_pneumatic', models.BooleanField(default=False, verbose_name='Пневматический')),
                ('has_namur_interface', models.BooleanField(default=False, verbose_name='NAMUR интерфейс')),
                ('has_visual_indicator', models.BooleanField(default=False, verbose_name='Визуальный индикатор')),
                ('max_current', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. ток (А)')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('body_material_specified', models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_body_material_specified', to='materials.materialspecified', verbose_name='Материал корпуса')),
                ('cable_glands_holes', models.ForeignKey(blank=True, help_text='Отверстия под кабельные вводы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_cable_glands_holes', to='electric_actuators.cableglandholesset', verbose_name='Отверстия КВ')),
                ('exd', models.ForeignKey(help_text='Степень Exd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_exd', to='params.exdoption', verbose_name='Exd')),
                ('ip', models.ForeignKey(help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_ip', to='params.ipoption', verbose_name='IP')),
                ('output_type', models.ForeignKey(help_text='Тип выходного сигнала', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_sensor_variety', to='pa_controls.limitswitchoutput', verbose_name='Выходной сигнал')),
                ('sensor_variety', models.ForeignKey(help_text='Тип сенсора', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_controls.limitswitchsensorvariety', verbose_name='Тип сенсора')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_model_line', to='pa_controls.limitswitchmodelline', verbose_name='Серия')),
                ('mounting_standards', models.ManyToManyField(blank=True, help_text='Стандарты присоединения NAMUR, с которыми совместим БКВ', related_name='limit_switch_box_mounting', to='pa_controls.pacontrolmountingstandard', verbose_name='Стандарты присоединения')),
            ],
            options={
                'verbose_name': 'Блок концевых выключателей',
                'verbose_name_plural': 'Блоки концевых выключателей',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
