# Generated by Django 5.2.4 on 2026-04-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0002_pacontrolmountingstandard_limitswitchmodelline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitswitchmodelline',
            options={'ordering': ['sorting_order', 'code'], 'verbose_name': 'Серия БКВ', 'verbose_name_plural': 'Серии БКВ'},
        ),
    ]
