# Generated by Django 5.2.4 on 2026-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0036_alter_electriccontrolunitoption_power_supply_option'),
        ('pa_controls', '0003_alter_limitswitchmodelline_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='max_current',
        ),
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='cable_glands_holes',
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='cable_glands_holes',
            field=models.ManyToManyField(blank=True, help_text='Отверстия под кабельные вводы', related_name='limit_switch_box_cable_glands_holes', to='electric_actuators.cableglandholesset', verbose_name='Отверстия КВ'),
        ),
    ]
