# Generated by Django 4.2.23 on 2026-04-27 17:00

import core.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_actuators', '0036_alter_electriccontrolunitoption_power_supply_option'),
        ('pa_controls', '0004_remove_limitswitchbox_max_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='cable_glands_holes',
        ),
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='mounting_standards',
        ),
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='weight',
        ),
        migrations.CreateModel(
            name='LimitSwitchBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название серии БКВ', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код клапана', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание серии БКВ', verbose_name='Описание')),
                ('name_template', models.TextField(blank=True, help_text='Шаблон для текстового названия БКВ', null=True, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания БКВ', null=True, verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Вес', max_digits=5, null=True, verbose_name='Вес, кг')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('cable_glands_holes', models.ManyToManyField(blank=True, help_text='Отверстия под кабельные вводы', related_name='limit_switch_body_cable_glands_holes', to='electric_actuators.cableglandholesset', verbose_name='Отверстия КВ')),
                ('mounting', models.ManyToManyField(blank=True, help_text='Стандарты присоединения NAMUR, с которыми совместим БКВ', related_name='limit_switch_body_mounting', to='pa_controls.pacontrolmountingstandard', verbose_name='Стандарты присоединения')),
            ],
            options={
                'verbose_name': 'Корпус БКВ',
                'verbose_name_plural': 'Корпуса БКВ',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Корпус БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_box_body', to='pa_controls.limitswitchbody', verbose_name='Корпус'),
        ),
    ]
