# Generated by Django 4.2.23 on 2026-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0005_remove_limitswitchbox_cable_glands_holes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchoutput',
            name='wire_count',
        ),
        migrations.AddField(
            model_name='limitswitchoutput',
            name='signal_type',
            field=models.CharField(choices=[('DRY', 'Сухой контакт (Passive)'), ('PNP', 'PNP (Active)'), ('NPN', 'NPN (Active)'), ('NAMUR', 'NAMUR (Ex)'), ('SS_2W', 'Solid State (2-wire)'), ('ANALOG', 'Аналоговый выход'), ('PNEUM', 'Пневматический')], default='DRY', max_length=10, verbose_name='Тип сигнала'),
        ),
        migrations.AddField(
            model_name='limitswitchoutput',
            name='wires_per_sensor',
            field=models.PositiveSmallIntegerField(default=2, help_text='Сколько жил кабеля занимает один датчик в блоке', verbose_name='Проводов на 1 датчик'),
        ),
        migrations.AlterField(
            model_name='limitswitchoutput',
            name='contact_form',
            field=models.CharField(blank=True, choices=[('SPST', 'SPST (Вкл/Выкл)'), ('SPDT', 'SPDT (Перекидной)'), ('DPST', 'DPST (2 линии Вкл/Выкл)'), ('DPDT', 'DPDT (2 перекидных)'), ('NONE', 'Нет (для аналоговых/пневмо)')], default='SPDT', max_length=10, null=True, verbose_name='Форма контактов'),
        ),
    ]
