# Generated by Django 5.2.4 on 2026-04-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0006_remove_limitswitchoutput_wire_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbody',
            name='description_template',
        ),
        migrations.RemoveField(
            model_name='limitswitchbody',
            name='name_template',
        ),
    ]
