# Generated by Django 5.2.4 on 2026-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0007_remove_limitswitchbody_description_template_and_more'),
        ('params', '0033_alter_exdoption_equipment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='exd',
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='exd',
            field=models.ManyToManyField(blank=True, help_text='Степень взрывозащиты (можно выбрать несколько вариантов)', related_name='limit_switch_boxes', to='params.exdoption', verbose_name='Взрывозащита'),
        ),
    ]
