# Generated by Django 5.2.4 on 2026-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0008_remove_limitswitchbox_exd_limitswitchbox_exd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitswitchoutput',
            name='contact_form',
            field=models.CharField(blank=True, choices=[('NO', 'SPST (Нормально открытый)'), ('NC', 'SPST (Нормально замкнутый)'), ('SPDT', 'SPDT (Перекидной)'), ('DPST', 'DPST (2 линии Вкл/Выкл)'), ('DPDT', 'DPDT (2 перекидных)'), ('NONE', 'Нет (для аналоговых/пневмо)'), ('ANALOG_SPDT', '1xАналог + 2xSPDT'), ('ANALOG_SPST', '1xАналог + 2xSPST')], default='SPDT', max_length=50, null=True, verbose_name='Форма контактов'),
        ),
        migrations.AlterField(
            model_name='limitswitchoutput',
            name='signal_type',
            field=models.CharField(choices=[('DRY', 'Сухой контакт (Passive)'), ('PNP', 'PNP (Active)'), ('NPN', 'NPN (Active)'), ('NAMUR', 'NAMUR (Ex)'), ('NAMUR_S', 'NAMUR с функцией безопасности'), ('SS_2W', '2-проводной бесконтактный (AC/DC)'), ('ANALOG', 'Аналоговый выход (4-20мА)'), ('PNEUM', 'Пневматический'), ('ANALOG_DRY', 'Аналог (4-20мА) + Сухой контакт'), ('ANALOG_NAMUR', 'Аналог (4-20мА) + NAMUR (Ex)')], default='DRY', max_length=50, verbose_name='Тип сигнала'),
        ),
    ]
