# Generated by Django 5.2.4 on 2026-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0009_alter_limitswitchoutput_contact_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Техническое наименование (например, 'Однополюсный перекидной')", max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Международное сокращение (SPST, SPDT, DPDT, DPST)', max_length=50, unique=True, verbose_name='Код')),
                ('wires_required', models.PositiveSmallIntegerField(help_text='Минимальное количество жил кабеля для подключения одной единицы (напр. SPDT = 3 провода)', verbose_name='Базовое кол-во проводов')),
                ('description', models.TextField(blank=True, help_text='Схематичное описание работы или примечания по монтажу', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Форма контактов',
                'verbose_name_plural': 'Формы контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Пользовательское описание (например, 'Нормально разомкнутый')", max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='Технический код состояния: NO (разомкнут), NC (замкнут), CO (перекидной)', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text="Описание состояния контакта в 'нормальном' (невозбужденном) положении датчика", verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Состояние контакта',
                'verbose_name_plural': 'Состояния контактов',
            },
        ),
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('is_ex', models.BooleanField(default=False, help_text='Флаг определяет, требуется ли для данного сигнала расчет искробезопасных параметров и барьер', verbose_name='Взрывозащищенный (Ex)')),
                ('description', models.TextField(blank=True, help_text='Подробное описание физического принципа работы сигнала', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип сигнала',
                'verbose_name_plural': 'Типы сигналов',
            },
        ),
    ]
