# Generated by Django 5.2.4 on 2026-04-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0010_contactform_contactstate_signaltype'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Текстовое название модели датчика', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код модели датчика', max_length=150, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание модели датчика', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('electrical_specs', models.CharField(help_text="Например: '8.2В / 25мА' или '250В (AC) / 1.0А' или '24В / 4-20мА'", max_length=255, verbose_name='Электрические характеристики')),
                ('wires_count', models.PositiveSmallIntegerField(default=2, help_text='Фактическое количество жил для подключения этого датчика', verbose_name='Кол-во проводов')),
                ('ui', models.FloatField(blank=True, null=True, verbose_name='Ui (В)')),
                ('ii', models.FloatField(blank=True, null=True, verbose_name='Ii (мА)')),
                ('pi', models.FloatField(blank=True, null=True, verbose_name='Pi (мВт)')),
                ('ci', models.FloatField(blank=True, null=True, verbose_name='Ci (нФ)')),
                ('li', models.FloatField(blank=True, null=True, verbose_name='Li (мкГн)')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Специфические данные: материал, частота, SIL, МДС, погрешность и т.д.', verbose_name='Дополнительные параметры')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_component_brand', to='producers.brands', verbose_name='Бренд датчика')),
                ('contact_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa_controls.contactform', verbose_name='Форма контактов')),
                ('contact_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa_controls.contactstate', verbose_name='Состояние контакта')),
                ('signal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa_controls.signaltype', verbose_name='Тип сигнала')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa_controls.limitswitchsensorvariety', verbose_name='Тип сенсора')),
            ],
            options={
                'verbose_name': 'Датчик (компонент)',
                'verbose_name_plural': 'Датчики (компоненты)',
            },
        ),
    ]
