# Generated by Django 5.2.4 on 2026-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0011_sensorcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='sensor_components',
            field=models.ManyToManyField(blank=True, help_text='Установленные датчики', related_name='limit_switch_boxes', to='pa_controls.sensorcomponent', verbose_name='Датчики'),
        ),
        migrations.AlterField(
            model_name='sensorcomponent',
            name='code',
            field=models.CharField(blank=True, help_text='Код модели датчика', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sensorcomponent',
            name='name',
            field=models.CharField(help_text='Текстовое название модели датчика', max_length=200, verbose_name='Название'),
        ),
    ]
