# Generated by Django 4.2.23 on 2026-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0012_limitswitchbox_sensor_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchsensorvariety',
            name='description_template',
            field=models.TextField(blank=True, help_text='Шаблон для описания сенсора', null=True, verbose_name='Шаблон описания'),
        ),
        migrations.AddField(
            model_name='limitswitchsensorvariety',
            name='name_template',
            field=models.TextField(blank=True, help_text='Шаблон для текстового названия сенсора', null=True, verbose_name='Шаблон названия'),
        ),
    ]
