# Generated by Django 5.2.4 on 2026-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0013_limitswitchsensorvariety_description_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcomponent',
            name='ci',
            field=models.FloatField(blank=True, help_text='Внутренняя емкость Ci (нФ): Суммарная емкость всех компонентов внутри датчика. При проектировании систем автоматики её учитывают вместе с емкостью кабеля, чтобы избежать накопления энергии.', null=True, verbose_name='Ci (нФ)'),
        ),
        migrations.AlterField(
            model_name='sensorcomponent',
            name='ii',
            field=models.FloatField(blank=True, help_text='Максимальный входной ток Ii (мА): Максимальный ток, который может выдержать внутренняя схема датчика при сохранении безопасности.', null=True, verbose_name='Ii (мА)'),
        ),
        migrations.AlterField(
            model_name='sensorcomponent',
            name='li',
            field=models.FloatField(blank=True, help_text='Внутренняя индуктивность Li (мкГн): Суммарная индуктивность датчика. Её учитывают для предотвращения искрового разряда при размыкании цепи.', null=True, verbose_name='Li (мкГн)'),
        ),
        migrations.AlterField(
            model_name='sensorcomponent',
            name='pi',
            field=models.FloatField(blank=True, help_text='Максимальная входная мощность Pi (мВт): Лимит мощности, которую устройство может рассеивать, чтобы не вызвать воспламенение окружающей среды.', null=True, verbose_name='Pi (мВт)'),
        ),
        migrations.AlterField(
            model_name='sensorcomponent',
            name='ui',
            field=models.FloatField(blank=True, help_text='Максимальное входное напряжение Ui (В): Это предел напряжения, который может быть подан на устройство без нарушения его искробезопасности. Если стоит 0, значит, прибор не сертифицирован как «искробезопасный аппарат».', null=True, verbose_name='Ui (В)'),
        ),
    ]
