# Generated by Django 5.2.4 on 2026-05-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0014_alter_sensorcomponent_ci_alter_sensorcomponent_ii_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='output_type',
        ),
        migrations.DeleteModel(
            name='LimitSwitchOutput',
        ),
    ]
