# Generated by Django 4.2.23 on 2026-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0015_remove_limitswitchbox_output_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitswitchbody',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание серии корпусов БКВ', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='limitswitchbody',
            name='name',
            field=models.CharField(help_text='Текстовое название серии корпусов БКВ', max_length=200, verbose_name='Название'),
        ),
    ]
