# Generated by Django 4.2.23 on 2026-05-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0016_alter_limitswitchbody_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='additional_sensor',
            field=models.ManyToManyField(blank=True, help_text='Дополнительные датчики', related_name='limit_switch_boxes_additional_sensor', to='pa_controls.sensorcomponent', verbose_name='Датчики дополнительные'),
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='primary_sensor',
            field=models.ForeignKey(blank=True, help_text='Основной датчик', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_boxes_primary_sensor', to='pa_controls.sensorcomponent', verbose_name='Датчик основной'),
        ),
    ]
