# Generated by Django 4.2.23 on 2026-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0018_alter_limitswitchbox_exd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='sensor_components',
        ),
    ]
