# Generated by Django 4.2.23 on 2026-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0050_delete_filtrationgrade'),
        ('pa_controls', '0019_remove_limitswitchbox_sensor_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitswitchbox',
            name='exd',
            field=models.ManyToManyField(blank=True, help_text='Степень взрывозащиты (можно выбрать несколько вариантов)', related_name='limit_switch_boxes_exd_new', to='params.exdoption', verbose_name='Взрывозащита'),
        ),
    ]
