# Generated by Django 4.2.23 on 2026-05-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0052_explosionprotectionlevel_is_active_and_more'),
        ('pa_controls', '0020_alter_limitswitchbox_exd'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='exd_v2',
            field=models.ManyToManyField(blank=True, help_text='Степень взрывозащиты (можно выбрать несколько вариантов)', to='params.exdoption', verbose_name='Взрывозащита v2'),
        ),
    ]
