# Generated by Django 4.2.23 on 2026-05-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0021_limitswitchbox_exd_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='exd',
        ),
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='exd_v2',
        ),
    ]
