# Generated by Django 4.2.23 on 2026-05-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0052_explosionprotectionlevel_is_active_and_more'),
        ('pa_controls', '0022_remove_limitswitchbox_exd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='exd',
            field=models.ManyToManyField(blank=True, help_text='Степень взрывозащиты (можно выбрать несколько вариантов)', to='params.exdoption', verbose_name='Взрывозащита'),
        ),
    ]
