# Generated by Django 4.2.23 on 2026-05-09 20:26
# --- отредактировано: SeparateDatabaseAndState, БД не трогаем

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0023_limitswitchbox_exd'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Не трогаем БД — таблица pa_controls_limitswitchbox_exd с данными остаётся
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='limitswitchbox',
                    name='exd',
                ),
            ],
        ),
    ]
