# Generated by Django 4.2.23 on 2026-05-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pa_controls', '0025_limitswitchbox_exd'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='equipment_type',
            field=models.ForeignKey(default=1, help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования'),
            preserve_default=False,
        ),
    ]
