# Generated by Django 5.2.4 on 2026-05-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0003_remove_certdata_equipment_type_and_more'),
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
        ('pa_controls', '0028_remove_limitswitchmodelline_cert_docs'),
        ('sku', '0004_alter_sku_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='sku',
            field=models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
    ]
