# Generated by Django 5.2.4 on 2026-05-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0008_alter_medialibraryitem_media_file_and_more'),
        ('pa_controls', '0029_limitswitchbox_images_limitswitchbox_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitswitchbox',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='limitswitchbox_images', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
    ]
