# Generated by Django 5.2.4 on 2026-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0008_alter_medialibraryitem_media_file_and_more'),
        ('pa_controls', '0030_alter_limitswitchbox_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitswitchbox',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, related_name='lsb_tech_docs', to='media_library.medialibraryitem', verbose_name='Техдокументация'),
        ),
    ]
