# Generated by Django 5.2.4 on 2026-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0011_remove_medialibraryitem_title'),
        ('pa_controls', '0030_alter_limitswitchbox_images'),
        ('params', '0054_alter_threadsize_thread_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitswitchbox',
            name='exd',
            field=models.ManyToManyField(blank=True, help_text='Степень взрывозащиты (можно выбрать несколько вариантов)', related_name='+', to='params.exdoption', verbose_name='Взрывозащита'),
        ),
        migrations.AlterField(
            model_name='limitswitchbox',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения из медиабиблиотеки', related_name='+', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='limitswitchbox',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, related_name='+', to='media_library.medialibraryitem', verbose_name='Техдокументация'),
        ),
    ]
