# Generated by Django 5.2.7 on 2026-05-29 07:50

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('media_library', '0012_imagegalleryset_imagegallerysetitem_and_more'),
        ('pa_controls', '0031_alter_limitswitchbox_exd_alter_limitswitchbox_images_and_more'),
        ('params', '0054_alter_threadsize_thread_diameter_and_more'),
        ('sku', '0004_alter_sku_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='images',
        ),
        migrations.RemoveField(
            model_name='limitswitchmodelline',
            name='images',
        ),
        migrations.AddField(
            model_name='limitswitchbox',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.CreateModel(
            name='LsbModelLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Текстовое название БКВ', verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код БКВ', max_length=150, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание БКВ', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('points', models.IntegerField(default=2, help_text='Количество точек переключения (датчиков)', verbose_name='Количество датчиков')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С')),
                ('is_pneumatic', models.BooleanField(default=False, verbose_name='Пневматический')),
                ('has_namur_interface', models.BooleanField(default=False, verbose_name='NAMUR интерфейс')),
                ('has_visual_indicator', models.BooleanField(default=False, verbose_name='Визуальный индикатор')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='signal_type, resistance, range и т.д.', verbose_name='Параметры')),
                ('additional_sensor', models.ManyToManyField(blank=True, help_text='Дополнительные датчики', related_name='lsb_item_additional_sensor', to='pa_controls.sensorcomponent', verbose_name='Датчики дополнительные')),
                ('body', models.ForeignKey(blank=True, help_text='Корпус БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsb_item_body', to='pa_controls.limitswitchbody', verbose_name='Корпус')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsb_item_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('body_material_specified', models.ForeignKey(blank=True, help_text='Материал корпуса арматуры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsb_item_body_material_specified', to='materials.materialspecified', verbose_name='Материал корпуса')),
                ('exd', models.ManyToManyField(blank=True, help_text='Степень взрывозащиты (можно выбрать несколько вариантов)', related_name='+', to='params.exdoption', verbose_name='Взрывозащита')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('ip', models.ForeignKey(help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsb_item_ip', to='params.ipoption', verbose_name='IP')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsb_item_model_line', to='pa_controls.limitswitchmodelline', verbose_name='Серия')),
                ('primary_sensor', models.ForeignKey(blank=True, help_text='Основной датчик', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsb_item_primary_sensor', to='pa_controls.sensorcomponent', verbose_name='Датчик основной')),
                ('sensor_variety', models.ForeignKey(help_text='Тип сенсора', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_controls.limitswitchsensorvariety', verbose_name='Тип сенсора')),
                ('sku', models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU')),
                ('tech_docs', models.ManyToManyField(blank=True, related_name='+', to='media_library.medialibraryitem', verbose_name='Техдокументация')),
            ],
            options={
                'verbose_name': 'Блок концевых выключателей',
                'verbose_name_plural': 'Блоки концевых выключателей',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.CatalogDictMixin, core.models.mixins.TemplateMixin, core.models.mixins.CopyMixin, models.Model),
        ),
    ]
