# Generated by Django 5.2.4 on 2026-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0032_remove_limitswitchbox_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название варианта количества датчиков', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Числовой код (2, 3, 4)', max_length=10, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Подробное описание конфигурации', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Количество датчиков БКВ',
                'verbose_name_plural': 'Количество датчиков БКВ',
                'ordering': ['sorting_order', 'code'],
            },
        ),
    ]
