# Generated by Django 5.2.4 on 2026-07-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0033_pointsoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='points_option',
            field=models.ForeignKey(blank=True, help_text='Ссылка на справочник количества датчиков', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_boxes', to='pa_controls.pointsoption', verbose_name='Количество датчиков (опция)'),
        ),
    ]
