# Generated by Django 5.2.4 on 2026-08-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0035_add_points_fk_lsb_item'),
        ('params', '0068_actuator_heater_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='signal_profile',
            field=models.ForeignKey(blank=True, help_text='Расширенный состав сигналов БКВ: роль (Открыто/Закрыто/Промежуточное) → датчик', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_boxes', to='params.controlunitsignalprofile', verbose_name='Профиль сигналов'),
        ),
    ]
