# Generated by Django 5.2.4 on 2026-08-25 15:25

from django.db import migrations, models


VISUAL_INDICATORS = [
    {
        'code': 'DOME-GREEN-RED',
        'name': 'Купол, Зеленый — «Открыто», Красный — «Закрыто»',
        'sorting_order': 1,
    },
    {
        'code': 'DOME-BLACK-YELLOW',
        'name': 'Купол, Черный — «Открыто», Желтый — «Закрыто»',
        'sorting_order': 2,
    },
    {
        'code': 'DOME-BLACK-RED',
        'name': 'Купол, Черный — «Открыто», Красный — «Закрыто»',
        'sorting_order': 3,
    },
]


def fill_visual_indicators(apps, schema_editor):
    VisualIndicatorType = apps.get_model('pa_controls', 'VisualIndicatorType')
    for item in VISUAL_INDICATORS:
        VisualIndicatorType.objects.get_or_create(code=item['code'], defaults=item)


def reverse_fill_visual_indicators(apps, schema_editor):
    VisualIndicatorType = apps.get_model('pa_controls', 'VisualIndicatorType')
    VisualIndicatorType.objects.filter(
        code__in=[i['code'] for i in VISUAL_INDICATORS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0036_limitswitchbox_signal_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualIndicatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Купол, Зеленый — «Открыто», Красный — «Закрыто»', max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код, например DOME-GREEN-RED', max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Примечания к виду индикатора', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли в списках выбора', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Вид визуального индикатора',
                'verbose_name_plural': 'Виды визуальных индикаторов',
                'ordering': ['sorting_order', 'code'],
            },
        ),
        migrations.RunPython(fill_visual_indicators, reverse_fill_visual_indicators),
    ]
