# Generated by Django 5.2.4 on 2026-08-25 15:31

import django.db.models.deletion
from django.db import migrations, models


INDICATOR_BY_SERIES = {
    'ЯМАЛ': 'DOME-GREEN-RED',
    'УРАЛ': 'DOME-GREEN-RED',
    'АМУР': 'DOME-GREEN-RED',
    'APL': 'DOME-BLACK-RED',
}


def fill_visual_indicators(apps, schema_editor):
    LimitSwitchBox = apps.get_model('pa_controls', 'LimitSwitchBox')
    VisualIndicatorType = apps.get_model('pa_controls', 'VisualIndicatorType')
    for series_name, code in INDICATOR_BY_SERIES.items():
        try:
            indicator = VisualIndicatorType.objects.get(code=code)
        except VisualIndicatorType.DoesNotExist:
            continue
        LimitSwitchBox.objects.filter(model_line__name=series_name).update(
            visual_indicator_type=indicator,
        )


def reverse_fill_visual_indicators(apps, schema_editor):
    LimitSwitchBox = apps.get_model('pa_controls', 'LimitSwitchBox')
    LimitSwitchBox.objects.filter(
        model_line__name__in=INDICATOR_BY_SERIES.keys(),
    ).update(visual_indicator_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0037_visualindicatortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='visual_indicator_type',
            field=models.ForeignKey(blank=True, help_text='Вид купола-индикатора положения на корпусе БКВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_switch_boxes', to='pa_controls.visualindicatortype', verbose_name='Вид визуального индикатора'),
        ),
        migrations.RunPython(fill_visual_indicators, reverse_fill_visual_indicators),
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='has_visual_indicator',
        ),
    ]
