# Generated by Django 5.2.4 on 2026-08-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0040_posi_seed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitswitchbox',
            name='additional_sensor',
        ),
    ]
