# Generated by Django 5.2.4 on 2026-08-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0041_remove_limitswitchbox_additional_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LsbModelLineItem',
        ),
    ]
