# Generated by Django 5.2.4 on 2026-08-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0042_delete_lsbmodellineitem'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posipneumaticthreadoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='posipneumaticthreadoption',
            name='model_line',
        ),
        migrations.RemoveField(
            model_name='posipneumaticthreadoption',
            name='thread_size',
        ),
        migrations.CreateModel(
            name='PosiBodyConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название варианта присоединений корпуса позиционера', max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код варианта присоединений', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание варианта присоединений', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('pneumatic_connection', models.ForeignKey(help_text='Тип пневмоприсоединения (трубка, NAMUR и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='posi_body_connections_pneumatic', to='params.pneumaticconnection', verbose_name='Пневмоприсоединение')),
                ('thread_size_set', models.ForeignKey(help_text='Набор резьб пневмоприсоединения', on_delete=django.db.models.deletion.PROTECT, related_name='posi_body_connections', to='params.threadsizeset', verbose_name='Набор резьб')),
            ],
            options={
                'verbose_name': 'Присоединения корпуса позиционера',
                'verbose_name_plural': 'Присоединения корпусов позиционеров',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PosiBodyConnectionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_connection_options', to='pa_controls.posimodelline', verbose_name='Серия позиционеров')),
                ('body_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_line_options', to='pa_controls.posibodyconnections', verbose_name='Присоединения корпуса')),
            ],
            options={
                'verbose_name': 'Присоединения корпуса для серии позиционеров',
                'verbose_name_plural': 'Присоединения корпусов для серий позиционеров',
                'ordering': ['is_default', 'sorting_order'],
                'unique_together': {('model_line', 'body_connection')},
            },
        ),
        migrations.DeleteModel(
            name='PosiPneumaticConnectionOption',
        ),
        migrations.DeleteModel(
            name='PosiPneumaticThreadOption',
        ),
    ]
