# Generated by Django 5.2.4 on 2026-08-25 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0043_alter_posipneumaticthreadoption_unique_together_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posibodyconnections',
            name='pneumatic_connection',
        ),
        migrations.RemoveField(
            model_name='posibodyconnections',
            name='thread_size_set',
        ),
        migrations.AddField(
            model_name='posibodyconnections',
            name='thread_in',
            field=models.ForeignKey(blank=True, help_text='Резьба входного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_body_connections_thread_in', to='params.threadsize', verbose_name='Пневмовход'),
        ),
        migrations.AddField(
            model_name='posibodyconnections',
            name='thread_out',
            field=models.ForeignKey(blank=True, help_text='Резьба выходного отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_body_connections_thread_out', to='params.threadsize', verbose_name='Пневмовыход'),
        ),
    ]
