# Generated by Django 5.2.4 on 2026-08-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0044_remove_posibodyconnections_pneumatic_connection_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='posibodyconnections',
            name='cable_gland_hole',
            field=models.ForeignKey(blank=True, help_text='Резьба отверстия под кабельный ввод', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_body_connections_cable_gland', to='params.threadsize', verbose_name='Отверстие под кабельный ввод'),
        ),
    ]
