# Generated by Django 5.2.4 on 2026-08-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0045_posibodyconnections_cable_gland_hole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosiCableGlandHolesOption',
        ),
    ]
