# Generated by Django 5.2.4 on 2026-08-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0046_delete_posicableglandholesoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posimodellineitem',
            name='cable_glands_holes',
        ),
        migrations.RemoveField(
            model_name='posimodellineitem',
            name='pneumatic_connection',
        ),
        migrations.RemoveField(
            model_name='posimodellineitem',
            name='pneumatic_connection_thread',
        ),
        migrations.AddField(
            model_name='posimodellineitem',
            name='body_connection',
            field=models.ForeignKey(blank=True, help_text='Присоединения корпуса: резьбы пневмовхода/выхода и отверстие КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positioner_items', to='pa_controls.posibodyconnections', verbose_name='Присоединения корпуса'),
        ),
    ]
