# Generated by Django 5.2.4 on 2026-08-25 19:17

import django.db.models.deletion
from django.db import migrations, models


def populate_lever_options(apps, schema_editor):
    """Заполняет acting_type и ход штока по кодам существующих рычагов.

    Ход штока имеет смысл только для линейного типа: для ротационных
    (NAMUR, вилочковый M6) поля остаются пустыми.
    """
    LeverOption = apps.get_model('pa_controls', 'LeverOption')
    ActingType = apps.get_model('pa_controls', 'ActingType')

    linear = ActingType.objects.filter(code='LINEAR').first()
    rotary = ActingType.objects.filter(code='ROTARY').first()

    mapping = {
        'LEVER-LIN-10-80': (linear, '10', '80'),
        'LEVER-LIN-40': (linear, '40', None),
        'LEVER-LIN-70': (linear, '70', None),
        'LEVER-LIN-100': (linear, '100', None),
        'LEVER-ROT-M6-39-FORK': (rotary, None, None),
        'LEVER-ROT-NAMUR': (rotary, None, None),
    }

    for obj in LeverOption.objects.all():
        acting_type, stroke_min, stroke_max = mapping.get(
            obj.code,
            (rotary if obj.name and 'Вращающ' in obj.name else linear, None, None),
        )
        obj.acting_type = acting_type
        obj.stroke_min_mm = stroke_min
        obj.stroke_max_mm = stroke_max
        obj.save(update_fields=['acting_type_id', 'stroke_min_mm', 'stroke_max_mm'])


def reverse_populate_lever_options(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0047_remove_posimodellineitem_cable_glands_holes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveroption',
            options={'ordering': ['acting_type', 'stroke_min_mm', 'sorting_order', 'code'],
                     'verbose_name': 'Рычаг позиционера',
                     'verbose_name_plural': 'Рычаги позиционеров'},
        ),
        migrations.AddField(
            model_name='leveroption',
            name='acting_type',
            field=models.ForeignKey(help_text='Линейный или ротационный', null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='lever_options', to='pa_controls.actingtype',
                                    verbose_name='Тип позиционера'),
        ),
        migrations.AddField(
            model_name='leveroption',
            name='stroke_max_mm',
            field=models.DecimalField(blank=True, decimal_places=1,
                                      help_text='Максимальный ход штока в миллиметрах (только для линейного типа)',
                                      max_digits=6, null=True, verbose_name='Макс. ход штока, мм'),
        ),
        migrations.AddField(
            model_name='leveroption',
            name='stroke_min_mm',
            field=models.DecimalField(blank=True, decimal_places=1,
                                      help_text='Минимальный ход штока в миллиметрах (только для линейного типа)',
                                      max_digits=6, null=True, verbose_name='Мин. ход штока, мм'),
        ),
        migrations.RunPython(populate_lever_options, reverse_populate_lever_options),
        migrations.AlterField(
            model_name='leveroption',
            name='acting_type',
            field=models.ForeignKey(help_text='Линейный или ротационный',
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='lever_options', to='pa_controls.actingtype',
                                    verbose_name='Тип позиционера'),
        ),
        migrations.RemoveField(
            model_name='leveroption',
            name='length_mm',
        ),
    ]
