# Generated by Django 5.2.4 on 2026-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0048_alter_leveroption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posibodyconnectionoption',
            name='only_non_ex',
            field=models.BooleanField(default=False, help_text='Вариант недоступен при выборе взрывозащиты', verbose_name='Только общепром'),
        ),
        migrations.AddField(
            model_name='posisignalprofileoption',
            name='only_non_ex',
            field=models.BooleanField(default=False, help_text='Вариант недоступен при выборе взрывозащиты', verbose_name='Только общепром'),
        ),
        migrations.AddField(
            model_name='positemperatureoption',
            name='only_non_ex',
            field=models.BooleanField(default=False, help_text='Вариант недоступен при выборе взрывозащиты', verbose_name='Только общепром'),
        ),
    ]
