# Generated by Django 5.2.4 on 2026-08-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0050_posi_feedback_seed'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosiExdOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(blank=True, help_text='Код опции для подстановки в артикул', max_length=50, verbose_name='Кодировка')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание этой опции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли эта опция стандартной для серии', verbose_name='Стандартная опция')),
                ('exd_options', models.ManyToManyField(blank=True, related_name='posi_model_line_exd_option_rows', to='params.exdoption', verbose_name='Виды взрывозащиты')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exd_options', to='pa_controls.posimodelline', verbose_name='Серия позиционеров')),
            ],
            options={
                'verbose_name': 'Взрывозащита для серии позиционеров',
                'verbose_name_plural': 'Взрывозащита для серий позиционеров',
                'ordering': ['is_default', 'sorting_order'],
            },
        ),
    ]
