# Generated by Codewhale 2026-08-27 — диагностические возможности позиционера (NAMUR NE 107)
"""Добавляет диагностические возможности смарт-позиционера:

- LOSS-OF-SIGNAL — Loss of Signal (LoS)
- LOSS-OF-POWER   — Loss of Power (LoP)
- LOSS-OF-AIR     — Loss of Air (LoA)
- INTERNAL-FAULT  — Internal Fault
"""
from django.db import migrations


DIAGNOSTIC_CAPABILITIES = [
    {
        'code': 'LOSS-OF-SIGNAL',
        'name': 'Loss of Signal (LoS)',
        'description': 'Падение или полное исчезновение управляющего сигнала (например, ниже 3.6 мА).',
        'sorting_order': 160,
    },
    {
        'code': 'LOSS-OF-POWER',
        'name': 'Loss of Power (LoP)',
        'description': 'Отключение основного питания (актуально для четырехпроводных схем '
                       'или позиционеров с шинной организацией вроде Fieldbus).',
        'sorting_order': 170,
    },
    {
        'code': 'LOSS-OF-AIR',
        'name': 'Loss of Air (LoA)',
        'description': 'Падение давления питания сжатого воздуха ниже критического уровня '
                       '(контролируется встроенным датчиком давления).',
        'sorting_order': 180,
    },
    {
        'code': 'INTERNAL-FAULT',
        'name': 'Internal Fault',
        'description': 'Внутренний сбой самого позиционера (ошибка процессора, '
                       'заклинивание внутреннего пилотного клапана).',
        'sorting_order': 190,
    },
]


def add_diagnostic_capabilities(apps, schema_editor):
    SmartCapabilityOption = apps.get_model('pa_controls', 'SmartCapabilityOption')
    for item in DIAGNOSTIC_CAPABILITIES:
        SmartCapabilityOption.objects.get_or_create(
            code=item['code'],
            defaults={
                'name': item['name'],
                'description': item.get('description', ''),
                'sorting_order': item.get('sorting_order', 0),
                'is_active': True,
            },
        )


def remove_diagnostic_capabilities(apps, schema_editor):
    SmartCapabilityOption = apps.get_model('pa_controls', 'SmartCapabilityOption')
    SmartCapabilityOption.objects.filter(
        code__in=[c['code'] for c in DIAGNOSTIC_CAPABILITIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0051_posiexdoption'),
    ]

    operations = [
        migrations.RunPython(add_diagnostic_capabilities, remove_diagnostic_capabilities),
    ]
