# Generated by Django 5.2.4 on 2026-09-01 14:36
# Дополнено вручную: перенос данных smart_capability_set серии в through-опции
# «Профиль сигналов» (PosiSignalProfileOption) ДО удаления поля с серии.

import django.db.models.deletion
from django.db import migrations, models


def copy_set_to_profile_options(apps, schema_editor):
    """Набор смарт-возможностей серии копируем на все её опции профиля сигналов."""
    PosiModelLine = apps.get_model('pa_controls', 'PosiModelLine')
    PosiSignalProfileOption = apps.get_model('pa_controls', 'PosiSignalProfileOption')

    for series in PosiModelLine.objects.exclude(smart_capability_set__isnull=True):
        PosiSignalProfileOption.objects.filter(
            model_line=series,
            smart_capability_set__isnull=True,
        ).update(smart_capability_set=series.smart_capability_set)


def noop_reverse(apps, schema_editor):
    """Обратный перенос не нужен (поле серии удаляется)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0052_posi_diagnostic_capabilities'),
    ]

    operations = [
        # 1. Новое поле на опции
        migrations.AddField(
            model_name='posisignalprofileoption',
            name='smart_capability_set',
            field=models.ForeignKey(blank=True, help_text='Возможности смарт-позиционера для этого профиля сигналов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_profile_options', to='pa_controls.smartcapabilityset', verbose_name='Набор смарт-возможностей'),
        ),
        # 2. Перенос данных серия → опции
        migrations.RunPython(copy_set_to_profile_options, noop_reverse),
        # 3. Удаление поля с серии
        migrations.RemoveField(
            model_name='posimodelline',
            name='smart_capability_set',
        ),
    ]
