# Generated by Django 5.2.4 on 2026-09-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0053_remove_posimodelline_smart_capability_set_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posisignalprofileoption',
            unique_together={('model_line', 'signal_profile', 'smart_capability_set')},
        ),
    ]
