# Generated by Django 5.2.4 on 2026-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0054_alter_posisignalprofileoption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='posimodelline',
            name='model_item_code_template',
            field=models.CharField(blank=True, help_text='Шаблон артикула (паттерн электроприводов). Плейсхолдеры: {model_code}, {acting_type}, {body_connection}, {lever}, {temperature}, {signal_profile}, {alarm}, {exd}, {ip}, {smart}', max_length=500, null=True, verbose_name='Шаблон артикула'),
        ),
    ]
