# Generated by Django 5.2.4 on 2026-09-01 16:25

import django.db.models.deletion
from django.db import migrations, models


def copy_acting_type_to_model_line(apps, schema_editor):
    """Тип действия серии: из дефолтной through-строки (is_default, иначе первая)."""
    PosiModelLine = apps.get_model('pa_controls', 'PosiModelLine')
    PosiActingTypeOption = apps.get_model('pa_controls', 'PosiActingTypeOption')

    for series in PosiModelLine.objects.all():
        row = (PosiActingTypeOption.objects
               .filter(model_line=series)
               .order_by('-is_default', 'sorting_order').first())
        if row:
            series.acting_type = row.acting_type
            series.save(update_fields=['acting_type'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0055_posimodelline_model_item_code_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='posimodelline',
            name='acting_type',
            field=models.ForeignKey(blank=True, help_text='Тип действия серии (линейный/ротационный)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_model_lines', to='pa_controls.actingtype', verbose_name='Тип действия'),
        ),
        # Перенос данных ДО удаления through-модели
        migrations.RunPython(copy_acting_type_to_model_line, noop_reverse),
        migrations.DeleteModel(
            name='PosiActingTypeOption',
        ),
    ]
