# Generated by Django 5.2.4 on 2026-09-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0056_posimodelline_acting_type_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveroption',
            options={'ordering': ['sorting_order', 'code'], 'verbose_name': 'Рычаг позиционера', 'verbose_name_plural': 'Рычаги позиционеров'},
        ),
        migrations.AlterModelOptions(
            name='posialarmoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Сигнал тревоги для серии позиционеров', 'verbose_name_plural': 'Сигналы тревоги для серий позиционеров'},
        ),
        migrations.AlterModelOptions(
            name='posibodyconnectionoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Присоединения корпуса для серии позиционеров', 'verbose_name_plural': 'Присоединения корпусов для серий позиционеров'},
        ),
        migrations.AlterModelOptions(
            name='posiexdoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Взрывозащита для серии позиционеров', 'verbose_name_plural': 'Взрывозащита для серий позиционеров'},
        ),
        migrations.AlterModelOptions(
            name='posileveroption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Рычаг для серии позиционеров', 'verbose_name_plural': 'Рычаги для серий позиционеров'},
        ),
        migrations.AlterModelOptions(
            name='posisignalprofileoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Профиль сигналов для серии позиционеров', 'verbose_name_plural': 'Профили сигналов для серий позиционеров'},
        ),
        migrations.AlterModelOptions(
            name='positemperatureoption',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Температурная опция серии позиционеров', 'verbose_name_plural': 'Температурные опции серий позиционеров'},
        ),
        migrations.CreateModel(
            name='PositionerConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=80, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т макс, °С')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_unique', models.BooleanField(default=True, verbose_name='Уникальная конфигурация')),
                ('selected_alarm', models.ForeignKey(blank=True, help_text='Профиль сигналов с ролью «Вых. Авария»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_alarms', to='params.controlunitsignalprofile', verbose_name='Сигнал тревоги')),
                ('selected_body_connection', models.ForeignKey(blank=True, help_text='Резьбы пневмовхода/выхода + отверстие под КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_body_connections', to='pa_controls.posibodyconnections', verbose_name='Присоединения корпуса')),
                ('selected_exd', models.ForeignKey(blank=True, help_text='Выбранный вид Exd из M2M строки (пусто — общепром)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_exd', to='params.exdoption', verbose_name='Вид взрывозащиты')),
                ('selected_exd_row', models.ForeignKey(blank=True, help_text='Through-строка PosiExdOption (кодировка + виды Exd)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_exd_rows', to='pa_controls.posiexdoption', verbose_name='Взрывозащита (кодировка)')),
                ('selected_lever', models.ForeignKey(blank=True, help_text='Длина и тип рычага', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_levers', to='pa_controls.leveroption', verbose_name='Рычаг')),
                ('selected_model_line', models.ForeignKey(blank=True, help_text='Серия позиционеров — фильтрует доступные опции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_configs', to='pa_controls.posimodelline', verbose_name='Серия')),
                ('selected_signal_profile', models.ForeignKey(blank=True, help_text='Реальный профиль сигналов (синхронизируется из опции серии)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_signal_profiles', to='params.controlunitsignalprofile', verbose_name='Профиль сигналов')),
                ('selected_signal_profile_option', models.ForeignKey(blank=True, help_text='Through-строка «Профиль сигналов» с encoding и smart-набором', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_signal_options', to='pa_controls.posisignalprofileoption', verbose_name='Профиль сигналов (опция серии)')),
                ('selected_smart_capability_set', models.ForeignKey(blank=True, help_text='Синхронизируется из выбранной through-строки профиля сигналов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_smart_sets', to='pa_controls.smartcapabilityset', verbose_name='Набор смарт-возможностей')),
                ('selected_temperature', models.ForeignKey(blank=True, help_text='Температурная through-опция серии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_temperatures', to='pa_controls.positemperatureoption', verbose_name='Температурное исполнение')),
            ],
            options={
                'verbose_name': 'Конфигурация конструктора позиционеров',
                'verbose_name_plural': 'Конфигурации конструктора позиционеров',
                'ordering': ['sorting_order', 'id'],
            },
        ),
    ]


