# Generated by Django 5.2.4 on 2026-09-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('pa_controls', '0057_positionerconstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='posisignalprofileoption',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='posisignalprofileoption',
            name='name',
            field=models.CharField(blank=True, help_text='Нащвание опции', max_length=200, null=True, verbose_name='Название'),
        ),
    ]
