# Generated by Django 5.2.7 on 2026-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0058_posisignalprofileoption_image_gallery_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posimodelline',
            name='exd',
        ),
        migrations.RemoveField(
            model_name='posimodellineitem',
            name='exd',
        ),
        migrations.AddField(
            model_name='posimodellineitem',
            name='exd_options',
            field=models.ManyToManyField(blank=True, help_text='Виды взрывозащиты (копируется из PosiExdOption серии)', related_name='positioner_items', to='params.exdoption', verbose_name='Виды взрывозащиты'),
        ),
    ]
