# Generated by Django 5.2.7 on 2026-09-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0059_remove_posimodelline_exd_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posimodellineitem',
            name='ip',
        ),
        migrations.AddField(
            model_name='posimodelline',
            name='ip',
            field=models.ForeignKey(blank=True, help_text='Степень защиты IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_model_line_ip', to='params.ipoption', verbose_name='IP'),
        ),
    ]
