# Generated by Django 5.2.7 on 2026-09-04 14:38

from django.db import migrations, models


def copy_only_non_ex_to_availability(apps, schema_editor):
    for model_name in ('PosiBodyConnectionOption', 'PosiSignalProfileOption', 'PosiTemperatureOption'):
        model = apps.get_model('pa_controls', model_name)
        model.objects.filter(only_non_ex=True).update(exd_availability='non_ex')


def reverse_availability(apps, schema_editor):
    for model_name in ('PosiBodyConnectionOption', 'PosiSignalProfileOption', 'PosiTemperatureOption'):
        model = apps.get_model('pa_controls', model_name)
        model.objects.filter(exd_availability='non_ex').update(only_non_ex=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0060_remove_posimodellineitem_ip_posimodelline_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='posibodyconnectionoption',
            name='exd_availability',
            field=models.CharField(choices=[('both', 'Для обоих исполнений'), ('non_ex', 'Только общепром'), ('ex', 'Только Ex')], default='both', help_text='Для каких исполнений доступен вариант', max_length=10, verbose_name='Доступность по взрывозащите'),
        ),
        migrations.AddField(
            model_name='posisignalprofileoption',
            name='exd_availability',
            field=models.CharField(choices=[('both', 'Для обоих исполнений'), ('non_ex', 'Только общепром'), ('ex', 'Только Ex')], default='both', help_text='Для каких исполнений доступен вариант', max_length=10, verbose_name='Доступность по взрывозащите'),
        ),
        migrations.AddField(
            model_name='positemperatureoption',
            name='exd_availability',
            field=models.CharField(choices=[('both', 'Для обоих исполнений'), ('non_ex', 'Только общепром'), ('ex', 'Только Ex')], default='both', help_text='Для каких исполнений доступен вариант', max_length=10, verbose_name='Доступность по взрывозащите'),
        ),
        migrations.RunPython(copy_only_non_ex_to_availability, reverse_availability),
        migrations.RemoveField(
            model_name='posibodyconnectionoption',
            name='only_non_ex',
        ),
        migrations.RemoveField(
            model_name='posisignalprofileoption',
            name='only_non_ex',
        ),
        migrations.RemoveField(
            model_name='positemperatureoption',
            name='only_non_ex',
        ),
    ]
