# Generated by Django 5.2.4 on 2026-09-05 11:11

import django.db.models.deletion
from django.db import migrations, models


def copy_thread_in_to_pneumatic_thread(apps, schema_editor):
    """Копируем резьбу пневмовхода в единое поле пневмоподключения.

    Разделение на вход/выход у позиционера не имеет смысла: по данным
    обе резьбы всегда совпадают, поэтому источник — thread_in.
    """
    PosiBodyConnections = apps.get_model('pa_controls', 'PosiBodyConnections')
    for row in PosiBodyConnections.objects.all().iterator():
        row.pneumatic_thread_id = row.thread_in_id
        row.save(update_fields=['pneumatic_thread'])


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0061_remove_posibodyconnectionoption_only_non_ex_and_more'),
        ('params', '0069_add_way_switch_x2_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='posibodyconnections',
            name='pneumatic_thread',
            field=models.ForeignKey(blank=True, help_text='Резьба отверстия для пневмоподключения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_body_connections_pneumatic_thread', to='params.threadsize', verbose_name='Резьба пневмоподключения'),
        ),
        migrations.RunPython(
            copy_thread_in_to_pneumatic_thread,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='posibodyconnections',
            name='thread_in',
        ),
        migrations.RemoveField(
            model_name='posibodyconnections',
            name='thread_out',
        ),
        migrations.AlterField(
            model_name='positionerconstructor',
            name='selected_body_connection',
            field=models.ForeignKey(blank=True, help_text='Резьба пневмоподключения + отверстие под КВ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posi_constructor_body_connections', to='pa_controls.posibodyconnections', verbose_name='Присоединения корпуса'),
        ),
    ]
