# Generated by Django 5.2.4 on 2026-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0064_alter_posiexdoption_exd_options_limitswitchexdoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posimodelline',
            name='model_item_code_template',
            field=models.CharField(blank=True, help_text='Шаблон артикула ', max_length=500, null=True, verbose_name='Шаблон артикула'),
        ),
    ]
