# Generated by Django 5.2.7 on 2026-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0065_alter_posimodelline_model_item_code_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcomponent',
            name='config_hash',
            field=models.CharField(blank=True, help_text='SHA-256 от типоразмера + опций; ключ дедупа и диффа', max_length=64, null=True, unique=True, verbose_name='Хэш конфигурации'),
        ),
    ]
