# Generated by Django 5.2.4 on 2026-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0067_limitswitchbox_config_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='description_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с description_template.', verbose_name='Переводы шаблона описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='name_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с name_template.', verbose_name='Переводы шаблона названия (ru/en/cn)'),
        ),
    ]
