# Generated by Django 5.2.4 on 2026-10-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0071_backfill_pa_controls_dict_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchbox',
            name='display_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": {"name": ..., "description": ..., "title": ..., "list_title": ..., "spec_title": ...}, "en": {...}, "cn": {...}}. Обновляется при сохранении айтема и командой rebuild_display_i18n.', verbose_name='Локализованное отображение (ru/en/cn)'),
        ),
    ]
