# Generated by Django 5.2.4 on 2026-10-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0072_limitswitchbox_display_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitswitchmodelline',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с description.', verbose_name='Переводы описания серии (ru/en/cn)'),
        ),
    ]
