# Generated by Django 5.2.7 on 2026-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0075_actingtype_description_i18n_actingtype_name_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posimodelline',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
    ]
