# Generated by Django 5.2.7 on 2026-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0076_posimodelline_description_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='posimodelline',
            name='description_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='posimodelline',
            name='name_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона названия (ru/en/cn)'),
        ),
    ]
