# Generated by Django 5.2.7 on 2026-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_controls', '0077_posimodelline_description_template_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcomponent',
            name='electrical_specs_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с electrical_specs.', verbose_name='Переводы электрических характеристик (ru/en/cn)'),
        ),
    ]
