# Generated by Django 5.2.4 on 2026-03-31 05:37

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('params', '0031_threadinnerouter'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticFittingVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название разновидности конструкции', max_length=10, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код разновидности конструкции привода', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности конструкции фитинга', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Название разновидности конструкции фитинга',
                'verbose_name_plural': 'Названия разновидностей конструкции фитинга',
                'ordering': ['sorting_order'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PneumaticFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название фитинга', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код фитинга', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности конструкции фитинга', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('body_material', models.ForeignKey(blank=True, help_text='Тип материала корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд фитингов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_brand', to='producers.brands', verbose_name='Бренд')),
                ('pipe_material', models.ForeignKey(blank=True, help_text='Тип материала корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_pipe_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель фитингов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_producer', to='producers.producer', verbose_name='Производитель')),
                ('thread', models.ForeignKey(blank=True, help_text='Резьба фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_thread', to='params.threadsize', verbose_name='Резьба')),
                ('thread_inner_outer', models.ForeignKey(blank=True, help_text='Резьба наружная или внутренняя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_thread_in_out', to='params.threadinnerouter', verbose_name='Резьба наружная или внутренняя')),
                ('fitting_variety', models.ForeignKey(blank=True, help_text='Тип фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_variety', to='pneumatic_fittings.pneumaticfittingvariety', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Пневматический фитинг',
                'verbose_name_plural': 'Пневматические фитинги',
                'ordering': ['sorting_order', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
