# Generated by Django 5.2.4 on 2026-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticfittingvariety',
            name='code',
            field=models.CharField(blank=True, help_text='Код разновидности конструкции привода', max_length=20, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingvariety',
            name='name',
            field=models.CharField(help_text='Название разновидности конструкции', max_length=200, verbose_name='Название'),
        ),
    ]
