# Generated by Django 5.2.4 on 2026-03-31 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('pneumatic_fittings', '0002_alter_pneumaticfittingvariety_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='pipe_material',
            field=models.ForeignKey(blank=True, help_text='Трубка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_pipe_material', to='materials.materialgeneral', verbose_name='Тип материала трубки'),
        ),
    ]
