# Generated by Django 5.2.4 on 2026-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0003_alter_pneumaticfitting_body_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='pipe_diameter',
            field=models.IntegerField(blank=True, help_text='Диаметр', null=True, verbose_name='Диаметр трубки, мм'),
        ),
    ]
