# Generated by Django 5.2.4 on 2026-03-31 15:21

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialgeneral_options_and_more'),
        ('pneumatic_fittings', '0004_pneumaticfitting_pipe_diameter'),
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='temp_max',
            field=models.SmallIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True, verbose_name='Темп.макс'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='temp_min',
            field=models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True, verbose_name='Темп.мин'),
        ),
        migrations.CreateModel(
            name='PneumaticFittingModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текстовое название фитинга', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код фитинга', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание разновидности серии фитингов', verbose_name='Описание')),
                ('name_template', models.CharField(help_text='Шаблон для текстового названия фитинга', max_length=300, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания фитинга', verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('work_temp_min', models.IntegerField(blank=True, default=-40, help_text='Минимальная рабочая температура, °С', null=True, verbose_name='Т раб.мин, °С')),
                ('work_temp_max', models.IntegerField(blank=True, default=120, help_text='Максимальная рабочая температура, °С', null=True, verbose_name='Т раб.макс, °С')),
                ('pressure_min', models.IntegerField(blank=True, default=40, help_text='Минимальное рабочее давление, бар', null=True, verbose_name='P раб.мин, бар')),
                ('pressure_max', models.IntegerField(blank=True, default=40, help_text='Максимальное рабочее давление, бар', null=True, verbose_name='P раб.макс, бар')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд фитингов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line_brand', to='producers.brands', verbose_name='Бренд')),
                ('fitting_variety', models.ForeignKey(blank=True, help_text='Тип фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line_variety', to='pneumatic_fittings.pneumaticfittingvariety', verbose_name='Тип')),
                ('pipe_material', models.ForeignKey(blank=True, help_text='Трубка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line_pipe_material', to='materials.materialgeneral', verbose_name='Тип материала трубки')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель фитингов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line_producer', to='producers.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Серия пневматических фитингов',
                'verbose_name_plural': 'Серии пневматических фитингов',
                'ordering': ['sorting_order', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='fitting_model_line',
            field=models.ForeignKey(blank=True, help_text='Серия фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line', to='pneumatic_fittings.pneumaticfittingmodelline', verbose_name='Серия'),
        ),
    ]
