# Generated by Django 4.2.23 on 2026-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0005_pneumaticfitting_temp_max_pneumaticfitting_temp_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='pressure_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='pressure_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Минимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.мин, бар'),
        ),
    ]
