# Generated by Django 4.2.23 on 2026-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0006_alter_pneumaticfittingmodelline_pressure_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='name',
            field=models.CharField(help_text='Текстовое название фитинга', max_length=300, verbose_name='Название'),
        ),
    ]
