# Generated by Django 4.2.23 on 2026-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0007_alter_pneumaticfitting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneumaticfitting',
            options={'ordering': ['pipe_diameter', 'thread'], 'verbose_name': 'Пневматический фитинг', 'verbose_name_plural': 'Пневматические фитинги'},
        ),
        migrations.AlterModelOptions(
            name='pneumaticfittingmodelline',
            options={'ordering': ['brand', 'code'], 'verbose_name': 'Серия пневматических фитингов', 'verbose_name_plural': 'Серии пневматических фитингов'},
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='flow_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пропускная способность глушителя (л/мин)', max_digits=10, null=True, verbose_name='Пропускная способность'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='noise_level',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Уровень шума глушителя (дБ)', max_digits=5, null=True, verbose_name='Уровень шума'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='operating_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное рабочее давление (бар)', max_digits=8, null=True, verbose_name='Рабочее давление'),
        ),
    ]
