# Generated by Django 5.2.4 on 2026-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0008_alter_pneumaticfitting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='flow_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пропускная способность глушителя (Норм.л/мин)', max_digits=10, null=True, verbose_name='Пропускная способность'),
        ),
    ]
