# Generated by Django 5.2.4 on 2026-04-23 05:29

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0010_fittingfixationmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название формы')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('help_text_content', models.TextField(blank=True, verbose_name='Особенности применения')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Форма фитинга',
                'verbose_name_plural': 'Формы фитингов',
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
