# Generated by Django 5.2.4 on 2026-04-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0011_fittingshape'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfittingvariety',
            name='fixation_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pneumatic_fittings.fittingfixationmethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pneumaticfittingvariety',
            name='shape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pneumatic_fittings.fittingshape'),
            preserve_default=False,
        ),
    ]
