# Generated by Django 5.2.4 on 2026-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0012_pneumaticfittingvariety_fixation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingshape',
            name='is_swivel',
            field=models.BooleanField(default=False, help_text='Можно ли вращать корпус относительно резьбовой части', verbose_name='Поворотный'),
        ),
    ]
