# Generated by Django 5.2.4 on 2026-04-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0013_fittingshape_is_swivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='model_line',
            field=models.ForeignKey(blank=True, help_text='Серия фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_line_new', to='pneumatic_fittings.pneumaticfittingmodelline', verbose_name='Серия'),
        ),
    ]
