# Generated by Django 5.2.4 on 2026-04-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0014_pneumaticfitting_model_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='fitting_model_line',
        ),
    ]
