# Generated by Django 5.2.4 on 2026-06-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipmenttype_content_type'),
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
        ('pneumatic_fittings', '0015_remove_pneumaticfitting_fitting_model_line'),
        ('sku', '0004_alter_sku_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='equipment_type',
            field=models.ForeignKey(default=2, help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='sku',
            field=models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='equipment_type',
            field=models.ForeignKey(default=2, help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='image_gallery',
            field=models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='tech_docs',
            field=models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы'),
        ),
    ]
