# Generated by Django 5.1.4 on 2026-08-23 16:31
# Reordered manually: AddField -> data copy -> RemoveField

from django.db import migrations, models


def copy_pressure_to_fitting(apps, schema_editor):
    """Копирует pressure_min/pressure_max из серий в артикулы.

    Для глушителей с точным operating_pressure меньше «конверта» серии
    (2901 1"/3/4", GAS-20/25 = 6 бар) берём точное значение артикула.
    """
    PneumaticFitting = apps.get_model('pneumatic_fittings', 'PneumaticFitting')
    for fitting in PneumaticFitting.objects.all().select_related('model_line'):
        line = fitting.model_line
        if line is None:
            continue
        fitting.pressure_min = line.pressure_min
        fitting.pressure_max = line.pressure_max
        if fitting.operating_pressure is not None and line.pressure_max is not None:
            if fitting.operating_pressure < line.pressure_max:
                fitting.pressure_max = fitting.operating_pressure
        fitting.save(update_fields=['pressure_min', 'pressure_max'])


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0016_pneumaticfitting_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='pressure_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='pressure_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.мин, бар'),
        ),
        migrations.RunPython(copy_pressure_to_fitting, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='fitting_variety',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='pipe_material',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='pressure_max',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='pressure_min',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='work_temp_max',
        ),
        migrations.RemoveField(
            model_name='pneumaticfittingmodelline',
            name='work_temp_min',
        ),
    ]
