# Generated by Django 5.1.4 on 2026-08-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0004_alter_certdata_media_item'),
        ('pneumatic_fittings', '0017_remove_pneumaticfitting_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='cert_docs',
            field=models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты'),
        ),
    ]
