# Generated by Django 5.1.4 on 2026-08-23 18:35
# Reordered: AddField -> data flags -> RemoveField

from django.db import migrations, models


def set_swivel_flags(apps, schema_editor):
    """Поворотные серии: 6520, 6522, 7526 (угловые поворотные Camozzi)."""
    Line = apps.get_model('pneumatic_fittings', 'PneumaticFittingModelLine')
    Line.objects.filter(code__in=['6520', '6522', '7526']).update(is_swivel=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0018_pneumaticfittingmodelline_cert_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='is_swivel',
            field=models.BooleanField(default=False, help_text='Поворотное исполнение серии фитингов', verbose_name='Поворотный'),
        ),
        migrations.RunPython(set_swivel_flags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='fittingshape',
            name='is_swivel',
        ),
    ]
