# Generated by Django 5.2.7 on 2026-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0020_pneumaticfitting_config_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingfixationmethod',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='fittingfixationmethod',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='fittingshape',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='fittingshape',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='pneumaticfittingvariety',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)'),
        ),
        migrations.AddField(
            model_name='pneumaticfittingvariety',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
    ]
