# Generated by Django 5.2.7 on 2026-10-08 13:06
# Доработан вручную: порядок операций изменён, чтобы скопировать
# форму/способ фиксации из разновидности ДО удаления поля fitting_variety.

import django.db.models.deletion
from django.db import migrations, models


def backfill_shape_fixation(apps, schema_editor):
    """Переносит shape/fixation_method из PneumaticFittingVariety в позиции
    и заменяет плейсхолдер {fitting_variety} в шаблонах названий/описаний."""
    PneumaticFitting = apps.get_model('pneumatic_fittings', 'PneumaticFitting')
    PneumaticFittingVariety = apps.get_model('pneumatic_fittings', 'PneumaticFittingVariety')
    EquipmentType = apps.get_model('core', 'EquipmentType')
    PneumaticFittingModelLine = apps.get_model('pneumatic_fittings', 'PneumaticFittingModelLine')

    # 1) Копируем форму и способ фиксации из разновидности.
    variety_map = {
        v.id: (v.shape_id, v.fixation_method_id)
        for v in PneumaticFittingVariety.objects.all()
    }
    for fitting in PneumaticFitting.objects.exclude(fitting_variety_id=None):
        shape_id, fixation_id = variety_map.get(fitting.fitting_variety_id, (None, None))
        if shape_id or fixation_id:
            PneumaticFitting.objects.filter(pk=fitting.pk).update(
                shape_id=shape_id, fixation_method_id=fixation_id,
            )

    # 2) Заменяем плейсхолдер {fitting_variety} в шаблонах названий/описаний.
    replacement = '{fixation_method} {shape}'
    for model in (EquipmentType, PneumaticFittingModelLine):
        for obj in model.objects.all():
            changed = []
            for field in ('name_template', 'description_template'):
                val = getattr(obj, field, None) or ''
                if isinstance(val, str) and '{fitting_variety}' in val:
                    setattr(obj, field, val.replace('{fitting_variety}', replacement))
                    changed.append(field)
            if changed:
                obj.save(update_fields=changed)


def reverse_backfill(apps, schema_editor):
    # Обратное восстановление невозможно (shape/fixation не содержат исходное имя
    # разновидности), поэтому reverse — no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0023_pneumaticfittingmodelline_description_template_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='shape',
            field=models.ForeignKey(blank=True, help_text='Форма фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_shape', to='pneumatic_fittings.fittingshape', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='fixation_method',
            field=models.ForeignKey(blank=True, help_text='Способ фиксации фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_fixation_method', to='pneumatic_fittings.fittingfixationmethod', verbose_name='Способ фиксации'),
        ),
        migrations.RunPython(backfill_shape_fixation, reverse_backfill),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='fitting_variety',
        ),
        migrations.DeleteModel(
            name='PneumaticFittingVariety',
        ),
    ]
