# Generated by Django 5.2.7 on 2026-10-08 13:32

import core.models.catalog_serializer
import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


def split_fitting_kinds(apps, schema_editor):
    """Переносит позиции глушителей/заглушек из PneumaticFitting в отдельные модели."""
    PneumaticFitting = apps.get_model('pneumatic_fittings', 'PneumaticFitting')
    PneumaticSilencer = apps.get_model('pneumatic_fittings', 'PneumaticSilencer')
    PneumaticPlug = apps.get_model('pneumatic_fittings', 'PneumaticPlug')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    SKU = apps.get_model('sku', 'SKU')

    shared = [
        'name', 'code', 'description', 'sorting_order', 'is_active',
        'pressure_min', 'pressure_max', 'temp_min', 'temp_max',
        'body_material_id', 'equipment_type_id', 'image_gallery_id',
        'model_line_id', 'thread_id', 'thread_inner_outer_id',
    ]

    def move(kind_code, TargetModel, model_name, extra_fields=()):
        ct, _ = ContentType.objects.get_or_create(app_label='pneumatic_fittings', model=model_name)
        qs = PneumaticFitting.objects.filter(model_line__equipment_type__code=kind_code)
        for old in qs:
            data = {f: getattr(old, f) for f in shared}
            for f in extra_fields:
                data[f] = getattr(old, f)
            data['sku_id'] = old.sku_id
            data['config_hash'] = None
            new_obj = TargetModel.objects.create(**data)
            if old.sku_id:
                SKU.objects.filter(pk=old.sku_id).update(
                    source_content_type=ct, source_object_id=new_obj.pk)
            old.delete()

    move('fitting-silencer', PneumaticSilencer, 'pneumaticsilencer',
         extra_fields=('flow_rate', 'noise_level', 'operating_pressure'))
    move('fitting-plug', PneumaticPlug, 'pneumaticplug')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_backfill_equipmenttype_template_i18n'),
        ('materials', '0011_materialgeneralmoredetailed_description_i18n_and_more'),
        ('media_library', '0017_name_i18n'),
        ('params', '0072_remove_controlunitsignalprofileentry_description_i18n_and_more'),
        ('pneumatic_fittings', '0024_remove_pneumaticfitting_fitting_variety_and_more'),
        ('sku', '0007_alter_sku_code_sku_sku_code_uniq_nobrand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание позиции', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='model_line',
            field=models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='pneumatic_fittings.pneumaticfittingmodelline', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='Резьба', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_thread', to='params.threadsize', verbose_name='Резьба'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='thread_inner_outer',
            field=models.ForeignKey(blank=True, help_text='Резьба наружная или внутренняя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_thread_in_out', to='params.threadinnerouter', verbose_name='Резьба наружная или внутренняя'),
        ),
        migrations.CreateModel(
            name='PneumaticPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_hash', models.CharField(blank=True, help_text='SHA-256 от типоразмера + опций; ключ дедупа и диффа', max_length=64, null=True, unique=True, verbose_name='Хэш конфигурации')),
                ('name', models.CharField(help_text='Текстовое название фитинга', max_length=300, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код фитинга', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание позиции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('pressure_min', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.мин, бар')),
                ('pressure_max', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар')),
                ('temp_min', models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True, verbose_name='Темп.мин')),
                ('temp_max', models.SmallIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True, verbose_name='Темп.макс')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('equipment_type', models.ForeignKey(help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='pneumatic_fittings.pneumaticfittingmodelline', verbose_name='Серия')),
                ('sku', models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
                ('thread', models.ForeignKey(blank=True, help_text='Резьба', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_thread', to='params.threadsize', verbose_name='Резьба')),
                ('thread_inner_outer', models.ForeignKey(blank=True, help_text='Резьба наружная или внутренняя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_thread_in_out', to='params.threadinnerouter', verbose_name='Резьба наружная или внутренняя')),
            ],
            options={
                'verbose_name': 'Заглушка пневматическая',
                'verbose_name_plural': 'Заглушки пневматические',
                'ordering': ['thread'],
            },
            bases=(core.models.catalog_serializer.CatalogSerializerMixin, core.models.mixins.StructuredDataMixin, core.models.mixins.TemplateMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PneumaticSilencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_hash', models.CharField(blank=True, help_text='SHA-256 от типоразмера + опций; ключ дедупа и диффа', max_length=64, null=True, unique=True, verbose_name='Хэш конфигурации')),
                ('name', models.CharField(help_text='Текстовое название фитинга', max_length=300, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код фитинга', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание позиции', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('pressure_min', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.мин, бар')),
                ('pressure_max', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное рабочее давление, бар', max_digits=6, null=True, verbose_name='P раб.макс, бар')),
                ('temp_min', models.SmallIntegerField(blank=True, help_text='Минимальная температура окружающей среды', null=True, verbose_name='Темп.мин')),
                ('temp_max', models.SmallIntegerField(blank=True, help_text='Максимальная температура окружающей среды', null=True, verbose_name='Темп.макс')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Пропускная способность глушителя (Норм.л/мин)', max_digits=10, null=True, verbose_name='Пропускная способность')),
                ('noise_level', models.DecimalField(blank=True, decimal_places=1, help_text='Уровень шума глушителя (дБ)', max_digits=5, null=True, verbose_name='Уровень шума')),
                ('operating_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное рабочее давление (бар)', max_digits=8, null=True, verbose_name='Рабочее давление')),
                ('body_material', models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса')),
                ('equipment_type', models.ForeignKey(help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('model_line', models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='pneumatic_fittings.pneumaticfittingmodelline', verbose_name='Серия')),
                ('sku', models.OneToOneField(blank=True, help_text='Запись в справочнике номенклатуры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.sku', verbose_name='SKU')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
                ('thread', models.ForeignKey(blank=True, help_text='Резьба', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_thread', to='params.threadsize', verbose_name='Резьба')),
                ('thread_inner_outer', models.ForeignKey(blank=True, help_text='Резьба наружная или внутренняя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_thread_in_out', to='params.threadinnerouter', verbose_name='Резьба наружная или внутренняя')),
            ],
            options={
                'verbose_name': 'Глушитель пневматический',
                'verbose_name_plural': 'Глушители пневматические',
                'ordering': ['thread'],
            },
            bases=(core.models.catalog_serializer.CatalogSerializerMixin, core.models.mixins.StructuredDataMixin, core.models.mixins.TemplateMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.RunPython(split_fitting_kinds, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='flow_rate',
        ),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='noise_level',
        ),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='operating_pressure',
        ),
    ]
