# Generated by Django 5.2.7 on 2026-10-08 14:44
# Доработан вручную: порядок операций изменён, добавлена data-миграция переноса
# серий глушителей/заглушек и бэкфилла формы/способа фиксации на серии фитингов.

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


def split_model_lines(apps, schema_editor):
    """Переносит серии глушителей/заглушек в отдельные модели и
    поднимает форму/способ фиксации на серии фитингов (из их позиций)."""
    PneumaticFittingModelLine = apps.get_model('pneumatic_fittings', 'PneumaticFittingModelLine')
    PneumaticSilencerModelLine = apps.get_model('pneumatic_fittings', 'PneumaticSilencerModelLine')
    PneumaticPlugModelLine = apps.get_model('pneumatic_fittings', 'PneumaticPlugModelLine')
    PneumaticFitting = apps.get_model('pneumatic_fittings', 'PneumaticFitting')
    PneumaticSilencer = apps.get_model('pneumatic_fittings', 'PneumaticSilencer')
    PneumaticPlug = apps.get_model('pneumatic_fittings', 'PneumaticPlug')

    def move_series(kind_code, TargetModel):
        id_map = {}
        for ml in PneumaticFittingModelLine.objects.filter(equipment_type__code=kind_code):
            new = TargetModel.objects.create(
                name=ml.name, code=ml.code, description=ml.description,
                name_template=ml.name_template, description_template=ml.description_template,
                sorting_order=ml.sorting_order, is_active=ml.is_active,
                producer_id=ml.producer_id, brand_id=ml.brand_id,
                equipment_type_id=ml.equipment_type_id, image_gallery_id=ml.image_gallery_id,
            )
            for m2m in ('tech_docs', 'cert_docs'):
                ids = list(getattr(ml, m2m).values_list('pk', flat=True))
                if ids:
                    getattr(new, m2m).set(ids)
            id_map[ml.id] = new.id
        return id_map

    sil_map = move_series('fitting-silencer', PneumaticSilencerModelLine)
    plug_map = move_series('fitting-plug', PneumaticPlugModelLine)

    # Перепривязываем позиции к новым сериям.
    for sil in PneumaticSilencer.objects.all():
        if sil.model_line_id in sil_map:
            PneumaticSilencer.objects.filter(pk=sil.pk).update(model_line_id=sil_map[sil.model_line_id])
    for plug in PneumaticPlug.objects.all():
        if plug.model_line_id in plug_map:
            PneumaticPlug.objects.filter(pk=plug.pk).update(model_line_id=plug_map[plug.model_line_id])

    # Поднимаем форму/способ фиксации с позиций на серии фитингов.
    for ml in PneumaticFittingModelLine.objects.filter(equipment_type__code='fitting-thread-pipe'):
        first = PneumaticFitting.objects.filter(model_line_id=ml.id).exclude(shape_id=None).first()
        if first is not None:
            PneumaticFittingModelLine.objects.filter(pk=ml.pk).update(
                shape_id=first.shape_id, fixation_method_id=first.fixation_method_id,
            )

    # Удаляем перенесённые серии из общей таблицы.
    moved_ids = list(sil_map) + list(plug_map)
    if moved_ids:
        PneumaticFittingModelLine.objects.filter(id__in=moved_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0006_name_i18n'),
        ('core', '0024_backfill_equipmenttype_template_i18n'),
        ('media_library', '0017_name_i18n'),
        ('pneumatic_fittings', '0026_fix_fitting_content_types'),
        ('producers', '0004_brands_description_i18n_brands_name_i18n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PneumaticPlugModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)')),
                ('name_template_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона названия (ru/en/cn)')),
                ('description_template_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона описания (ru/en/cn)')),
                ('name', models.CharField(help_text='Текстовое название серии', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код серии', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание серии', verbose_name='Описание')),
                ('name_template', models.CharField(help_text='Шаблон для текстового названия', max_length=300, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания', verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_brand', to='producers.brands', verbose_name='Бренд')),
                ('cert_docs', models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты')),
                ('equipment_type', models.ForeignKey(help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_producer', to='producers.producer', verbose_name='Производитель')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
            ],
            options={
                'verbose_name': 'Серия заглушек пневматических',
                'verbose_name_plural': 'Серии заглушек пневматических',
                'ordering': ['brand', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PneumaticSilencerModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)')),
                ('name_template_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона названия (ru/en/cn)')),
                ('description_template_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с шаблоном.', verbose_name='Переводы шаблона описания (ru/en/cn)')),
                ('name', models.CharField(help_text='Текстовое название серии', max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код серии', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Текстовое описание серии', verbose_name='Описание')),
                ('name_template', models.CharField(help_text='Шаблон для текстового названия', max_length=300, verbose_name='Шаблон названия')),
                ('description_template', models.TextField(blank=True, help_text='Шаблон для описания', verbose_name='Шаблон описания')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_brand', to='producers.brands', verbose_name='Бренд')),
                ('cert_docs', models.ManyToManyField(blank=True, help_text='Сертификаты', related_name='+', to='cert_doc.certdata', verbose_name='Сертификаты')),
                ('equipment_type', models.ForeignKey(help_text='К какому типу оборудования относится эта запись', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования')),
                ('image_gallery', models.ForeignKey(blank=True, help_text='Набор изображений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.imagegalleryset', verbose_name='Галерея изображений')),
                ('producer', models.ForeignKey(blank=True, help_text='Производитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_producer', to='producers.producer', verbose_name='Производитель')),
                ('tech_docs', models.ManyToManyField(blank=True, help_text='Технические документы', related_name='+', to='media_library.medialibraryitem', verbose_name='Тех.документы')),
            ],
            options={
                'verbose_name': 'Серия глушителей пневматических',
                'verbose_name_plural': 'Серии глушителей пневматических',
                'ordering': ['brand', 'code'],
            },
            bases=(core.models.mixins.StructuredDataMixin, core.models.mixins.CopyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='fixation_method',
            field=models.ForeignKey(blank=True, help_text='Способ фиксации фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_lines_fixation', to='pneumatic_fittings.fittingfixationmethod', verbose_name='Способ фиксации'),
        ),
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='shape',
            field=models.ForeignKey(blank=True, help_text='Форма фитинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumatic_fitting_model_lines', to='pneumatic_fittings.fittingshape', verbose_name='Форма'),
        ),
        migrations.RunPython(split_model_lines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='fixation_method',
        ),
        migrations.RemoveField(
            model_name='pneumaticfitting',
            name='shape',
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='code',
            field=models.CharField(blank=True, help_text='Код позиции', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='model_line',
            field=models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumaticfitting_items', to='pneumatic_fittings.pneumaticfittingmodelline', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='pneumaticfitting',
            name='name',
            field=models.CharField(help_text='Текстовое название позиции', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_brand', to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='code',
            field=models.CharField(blank=True, help_text='Код серии', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовое описание серии', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='description_template',
            field=models.TextField(blank=True, help_text='Шаблон для описания', verbose_name='Шаблон описания'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='name',
            field=models.CharField(help_text='Текстовое название серии', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='name_template',
            field=models.CharField(help_text='Шаблон для текстового названия', max_length=300, verbose_name='Шаблон названия'),
        ),
        migrations.AlterField(
            model_name='pneumaticfittingmodelline',
            name='producer',
            field=models.ForeignKey(blank=True, help_text='Производитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_producer', to='producers.producer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='pneumaticplug',
            name='code',
            field=models.CharField(blank=True, help_text='Код позиции', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pneumaticplug',
            name='model_line',
            field=models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumaticplug_items', to='pneumatic_fittings.pneumaticplugmodelline', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='pneumaticplug',
            name='name',
            field=models.CharField(help_text='Текстовое название позиции', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pneumaticsilencer',
            name='code',
            field=models.CharField(blank=True, help_text='Код позиции', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pneumaticsilencer',
            name='model_line',
            field=models.ForeignKey(blank=True, help_text='Серия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumaticsilencer_items', to='pneumatic_fittings.pneumaticsilencermodelline', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='pneumaticsilencer',
            name='name',
            field=models.CharField(help_text='Текстовое название позиции', max_length=300, verbose_name='Название'),
        ),
    ]
