# Generated by Django 5.2.4 on 2026-10-09 10:54

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0027_remove_pneumaticfitting_fixation_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlugSilencerBodyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)')),
                ('description_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала корпуса')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('help_text_content', models.TextField(blank=True, verbose_name='Описание материала корпуса')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Материал корпуса глушителя/заглушки',
                'verbose_name_plural': 'Материалы корпуса глушителя/заглушки',
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SilencerFilterElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)')),
                ('description_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала глушителя')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('help_text_content', models.TextField(blank=True, verbose_name='Описание материала глушителя')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Материал глушителя',
                'verbose_name_plural': 'Материалы глушителей',
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SilencerShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)')),
                ('description_i18n', models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с описанием.', verbose_name='Переводы описания (ru/en/cn)')),
                ('name', models.CharField(max_length=100, verbose_name='Название формы')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('help_text_content', models.TextField(blank=True, verbose_name='Форма глушителя - описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка')),
                ('is_active', models.BooleanField(default=True, help_text='Активно свойство или нет', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Форма глушителя',
                'verbose_name_plural': 'Формы глушителей',
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
