# Generated by Django 5.2.4 on 2026-10-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneumatic_fittings', '0028_plugsilencerbodymaterial_silencerfilterelement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='silencerfilterelement',
            options={'verbose_name': 'Материал фильтрующего элемента глушителя', 'verbose_name_plural': 'Материалы фильтрующего элемента глушителей'},
        ),
        migrations.AlterField(
            model_name='silencerfilterelement',
            name='help_text_content',
            field=models.TextField(blank=True, verbose_name='Описание материала фильтрующего элемента глушителя'),
        ),
        migrations.AlterField(
            model_name='silencerfilterelement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название материала фильтрующего элемента глушителя'),
        ),
    ]
