# Generated by Django 5.2.4 on 2026-10-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_materialgeneralmoredetailed_description_i18n_and_more'),
        ('pneumatic_fittings', '0029_alter_silencerfilterelement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneumaticfitting',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Вес, кг', max_digits=6, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='pneumaticfitting',
            name='width_across_flats',
            field=models.SmallIntegerField(blank=True, help_text='Размер гайки под ключ, мм', null=True, verbose_name='Ключ, мм'),
        ),
        migrations.AddField(
            model_name='pneumaticfittingmodelline',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AddField(
            model_name='pneumaticplug',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Вес, кг', max_digits=6, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='pneumaticplug',
            name='width_across_flats',
            field=models.SmallIntegerField(blank=True, help_text='Размер гайки под ключ, мм', null=True, verbose_name='Ключ, мм'),
        ),
        migrations.AddField(
            model_name='pneumaticplugmodelline',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AddField(
            model_name='pneumaticsilencer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Вес, кг', max_digits=6, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='pneumaticsilencer',
            name='width_across_flats',
            field=models.SmallIntegerField(blank=True, help_text='Размер гайки под ключ, мм', null=True, verbose_name='Ключ, мм'),
        ),
        migrations.AddField(
            model_name='pneumaticsilencermodelline',
            name='body_material',
            field=models.ForeignKey(blank=True, help_text='Корпус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_body_material', to='materials.materialgeneral', verbose_name='Тип материала корпуса'),
        ),
        migrations.AddField(
            model_name='pneumaticsilencermodelline',
            name='filter_element',
            field=models.ForeignKey(blank=True, help_text='Фильтрующий элемент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumaticsilencer_filter_element', to='pneumatic_fittings.silencerfilterelement', verbose_name='Фильтрующий элемент'),
        ),
        migrations.AddField(
            model_name='pneumaticsilencermodelline',
            name='shape',
            field=models.ForeignKey(blank=True, help_text='Форма корпуса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneumaticsilencer_shape', to='pneumatic_fittings.silencershape', verbose_name='Форма корпуса'),
        ),
    ]
