# Generated by Django 5.2.4 on 2025-12-03 07:41

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0002_alter_medialibraryitem_media_file_and_more'),
        ('producers', '0002_brands_code_brands_description_brands_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('name', models.CharField(blank=True, help_text='Название типа сертификата', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код типа сертификата', max_length=50, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип сертификата',
                'verbose_name_plural': 'Типы сертификатов',
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Объект помечен как удаленный', verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('sorting_order', models.IntegerField(default=0, help_text='Порядок в списках (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект в интерфейсе', verbose_name='Активно')),
                ('name', models.CharField(blank=True, help_text='Название сертификата', max_length=100, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Код сертификата', max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Описание сертификата - для каких серий и брендов', verbose_name='Описание')),
                ('issued_by', models.CharField(blank=True, help_text='Название организации, выдавшей сертификат', max_length=500, null=True, verbose_name='Кем выдан')),
                ('valid_from', models.DateField(blank=True, help_text='Срок действия с', null=True, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, help_text='Срок действия до', null=True, verbose_name='Действует до')),
                ('public_url', models.CharField(blank=True, help_text='URL адрес для скачивания', max_length=2000, null=True, verbose_name='URL')),
                ('brand', models.ForeignKey(blank=True, help_text='Бренд для сертификата (для фильтрации)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_owner_brand', to='producers.brands')),
                ('media_item', models.ForeignKey(blank=True, help_text='Связанный файл из медиабиблиотеки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='media_library.medialibraryitem', verbose_name='Медиафайл')),
                ('cert_variety', models.ForeignKey(help_text='Тип сертификата', on_delete=django.db.models.deletion.CASCADE, to='cert_doc.certvariety', verbose_name='Тип сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['sorting_order', 'cert_variety'],
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
