# Generated by Django 4.2.23 on 2026-05-12 18:25

import core.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cert_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certdata',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='К какому типу оборудования относится сертификат', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.CreateModel(
            name='CertRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID связанного объекта')),
                ('cert_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='cert_doc.certdata', verbose_name='Сертификат')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label__in': ['pneumatic_fittings', 'solenoid_valves', 'electric_actuators', 'pneumatic_actuators', 'cable_glands', 'gearbox', 'pa_controls', 'filter_regulator', 'valve_data', 'producers']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип связанного объекта')),
            ],
            options={
                'verbose_name': 'Связь сертификата',
                'verbose_name_plural': 'Связи сертификатов',
                'unique_together': {('cert_data', 'content_type', 'object_id')},
            },
            bases=(core.models.mixins.StructuredDataMixin, models.Model),
        ),
    ]
