# Generated by Django 4.2.23 on 2026-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cert_doc', '0002_certdata_equipment_type_certrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certdata',
            name='equipment_type',
        ),
        migrations.AddField(
            model_name='certdata',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, help_text='К каким типам оборудования относится сертификат', to='core.equipmenttype', verbose_name='Типы оборудования'),
        ),
        migrations.DeleteModel(
            name='CertRelation',
        ),
    ]
