# Generated by Django 5.2.7 on 2026-05-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0003_remove_certdata_equipment_type_and_more'),
        ('media_library', '0011_remove_medialibraryitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certdata',
            name='media_item',
            field=models.OneToOneField(blank=True, help_text='Связанный файл из медиабиблиотеки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_data', to='media_library.medialibraryitem', verbose_name='Медиафайл'),
        ),
    ]
