# Generated by Django 5.2.7 on 2026-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_doc', '0005_certvariety_description_i18n_certvariety_name_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='certdata',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"ru": ..., "en": ..., "cn": ...}. "ru" синхронизируется с названием.', verbose_name='Переводы названия (ru/en/cn)'),
        ),
    ]
