# Generated by Django 4.2.23 on 2025-11-06 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storage_manager.fields
import storage_manager.storage_backends.local


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название категории', max_length=50, unique=True, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код категории (заглавные латинские буквы, цифры, подчеркивания)', max_length=20, unique=True, verbose_name='Код категории')),
                ('description', models.TextField(blank=True, help_text='Подробное описание категории', verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='📁', help_text='Emoji или код иконки для отображения', max_length=50, verbose_name='Иконка')),
                ('is_predefined', models.BooleanField(default=False, editable=False, verbose_name='Предопределенная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория медиа',
                'verbose_name_plural': 'Категории медиа',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название тега', max_length=50, unique=True, verbose_name='Название тега')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тег медиа',
                'verbose_name_plural': 'Теги медиа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название медиа элемента', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание содержимого', verbose_name='Описание')),
                ('media_file', storage_manager.fields.ManagedFileField(blank=True, help_text='Загрузите медиафайл', null=True, storage=storage_manager.storage_backends.local.LocalStorage(), upload_to='media_library/', verbose_name='Медиафайл')),
                ('preview_file', storage_manager.fields.ManagedFileField(blank=True, editable=False, help_text='Автоматически создаваемое превью для изображений', null=True, storage=storage_manager.storage_backends.local.LocalStorage(), upload_to='media_library/previews/', verbose_name='Превью')),
                ('mime_type', models.CharField(blank=True, help_text='Тип содержимого файла (определяется автоматически)', max_length=100, verbose_name='MIME-тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_public', models.BooleanField(default=True, help_text='Доступен для всех пользователей', verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='media_library.mediacategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_media_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('tags', models.ManyToManyField(blank=True, related_name='media_items', to='media_library.mediatag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Элемент медиабиблиотеки',
                'verbose_name_plural': 'Элементы медиабиблиотеки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediacategory',
            index=models.Index(fields=['code', 'is_active'], name='media_libra_code_6fdcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='medialibraryitem',
            index=models.Index(fields=['category', 'is_active'], name='media_libra_categor_d2290a_idx'),
        ),
        migrations.AddIndex(
            model_name='medialibraryitem',
            index=models.Index(fields=['created_at'], name='media_libra_created_2a2e36_idx'),
        ),
        migrations.AddIndex(
            model_name='medialibraryitem',
            index=models.Index(fields=['is_public', 'is_active'], name='media_libra_is_publ_fcdeda_idx'),
        ),
    ]
