# Generated by Django 4.2.23 on 2025-11-07 19:07

from django.db import migrations
import storage_manager.fields
import storage_manager.storage_backends.local


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibraryitem',
            name='media_file',
            field=storage_manager.fields.ManagedFileField(blank=True, help_text='Загрузите медиафайл', null=True, storage=storage_manager.storage_backends.local.LocalStorage(), upload_to='', verbose_name='Медиафайл'),
        ),
        migrations.AlterField(
            model_name='medialibraryitem',
            name='preview_file',
            field=storage_manager.fields.ManagedFileField(blank=True, editable=False, help_text='Автоматически создаваемое превью для изображений', null=True, storage=storage_manager.storage_backends.local.LocalStorage(), upload_to='', verbose_name='Превью'),
        ),
    ]
