# Generated by Django 4.2.23 on 2026-05-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media_library', '0002_alter_medialibraryitem_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibraryitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип связанного объекта'),
        ),
        migrations.AddField(
            model_name='medialibraryitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта'),
        ),
    ]
