# Generated by Django 4.2.23 on 2026-05-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('media_library', '0003_medialibraryitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibraryitem',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='К какому типу оборудования относится файл', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype', verbose_name='Тип оборудования'),
        ),
    ]
