# Generated by Django 4.2.23 on 2026-05-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_brands_options_alter_producer_options_and_more'),
        ('media_library', '0004_medialibraryitem_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medialibraryitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='medialibraryitem',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд для быстрой фильтрации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.brands', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='medialibraryitem',
            name='keywords',
            field=models.CharField(blank=True, help_text='Через запятую: насос, нержавейка, DN50', max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.DeleteModel(
            name='MediaTag',
        ),
    ]
