# Generated by Django 4.2.23 on 2026-05-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_remove_medialibraryitem_tags_medialibraryitem_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medialibraryitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='medialibraryitem',
            name='object_id',
        ),
    ]
