# Generated by Django 5.2.4 on 2026-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0006_remove_medialibraryitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibraryitem',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Изображение по умолчанию', verbose_name='Пол умолчанию'),
        ),
        migrations.AddField(
            model_name='medialibraryitem',
            name='sorting_order',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в списке', verbose_name='Cортировка'),
        ),
    ]
