# Generated by Django 5.2.4 on 2026-05-26 12:53

import storage_manager.fields
import storage_manager.storage_backends.cloudru
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0007_medialibraryitem_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibraryitem',
            name='media_file',
            field=storage_manager.fields.ManagedFileField(blank=True, help_text='Загрузите медиафайл', null=True, storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='', verbose_name='Медиафайл'),
        ),
        migrations.AlterField(
            model_name='medialibraryitem',
            name='preview_file',
            field=storage_manager.fields.ManagedFileField(blank=True, editable=False, help_text='Автоматически создаваемое превью для изображений', null=True, storage=storage_manager.storage_backends.cloudru.CloudRuStorage(), upload_to='', verbose_name='Превью'),
        ),
    ]
