# Generated by Django 4.2.23 on 2026-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0008_alter_medialibraryitem_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibraryitem',
            name='code',
            field=models.CharField(blank=True, help_text='Код элемента', max_length=150, null=True, verbose_name='Код'),
        ),
    ]
