# Generated by Django 4.2.23 on 2026-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0009_medialibraryitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibraryitem',
            name='name',
            field=models.CharField(default=1, help_text='Название медиа элемента', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
