# Generated by Django 4.2.23 on 2026-05-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0010_medialibraryitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medialibraryitem',
            name='title',
        ),
    ]
