# Generated by Django 5.2.7 on 2026-05-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0011_remove_medialibraryitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallerySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Код')),
                ('keywords', models.CharField(blank=True, help_text='Через запятую, для поиска', max_length=500, verbose_name='Ключевые слова')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Набор изображений',
                'verbose_name_plural': 'Наборы изображений',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.CreateModel(
            name='ImageGallerySetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('gallery_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media_library.imagegalleryset', verbose_name='Набор')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media_library.medialibraryitem', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Элемент набора',
                'verbose_name_plural': 'Элементы наборов',
                'ordering': ['sorting_order'],
            },
        ),
        migrations.AddField(
            model_name='imagegalleryset',
            name='images',
            field=models.ManyToManyField(related_name='gallery_sets', through='media_library.ImageGallerySetItem', to='media_library.medialibraryitem', verbose_name='Изображения'),
        ),
    ]
