# Generated by Django 5.2.4 on 2026-06-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0013_add_variants_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medialibraryitem',
            name='variants',
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='icon, thumb, card, page, full, email', max_length=20, verbose_name='Роль')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина, px')),
                ('height', models.PositiveIntegerField(verbose_name='Высота, px')),
                ('format', models.CharField(help_text='webp, jpeg, png, pdf', max_length=10, verbose_name='Формат')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь в хранилище')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла, байт')),
                ('page_num', models.PositiveIntegerField(blank=True, help_text='Только для PDF', null=True, verbose_name='Номер страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media_library.medialibraryitem', verbose_name='Элемент медиабиблиотеки')),
            ],
            options={
                'verbose_name': 'Вариант медиа',
                'verbose_name_plural': 'Варианты медиа',
                'ordering': ['media_item', 'page_num', 'role', 'width'],
                'unique_together': {('media_item', 'role', 'width', 'page_num')},
            },
        ),
    ]
