# Generated by Django 5.2.4 on 2026-09-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0014_replace_variants_jsonfield_with_through_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallerysetitem',
            name='image',
            field=models.ForeignKey(limit_choices_to={'category__code': 'PRODUCT_GALLERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media_library.medialibraryitem', verbose_name='Изображение'),
        ),
    ]
